//! Fixture replay for the schema-backed settings sync beta projection.
//!
//! The fixtures live under `fixtures/settings/sync_beta/` and are
//! generated by the `aureline_settings_inspect` CLI bin so the
//! checked-in JSON stays a literal projection of the resolver and
//! the alpha conflict packet (no hand-written drift).

use aureline_settings::sync::{
    SyncConflictReviewBetaPage, SyncConflictReviewBetaSupportExport, SyncStateClass,
};

#[test]
fn sync_beta_fixtures_round_trip_through_shared_types() {
    let page: SyncConflictReviewBetaPage = serde_json::from_str(include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../fixtures/settings/sync_beta/review_page.json"
    )))
    .unwrap();
    assert_eq!(page.shared_contract_ref, "settings:sync_beta:v1");
    assert!(page.state_summary.stale_count >= 1);
    assert!(page.state_summary.disabled_device_count >= 1);
    assert!(page.state_summary.rollback_required_count >= 1);
    assert!(page.state_summary.policy_locked_count >= 1);
    assert!(!page.disabled_devices.is_empty());

    let stale_row = page
        .rows
        .iter()
        .find(|row| row.sync_state == SyncStateClass::Stale)
        .expect("page must include a stale row");
    assert_eq!(stale_row.recommended_resolution_path, "keep_local");
    assert!(stale_row.rollback_decision.retry_allowed);
    assert_eq!(
        stale_row.rollback_decision.retry_state,
        "retry_when_fresh_bundle_arrives"
    );

    let disabled_row = page
        .rows
        .iter()
        .find(|row| row.sync_state == SyncStateClass::DisabledDevice)
        .expect("page must include a disabled-device row");
    assert_eq!(disabled_row.recommended_resolution_path, "keep_local");
    assert_eq!(
        disabled_row.rollback_decision.retry_state,
        "retry_when_remote_device_active"
    );

    let policy_row = page
        .rows
        .iter()
        .find(|row| row.lock_state == "policy_locked")
        .expect("page must include a policy-locked row");
    assert!(policy_row.policy_lock_ref.is_some());
    assert!(policy_row.rollback_decision.rollback_required);
    assert!(policy_row.rollback_decision.approval_required);

    let export: SyncConflictReviewBetaSupportExport = serde_json::from_str(include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../fixtures/settings/sync_beta/support_export.json"
    )))
    .unwrap();
    assert_eq!(export.shared_contract_ref, "settings:sync_beta:v1");
    assert_eq!(export.page.shared_contract_ref, "settings:sync_beta:v1");
    assert!(export.rollback_required_count >= 1);

    for row in &export.page.rows {
        if let Some(packet_ref) = &row.source_packet_ref {
            assert!(
                export
                    .conflict_packets
                    .iter()
                    .any(|packet| packet.packet_id == *packet_ref),
                "row {} should match an alpha conflict packet by source_packet_ref",
                row.setting_id
            );
        }
    }
    assert!(export
        .conflict_packets
        .iter()
        .any(|packet| packet.policy_lock_ref.is_some()));
}
