//! Fixture replay for the schema-backed settings UI beta projection.
//!
//! The fixtures live under `fixtures/settings/ui_beta/` and are
//! generated by the `aureline_settings_inspect` CLI bin so the
//! checked-in JSON stays a literal projection of the inspector
//! resolver (no hand-written drift).

use aureline_settings::ui::{
    SettingsUiBetaInspectorPane, SettingsUiBetaPage, SettingsUiBetaSupportExport,
    SettingsUiBetaWriteComposer,
};

#[test]
fn ui_beta_fixtures_round_trip_through_shared_types() {
    let page: SettingsUiBetaPage = serde_json::from_str(include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../fixtures/settings/ui_beta/page_all_settings.json"
    )))
    .unwrap();
    assert_eq!(page.page_id, "all");
    assert_eq!(page.shared_contract_ref, "settings:ui_beta:v1");
    assert!(
        page.groups.iter().any(|group| group.group_id == "editor"),
        "page must include the editor group"
    );
    assert!(
        page.groups.iter().any(|group| group.group_id == "security"),
        "page must include the security group"
    );
    assert!(page.policy_summary.policy_locked_count >= 1);
    assert!(page.restart_summary.restart_required_count >= 1);
    assert!(page
        .policy_summary
        .policy_sources_present
        .iter()
        .any(|label| label.contains("Admin policy")));

    let pane: SettingsUiBetaInspectorPane = serde_json::from_str(include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../fixtures/settings/ui_beta/inspector_pane_security_egress.json"
    )))
    .unwrap();
    assert_eq!(pane.setting_id, "security.ai.egress_policy");
    assert_eq!(pane.lock_explanation.state, "policy_locked");
    assert!(pane.policy_lock_explanation.is_some());
    assert!(pane
        .source_chain
        .iter()
        .any(|row| row.relation == "winner" && row.relation_label == "Winning source"));
    assert!(pane.source_chain.iter().any(|row| row.relation == "capped"));

    let composer: SettingsUiBetaWriteComposer = serde_json::from_str(include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../fixtures/settings/ui_beta/write_composer_policy_denied.json"
    )))
    .unwrap();
    assert_eq!(composer.verdict, "denied");
    assert!(composer.destination_preview.scope_explicit);
    assert_eq!(
        composer.destination_preview.scope_broadening_verdict,
        "none"
    );
    let denial = composer
        .denial_explanation
        .as_ref()
        .expect("denied composer must carry a denial explanation");
    assert_eq!(denial.reason, "policy_locked_value");
    assert!(denial.owner_label.contains("Admin policy"));
    assert!(denial
        .remediation_label
        .to_lowercase()
        .contains("administrator"));
    assert!(denial.policy_source_ref.is_some());

    let export: SettingsUiBetaSupportExport = serde_json::from_str(include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../fixtures/settings/ui_beta/support_export_parity.json"
    )))
    .unwrap();
    assert_eq!(export.shared_contract_ref, "settings:ui_beta:v1");
    assert_eq!(export.page.shared_contract_ref, "settings:ui_beta:v1");
    for row in export
        .page
        .groups
        .iter()
        .flat_map(|group| group.rows.iter())
    {
        let matching = export
            .effective_settings
            .iter()
            .find(|record| record.source_record_ref == row.source_record_ref);
        assert!(
            matching.is_some(),
            "row {} should match an inspector record by source_record_ref",
            row.setting_id
        );
    }
    assert!(export
        .effective_settings
        .iter()
        .any(|record| record.lock_state == "policy_locked"));
}
