//! Typed truth-surface evidence-ingestion register that makes every M5 feature
//! family's canonical lifecycle state visible wherever users, admins, support
//! engineers, and release owners actually look.
//!
//! The M5 depth lanes ship behind a set of canonical, checked-in evidence
//! packets: the feature family register, the depth-claim qualification matrix,
//! the cross-surface hardening scorecards, and the certified evidence index.
//! Those packets are the single source of truth for *what each family currently
//! claims* and *how far each family is narrowed below stable*. The risk this
//! register removes is **drift**: a Help/About page, service-health row, release
//! center card, support export, or public-truth pack that once read "stable" and
//! keeps reading "stable" after the backing evidence aged out, narrowed, or hit a
//! policy block.
//!
//! This module is the **truth-surface ingestion register** for the M5 learnability
//! and boundary lane (the XT-12 learnability/boundary truth track). For every M5
//! feature family it records one row per user-/operator-facing truth surface
//! ([`TruthSurface`]). Each [`IngestionRow`]:
//!
//! - names the family it ingests ([`IngestionRow::family_kind`],
//!   [`IngestionRow::family_ref`]) and the canonical source-packet entry it reads
//!   ([`IngestionRow::canonical_source_ref`]);
//! - pins the canonical claim ceiling ([`IngestionRow::canonical_claim_label`])
//!   and the canonical effective label ([`IngestionRow::canonical_published_label`])
//!   straight from that source packet -- never retyped per surface;
//! - publishes a label ([`IngestionRow::published_label`]) that **must equal** the
//!   canonical effective label, so a surface can never advertise a wider claim than
//!   the packet backing it;
//! - exposes the surfacing state ([`IngestState`]) -- `current`, `stale`,
//!   `narrowed`, `policy_blocked`, `preview_only`, or `underqualified` -- so a
//!   reader can tell *why* a lane is below stable without reading internal notes;
//! - always discloses posture ([`PostureClass`]) -- `local_only`, `mirrored`,
//!   `managed`, or `browser_handoff` -- because boundary posture is never inferred;
//! - for service-health rows, carries the operational [`ServiceContractState`]
//!   (reused from the docs/help/About/service-health truth register) alongside the
//!   lifecycle label.
//!
//! The register is generated by `tools/regenerate_m5_truth_surface_ingestion.py`,
//! which reads the canonical feature family register and projects it onto the
//! truth surfaces, and is checked in at
//! `artifacts/release/m5/m5_truth_surface_evidence_ingestion.json` and embedded
//! here so this typed consumer and the CI gate agree on every row without a cargo
//! build in CI.
//!
//! The model is metadata-only: every field is a typed state or an opaque ref. It
//! carries no raw artifacts, logs, signatures, or credential material. Two classes
//! of check live outside this model because they need more than the register sees:
//! date arithmetic (recomputing freshness against an `as_of` date) and the
//! cross-artifact drift check (re-reading the canonical source packet to confirm
//! the ingested labels still match). Those live in the CI gate at
//! `tools/ci/m5/truth_surface_ingestion_check.py`. This model enforces the
//! structural and logical invariants that hold regardless of the clock and the
//! neighbouring artifact: the no-widening ceiling, state/label coherence,
//! posture disclosure, service-contract wiring, surface and family coverage,
//! and the publication verdict.

use std::collections::BTreeSet;

use serde::{Deserialize, Serialize};

use crate::harden_docs_help_about_and_service_health_truth::ServiceContractState;
use crate::stable_claim_matrix::{LaunchCutline, StableClaimLevel};

#[cfg(test)]
mod tests;

/// Supported truth-surface ingestion schema version.
pub const M5_TRUTH_SURFACE_INGESTION_SCHEMA_VERSION: u32 = 1;

/// Stable record-kind tag for the register.
pub const M5_TRUTH_SURFACE_INGESTION_RECORD_KIND: &str = "m5_truth_surface_evidence_ingestion";

/// Repo-relative path to the checked-in register.
pub const M5_TRUTH_SURFACE_INGESTION_PATH: &str =
    "artifacts/release/m5/m5_truth_surface_evidence_ingestion.json";

/// Embedded checked-in register JSON.
pub const M5_TRUTH_SURFACE_INGESTION_JSON: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../artifacts/release/m5/m5_truth_surface_evidence_ingestion.json"
));

/// A user-/operator-facing truth surface that ingests canonical M5 evidence.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TruthSurface {
    /// In-product Help and the About / provenance card.
    HelpAbout,
    /// Service-health row (carries an operational contract state).
    ServiceHealth,
    /// Release-center family card.
    ReleaseCenter,
    /// Support-export row.
    SupportExport,
    /// Outward-facing public-truth pack.
    PublicTruthPack,
}

impl TruthSurface {
    /// Every truth surface the register must cover.
    pub const ALL: [Self; 5] = [
        Self::HelpAbout,
        Self::ServiceHealth,
        Self::ReleaseCenter,
        Self::SupportExport,
        Self::PublicTruthPack,
    ];
}

/// The M5 feature family a row ingests.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FamilyKind {
    /// Notebook and computational-document family.
    Notebook,
    /// Data-rich grid/query family.
    DataRich,
    /// AI-adjacent assistance family.
    AiAdjacent,
    /// Framework / language-pack family.
    Framework,
    /// Review and pipeline family.
    Review,
    /// Browser/mobile companion family.
    Companion,
    /// Admin-managed depth family.
    ManagedDepth,
}

impl FamilyKind {
    /// Every M5 feature family the register must cover.
    pub const ALL: [Self; 7] = [
        Self::Notebook,
        Self::DataRich,
        Self::AiAdjacent,
        Self::Framework,
        Self::Review,
        Self::Companion,
        Self::ManagedDepth,
    ];
}

/// The state a truth surface publishes for a family, projected from the canonical
/// family lifecycle state. Never wider than the source.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum IngestState {
    /// Backed at the canonical claim ceiling; nothing narrowed.
    Current,
    /// Backing proof packet aged out of its freshness SLO.
    Stale,
    /// Narrowed below the claim ceiling for a structural reason (e.g. missing
    /// rollback path).
    Narrowed,
    /// A policy block prevents publishing at the claim ceiling.
    PolicyBlocked,
    /// Surfaced as preview-only because the family is still incomplete.
    PreviewOnly,
    /// Provisionally qualified on an active waiver.
    Underqualified,
}

impl IngestState {
    /// True when the surface is fully backed at the ceiling.
    pub const fn is_current(self) -> bool {
        matches!(self, Self::Current)
    }

    /// States that require the published label to sit strictly below the stable
    /// cutline. `Current` is at the ceiling and `Underqualified` may sit at the
    /// ceiling on a waiver, so both are excluded.
    pub const fn requires_below_cutline(self) -> bool {
        matches!(
            self,
            Self::Stale | Self::Narrowed | Self::PolicyBlocked | Self::PreviewOnly
        )
    }
}

/// The boundary posture surfaced on every row. Always explicit, never inferred.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PostureClass {
    /// Runs locally with no managed reachability dependency.
    LocalOnly,
    /// Mirrored through a managed provider/registry surface.
    Mirrored,
    /// Admin-managed; behavior governed by policy.
    Managed,
    /// Hands off to the system browser / companion device for high-risk steps.
    BrowserHandoff,
}

/// A reason a surface publishes a non-current ingestion state, readable without
/// internal notes.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum IngestReason {
    /// The source family is on an active qualification waiver.
    SourceOnActiveWaiver,
    /// The source proof packet breached its freshness SLO.
    SourceProofPacketStale,
    /// The source family is structurally incomplete.
    SourceFamilyIncomplete,
    /// The source family has no verified rollback path.
    SourceRollbackPathMissing,
    /// The family is admin-managed and gated by policy.
    AdminPolicyManaged,
    /// The source family is narrowed for another recorded reason.
    SourceFamilyNarrowed,
}

/// One contradiction rule the ingestion register declares; the CI gate and this
/// model both honour it.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ContradictionRule {
    /// Stable rule id.
    pub rule_id: String,
    /// Human-readable title.
    pub title: String,
    /// The condition that fires the rule.
    pub trigger_reason: String,
    /// The default action when the rule fires.
    pub default_action: String,
    /// Whether firing this rule blocks publication.
    pub blocks_publication: bool,
    /// Reviewable rationale.
    pub rationale: String,
}

/// Canonical source-packet refs the register ingests, kept explicit so consumers
/// can trace every row back to its source of truth.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SourceRefs {
    /// The canonical M5 feature family register.
    pub feature_family_register_ref: String,
    /// The depth-claim qualification matrix.
    pub depth_claim_manifest_ref: String,
    /// The cross-surface hardening scorecards.
    pub cross_surface_hardening_ref: String,
    /// The certified evidence index.
    pub certify_train_register_ref: String,
    /// The docs/help/About/service-health truth register.
    pub docs_help_about_service_health_truth_ref: String,
}

/// One `(family, truth surface)` ingestion binding.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct IngestionRow {
    /// Stable entry id (`ingest:<family>:<surface>`).
    pub entry_id: String,
    /// Human-readable title.
    pub title: String,
    /// The family this row ingests.
    pub family_kind: FamilyKind,
    /// The canonical family ref (`surface:m5_<family>`).
    pub family_ref: String,
    /// The truth surface this row governs.
    pub truth_surface: TruthSurface,
    /// The surface-specific destination ref.
    pub surface_ref: String,
    /// One-line summary of the surfaced row.
    pub surface_summary: String,
    /// Whether the family is on the release-blocking set.
    pub release_blocking: bool,
    /// The canonical source-packet entry id this row reads.
    pub canonical_source_ref: String,
    /// The canonical claim ceiling for the family.
    pub canonical_claim_label: StableClaimLevel,
    /// The canonical effective (published) label for the family.
    pub canonical_published_label: StableClaimLevel,
    /// The surfacing state this row publishes.
    pub ingest_state: IngestState,
    /// The boundary posture, always explicit.
    pub posture: PostureClass,
    /// The label this surface publishes; must equal `canonical_published_label`.
    pub published_label: StableClaimLevel,
    /// Reasons explaining a non-current state.
    pub active_ingest_reasons: Vec<IngestReason>,
    /// The proof/evidence ref backing the surfaced truth.
    pub evidence_ref: String,
    /// The operational contract state (service-health rows only).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service_contract_state: Option<ServiceContractState>,
    /// Reviewable rationale.
    pub rationale: String,
}

/// The publication verdict for the register.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct IngestPublicationRecord {
    /// The publication gate name.
    pub publication_gate: String,
    /// `proceed` or `hold`.
    pub decision: String,
    /// Contradiction rule ids blocking publication.
    pub blocking_rule_ids: Vec<String>,
    /// Row entry ids blocking publication.
    pub blocking_entry_ids: Vec<String>,
    /// Reviewable rationale.
    pub rationale: String,
}

/// Roll-up counts over the register.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct IngestSummary {
    /// Total ingestion rows.
    pub total_rows: usize,
    /// Distinct families covered.
    pub total_families: usize,
    /// Distinct truth surfaces covered.
    pub total_surfaces: usize,
    /// Rows whose family is release-blocking.
    pub release_blocking_rows: usize,
    /// Rows whose published label is below the stable cutline.
    pub rows_below_cutline: usize,
    /// Service-health rows.
    pub service_health_rows: usize,
    /// Contradiction rules currently firing.
    pub contradiction_rules_firing: usize,
    /// Rows in the `current` state.
    pub rows_current: usize,
    /// Rows in the `stale` state.
    pub rows_stale: usize,
    /// Rows in the `narrowed` state.
    pub rows_narrowed: usize,
    /// Rows in the `policy_blocked` state.
    pub rows_policy_blocked: usize,
    /// Rows in the `preview_only` state.
    pub rows_preview_only: usize,
    /// Rows in the `underqualified` state.
    pub rows_underqualified: usize,
    /// Help/About rows.
    pub help_about_rows: usize,
    /// Release-center rows.
    pub release_center_rows: usize,
    /// Support-export rows.
    pub support_export_rows: usize,
    /// Public-truth-pack rows.
    pub public_truth_pack_rows: usize,
}

/// The checked-in truth-surface ingestion register.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct M5TruthSurfaceIngestion {
    /// Schema version.
    pub schema_version: u32,
    /// Record kind tag.
    pub record_kind: String,
    /// Stable register id.
    pub register_id: String,
    /// Publication status.
    pub status: String,
    /// Overview doc page.
    pub overview_page: String,
    /// The `as_of` date the register reflects.
    pub as_of: String,
    /// Canonical source-packet refs.
    pub source_refs: SourceRefs,
    /// The claim manifest ref the families bind to.
    pub claim_manifest_ref: String,
    /// The family-kind vocabulary.
    pub family_kinds: Vec<FamilyKind>,
    /// The truth-surface vocabulary.
    pub truth_surfaces: Vec<TruthSurface>,
    /// The ingest-state vocabulary.
    pub ingest_states: Vec<IngestState>,
    /// The posture vocabulary.
    pub posture_classes: Vec<PostureClass>,
    /// The service-contract-state vocabulary.
    pub service_contract_states: Vec<ServiceContractState>,
    /// The lifecycle-label vocabulary.
    pub lifecycle_labels: Vec<StableClaimLevel>,
    /// The stable cutline.
    pub launch_cutline: LaunchCutline,
    /// Release-blocking family refs.
    pub release_blocking_family_refs: Vec<String>,
    /// Declared contradiction rules.
    pub contradiction_rules: Vec<ContradictionRule>,
    /// The ingestion rows.
    pub rows: Vec<IngestionRow>,
    /// The publication verdict.
    pub publication: IngestPublicationRecord,
    /// Roll-up counts.
    pub summary: IngestSummary,
}

/// A structural or logical invariant the register violated.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case", tag = "code", content = "detail")]
pub enum IngestionViolation {
    /// Schema version did not match the supported version.
    SchemaVersionMismatch { found: u32 },
    /// Record kind tag did not match.
    RecordKindMismatch { found: String },
    /// A required string field was empty.
    EmptyField { entry_id: String, field: String },
    /// The published label is wider than the canonical claim ceiling.
    PublishedExceedsCeiling { entry_id: String },
    /// The published label does not equal the canonical effective label.
    PublishedNotCanonical { entry_id: String },
    /// The canonical effective label is wider than the canonical ceiling.
    SourceLabelInconsistent { entry_id: String },
    /// A current row carries narrowing reasons or is not at the ceiling.
    CurrentRowNotBacked { entry_id: String },
    /// A non-current row has no reasons.
    NarrowedRowWithoutReason { entry_id: String },
    /// A below-cutline state did not narrow below the stable cutline.
    NarrowedStateNotBelowCutline { entry_id: String },
    /// A service-health row is missing its contract state.
    ServiceHealthMissingContractState { entry_id: String },
    /// A non-service-health row carries a contract state.
    NonServiceHealthHasContractState { entry_id: String },
    /// A family ref claims release-blocking inconsistently with the declared set.
    ReleaseBlockingMismatch { entry_id: String },
    /// A declared family kind was never covered by any row.
    FamilyKindUncovered { family_kind: FamilyKind },
    /// A declared truth surface was never covered by any row.
    TruthSurfaceUncovered { truth_surface: TruthSurface },
    /// A family is missing a row for at least one truth surface.
    FamilySurfaceCoverageGap {
        family_kind: FamilyKind,
        truth_surface: TruthSurface,
    },
    /// The publication verdict did not match the computed verdict.
    PublicationVerdictMismatch { found: String, expected: String },
    /// The summary did not match the computed roll-up.
    SummaryMismatch { field: String },
}

impl M5TruthSurfaceIngestion {
    /// Validate every structural and logical invariant the register must hold.
    ///
    /// Returns an empty vector when the register is internally coherent. Clock and
    /// cross-artifact checks live in the CI gate; this method enforces invariants
    /// independent of the date and the neighbouring source packet.
    pub fn validate(&self) -> Vec<IngestionViolation> {
        let mut out = Vec::new();

        if self.schema_version != M5_TRUTH_SURFACE_INGESTION_SCHEMA_VERSION {
            out.push(IngestionViolation::SchemaVersionMismatch {
                found: self.schema_version,
            });
        }
        if self.record_kind != M5_TRUTH_SURFACE_INGESTION_RECORD_KIND {
            out.push(IngestionViolation::RecordKindMismatch {
                found: self.record_kind.clone(),
            });
        }

        let blocking_set: BTreeSet<&str> = self
            .release_blocking_family_refs
            .iter()
            .map(String::as_str)
            .collect();

        for row in &self.rows {
            self.validate_row(row, &blocking_set, &mut out);
        }

        self.validate_coverage(&mut out);
        self.validate_publication(&mut out);
        self.validate_summary(&mut out);

        out
    }

    fn validate_row(
        &self,
        row: &IngestionRow,
        blocking_set: &BTreeSet<&str>,
        out: &mut Vec<IngestionViolation>,
    ) {
        let id = row.entry_id.clone();

        for (field, value) in [
            ("entry_id", &row.entry_id),
            ("family_ref", &row.family_ref),
            ("surface_ref", &row.surface_ref),
            ("surface_summary", &row.surface_summary),
            ("canonical_source_ref", &row.canonical_source_ref),
            ("evidence_ref", &row.evidence_ref),
            ("rationale", &row.rationale),
        ] {
            if value.trim().is_empty() {
                out.push(IngestionViolation::EmptyField {
                    entry_id: id.clone(),
                    field: field.to_string(),
                });
            }
        }

        // The source packet must itself be coherent: effective <= ceiling.
        if row.canonical_published_label.rank() > row.canonical_claim_label.rank() {
            out.push(IngestionViolation::SourceLabelInconsistent {
                entry_id: id.clone(),
            });
        }

        // No widening: the published label cannot exceed the ceiling...
        if row.published_label.rank() > row.canonical_claim_label.rank() {
            out.push(IngestionViolation::PublishedExceedsCeiling {
                entry_id: id.clone(),
            });
        }
        // ...and must reflect the canonical effective label exactly (no stale copy).
        if row.published_label != row.canonical_published_label {
            out.push(IngestionViolation::PublishedNotCanonical {
                entry_id: id.clone(),
            });
        }

        // State / reason coherence.
        if row.ingest_state.is_current() {
            if !row.active_ingest_reasons.is_empty()
                || row.published_label != row.canonical_claim_label
            {
                out.push(IngestionViolation::CurrentRowNotBacked {
                    entry_id: id.clone(),
                });
            }
        } else if row.active_ingest_reasons.is_empty() {
            out.push(IngestionViolation::NarrowedRowWithoutReason {
                entry_id: id.clone(),
            });
        }

        // Below-cutline states must actually narrow below stable.
        if row.ingest_state.requires_below_cutline() && row.published_label.is_at_or_above_cutline()
        {
            out.push(IngestionViolation::NarrowedStateNotBelowCutline {
                entry_id: id.clone(),
            });
        }

        // Service-contract state is present iff this is a service-health row.
        match row.truth_surface {
            TruthSurface::ServiceHealth => {
                if row.service_contract_state.is_none() {
                    out.push(IngestionViolation::ServiceHealthMissingContractState {
                        entry_id: id.clone(),
                    });
                }
            }
            _ => {
                if row.service_contract_state.is_some() {
                    out.push(IngestionViolation::NonServiceHealthHasContractState {
                        entry_id: id.clone(),
                    });
                }
            }
        }

        // Release-blocking flag must agree with the declared family set.
        let declared_blocking = blocking_set.contains(row.family_ref.as_str());
        if declared_blocking != row.release_blocking {
            out.push(IngestionViolation::ReleaseBlockingMismatch { entry_id: id });
        }
    }

    fn validate_coverage(&self, out: &mut Vec<IngestionViolation>) {
        let covered_families: BTreeSet<FamilyKind> =
            self.rows.iter().map(|r| r.family_kind).collect();
        for kind in FamilyKind::ALL {
            if !covered_families.contains(&kind) {
                out.push(IngestionViolation::FamilyKindUncovered { family_kind: kind });
            }
        }

        let covered_surfaces: BTreeSet<TruthSurface> =
            self.rows.iter().map(|r| r.truth_surface).collect();
        for surface in TruthSurface::ALL {
            if !covered_surfaces.contains(&surface) {
                out.push(IngestionViolation::TruthSurfaceUncovered {
                    truth_surface: surface,
                });
            }
        }

        // Every covered family must appear on every truth surface.
        let pairs: BTreeSet<(FamilyKind, TruthSurface)> = self
            .rows
            .iter()
            .map(|r| (r.family_kind, r.truth_surface))
            .collect();
        for kind in &covered_families {
            for surface in TruthSurface::ALL {
                if !pairs.contains(&(*kind, surface)) {
                    out.push(IngestionViolation::FamilySurfaceCoverageGap {
                        family_kind: *kind,
                        truth_surface: surface,
                    });
                }
            }
        }
    }

    fn validate_publication(&self, out: &mut Vec<IngestionViolation>) {
        let expected = self.computed_decision();
        if self.publication.decision != expected {
            out.push(IngestionViolation::PublicationVerdictMismatch {
                found: self.publication.decision.clone(),
                expected,
            });
        }
    }

    /// The verdict implied by the rows: `hold` if any row widens or omits a
    /// required disclosure, `proceed` otherwise.
    fn computed_decision(&self) -> String {
        let any_widening = self.rows.iter().any(|r| {
            r.published_label != r.canonical_published_label
                || r.published_label.rank() > r.canonical_claim_label.rank()
        });
        if any_widening {
            "hold".to_string()
        } else {
            "proceed".to_string()
        }
    }

    fn validate_summary(&self, out: &mut Vec<IngestionViolation>) {
        let computed = self.computed_summary();
        let s = &self.summary;
        let checks: [(&str, bool); 17] = [
            ("total_rows", s.total_rows == computed.total_rows),
            (
                "total_families",
                s.total_families == computed.total_families,
            ),
            (
                "total_surfaces",
                s.total_surfaces == computed.total_surfaces,
            ),
            (
                "release_blocking_rows",
                s.release_blocking_rows == computed.release_blocking_rows,
            ),
            (
                "rows_below_cutline",
                s.rows_below_cutline == computed.rows_below_cutline,
            ),
            (
                "service_health_rows",
                s.service_health_rows == computed.service_health_rows,
            ),
            (
                "contradiction_rules_firing",
                s.contradiction_rules_firing == computed.contradiction_rules_firing,
            ),
            ("rows_current", s.rows_current == computed.rows_current),
            ("rows_stale", s.rows_stale == computed.rows_stale),
            ("rows_narrowed", s.rows_narrowed == computed.rows_narrowed),
            (
                "rows_policy_blocked",
                s.rows_policy_blocked == computed.rows_policy_blocked,
            ),
            (
                "rows_preview_only",
                s.rows_preview_only == computed.rows_preview_only,
            ),
            (
                "rows_underqualified",
                s.rows_underqualified == computed.rows_underqualified,
            ),
            (
                "help_about_rows",
                s.help_about_rows == computed.help_about_rows,
            ),
            (
                "release_center_rows",
                s.release_center_rows == computed.release_center_rows,
            ),
            (
                "support_export_rows",
                s.support_export_rows == computed.support_export_rows,
            ),
            (
                "public_truth_pack_rows",
                s.public_truth_pack_rows == computed.public_truth_pack_rows,
            ),
        ];
        for (field, ok) in checks {
            if !ok {
                out.push(IngestionViolation::SummaryMismatch {
                    field: field.to_string(),
                });
            }
        }
    }

    /// Recompute the roll-up counts directly from the rows.
    pub fn computed_summary(&self) -> IngestSummary {
        let count_state =
            |state: IngestState| self.rows.iter().filter(|r| r.ingest_state == state).count();
        let count_surface = |surface: TruthSurface| {
            self.rows
                .iter()
                .filter(|r| r.truth_surface == surface)
                .count()
        };
        let service_health_rows = count_surface(TruthSurface::ServiceHealth);
        IngestSummary {
            total_rows: self.rows.len(),
            total_families: self
                .rows
                .iter()
                .map(|r| r.family_kind)
                .collect::<BTreeSet<_>>()
                .len(),
            total_surfaces: self
                .rows
                .iter()
                .map(|r| r.truth_surface)
                .collect::<BTreeSet<_>>()
                .len(),
            release_blocking_rows: self.rows.iter().filter(|r| r.release_blocking).count(),
            rows_below_cutline: self
                .rows
                .iter()
                .filter(|r| !r.published_label.is_at_or_above_cutline())
                .count(),
            service_health_rows,
            contradiction_rules_firing: 0,
            rows_current: count_state(IngestState::Current),
            rows_stale: count_state(IngestState::Stale),
            rows_narrowed: count_state(IngestState::Narrowed),
            rows_policy_blocked: count_state(IngestState::PolicyBlocked),
            rows_preview_only: count_state(IngestState::PreviewOnly),
            rows_underqualified: count_state(IngestState::Underqualified),
            help_about_rows: count_surface(TruthSurface::HelpAbout),
            release_center_rows: count_surface(TruthSurface::ReleaseCenter),
            support_export_rows: count_surface(TruthSurface::SupportExport),
            public_truth_pack_rows: count_surface(TruthSurface::PublicTruthPack),
        }
    }

    /// All rows for one truth surface, in declared order.
    pub fn rows_for_surface(&self, surface: TruthSurface) -> impl Iterator<Item = &IngestionRow> {
        self.rows.iter().filter(move |r| r.truth_surface == surface)
    }

    /// All rows for one family, in declared order.
    pub fn rows_for_family(&self, family: FamilyKind) -> impl Iterator<Item = &IngestionRow> {
        self.rows.iter().filter(move |r| r.family_kind == family)
    }
}

/// Parse the embedded checked-in register.
pub fn current_m5_truth_surface_ingestion() -> Result<M5TruthSurfaceIngestion, serde_json::Error> {
    serde_json::from_str(M5_TRUTH_SURFACE_INGESTION_JSON)
}
