//! Citation-ready knowledge-plane evidence packet.
//!
//! This module is the graph-owned contract that finalises topology maps,
//! impact explorer cards, ownership cards, and architecture explainer
//! snapshots into a single export-safe truth source. It binds the v24
//! promise that every claimed stable knowledge-plane row:
//!
//! - Shares one node/edge identity space, one freshness/confidence
//!   vocabulary, and one out-of-scope count model across topology
//!   canvases, list/table fallbacks, breadcrumbs, AI inspectors,
//!   onboarding tours, and review explainer cards.
//! - Never collapses `outside current slice` into `no impact found`.
//!   An impact card with hidden or out-of-scope counts must pin the
//!   exact widen action needed to compute a broader answer.
//! - Distinguishes curated first-party ownership, policy-derived
//!   ownership, imported provider metadata, and heuristic inference
//!   instead of merging every human or system role into one generic
//!   `owner` field.
//! - Pins cited refs, generated-versus-curated source class, freshness,
//!   confidence, and evidence-opening actions on every explainer
//!   snapshot. Generated prose may never ship without citations or an
//!   explicit inference label.
//!
//! The freshness and confidence vocabularies come from
//! [`crate::freshness_propagation_packet`] so the knowledge-plane
//! contract does not invent its own freshness or confidence states.
//!
//! The packet is intentionally metadata-only — it carries no raw node
//! bodies, no raw provider payloads, no secrets, and no ambient
//! credentials — and is read verbatim by the topology canvas, list/
//! table fallback, breadcrumb surface, AI inspector, onboarding tour,
//! review explainer card, CLI/headless emitter, support export, and
//! the release proof index instead of reconstructing knowledge-plane
//! truth from row-local prose.

use std::collections::BTreeSet;
use std::error::Error;
use std::fmt;

use serde::{Deserialize, Serialize};

use crate::freshness_propagation_packet::{CapturedVsLiveClass, ConfidenceClass, FreshnessClass};

/// Stable record-kind tag for [`KnowledgeEvidencePacket`].
pub const KNOWLEDGE_EVIDENCE_PACKET_RECORD_KIND: &str = "graph_knowledge_evidence_packet";

/// Stable record-kind tag for [`KnowledgeEvidencePacketSupportExport`].
pub const KNOWLEDGE_EVIDENCE_PACKET_SUPPORT_EXPORT_RECORD_KIND: &str =
    "graph_knowledge_evidence_support_export";

/// Integer schema version for the stable knowledge-plane evidence packet.
pub const KNOWLEDGE_EVIDENCE_PACKET_SCHEMA_VERSION: u32 = 1;

/// Repo-relative path of the reviewer doc.
pub const KNOWLEDGE_EVIDENCE_PACKET_DOC_REF: &str = "docs/search/m4/knowledge_evidence_packet.md";

/// Repo-relative path of the human-readable artifact narrative.
pub const KNOWLEDGE_EVIDENCE_PACKET_ARTIFACT_DOC_REF: &str =
    "artifacts/search/m4/knowledge_evidence_packet.md";

/// Repo-relative path of the JSON schema.
pub const KNOWLEDGE_EVIDENCE_PACKET_SCHEMA_REF: &str =
    "schemas/search/knowledge_evidence_packet.schema.json";

/// Repo-relative path of the protected fixture corpus directory.
pub const KNOWLEDGE_EVIDENCE_PACKET_FIXTURE_DIR: &str =
    "fixtures/search/m4/knowledge_evidence_packet";

/// Repo-relative path of the checked-in stable knowledge-plane packet.
pub const KNOWLEDGE_EVIDENCE_PACKET_ARTIFACT_REF: &str =
    "artifacts/search/m4/knowledge_evidence_packet.json";

/// Closed source class for an explainer snapshot.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ExplainerSourceClass {
    /// Snapshot was curated from authoritative source artifacts.
    Curated,
    /// Snapshot was generated by an inference / summarization producer.
    Generated,
}

impl ExplainerSourceClass {
    /// Stable token used in fixtures, schemas, and support exports.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Curated => "curated",
            Self::Generated => "generated",
        }
    }
}

/// Closed ownership class for an [`OwnershipCard`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum OwnershipClass {
    /// Ownership comes from a curated first-party register (CODEOWNERS, ownership matrix).
    CuratedFirstParty,
    /// Ownership comes from a policy rule (e.g. workspace policy view).
    PolicyDerived,
    /// Ownership comes from imported provider metadata (registry, SCM, identity provider).
    ImportedProviderMetadata,
    /// Ownership was inferred heuristically and does not bind to a curated record.
    HeuristicInferred,
}

impl OwnershipClass {
    /// Every closed ownership class in declaration order.
    pub const ALL: [Self; 4] = [
        Self::CuratedFirstParty,
        Self::PolicyDerived,
        Self::ImportedProviderMetadata,
        Self::HeuristicInferred,
    ];

    /// Stable token used in fixtures, schemas, and support exports.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::CuratedFirstParty => "curated_first_party",
            Self::PolicyDerived => "policy_derived",
            Self::ImportedProviderMetadata => "imported_provider_metadata",
            Self::HeuristicInferred => "heuristic_inferred",
        }
    }

    /// True when the class requires a partiality note on the card.
    pub const fn requires_partiality_note(self) -> bool {
        !matches!(self, Self::CuratedFirstParty)
    }
}

/// Closed "no impact" state for an impact card.
///
/// `no_impact_found` may never stand in for `outside_current_slice`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum NoImpactState {
    /// Impact is visible inside the active slice; the card shows the impact edges.
    VisibleImpactPresent,
    /// No impact exists in the workspace or active slice at all.
    NoImpactInWorkspaceOrSlice,
    /// Impact exists outside the active slice; the card must disclose the count and widen action.
    ImpactOutsideSliceDisclosed,
}

impl NoImpactState {
    /// Stable token used in fixtures, schemas, and support exports.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::VisibleImpactPresent => "visible_impact_present",
            Self::NoImpactInWorkspaceOrSlice => "no_impact_in_workspace_or_slice",
            Self::ImpactOutsideSliceDisclosed => "impact_outside_slice_disclosed",
        }
    }

    /// True when the state requires a widen action.
    pub const fn requires_widen_action(self) -> bool {
        matches!(self, Self::ImpactOutsideSliceDisclosed)
    }
}

/// Closed evidence-opening action class.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum EvidenceOpeningActionClass {
    /// Open a source / docs anchor cited by the snapshot.
    OpenSourceAtAnchor,
    /// Inspect the canonical graph relation behind a row.
    InspectGraphRelation,
    /// Open the non-canvas topology table projection.
    OpenTopologyTable,
    /// Widen or change the active workset scope.
    WidenScope,
    /// Export the compact evidence card.
    ExportEvidenceCard,
}

impl EvidenceOpeningActionClass {
    /// Stable token used in fixtures, schemas, and support exports.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::OpenSourceAtAnchor => "open_source_at_anchor",
            Self::InspectGraphRelation => "inspect_graph_relation",
            Self::OpenTopologyTable => "open_topology_table",
            Self::WidenScope => "widen_scope",
            Self::ExportEvidenceCard => "export_evidence_card",
        }
    }
}

/// Closed consumer surface that must inherit the knowledge-plane packet verbatim.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum KnowledgeConsumerSurface {
    /// Topology canvas / map view.
    TopologyCanvas,
    /// List / table fallback for keyboard and screen-reader users.
    ListTableFallback,
    /// Breadcrumb surface (parent / ancestor links).
    Breadcrumb,
    /// AI inspector / context picker projection.
    AiInspector,
    /// Onboarding tour projection.
    OnboardingTour,
    /// Review explainer card projection.
    ReviewExplainerCard,
    /// CLI / headless emitter for knowledge-plane queries.
    CliHeadless,
    /// Support export bundle projection.
    SupportExport,
    /// Release proof index entry.
    ReleaseProofIndex,
}

impl KnowledgeConsumerSurface {
    /// Every required consumer surface in declaration order.
    pub const REQUIRED: [Self; 9] = [
        Self::TopologyCanvas,
        Self::ListTableFallback,
        Self::Breadcrumb,
        Self::AiInspector,
        Self::OnboardingTour,
        Self::ReviewExplainerCard,
        Self::CliHeadless,
        Self::SupportExport,
        Self::ReleaseProofIndex,
    ];

    /// Stable token used in fixtures, schemas, and support exports.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::TopologyCanvas => "topology_canvas",
            Self::ListTableFallback => "list_table_fallback",
            Self::Breadcrumb => "breadcrumb",
            Self::AiInspector => "ai_inspector",
            Self::OnboardingTour => "onboarding_tour",
            Self::ReviewExplainerCard => "review_explainer_card",
            Self::CliHeadless => "cli_headless",
            Self::SupportExport => "support_export",
            Self::ReleaseProofIndex => "release_proof_index",
        }
    }
}

/// Closed promotion state for [`KnowledgeEvidencePacket`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum KnowledgePromotionState {
    /// Packet certifies a stable claim.
    Stable,
    /// Packet must remain narrowed below stable until a recorded gap closes.
    NarrowedBelowStable,
    /// Packet has a blocker finding and cannot publish on stable surfaces.
    BlocksStable,
}

impl KnowledgePromotionState {
    /// Stable token used in fixtures, schemas, and support exports.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Stable => "stable",
            Self::NarrowedBelowStable => "narrowed_below_stable",
            Self::BlocksStable => "blocks_stable",
        }
    }
}

/// Severity for one validation finding.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum KnowledgeFindingSeverity {
    /// Informational finding.
    Info,
    /// Reviewable finding that narrows the packet below stable.
    Warning,
    /// Blocker that prevents stable publication.
    Blocker,
}

/// Closed validation-finding vocabulary for [`KnowledgeEvidencePacket`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum KnowledgeFindingKind {
    /// Record kind does not match the schema.
    WrongRecordKind,
    /// Schema version does not match the frozen schema.
    WrongSchemaVersion,
    /// Packet identity refs are empty.
    MissingPacketIdentity,
    /// Shared identity model is missing or incomplete.
    MissingSharedIdentityModel,
    /// Topology view is missing.
    MissingTopologyView,
    /// Topology view edges reference node ids that are not present in the shared identity model.
    NodeEdgeIdentityMismatch,
    /// Topology view drops out-of-scope counts.
    OutOfScopeCountDropped,
    /// Topology view has out-of-scope nodes or edges but no widen-scope action ref.
    TopologyMissingWidenAction,
    /// Impact card with out-of-scope or hidden impact collapsed to `no_impact_found`.
    NoImpactCollapsedOnOutOfScopeImpact,
    /// Impact card declares `impact_outside_slice_disclosed` but drops the widen action ref.
    ImpactCardMissingWidenAction,
    /// Ownership card carries no `ownership_class` token.
    OwnershipClassMissing,
    /// Ownership card requires a partiality note for its class but has none.
    OwnershipPartialityNoteMissing,
    /// Explainer snapshot is missing its source class.
    ExplainerSourceClassMissing,
    /// Generated explainer snapshot drops both citations and an inference label.
    GeneratedExplainerMissingCitationsOrInference,
    /// Explainer snapshot drops its evidence-opening actions.
    ExplainerMissingEvidenceOpeningActions,
    /// A required consumer projection is missing.
    MissingConsumerProjection,
    /// A consumer projection drops or remints knowledge-plane truth.
    ConsumerProjectionDrift,
    /// A consumer projection drops the node/edge identity binding.
    NodeEdgeIdentityDropped,
    /// A consumer projection drops the freshness vocabulary binding.
    FreshnessVocabularyDropped,
    /// A consumer projection drops the confidence vocabulary binding.
    ConfidenceVocabularyDropped,
    /// A consumer projection drops the out-of-scope count model.
    OutOfScopeCountModelDropped,
    /// A row admits raw query text, raw node bodies, secrets, or provider payloads.
    RawBoundaryMaterialPresent,
    /// Stored promotion state disagrees with derived findings.
    PromotionStateMismatch,
}

impl KnowledgeFindingKind {
    /// Stable token used in fixtures, schemas, and support exports.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::WrongRecordKind => "wrong_record_kind",
            Self::WrongSchemaVersion => "wrong_schema_version",
            Self::MissingPacketIdentity => "missing_packet_identity",
            Self::MissingSharedIdentityModel => "missing_shared_identity_model",
            Self::MissingTopologyView => "missing_topology_view",
            Self::NodeEdgeIdentityMismatch => "node_edge_identity_mismatch",
            Self::OutOfScopeCountDropped => "out_of_scope_count_dropped",
            Self::TopologyMissingWidenAction => "topology_missing_widen_action",
            Self::NoImpactCollapsedOnOutOfScopeImpact => {
                "no_impact_collapsed_on_out_of_scope_impact"
            }
            Self::ImpactCardMissingWidenAction => "impact_card_missing_widen_action",
            Self::OwnershipClassMissing => "ownership_class_missing",
            Self::OwnershipPartialityNoteMissing => "ownership_partiality_note_missing",
            Self::ExplainerSourceClassMissing => "explainer_source_class_missing",
            Self::GeneratedExplainerMissingCitationsOrInference => {
                "generated_explainer_missing_citations_or_inference"
            }
            Self::ExplainerMissingEvidenceOpeningActions => {
                "explainer_missing_evidence_opening_actions"
            }
            Self::MissingConsumerProjection => "missing_consumer_projection",
            Self::ConsumerProjectionDrift => "consumer_projection_drift",
            Self::NodeEdgeIdentityDropped => "node_edge_identity_dropped",
            Self::FreshnessVocabularyDropped => "freshness_vocabulary_dropped",
            Self::ConfidenceVocabularyDropped => "confidence_vocabulary_dropped",
            Self::OutOfScopeCountModelDropped => "out_of_scope_count_model_dropped",
            Self::RawBoundaryMaterialPresent => "raw_boundary_material_present",
            Self::PromotionStateMismatch => "promotion_state_mismatch",
        }
    }
}

/// One validation finding emitted by the knowledge-plane validator.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct KnowledgeValidationFinding {
    /// Closed finding kind.
    pub finding_kind: KnowledgeFindingKind,
    /// Finding severity.
    pub severity: KnowledgeFindingSeverity,
    /// Short support-safe summary.
    pub summary: String,
}

impl KnowledgeValidationFinding {
    fn new(
        finding_kind: KnowledgeFindingKind,
        severity: KnowledgeFindingSeverity,
        summary: impl Into<String>,
    ) -> Self {
        Self {
            finding_kind,
            severity,
            summary: summary.into(),
        }
    }
}

/// Shared identity model binding every knowledge-plane surface to the
/// same node/edge identity space, the same freshness/confidence
/// vocabulary, and the same out-of-scope count model.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SharedIdentityModel {
    /// Stable identity-model ref.
    pub identity_model_ref: String,
    /// Canonical node ids visible to every consumer surface.
    pub node_ids: Vec<String>,
    /// Canonical edge ids visible to every consumer surface.
    pub edge_ids: Vec<String>,
    /// Freshness vocabulary ref (e.g. the freshness-propagation contract).
    pub freshness_vocabulary_ref: String,
    /// Confidence vocabulary ref (e.g. the freshness-propagation contract).
    pub confidence_vocabulary_ref: String,
    /// Out-of-scope count model ref (visible, hidden, out-of-scope, widen-action).
    pub out_of_scope_count_model_ref: String,
}

impl SharedIdentityModel {
    fn is_valid(&self) -> bool {
        !self.identity_model_ref.trim().is_empty()
            && !self.freshness_vocabulary_ref.trim().is_empty()
            && !self.confidence_vocabulary_ref.trim().is_empty()
            && !self.out_of_scope_count_model_ref.trim().is_empty()
    }

    fn node_set(&self) -> BTreeSet<&str> {
        self.node_ids.iter().map(String::as_str).collect()
    }

    fn edge_set(&self) -> BTreeSet<&str> {
        self.edge_ids.iter().map(String::as_str).collect()
    }
}

/// One graph node visible to the topology view.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TopologyNode {
    /// Canonical graph node id.
    pub node_id: String,
    /// Redaction-aware display label.
    pub display_label: String,
    /// Freshness class from the shared vocabulary.
    pub freshness: FreshnessClass,
    /// Confidence class from the shared vocabulary.
    pub confidence: ConfidenceClass,
}

/// One graph edge visible to the topology view.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TopologyEdge {
    /// Canonical graph edge id.
    pub edge_id: String,
    /// Canonical source node id.
    pub from_node_id: String,
    /// Canonical target node id.
    pub to_node_id: String,
    /// Edge class token.
    pub edge_class: String,
    /// Freshness class from the shared vocabulary.
    pub freshness: FreshnessClass,
    /// Confidence class from the shared vocabulary.
    pub confidence: ConfidenceClass,
}

/// Topology view bound to the shared identity model.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TopologyView {
    /// Stable view ref.
    pub view_id: String,
    /// Topology nodes visible to every consumer surface.
    pub nodes: Vec<TopologyNode>,
    /// Topology edges visible to every consumer surface.
    pub edges: Vec<TopologyEdge>,
    /// Count of visible nodes inside the active slice.
    pub visible_node_count: usize,
    /// Count of visible edges inside the active slice.
    pub visible_edge_count: usize,
    /// Count of nodes hidden by scope, policy, or the loaded slice.
    pub out_of_scope_node_count: usize,
    /// Count of edges hidden by scope, policy, or the loaded slice.
    pub out_of_scope_edge_count: usize,
    /// Required widen-scope action ref when any out-of-scope count is non-zero.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub widen_scope_action_ref: Option<String>,
}

impl TopologyView {
    fn requires_widen_action(&self) -> bool {
        self.out_of_scope_node_count > 0 || self.out_of_scope_edge_count > 0
    }
}

/// Impact card bound to the shared identity model.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ImpactCard {
    /// Stable card id.
    pub card_id: String,
    /// Canonical subject graph node id.
    pub subject_node_id: String,
    /// Closed no-impact state.
    pub no_impact_state: NoImpactState,
    /// Count of impact edges visible inside the active slice.
    pub visible_impact_count: usize,
    /// Count of impact edges hidden or out-of-scope (must be preserved across surfaces).
    pub hidden_or_out_of_scope_count: usize,
    /// Required widen action when `no_impact_state` is `impact_outside_slice_disclosed`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub widen_action_ref: Option<String>,
    /// Freshness class from the shared vocabulary.
    pub freshness: FreshnessClass,
    /// Confidence class from the shared vocabulary.
    pub confidence: ConfidenceClass,
    /// True when raw query text, raw node bodies, secrets, and provider payloads are excluded.
    pub raw_boundary_material_excluded: bool,
}

impl ImpactCard {
    fn collapses_on_out_of_scope(&self) -> bool {
        matches!(
            self.no_impact_state,
            NoImpactState::NoImpactInWorkspaceOrSlice
        ) && self.hidden_or_out_of_scope_count > 0
    }
}

/// Ownership card distinguishing curated, policy-derived, imported, and heuristic ownership.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct OwnershipCard {
    /// Stable card id.
    pub card_id: String,
    /// Canonical subject graph node id (file, directory, service, route, etc.).
    pub subject_node_id: String,
    /// Closed ownership class.
    pub ownership_class: OwnershipClass,
    /// Redaction-aware owner display label.
    pub owner_display_label: String,
    /// Source ref (CODEOWNERS path, policy ref, provider metadata ref, heuristic ref).
    pub source_ref: String,
    /// Freshness class from the shared vocabulary.
    pub freshness: FreshnessClass,
    /// Confidence class from the shared vocabulary.
    pub confidence: ConfidenceClass,
    /// Required partiality note for non-curated ownership classes.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub partiality_note: Option<String>,
    /// True when raw query text, raw node bodies, secrets, and provider payloads are excluded.
    pub raw_boundary_material_excluded: bool,
}

/// One citation listed by an explainer snapshot.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ExplainerCitation {
    /// Stable citation id inside the snapshot.
    pub citation_id: String,
    /// Citation subject ref (graph node, edge, docs anchor, etc.).
    pub subject_ref: String,
    /// Redaction-aware display label.
    pub display_label: String,
}

/// One evidence-opening action exposed by an explainer snapshot.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct EvidenceOpeningAction {
    /// Stable action id.
    pub action_id: String,
    /// Action class token.
    pub action_class: EvidenceOpeningActionClass,
    /// Subject ref the action opens.
    pub subject_ref: String,
    /// True when the action preserves the packet's active scope boundary.
    pub preserves_scope: bool,
}

/// Architecture explainer snapshot bound to the shared identity model.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ExplainerSnapshot {
    /// Stable snapshot id.
    pub snapshot_id: String,
    /// Canonical subject graph node id.
    pub subject_node_id: String,
    /// Closed source class for the snapshot.
    pub source_class: ExplainerSourceClass,
    /// Short, redaction-aware prose summary ref.
    pub prose_ref: String,
    /// Ordered citations backing the snapshot.
    pub citations: Vec<ExplainerCitation>,
    /// Required inference label when `source_class` is `generated` and citations are empty.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub inference_label: Option<String>,
    /// Evidence-opening actions exposed by the snapshot.
    pub evidence_opening_actions: Vec<EvidenceOpeningAction>,
    /// Freshness class from the shared vocabulary.
    pub freshness: FreshnessClass,
    /// Confidence class from the shared vocabulary.
    pub confidence: ConfidenceClass,
    /// True when raw query text, raw node bodies, secrets, and provider payloads are excluded.
    pub raw_boundary_material_excluded: bool,
}

impl ExplainerSnapshot {
    fn meets_citation_or_inference_requirement(&self) -> bool {
        match self.source_class {
            ExplainerSourceClass::Curated => true,
            ExplainerSourceClass::Generated => {
                !self.citations.is_empty()
                    || self
                        .inference_label
                        .as_deref()
                        .map(|label| !label.trim().is_empty())
                        .unwrap_or(false)
            }
        }
    }
}

/// Consumer projection proving a surface reads the same packet without
/// reinventing knowledge-plane truth locally.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct KnowledgeConsumerProjection {
    /// Consumer surface class.
    pub consumer_surface: KnowledgeConsumerSurface,
    /// Stable projection ref.
    pub projection_ref: String,
    /// Packet id consumed by the projection.
    pub packet_id_ref: String,
    /// Render timestamp.
    pub rendered_at: String,
    /// True when the surface preserves the shared node/edge identity binding verbatim.
    pub preserves_node_edge_identity: bool,
    /// True when the surface preserves the freshness vocabulary verbatim.
    pub preserves_freshness_vocabulary: bool,
    /// True when the surface preserves the confidence vocabulary verbatim.
    pub preserves_confidence_vocabulary: bool,
    /// True when the surface preserves the out-of-scope count model verbatim.
    pub preserves_out_of_scope_count_model: bool,
    /// True when the surface preserves the impact card widen-action ref verbatim.
    pub preserves_widen_action: bool,
    /// True when the surface preserves the ownership class taxonomy verbatim.
    pub preserves_ownership_class: bool,
    /// True when the surface preserves explainer citations and the inference label verbatim.
    pub preserves_explainer_citations: bool,
    /// True when the surface preserves the same packet id.
    pub preserves_same_packet: bool,
    /// True when JSON export is available from the projection.
    pub supports_json_export: bool,
    /// True when raw private material is excluded.
    pub raw_private_material_excluded: bool,
    /// True when ambient authority / credentials are excluded.
    pub ambient_authority_excluded: bool,
}

impl KnowledgeConsumerProjection {
    fn preserves_truth_for(&self, packet_id: &str) -> bool {
        self.packet_id_ref == packet_id
            && self.preserves_same_packet
            && self.preserves_node_edge_identity
            && self.preserves_freshness_vocabulary
            && self.preserves_confidence_vocabulary
            && self.preserves_out_of_scope_count_model
            && self.preserves_widen_action
            && self.preserves_ownership_class
            && self.preserves_explainer_citations
            && self.supports_json_export
            && self.raw_private_material_excluded
            && self.ambient_authority_excluded
            && !self.projection_ref.trim().is_empty()
    }
}

/// Constructor input for [`KnowledgeEvidencePacket::materialize`].
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct KnowledgeEvidencePacketInput {
    /// Stable packet id.
    pub packet_id: String,
    /// Claimed workflow or surface id.
    pub workflow_or_surface_id: String,
    /// Capture timestamp for the packet as a whole.
    pub generated_at: String,
    /// Captured-vs-live status.
    pub captured_vs_live: CapturedVsLiveClass,
    /// Shared identity model binding every consumer surface.
    pub shared_identity_model: SharedIdentityModel,
    /// Topology view bound to the shared identity model.
    pub topology_view: TopologyView,
    /// Impact cards bound to the shared identity model.
    #[serde(default)]
    pub impact_cards: Vec<ImpactCard>,
    /// Ownership cards bound to the shared identity model.
    #[serde(default)]
    pub ownership_cards: Vec<OwnershipCard>,
    /// Explainer snapshots bound to the shared identity model.
    #[serde(default)]
    pub explainer_snapshots: Vec<ExplainerSnapshot>,
    /// Consumer projections preserving this packet.
    #[serde(default)]
    pub consumer_projections: Vec<KnowledgeConsumerProjection>,
    /// Source contract refs (docs / fixtures / artifact) consumed by the packet.
    #[serde(default)]
    pub source_contract_refs: Vec<String>,
}

/// Graph-owned packet for citation-ready knowledge-plane evidence.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct KnowledgeEvidencePacket {
    /// Stable record kind.
    pub record_kind: String,
    /// Schema version.
    pub schema_version: u32,
    /// Stable packet id.
    pub packet_id: String,
    /// Claimed workflow or surface id.
    pub workflow_or_surface_id: String,
    /// Packet capture timestamp.
    pub generated_at: String,
    /// Captured-vs-live status.
    pub captured_vs_live: CapturedVsLiveClass,
    /// Shared identity model binding every consumer surface.
    pub shared_identity_model: SharedIdentityModel,
    /// Topology view bound to the shared identity model.
    pub topology_view: TopologyView,
    /// Impact cards bound to the shared identity model.
    #[serde(default)]
    pub impact_cards: Vec<ImpactCard>,
    /// Ownership cards bound to the shared identity model.
    #[serde(default)]
    pub ownership_cards: Vec<OwnershipCard>,
    /// Explainer snapshots bound to the shared identity model.
    #[serde(default)]
    pub explainer_snapshots: Vec<ExplainerSnapshot>,
    /// Consumer projections preserving this packet.
    #[serde(default)]
    pub consumer_projections: Vec<KnowledgeConsumerProjection>,
    /// Source contract refs consumed by the packet.
    #[serde(default)]
    pub source_contract_refs: Vec<String>,
    /// Derived promotion state.
    pub promotion_state: KnowledgePromotionState,
    /// Validation findings captured at materialization.
    #[serde(default)]
    pub validation_findings: Vec<KnowledgeValidationFinding>,
}

impl KnowledgeEvidencePacket {
    /// Materialize a packet and record derived validation findings.
    pub fn materialize(input: KnowledgeEvidencePacketInput) -> Self {
        let mut packet = Self {
            record_kind: KNOWLEDGE_EVIDENCE_PACKET_RECORD_KIND.to_owned(),
            schema_version: KNOWLEDGE_EVIDENCE_PACKET_SCHEMA_VERSION,
            packet_id: input.packet_id,
            workflow_or_surface_id: input.workflow_or_surface_id,
            generated_at: input.generated_at,
            captured_vs_live: input.captured_vs_live,
            shared_identity_model: input.shared_identity_model,
            topology_view: input.topology_view,
            impact_cards: input.impact_cards,
            ownership_cards: input.ownership_cards,
            explainer_snapshots: input.explainer_snapshots,
            consumer_projections: input.consumer_projections,
            source_contract_refs: input.source_contract_refs,
            promotion_state: KnowledgePromotionState::Stable,
            validation_findings: Vec::new(),
        };
        let findings = packet.derived_findings(false);
        packet.promotion_state = promotion_state_for_findings(&findings);
        packet.validation_findings = findings;
        packet
    }

    /// Re-validate the packet against stable knowledge-plane invariants.
    pub fn validate(&self) -> Vec<KnowledgeValidationFinding> {
        self.derived_findings(true)
    }

    /// True when this packet has no blocker-level finding.
    pub fn is_stable(&self) -> bool {
        !self
            .validate()
            .iter()
            .any(|finding| finding.severity == KnowledgeFindingSeverity::Blocker)
    }

    /// Returns true when a consumer projection preserves this packet for `surface`.
    pub fn has_projection_for(&self, surface: KnowledgeConsumerSurface) -> bool {
        self.consumer_projections.iter().any(|projection| {
            projection.consumer_surface == surface
                && projection.preserves_truth_for(&self.packet_id)
        })
    }

    /// Returns the unique ownership-class tokens carried across ownership cards.
    pub fn ownership_class_tokens(&self) -> Vec<&'static str> {
        let mut set = BTreeSet::new();
        for card in &self.ownership_cards {
            set.insert(card.ownership_class);
        }
        set.into_iter().map(OwnershipClass::as_str).collect()
    }

    /// Returns the unique no-impact state tokens carried across impact cards.
    pub fn no_impact_state_tokens(&self) -> Vec<&'static str> {
        let mut set = BTreeSet::new();
        for card in &self.impact_cards {
            set.insert(card.no_impact_state);
        }
        set.into_iter().map(NoImpactState::as_str).collect()
    }

    /// Returns the unique explainer source-class tokens carried across snapshots.
    pub fn explainer_source_class_tokens(&self) -> Vec<&'static str> {
        let mut set = BTreeSet::new();
        for snapshot in &self.explainer_snapshots {
            set.insert(snapshot.source_class);
        }
        set.into_iter().map(ExplainerSourceClass::as_str).collect()
    }

    /// Build a support export wrapping the exact product packet.
    pub fn support_export(
        &self,
        export_id: impl Into<String>,
        exported_at: impl Into<String>,
    ) -> KnowledgeEvidencePacketSupportExport {
        KnowledgeEvidencePacketSupportExport {
            record_kind: KNOWLEDGE_EVIDENCE_PACKET_SUPPORT_EXPORT_RECORD_KIND.to_owned(),
            schema_version: KNOWLEDGE_EVIDENCE_PACKET_SCHEMA_VERSION,
            export_id: export_id.into(),
            export_packet_id_ref: self.packet_id.clone(),
            exported_at: exported_at.into(),
            raw_private_material_excluded: true,
            ambient_authority_excluded: true,
            export_packet: self.clone(),
        }
    }

    fn derived_findings(&self, include_record_fields: bool) -> Vec<KnowledgeValidationFinding> {
        let mut findings = Vec::new();

        if include_record_fields && self.record_kind != KNOWLEDGE_EVIDENCE_PACKET_RECORD_KIND {
            findings.push(KnowledgeValidationFinding::new(
                KnowledgeFindingKind::WrongRecordKind,
                KnowledgeFindingSeverity::Blocker,
                "knowledge-evidence packet has the wrong record kind",
            ));
        }
        if include_record_fields && self.schema_version != KNOWLEDGE_EVIDENCE_PACKET_SCHEMA_VERSION
        {
            findings.push(KnowledgeValidationFinding::new(
                KnowledgeFindingKind::WrongSchemaVersion,
                KnowledgeFindingSeverity::Blocker,
                "knowledge-evidence packet has the wrong schema version",
            ));
        }
        if self.packet_id.trim().is_empty()
            || self.workflow_or_surface_id.trim().is_empty()
            || self.generated_at.trim().is_empty()
        {
            findings.push(KnowledgeValidationFinding::new(
                KnowledgeFindingKind::MissingPacketIdentity,
                KnowledgeFindingSeverity::Blocker,
                "packet id, workflow id, and capture timestamp are required",
            ));
        }
        if !self.shared_identity_model.is_valid() {
            findings.push(KnowledgeValidationFinding::new(
                KnowledgeFindingKind::MissingSharedIdentityModel,
                KnowledgeFindingSeverity::Blocker,
                "shared identity model must declare identity, freshness, confidence, and out-of-scope refs",
            ));
        }

        if self.topology_view.view_id.trim().is_empty() {
            findings.push(KnowledgeValidationFinding::new(
                KnowledgeFindingKind::MissingTopologyView,
                KnowledgeFindingSeverity::Blocker,
                "topology view must declare a view id",
            ));
        }

        let node_set = self.shared_identity_model.node_set();
        let edge_set = self.shared_identity_model.edge_set();
        for node in &self.topology_view.nodes {
            if !node_set.contains(node.node_id.as_str()) {
                findings.push(KnowledgeValidationFinding::new(
                    KnowledgeFindingKind::NodeEdgeIdentityMismatch,
                    KnowledgeFindingSeverity::Blocker,
                    format!(
                        "topology node {} is not pinned by the shared identity model",
                        node.node_id
                    ),
                ));
            }
        }
        for edge in &self.topology_view.edges {
            if !edge_set.contains(edge.edge_id.as_str()) {
                findings.push(KnowledgeValidationFinding::new(
                    KnowledgeFindingKind::NodeEdgeIdentityMismatch,
                    KnowledgeFindingSeverity::Blocker,
                    format!(
                        "topology edge {} is not pinned by the shared identity model",
                        edge.edge_id
                    ),
                ));
            }
            if !node_set.contains(edge.from_node_id.as_str())
                || !node_set.contains(edge.to_node_id.as_str())
            {
                findings.push(KnowledgeValidationFinding::new(
                    KnowledgeFindingKind::NodeEdgeIdentityMismatch,
                    KnowledgeFindingSeverity::Blocker,
                    format!(
                        "topology edge {} references unpinned endpoint nodes",
                        edge.edge_id
                    ),
                ));
            }
        }

        if self.topology_view.visible_node_count != self.topology_view.nodes.len() {
            findings.push(KnowledgeValidationFinding::new(
                KnowledgeFindingKind::OutOfScopeCountDropped,
                KnowledgeFindingSeverity::Blocker,
                "topology view visible node count does not match the projected node list",
            ));
        }
        if self.topology_view.visible_edge_count != self.topology_view.edges.len() {
            findings.push(KnowledgeValidationFinding::new(
                KnowledgeFindingKind::OutOfScopeCountDropped,
                KnowledgeFindingSeverity::Blocker,
                "topology view visible edge count does not match the projected edge list",
            ));
        }
        if self.topology_view.requires_widen_action()
            && self
                .topology_view
                .widen_scope_action_ref
                .as_deref()
                .map(|reference| reference.trim().is_empty())
                .unwrap_or(true)
        {
            findings.push(KnowledgeValidationFinding::new(
                KnowledgeFindingKind::TopologyMissingWidenAction,
                KnowledgeFindingSeverity::Blocker,
                "topology view has out-of-scope counts but no widen-scope action ref",
            ));
        }

        for card in &self.impact_cards {
            if card.collapses_on_out_of_scope() {
                findings.push(KnowledgeValidationFinding::new(
                    KnowledgeFindingKind::NoImpactCollapsedOnOutOfScopeImpact,
                    KnowledgeFindingSeverity::Blocker,
                    format!(
                        "impact card {} collapses out-of-scope impact into no_impact_in_workspace_or_slice",
                        card.card_id
                    ),
                ));
            }
            if card.no_impact_state.requires_widen_action()
                && card
                    .widen_action_ref
                    .as_deref()
                    .map(|reference| reference.trim().is_empty())
                    .unwrap_or(true)
            {
                findings.push(KnowledgeValidationFinding::new(
                    KnowledgeFindingKind::ImpactCardMissingWidenAction,
                    KnowledgeFindingSeverity::Blocker,
                    format!(
                        "impact card {} discloses outside-slice impact but drops the widen-action ref",
                        card.card_id
                    ),
                ));
            }
            if !card.raw_boundary_material_excluded {
                findings.push(KnowledgeValidationFinding::new(
                    KnowledgeFindingKind::RawBoundaryMaterialPresent,
                    KnowledgeFindingSeverity::Blocker,
                    format!("impact card {} admits raw boundary material", card.card_id),
                ));
            }
            if !node_set.contains(card.subject_node_id.as_str()) {
                findings.push(KnowledgeValidationFinding::new(
                    KnowledgeFindingKind::NodeEdgeIdentityMismatch,
                    KnowledgeFindingSeverity::Blocker,
                    format!(
                        "impact card {} subject node {} is not pinned by the shared identity model",
                        card.card_id, card.subject_node_id
                    ),
                ));
            }
        }

        for card in &self.ownership_cards {
            if card.card_id.trim().is_empty() {
                findings.push(KnowledgeValidationFinding::new(
                    KnowledgeFindingKind::OwnershipClassMissing,
                    KnowledgeFindingSeverity::Blocker,
                    "ownership card is missing its card id",
                ));
            }
            if card.ownership_class.requires_partiality_note()
                && card
                    .partiality_note
                    .as_deref()
                    .map(|note| note.trim().is_empty())
                    .unwrap_or(true)
            {
                findings.push(KnowledgeValidationFinding::new(
                    KnowledgeFindingKind::OwnershipPartialityNoteMissing,
                    KnowledgeFindingSeverity::Blocker,
                    format!(
                        "ownership card {} uses {} but carries no partiality note",
                        card.card_id,
                        card.ownership_class.as_str()
                    ),
                ));
            }
            if !card.raw_boundary_material_excluded {
                findings.push(KnowledgeValidationFinding::new(
                    KnowledgeFindingKind::RawBoundaryMaterialPresent,
                    KnowledgeFindingSeverity::Blocker,
                    format!(
                        "ownership card {} admits raw boundary material",
                        card.card_id
                    ),
                ));
            }
            if !node_set.contains(card.subject_node_id.as_str()) {
                findings.push(KnowledgeValidationFinding::new(
                    KnowledgeFindingKind::NodeEdgeIdentityMismatch,
                    KnowledgeFindingSeverity::Blocker,
                    format!(
                        "ownership card {} subject node {} is not pinned by the shared identity model",
                        card.card_id, card.subject_node_id
                    ),
                ));
            }
        }

        for snapshot in &self.explainer_snapshots {
            if snapshot.snapshot_id.trim().is_empty() {
                findings.push(KnowledgeValidationFinding::new(
                    KnowledgeFindingKind::ExplainerSourceClassMissing,
                    KnowledgeFindingSeverity::Blocker,
                    "explainer snapshot is missing its snapshot id",
                ));
            }
            if !snapshot.meets_citation_or_inference_requirement() {
                findings.push(KnowledgeValidationFinding::new(
                    KnowledgeFindingKind::GeneratedExplainerMissingCitationsOrInference,
                    KnowledgeFindingSeverity::Blocker,
                    format!(
                        "explainer snapshot {} is generated but ships without citations or an inference label",
                        snapshot.snapshot_id
                    ),
                ));
            }
            if snapshot.evidence_opening_actions.is_empty() {
                findings.push(KnowledgeValidationFinding::new(
                    KnowledgeFindingKind::ExplainerMissingEvidenceOpeningActions,
                    KnowledgeFindingSeverity::Blocker,
                    format!(
                        "explainer snapshot {} has no evidence-opening actions",
                        snapshot.snapshot_id
                    ),
                ));
            }
            if !snapshot.raw_boundary_material_excluded {
                findings.push(KnowledgeValidationFinding::new(
                    KnowledgeFindingKind::RawBoundaryMaterialPresent,
                    KnowledgeFindingSeverity::Blocker,
                    format!(
                        "explainer snapshot {} admits raw boundary material",
                        snapshot.snapshot_id
                    ),
                ));
            }
            if !node_set.contains(snapshot.subject_node_id.as_str()) {
                findings.push(KnowledgeValidationFinding::new(
                    KnowledgeFindingKind::NodeEdgeIdentityMismatch,
                    KnowledgeFindingSeverity::Blocker,
                    format!(
                        "explainer snapshot {} subject node {} is not pinned by the shared identity model",
                        snapshot.snapshot_id, snapshot.subject_node_id
                    ),
                ));
            }
        }

        for required_surface in KnowledgeConsumerSurface::REQUIRED {
            if !self.has_projection_for(required_surface) {
                findings.push(KnowledgeValidationFinding::new(
                    KnowledgeFindingKind::MissingConsumerProjection,
                    KnowledgeFindingSeverity::Blocker,
                    format!(
                        "packet {} is missing a preserved {} projection",
                        self.packet_id,
                        required_surface.as_str()
                    ),
                ));
            }
        }
        for projection in &self.consumer_projections {
            if !projection.preserves_truth_for(&self.packet_id) {
                findings.push(KnowledgeValidationFinding::new(
                    KnowledgeFindingKind::ConsumerProjectionDrift,
                    KnowledgeFindingSeverity::Blocker,
                    format!(
                        "projection {} does not preserve knowledge-plane truth",
                        projection.projection_ref
                    ),
                ));
            }
            if !projection.preserves_node_edge_identity {
                findings.push(KnowledgeValidationFinding::new(
                    KnowledgeFindingKind::NodeEdgeIdentityDropped,
                    KnowledgeFindingSeverity::Blocker,
                    format!(
                        "projection {} drops the node/edge identity binding",
                        projection.projection_ref
                    ),
                ));
            }
            if !projection.preserves_freshness_vocabulary {
                findings.push(KnowledgeValidationFinding::new(
                    KnowledgeFindingKind::FreshnessVocabularyDropped,
                    KnowledgeFindingSeverity::Blocker,
                    format!(
                        "projection {} drops the freshness vocabulary",
                        projection.projection_ref
                    ),
                ));
            }
            if !projection.preserves_confidence_vocabulary {
                findings.push(KnowledgeValidationFinding::new(
                    KnowledgeFindingKind::ConfidenceVocabularyDropped,
                    KnowledgeFindingSeverity::Blocker,
                    format!(
                        "projection {} drops the confidence vocabulary",
                        projection.projection_ref
                    ),
                ));
            }
            if !projection.preserves_out_of_scope_count_model {
                findings.push(KnowledgeValidationFinding::new(
                    KnowledgeFindingKind::OutOfScopeCountModelDropped,
                    KnowledgeFindingSeverity::Blocker,
                    format!(
                        "projection {} drops the out-of-scope count model",
                        projection.projection_ref
                    ),
                ));
            }
        }

        if include_record_fields {
            let mut without_promotion = findings.clone();
            without_promotion.retain(|finding| {
                finding.finding_kind != KnowledgeFindingKind::PromotionStateMismatch
            });
            let derived = promotion_state_for_findings(&without_promotion);
            if self.promotion_state != derived {
                findings.push(KnowledgeValidationFinding::new(
                    KnowledgeFindingKind::PromotionStateMismatch,
                    KnowledgeFindingSeverity::Blocker,
                    "stored promotion state does not match derived findings",
                ));
            }
        }

        findings
    }
}

fn promotion_state_for_findings(
    findings: &[KnowledgeValidationFinding],
) -> KnowledgePromotionState {
    if findings
        .iter()
        .any(|finding| finding.severity == KnowledgeFindingSeverity::Blocker)
    {
        KnowledgePromotionState::BlocksStable
    } else if findings
        .iter()
        .any(|finding| finding.severity == KnowledgeFindingSeverity::Warning)
    {
        KnowledgePromotionState::NarrowedBelowStable
    } else {
        KnowledgePromotionState::Stable
    }
}

/// Support-export wrapper preserving the product knowledge-plane packet verbatim.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct KnowledgeEvidencePacketSupportExport {
    /// Stable record kind.
    pub record_kind: String,
    /// Schema version.
    pub schema_version: u32,
    /// Stable export id.
    pub export_id: String,
    /// Export packet id preserved by the export.
    pub export_packet_id_ref: String,
    /// Export timestamp.
    pub exported_at: String,
    /// True when raw private material is excluded.
    pub raw_private_material_excluded: bool,
    /// True when ambient credentials / authority are excluded.
    pub ambient_authority_excluded: bool,
    /// Exact product packet preserved by the export.
    pub export_packet: KnowledgeEvidencePacket,
}

impl KnowledgeEvidencePacketSupportExport {
    /// True when the export preserves the same packet id safely.
    pub fn is_export_safe(&self) -> bool {
        self.record_kind == KNOWLEDGE_EVIDENCE_PACKET_SUPPORT_EXPORT_RECORD_KIND
            && self.schema_version == KNOWLEDGE_EVIDENCE_PACKET_SCHEMA_VERSION
            && self.export_packet_id_ref == self.export_packet.packet_id
            && self.raw_private_material_excluded
            && self.ambient_authority_excluded
            && self.export_packet.validate().is_empty()
    }
}

/// Errors emitted when reading the checked-in stable knowledge-plane packet.
#[derive(Debug)]
pub enum KnowledgeEvidenceArtifactError {
    /// Packet failed to parse.
    Packet(serde_json::Error),
    /// Packet failed validation.
    Validation(Vec<KnowledgeValidationFinding>),
}

impl fmt::Display for KnowledgeEvidenceArtifactError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Packet(error) => write!(
                formatter,
                "graph knowledge-evidence packet parse failed: {error}"
            ),
            Self::Validation(findings) => {
                let tokens = findings
                    .iter()
                    .map(|finding| finding.finding_kind.as_str())
                    .collect::<Vec<_>>()
                    .join(",");
                write!(
                    formatter,
                    "graph knowledge-evidence packet failed validation: {tokens}"
                )
            }
        }
    }
}

impl Error for KnowledgeEvidenceArtifactError {}

/// Returns the checked-in stable knowledge-plane evidence packet.
///
/// # Errors
///
/// Returns an artifact error if the checked-in packet does not parse or validate.
pub fn current_stable_knowledge_evidence_packet(
) -> Result<KnowledgeEvidencePacket, KnowledgeEvidenceArtifactError> {
    let packet: KnowledgeEvidencePacket = serde_json::from_str(include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../artifacts/search/m4/knowledge_evidence_packet.json"
    )))
    .map_err(KnowledgeEvidenceArtifactError::Packet)?;
    let findings = packet.validate();
    if findings.is_empty() {
        Ok(packet)
    } else {
        Err(KnowledgeEvidenceArtifactError::Validation(findings))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_identity_model() -> SharedIdentityModel {
        SharedIdentityModel {
            identity_model_ref: "identity_model:knowledge_evidence:baseline".to_owned(),
            node_ids: vec![
                "graph:node:src/router/main.rs#router_module".to_owned(),
                "graph:node:src/router/main.rs#router_main".to_owned(),
                "graph:node:src/router/handlers.rs#dispatch".to_owned(),
            ],
            edge_ids: vec!["graph:edge:router_module->dispatch".to_owned()],
            freshness_vocabulary_ref: "docs/search/m4/freshness_propagation_packet.md".to_owned(),
            confidence_vocabulary_ref: "docs/search/m4/freshness_propagation_packet.md".to_owned(),
            out_of_scope_count_model_ref:
                "docs/search/m4/knowledge_evidence_packet.md#out-of-scope-counts".to_owned(),
        }
    }

    fn sample_topology_view() -> TopologyView {
        TopologyView {
            view_id: "topology_view:baseline".to_owned(),
            nodes: vec![
                TopologyNode {
                    node_id: "graph:node:src/router/main.rs#router_module".to_owned(),
                    display_label: "router_module".to_owned(),
                    freshness: FreshnessClass::Live,
                    confidence: ConfidenceClass::Exact,
                },
                TopologyNode {
                    node_id: "graph:node:src/router/handlers.rs#dispatch".to_owned(),
                    display_label: "dispatch".to_owned(),
                    freshness: FreshnessClass::Live,
                    confidence: ConfidenceClass::Exact,
                },
            ],
            edges: vec![TopologyEdge {
                edge_id: "graph:edge:router_module->dispatch".to_owned(),
                from_node_id: "graph:node:src/router/main.rs#router_module".to_owned(),
                to_node_id: "graph:node:src/router/handlers.rs#dispatch".to_owned(),
                edge_class: "calls".to_owned(),
                freshness: FreshnessClass::Live,
                confidence: ConfidenceClass::Exact,
            }],
            visible_node_count: 2,
            visible_edge_count: 1,
            out_of_scope_node_count: 0,
            out_of_scope_edge_count: 0,
            widen_scope_action_ref: None,
        }
    }

    fn sample_impact_card() -> ImpactCard {
        ImpactCard {
            card_id: "impact:router_module".to_owned(),
            subject_node_id: "graph:node:src/router/main.rs#router_module".to_owned(),
            no_impact_state: NoImpactState::VisibleImpactPresent,
            visible_impact_count: 1,
            hidden_or_out_of_scope_count: 0,
            widen_action_ref: None,
            freshness: FreshnessClass::Live,
            confidence: ConfidenceClass::Exact,
            raw_boundary_material_excluded: true,
        }
    }

    fn sample_ownership_card() -> OwnershipCard {
        OwnershipCard {
            card_id: "ownership:router_module".to_owned(),
            subject_node_id: "graph:node:src/router/main.rs#router_module".to_owned(),
            ownership_class: OwnershipClass::CuratedFirstParty,
            owner_display_label: "team:router".to_owned(),
            source_ref: "CODEOWNERS:src/router/".to_owned(),
            freshness: FreshnessClass::Live,
            confidence: ConfidenceClass::Exact,
            partiality_note: None,
            raw_boundary_material_excluded: true,
        }
    }

    fn sample_explainer_snapshot() -> ExplainerSnapshot {
        ExplainerSnapshot {
            snapshot_id: "explainer:router_module".to_owned(),
            subject_node_id: "graph:node:src/router/main.rs#router_module".to_owned(),
            source_class: ExplainerSourceClass::Curated,
            prose_ref: "docs/graph/router_module.md#overview".to_owned(),
            citations: vec![ExplainerCitation {
                citation_id: "citation:router_module".to_owned(),
                subject_ref: "graph:node:src/router/main.rs#router_module".to_owned(),
                display_label: "router_module".to_owned(),
            }],
            inference_label: None,
            evidence_opening_actions: vec![EvidenceOpeningAction {
                action_id: "action:router_module:open_source".to_owned(),
                action_class: EvidenceOpeningActionClass::OpenSourceAtAnchor,
                subject_ref: "graph:node:src/router/main.rs#router_module".to_owned(),
                preserves_scope: true,
            }],
            freshness: FreshnessClass::Live,
            confidence: ConfidenceClass::Exact,
            raw_boundary_material_excluded: true,
        }
    }

    fn sample_projection(
        surface: KnowledgeConsumerSurface,
        packet_id: &str,
    ) -> KnowledgeConsumerProjection {
        KnowledgeConsumerProjection {
            consumer_surface: surface,
            projection_ref: format!("projection:{}", surface.as_str()),
            packet_id_ref: packet_id.to_owned(),
            rendered_at: "2026-05-26T12:00:01Z".to_owned(),
            preserves_node_edge_identity: true,
            preserves_freshness_vocabulary: true,
            preserves_confidence_vocabulary: true,
            preserves_out_of_scope_count_model: true,
            preserves_widen_action: true,
            preserves_ownership_class: true,
            preserves_explainer_citations: true,
            preserves_same_packet: true,
            supports_json_export: true,
            raw_private_material_excluded: true,
            ambient_authority_excluded: true,
        }
    }

    fn baseline_input(packet_id: &str) -> KnowledgeEvidencePacketInput {
        KnowledgeEvidencePacketInput {
            packet_id: packet_id.to_owned(),
            workflow_or_surface_id: "workflow.graph.knowledge_evidence.baseline".to_owned(),
            generated_at: "2026-05-26T12:00:00Z".to_owned(),
            captured_vs_live: CapturedVsLiveClass::Live,
            shared_identity_model: sample_identity_model(),
            topology_view: sample_topology_view(),
            impact_cards: vec![sample_impact_card()],
            ownership_cards: vec![sample_ownership_card()],
            explainer_snapshots: vec![sample_explainer_snapshot()],
            consumer_projections: KnowledgeConsumerSurface::REQUIRED
                .iter()
                .copied()
                .map(|surface| sample_projection(surface, packet_id))
                .collect(),
            source_contract_refs: vec![KNOWLEDGE_EVIDENCE_PACKET_DOC_REF.to_owned()],
        }
    }

    #[test]
    fn closed_tokens_are_pinned() {
        assert_eq!(
            OwnershipClass::CuratedFirstParty.as_str(),
            "curated_first_party"
        );
        assert_eq!(OwnershipClass::PolicyDerived.as_str(), "policy_derived");
        assert_eq!(
            OwnershipClass::ImportedProviderMetadata.as_str(),
            "imported_provider_metadata"
        );
        assert_eq!(
            OwnershipClass::HeuristicInferred.as_str(),
            "heuristic_inferred"
        );
        assert_eq!(
            NoImpactState::ImpactOutsideSliceDisclosed.as_str(),
            "impact_outside_slice_disclosed"
        );
        assert_eq!(
            EvidenceOpeningActionClass::WidenScope.as_str(),
            "widen_scope"
        );
        assert_eq!(
            KnowledgeConsumerSurface::ReviewExplainerCard.as_str(),
            "review_explainer_card"
        );
        assert_eq!(ExplainerSourceClass::Generated.as_str(), "generated");
    }

    #[test]
    fn baseline_packet_certifies_stable() {
        let packet = KnowledgeEvidencePacket::materialize(baseline_input(
            "packet:m4:knowledge_evidence:baseline",
        ));
        assert_eq!(
            packet.promotion_state,
            KnowledgePromotionState::Stable,
            "unexpected findings: {:?}",
            packet
                .validation_findings
                .iter()
                .map(|finding| finding.finding_kind.as_str())
                .collect::<Vec<_>>()
        );
        assert!(packet.validation_findings.is_empty());
    }

    #[test]
    fn impact_card_collapsing_out_of_scope_blocks_stable() {
        let mut input = baseline_input("packet:m4:knowledge_evidence:no_impact_collapse");
        if let Some(card) = input.impact_cards.first_mut() {
            card.no_impact_state = NoImpactState::NoImpactInWorkspaceOrSlice;
            card.visible_impact_count = 0;
            card.hidden_or_out_of_scope_count = 3;
        }
        let packet = KnowledgeEvidencePacket::materialize(input);
        assert_eq!(
            packet.promotion_state,
            KnowledgePromotionState::BlocksStable
        );
        assert!(packet
            .validation_findings
            .iter()
            .any(|finding| finding.finding_kind
                == KnowledgeFindingKind::NoImpactCollapsedOnOutOfScopeImpact));
    }

    #[test]
    fn impact_card_missing_widen_action_blocks_stable() {
        let mut input = baseline_input("packet:m4:knowledge_evidence:missing_widen_action");
        if let Some(card) = input.impact_cards.first_mut() {
            card.no_impact_state = NoImpactState::ImpactOutsideSliceDisclosed;
            card.visible_impact_count = 0;
            card.hidden_or_out_of_scope_count = 2;
            card.widen_action_ref = None;
        }
        let packet = KnowledgeEvidencePacket::materialize(input);
        assert_eq!(
            packet.promotion_state,
            KnowledgePromotionState::BlocksStable
        );
        assert!(packet
            .validation_findings
            .iter()
            .any(|finding| finding.finding_kind
                == KnowledgeFindingKind::ImpactCardMissingWidenAction));
    }

    #[test]
    fn ownership_card_without_partiality_note_blocks_stable() {
        let mut input = baseline_input("packet:m4:knowledge_evidence:ownership_no_note");
        if let Some(card) = input.ownership_cards.first_mut() {
            card.ownership_class = OwnershipClass::HeuristicInferred;
            card.partiality_note = None;
        }
        let packet = KnowledgeEvidencePacket::materialize(input);
        assert_eq!(
            packet.promotion_state,
            KnowledgePromotionState::BlocksStable
        );
        assert!(packet
            .validation_findings
            .iter()
            .any(|finding| finding.finding_kind
                == KnowledgeFindingKind::OwnershipPartialityNoteMissing));
    }

    #[test]
    fn generated_explainer_without_citations_or_inference_label_blocks_stable() {
        let mut input = baseline_input("packet:m4:knowledge_evidence:generated_no_evidence");
        if let Some(snapshot) = input.explainer_snapshots.first_mut() {
            snapshot.source_class = ExplainerSourceClass::Generated;
            snapshot.citations.clear();
            snapshot.inference_label = None;
        }
        let packet = KnowledgeEvidencePacket::materialize(input);
        assert_eq!(
            packet.promotion_state,
            KnowledgePromotionState::BlocksStable
        );
        assert!(packet
            .validation_findings
            .iter()
            .any(|finding| finding.finding_kind
                == KnowledgeFindingKind::GeneratedExplainerMissingCitationsOrInference));
    }

    #[test]
    fn missing_consumer_projection_blocks_stable() {
        let mut input = baseline_input("packet:m4:knowledge_evidence:missing_projection");
        input.consumer_projections.pop();
        let packet = KnowledgeEvidencePacket::materialize(input);
        assert_eq!(
            packet.promotion_state,
            KnowledgePromotionState::BlocksStable
        );
        assert!(
            packet
                .validation_findings
                .iter()
                .any(|finding| finding.finding_kind
                    == KnowledgeFindingKind::MissingConsumerProjection)
        );
    }

    #[test]
    fn topology_view_with_out_of_scope_but_no_widen_action_blocks_stable() {
        let mut input = baseline_input("packet:m4:knowledge_evidence:topology_no_widen");
        input.topology_view.out_of_scope_node_count = 5;
        input.topology_view.out_of_scope_edge_count = 3;
        input.topology_view.widen_scope_action_ref = None;
        let packet = KnowledgeEvidencePacket::materialize(input);
        assert_eq!(
            packet.promotion_state,
            KnowledgePromotionState::BlocksStable
        );
        assert!(packet.validation_findings.iter().any(
            |finding| finding.finding_kind == KnowledgeFindingKind::TopologyMissingWidenAction
        ));
    }

    #[test]
    fn node_edge_identity_mismatch_blocks_stable() {
        let mut input = baseline_input("packet:m4:knowledge_evidence:identity_mismatch");
        input.topology_view.nodes.push(TopologyNode {
            node_id: "graph:node:unknown".to_owned(),
            display_label: "unknown".to_owned(),
            freshness: FreshnessClass::Live,
            confidence: ConfidenceClass::Exact,
        });
        input.topology_view.visible_node_count = input.topology_view.nodes.len();
        let packet = KnowledgeEvidencePacket::materialize(input);
        assert_eq!(
            packet.promotion_state,
            KnowledgePromotionState::BlocksStable
        );
        assert!(packet
            .validation_findings
            .iter()
            .any(|finding| finding.finding_kind == KnowledgeFindingKind::NodeEdgeIdentityMismatch));
    }
}
