//! Generated-artifact lineage records, rules, and detector.
//!
//! Every projection here works on workspace-relative, forward-slash-normalized
//! paths. Callers that hold absolute paths or platform paths must translate
//! into the workspace-relative form before consulting the detector — the
//! lineage truth never inspects the filesystem.

use serde::{Deserialize, Serialize};

/// Schema version for the seeded lineage-hint payload shape.
pub type LineageHintSchemaVersion = u32;

/// Identifies the `generated_artifact_lineage_record` record kind.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum LineageHintRecordKind {
    /// `generated_artifact_lineage_record`
    GeneratedArtifactLineageRecord,
}

/// Closed vocabulary for the kind of generated artifact a row represents.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum GeneratedArtifactClass {
    /// Lockfile (e.g., `Cargo.lock`, `package-lock.json`).
    Lockfile,
    /// Build output produced by a compiler / bundler / packager.
    BuildOutput,
    /// Generated source file co-located with hand-authored code (e.g.,
    /// `*.gen.rs`, `*_pb.rs`).
    GeneratedSourceSibling,
    /// Snapshot of third-party source vendored into the workspace.
    VendoredSnapshot,
}

impl GeneratedArtifactClass {
    /// Stable token used in records, fixtures, and shell snapshots.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Lockfile => "lockfile",
            Self::BuildOutput => "build_output",
            Self::GeneratedSourceSibling => "generated_source_sibling",
            Self::VendoredSnapshot => "vendored_snapshot",
        }
    }

    /// Short attribution badge surfaces render next to a row to disclose the
    /// generated-versus-canonical boundary.
    pub const fn badge(self) -> &'static str {
        match self {
            Self::Lockfile => "lockfile",
            Self::BuildOutput => "build output",
            Self::GeneratedSourceSibling => "generated",
            Self::VendoredSnapshot => "vendored",
        }
    }

    /// Human-readable label suitable for an explorer/search row hint.
    pub const fn label(self) -> &'static str {
        match self {
            Self::Lockfile => "Lockfile (resolver-generated; edit the manifest)",
            Self::BuildOutput => "Build output (regenerated by the producer)",
            Self::GeneratedSourceSibling => "Generated source (edit the canonical sibling)",
            Self::VendoredSnapshot => "Vendored snapshot (third-party copy; edit upstream)",
        }
    }
}

/// Closed vocabulary describing how trustworthy the lineage inference is.
///
/// Surfaces SHOULD render the freshness label directly; they MUST NOT collapse
/// `possibly_stale` into a generic "loading" badge or hide `unknown` behind a
/// silent fallback.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum LineageFreshnessClass {
    /// Lineage was derived from a co-located canonical sibling we just
    /// inspected; the generated row is expected to be in sync.
    DerivedFromCanonical,
    /// Lineage is known but freshness against the canonical source cannot be
    /// confirmed from path inspection alone.
    PossiblyStale,
    /// Vendored / mirrored snapshot. The local copy is intentionally not
    /// regenerated; surfaces should pivot to the upstream when relevant.
    SnapshotOnly,
    /// Lineage class is known but the freshness signal is unavailable.
    Unknown,
}

impl LineageFreshnessClass {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::DerivedFromCanonical => "derived_from_canonical",
            Self::PossiblyStale => "possibly_stale",
            Self::SnapshotOnly => "snapshot_only",
            Self::Unknown => "unknown",
        }
    }

    /// Short label suitable for a chrome chip.
    pub const fn label(self) -> &'static str {
        match self {
            Self::DerivedFromCanonical => "Derived",
            Self::PossiblyStale => "Possibly stale",
            Self::SnapshotOnly => "Snapshot",
            Self::Unknown => "Unknown",
        }
    }
}

/// Lineage hint emitted for one workspace-relative path.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct LineageHintRecord {
    pub record_kind: LineageHintRecordKind,
    pub schema_version: LineageHintSchemaVersion,
    /// Workspace-relative path (forward-slash) of the generated artifact.
    pub generated_relative_path: String,
    /// Generated-artifact class.
    pub generated_class: GeneratedArtifactClass,
    /// Workspace-relative path (forward-slash) of the source-canonical
    /// artifact, when known. `None` for build outputs that have no single
    /// canonical sibling and for vendored snapshots whose canonical source is
    /// upstream.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source_canonical_relative_path: Option<String>,
    /// Stable producer identifier (e.g., `producer:cargo_lockfile`).
    pub producer_id: String,
    /// Human-readable producer label for chrome.
    pub producer_label: String,
    /// Lineage freshness class.
    pub freshness_class: LineageFreshnessClass,
    /// Short explainer suitable for tooltips and a11y exports.
    pub explainer: String,
    /// Stable rule identifier that produced the hint.
    pub rule_id: String,
}

impl LineageHintRecord {
    /// Stable record-kind tag carried in serialized records.
    pub const RECORD_KIND: &'static str = "generated_artifact_lineage_record";

    /// Schema version for the seeded payload shape.
    pub const SCHEMA_VERSION: LineageHintSchemaVersion = 1;

    /// True when the hint identifies a source-canonical sibling the user can
    /// pivot to.
    pub fn has_source_canonical(&self) -> bool {
        self.source_canonical_relative_path.is_some()
    }
}

/// Rule matcher vocabulary.
///
/// Matchers operate on workspace-relative, forward-slash-normalized paths.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum RuleMatcher {
    /// Match when the basename equals the given string (case-sensitive).
    BasenameEquals { basename: String },
    /// Match when the basename ends with the given suffix (case-sensitive).
    BasenameSuffix { suffix: String },
    /// Match when the path begins with the given directory prefix
    /// (e.g. `target/`). The prefix must end with `/`.
    DirectoryPrefix { prefix: String },
}

impl RuleMatcher {
    fn matches(&self, relative_path: &str) -> bool {
        let basename = basename_of(relative_path);
        match self {
            RuleMatcher::BasenameEquals { basename: needle } => basename == needle.as_str(),
            RuleMatcher::BasenameSuffix { suffix } => basename.ends_with(suffix.as_str()),
            RuleMatcher::DirectoryPrefix { prefix } => relative_path.starts_with(prefix.as_str()),
        }
    }
}

/// How to derive the source-canonical path from the matched generated path.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum SourceCanonicalLink {
    /// No source-canonical sibling. Used for build outputs whose canonical
    /// source spans many files.
    None,
    /// Source canonical lives in the same directory as the generated artifact
    /// under the named basename (e.g. `Cargo.lock` → `Cargo.toml`).
    SiblingByName { basename: String },
    /// Source canonical is the same path with the given suffix stripped from
    /// the basename and replaced with the named replacement (e.g.
    /// `*.gen.rs` → `*.rs`).
    StripBasenameSuffix {
        suffix: String,
        replacement: String,
    },
}

impl SourceCanonicalLink {
    fn resolve(&self, relative_path: &str) -> Option<String> {
        match self {
            SourceCanonicalLink::None => None,
            SourceCanonicalLink::SiblingByName { basename } => {
                let dir = directory_of(relative_path);
                if dir.is_empty() {
                    Some(basename.clone())
                } else {
                    Some(format!("{dir}/{basename}"))
                }
            }
            SourceCanonicalLink::StripBasenameSuffix {
                suffix,
                replacement,
            } => {
                let original_basename = basename_of(relative_path);
                let stripped = original_basename.strip_suffix(suffix.as_str())?;
                let new_basename = format!("{stripped}{replacement}");
                let dir = directory_of(relative_path);
                if dir.is_empty() {
                    Some(new_basename)
                } else {
                    Some(format!("{dir}/{new_basename}"))
                }
            }
        }
    }
}

/// One generated-artifact rule.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct GeneratedArtifactRule {
    pub rule_id: String,
    pub class: GeneratedArtifactClass,
    pub matcher: RuleMatcher,
    pub source_canonical: SourceCanonicalLink,
    pub producer_id: String,
    pub producer_label: String,
    pub freshness_class: LineageFreshnessClass,
    pub explainer: String,
}

impl GeneratedArtifactRule {
    fn apply(&self, relative_path: &str) -> Option<LineageHintRecord> {
        if !self.matcher.matches(relative_path) {
            return None;
        }
        Some(LineageHintRecord {
            record_kind: LineageHintRecordKind::GeneratedArtifactLineageRecord,
            schema_version: LineageHintRecord::SCHEMA_VERSION,
            generated_relative_path: relative_path.to_string(),
            generated_class: self.class,
            source_canonical_relative_path: self.source_canonical.resolve(relative_path),
            producer_id: self.producer_id.clone(),
            producer_label: self.producer_label.clone(),
            freshness_class: self.freshness_class,
            explainer: self.explainer.clone(),
            rule_id: self.rule_id.clone(),
        })
    }
}

/// Ordered set of generated-artifact rules. The first rule that matches wins.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct GeneratedArtifactCatalog {
    rules: Vec<GeneratedArtifactRule>,
}

impl GeneratedArtifactCatalog {
    /// Empty catalog (no rules).
    pub fn new() -> Self {
        Self::default()
    }

    /// Build a catalog from an explicit rule list. The list is consumed and
    /// the first matching rule wins on detection.
    pub fn with_rules(rules: Vec<GeneratedArtifactRule>) -> Self {
        Self { rules }
    }

    /// Borrow the rule list.
    pub fn rules(&self) -> &[GeneratedArtifactRule] {
        &self.rules
    }

    /// Append an additional rule to the catalog. Useful for tests / fixtures
    /// that want to extend the default rule set without reconstructing it.
    pub fn push(&mut self, rule: GeneratedArtifactRule) {
        self.rules.push(rule);
    }

    /// Detect lineage for the given workspace-relative path. Returns `None`
    /// when no rule matches.
    pub fn detect(&self, relative_path: &str) -> Option<LineageHintRecord> {
        for rule in &self.rules {
            if let Some(hint) = rule.apply(relative_path) {
                return Some(hint);
            }
        }
        None
    }
}

/// Detect lineage against the default catalog. Convenience wrapper around
/// [`GeneratedArtifactCatalog::detect`].
pub fn detect_lineage(relative_path: &str) -> Option<LineageHintRecord> {
    default_catalog().detect(relative_path)
}

/// The M1 default rule catalog. Covers lockfiles, common build outputs, and
/// a small set of generated-source-sibling patterns. Rules are intentionally
/// conservative: a missing rule produces no hint.
pub fn default_catalog() -> GeneratedArtifactCatalog {
    GeneratedArtifactCatalog::with_rules(vec![
        // ---- Lockfiles ----------------------------------------------------
        GeneratedArtifactRule {
            rule_id: "lockfile.cargo".to_string(),
            class: GeneratedArtifactClass::Lockfile,
            matcher: RuleMatcher::BasenameEquals {
                basename: "Cargo.lock".to_string(),
            },
            source_canonical: SourceCanonicalLink::SiblingByName {
                basename: "Cargo.toml".to_string(),
            },
            producer_id: "producer:cargo_lockfile".to_string(),
            producer_label: "Cargo lockfile".to_string(),
            freshness_class: LineageFreshnessClass::DerivedFromCanonical,
            explainer: "Resolver-generated lockfile; edit Cargo.toml to change dependencies."
                .to_string(),
        },
        GeneratedArtifactRule {
            rule_id: "lockfile.npm".to_string(),
            class: GeneratedArtifactClass::Lockfile,
            matcher: RuleMatcher::BasenameEquals {
                basename: "package-lock.json".to_string(),
            },
            source_canonical: SourceCanonicalLink::SiblingByName {
                basename: "package.json".to_string(),
            },
            producer_id: "producer:npm_lockfile".to_string(),
            producer_label: "npm lockfile".to_string(),
            freshness_class: LineageFreshnessClass::DerivedFromCanonical,
            explainer: "Resolver-generated lockfile; edit package.json to change dependencies."
                .to_string(),
        },
        GeneratedArtifactRule {
            rule_id: "lockfile.yarn".to_string(),
            class: GeneratedArtifactClass::Lockfile,
            matcher: RuleMatcher::BasenameEquals {
                basename: "yarn.lock".to_string(),
            },
            source_canonical: SourceCanonicalLink::SiblingByName {
                basename: "package.json".to_string(),
            },
            producer_id: "producer:yarn_lockfile".to_string(),
            producer_label: "Yarn lockfile".to_string(),
            freshness_class: LineageFreshnessClass::DerivedFromCanonical,
            explainer: "Resolver-generated lockfile; edit package.json to change dependencies."
                .to_string(),
        },
        GeneratedArtifactRule {
            rule_id: "lockfile.pnpm".to_string(),
            class: GeneratedArtifactClass::Lockfile,
            matcher: RuleMatcher::BasenameEquals {
                basename: "pnpm-lock.yaml".to_string(),
            },
            source_canonical: SourceCanonicalLink::SiblingByName {
                basename: "package.json".to_string(),
            },
            producer_id: "producer:pnpm_lockfile".to_string(),
            producer_label: "pnpm lockfile".to_string(),
            freshness_class: LineageFreshnessClass::DerivedFromCanonical,
            explainer: "Resolver-generated lockfile; edit package.json to change dependencies."
                .to_string(),
        },
        GeneratedArtifactRule {
            rule_id: "lockfile.poetry".to_string(),
            class: GeneratedArtifactClass::Lockfile,
            matcher: RuleMatcher::BasenameEquals {
                basename: "poetry.lock".to_string(),
            },
            source_canonical: SourceCanonicalLink::SiblingByName {
                basename: "pyproject.toml".to_string(),
            },
            producer_id: "producer:poetry_lockfile".to_string(),
            producer_label: "Poetry lockfile".to_string(),
            freshness_class: LineageFreshnessClass::DerivedFromCanonical,
            explainer: "Resolver-generated lockfile; edit pyproject.toml to change dependencies."
                .to_string(),
        },
        GeneratedArtifactRule {
            rule_id: "lockfile.pipenv".to_string(),
            class: GeneratedArtifactClass::Lockfile,
            matcher: RuleMatcher::BasenameEquals {
                basename: "Pipfile.lock".to_string(),
            },
            source_canonical: SourceCanonicalLink::SiblingByName {
                basename: "Pipfile".to_string(),
            },
            producer_id: "producer:pipenv_lockfile".to_string(),
            producer_label: "Pipenv lockfile".to_string(),
            freshness_class: LineageFreshnessClass::DerivedFromCanonical,
            explainer: "Resolver-generated lockfile; edit Pipfile to change dependencies."
                .to_string(),
        },
        // ---- Build outputs ------------------------------------------------
        GeneratedArtifactRule {
            rule_id: "build_output.cargo_target".to_string(),
            class: GeneratedArtifactClass::BuildOutput,
            matcher: RuleMatcher::DirectoryPrefix {
                prefix: "target/".to_string(),
            },
            source_canonical: SourceCanonicalLink::None,
            producer_id: "producer:cargo_target".to_string(),
            producer_label: "Cargo build output".to_string(),
            freshness_class: LineageFreshnessClass::PossiblyStale,
            explainer: "Cargo build output; regenerated by `cargo build`. Not safe to edit."
                .to_string(),
        },
        GeneratedArtifactRule {
            rule_id: "build_output.dist".to_string(),
            class: GeneratedArtifactClass::BuildOutput,
            matcher: RuleMatcher::DirectoryPrefix {
                prefix: "dist/".to_string(),
            },
            source_canonical: SourceCanonicalLink::None,
            producer_id: "producer:dist_bundle".to_string(),
            producer_label: "Distribution bundle".to_string(),
            freshness_class: LineageFreshnessClass::PossiblyStale,
            explainer: "Bundler/packager output; regenerated by the build pipeline.".to_string(),
        },
        GeneratedArtifactRule {
            rule_id: "build_output.build_dir".to_string(),
            class: GeneratedArtifactClass::BuildOutput,
            matcher: RuleMatcher::DirectoryPrefix {
                prefix: "build/".to_string(),
            },
            source_canonical: SourceCanonicalLink::None,
            producer_id: "producer:build_dir".to_string(),
            producer_label: "Build directory".to_string(),
            freshness_class: LineageFreshnessClass::PossiblyStale,
            explainer: "Build-tool output directory; regenerated by the toolchain.".to_string(),
        },
        // ---- Vendored snapshots ------------------------------------------
        GeneratedArtifactRule {
            rule_id: "vendored.node_modules".to_string(),
            class: GeneratedArtifactClass::VendoredSnapshot,
            matcher: RuleMatcher::DirectoryPrefix {
                prefix: "node_modules/".to_string(),
            },
            source_canonical: SourceCanonicalLink::None,
            producer_id: "producer:npm_install".to_string(),
            producer_label: "Vendored node_modules".to_string(),
            freshness_class: LineageFreshnessClass::SnapshotOnly,
            explainer: "Materialized by the package manager; edit upstream and reinstall."
                .to_string(),
        },
        GeneratedArtifactRule {
            rule_id: "vendored.cargo_vendor".to_string(),
            class: GeneratedArtifactClass::VendoredSnapshot,
            matcher: RuleMatcher::DirectoryPrefix {
                prefix: "vendor/".to_string(),
            },
            source_canonical: SourceCanonicalLink::None,
            producer_id: "producer:cargo_vendor".to_string(),
            producer_label: "Vendored sources".to_string(),
            freshness_class: LineageFreshnessClass::SnapshotOnly,
            explainer: "Vendored third-party copy; edit upstream rather than this snapshot."
                .to_string(),
        },
        // ---- Generated source siblings -----------------------------------
        GeneratedArtifactRule {
            rule_id: "source_sibling.gen_rs".to_string(),
            class: GeneratedArtifactClass::GeneratedSourceSibling,
            matcher: RuleMatcher::BasenameSuffix {
                suffix: ".gen.rs".to_string(),
            },
            source_canonical: SourceCanonicalLink::StripBasenameSuffix {
                suffix: ".gen.rs".to_string(),
                replacement: ".rs".to_string(),
            },
            producer_id: "producer:rust_codegen".to_string(),
            producer_label: "Rust codegen".to_string(),
            freshness_class: LineageFreshnessClass::PossiblyStale,
            explainer: "Generated Rust file; the canonical sibling is the matching .rs source."
                .to_string(),
        },
        GeneratedArtifactRule {
            rule_id: "source_sibling.proto_rs".to_string(),
            class: GeneratedArtifactClass::GeneratedSourceSibling,
            matcher: RuleMatcher::BasenameSuffix {
                suffix: "_pb.rs".to_string(),
            },
            source_canonical: SourceCanonicalLink::None,
            producer_id: "producer:protoc_rust".to_string(),
            producer_label: "Proto codegen".to_string(),
            freshness_class: LineageFreshnessClass::PossiblyStale,
            explainer: "Proto-generated Rust file; the canonical source is the matching .proto."
                .to_string(),
        },
        GeneratedArtifactRule {
            rule_id: "source_sibling.generated_ts".to_string(),
            class: GeneratedArtifactClass::GeneratedSourceSibling,
            matcher: RuleMatcher::BasenameSuffix {
                suffix: ".generated.ts".to_string(),
            },
            source_canonical: SourceCanonicalLink::StripBasenameSuffix {
                suffix: ".generated.ts".to_string(),
                replacement: ".ts".to_string(),
            },
            producer_id: "producer:ts_codegen".to_string(),
            producer_label: "TypeScript codegen".to_string(),
            freshness_class: LineageFreshnessClass::PossiblyStale,
            explainer: "Generated TypeScript file; edit the canonical sibling source.".to_string(),
        },
    ])
}

fn basename_of(relative_path: &str) -> &str {
    relative_path
        .rsplit_once('/')
        .map(|(_, name)| name)
        .unwrap_or(relative_path)
}

fn directory_of(relative_path: &str) -> &str {
    relative_path
        .rsplit_once('/')
        .map(|(dir, _)| dir)
        .unwrap_or("")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cargo_lockfile_points_to_manifest_sibling() {
        let hint = detect_lineage("Cargo.lock").expect("Cargo.lock must produce a hint");
        assert_eq!(hint.generated_class, GeneratedArtifactClass::Lockfile);
        assert_eq!(
            hint.source_canonical_relative_path.as_deref(),
            Some("Cargo.toml")
        );
        assert_eq!(hint.rule_id, "lockfile.cargo");
        assert_eq!(
            hint.freshness_class,
            LineageFreshnessClass::DerivedFromCanonical
        );
    }

    #[test]
    fn nested_cargo_lockfile_resolves_relative_to_directory() {
        let hint = detect_lineage("crates/aureline-shell/Cargo.lock")
            .expect("nested Cargo.lock must produce a hint");
        assert_eq!(
            hint.source_canonical_relative_path.as_deref(),
            Some("crates/aureline-shell/Cargo.toml")
        );
    }

    #[test]
    fn target_subtree_is_build_output_without_canonical_sibling() {
        let hint = detect_lineage("target/debug/build/foo.rs")
            .expect("target subtree must produce a hint");
        assert_eq!(hint.generated_class, GeneratedArtifactClass::BuildOutput);
        assert!(hint.source_canonical_relative_path.is_none());
        assert_eq!(
            hint.freshness_class,
            LineageFreshnessClass::PossiblyStale
        );
    }

    #[test]
    fn gen_rs_strips_suffix_for_canonical_sibling() {
        let hint = detect_lineage("crates/aureline-rpc/src/api.gen.rs")
            .expect(".gen.rs must produce a hint");
        assert_eq!(
            hint.generated_class,
            GeneratedArtifactClass::GeneratedSourceSibling
        );
        assert_eq!(
            hint.source_canonical_relative_path.as_deref(),
            Some("crates/aureline-rpc/src/api.rs")
        );
    }

    #[test]
    fn vendored_node_modules_is_snapshot_only() {
        let hint = detect_lineage("node_modules/lodash/index.js")
            .expect("node_modules subtree must produce a hint");
        assert_eq!(
            hint.generated_class,
            GeneratedArtifactClass::VendoredSnapshot
        );
        assert_eq!(hint.freshness_class, LineageFreshnessClass::SnapshotOnly);
        assert!(hint.source_canonical_relative_path.is_none());
    }

    #[test]
    fn ordinary_source_file_returns_no_hint() {
        assert!(detect_lineage("src/main.rs").is_none());
        assert!(detect_lineage("README.md").is_none());
        assert!(detect_lineage("docs/notes.md").is_none());
    }

    #[test]
    fn unknown_path_with_lockfile_basename_in_subdir_still_matches() {
        let hint = detect_lineage("services/api/package-lock.json")
            .expect("nested package-lock.json must match");
        assert_eq!(
            hint.source_canonical_relative_path.as_deref(),
            Some("services/api/package.json")
        );
        assert_eq!(hint.rule_id, "lockfile.npm");
    }

    #[test]
    fn record_round_trips_through_serde() {
        let hint = detect_lineage("Cargo.lock").expect("hint must exist");
        let json = serde_json::to_string(&hint).expect("serialize");
        let parsed: LineageHintRecord = serde_json::from_str(&json).expect("parse");
        assert_eq!(parsed, hint);
    }

    #[test]
    fn empty_catalog_returns_none() {
        let catalog = GeneratedArtifactCatalog::new();
        assert!(catalog.detect("Cargo.lock").is_none());
    }

    #[test]
    fn directory_prefix_does_not_match_partial_segment() {
        // The "target" directory prefix must not greedily match a path that
        // merely starts with the literal characters "target" (e.g. a folder
        // named `targets/`).
        let hint = detect_lineage("targets/manifest.json");
        assert!(hint.is_none());
    }

    #[test]
    fn first_matching_rule_wins() {
        // Build a synthetic catalog where two rules could match the same
        // basename and confirm the first wins.
        let catalog = GeneratedArtifactCatalog::with_rules(vec![
            GeneratedArtifactRule {
                rule_id: "first.rule".to_string(),
                class: GeneratedArtifactClass::Lockfile,
                matcher: RuleMatcher::BasenameEquals {
                    basename: "test.lock".to_string(),
                },
                source_canonical: SourceCanonicalLink::None,
                producer_id: "producer:first".to_string(),
                producer_label: "First".to_string(),
                freshness_class: LineageFreshnessClass::Unknown,
                explainer: "first".to_string(),
            },
            GeneratedArtifactRule {
                rule_id: "second.rule".to_string(),
                class: GeneratedArtifactClass::Lockfile,
                matcher: RuleMatcher::BasenameSuffix {
                    suffix: ".lock".to_string(),
                },
                source_canonical: SourceCanonicalLink::None,
                producer_id: "producer:second".to_string(),
                producer_label: "Second".to_string(),
                freshness_class: LineageFreshnessClass::Unknown,
                explainer: "second".to_string(),
            },
        ]);
        let hint = catalog.detect("test.lock").expect("matches first rule");
        assert_eq!(hint.rule_id, "first.rule");
    }
}
