//! Fixture replay for the beta attention-routing corpus.
//!
//! The fixtures live under `fixtures/ux/m3/notification_routing/` and are
//! generated by the `aureline_shell_attention_router` CLI bin, so the
//! checked-in JSON stays a literal projection of the seeded
//! [`AttentionRoutingCorpus`]. These tests guard the exit-gate contract: one
//! typed route outcome per envelope, stable across surfaces, with preserved
//! reopen target, durable truth, and privacy-safe companion handoff.

use aureline_shell::attention_router::{
    seeded_attention_routing_corpus, validate_attention_routing_corpus, AttentionRouteSupportExport,
    AttentionRoutingCase, AttentionRoutingCorpus, ChannelResolutionClass, CompanionHandoffClass,
    ATTENTION_ROUTER_BETA_SCHEMA_VERSION, ATTENTION_ROUTER_BETA_SHARED_CONTRACT_REF,
};
use aureline_shell::notifications::actions::NotificationLifecycleActionKind;
use aureline_shell::notifications::envelope::FanoutSurfaceClass;

const FIXTURE_DIR: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../fixtures/ux/m3/notification_routing"
);

fn load<T: serde::de::DeserializeOwned>(filename: &str) -> T {
    let path = format!("{FIXTURE_DIR}/{filename}");
    let body =
        std::fs::read_to_string(&path).unwrap_or_else(|err| panic!("failed to read {path}: {err}"));
    serde_json::from_str(&body).unwrap_or_else(|err| panic!("failed to parse {path}: {err}"))
}

#[test]
fn corpus_fixture_matches_seeded_builder() {
    let on_disk: AttentionRoutingCorpus = load("corpus.json");
    let live = seeded_attention_routing_corpus();
    assert_eq!(
        on_disk, live,
        "fixtures must match the seeded corpus; regenerate with the headless inspector \
         (cargo run -p aureline-shell --bin aureline_shell_attention_router -- corpus)"
    );
}

#[test]
fn corpus_fixture_validates_and_carries_shared_contract() {
    let corpus: AttentionRoutingCorpus = load("corpus.json");
    assert_eq!(corpus.schema_version, ATTENTION_ROUTER_BETA_SCHEMA_VERSION);
    assert_eq!(
        corpus.shared_contract_ref,
        ATTENTION_ROUTER_BETA_SHARED_CONTRACT_REF
    );
    validate_attention_routing_corpus(&corpus).expect("corpus fixture must validate");

    // The cases fixture is the same case vector the corpus carries.
    let cases: Vec<AttentionRoutingCase> = load("cases.json");
    assert_eq!(cases, corpus.cases);
}

#[test]
fn every_outcome_keeps_one_reopen_target_and_durable_truth() {
    let corpus: AttentionRoutingCorpus = load("corpus.json");
    for case in &corpus.cases {
        let outcome = &case.outcome;
        assert!(
            outcome.all_routes_preserve_reopen_target,
            "{}: a surface diverged from the reopen target",
            case.case_id
        );
        assert!(
            outcome.durable_truth_preserved,
            "{}: durable truth was not preserved",
            case.case_id
        );
        assert!(
            outcome.no_generic_home_reopen,
            "{}: reopen target is not truthful",
            case.case_id
        );
        // No claimed beta path opens a generic home: every resolved route
        // points at the same reopen target ref the outcome carries.
        for route in &outcome.resolved_surface_routes {
            assert_eq!(
                route.reopen_target_ref, outcome.reopen_target.reopen_target_ref,
                "{}: surface {} diverged",
                case.case_id,
                route.fanout_surface_class.as_str()
            );
        }
        // The six governed verbs are published on every outcome.
        let kinds: Vec<NotificationLifecycleActionKind> = outcome
            .available_lifecycle_actions
            .iter()
            .map(|a| a.action_kind)
            .collect();
        for required in [
            NotificationLifecycleActionKind::Dismiss,
            NotificationLifecycleActionKind::Snooze,
            NotificationLifecycleActionKind::Acknowledge,
            NotificationLifecycleActionKind::Mute,
            NotificationLifecycleActionKind::Clear,
            NotificationLifecycleActionKind::Resolve,
        ] {
            assert!(
                kinds.contains(&required),
                "{}: missing governed action {required:?}",
                case.case_id
            );
        }
    }
}

#[test]
fn corpus_covers_the_full_surface_set_and_resolution_classes() {
    let corpus: AttentionRoutingCorpus = load("corpus.json");
    for surface in [
        FanoutSurfaceClass::DurableJobRow,
        FanoutSurfaceClass::StatusItem,
        FanoutSurfaceClass::ActivityCenterDigestCard,
        FanoutSurfaceClass::Toast,
        FanoutSurfaceClass::ContextualBanner,
        FanoutSurfaceClass::OsNotification,
        FanoutSurfaceClass::LockScreenSummary,
        FanoutSurfaceClass::CompanionPush,
    ] {
        assert!(
            corpus.summary.surfaces_covered.contains(&surface),
            "corpus must cover surface {}",
            surface.as_str()
        );
    }
    for class in [
        ChannelResolutionClass::DeliveredInApp,
        ChannelResolutionClass::DeliveredExternalSummary,
        ChannelResolutionClass::SuppressedForegroundRedundant,
        ChannelResolutionClass::LockScreenNotApplicable,
        ChannelResolutionClass::CompanionUnavailable,
        ChannelResolutionClass::CompanionPolicyBlocked,
        ChannelResolutionClass::HeldByQuietHoursOrFocus,
        ChannelResolutionClass::SuppressedByPolicy,
        ChannelResolutionClass::DedupedRepeat,
    ] {
        assert!(
            corpus.summary.resolution_classes_covered.contains(&class),
            "corpus must cover resolution class {}",
            class.as_str()
        );
    }
}

#[test]
fn support_export_is_privacy_safe_and_row_aligned() {
    let corpus: AttentionRoutingCorpus = load("corpus.json");
    let on_disk: AttentionRouteSupportExport = load("support_export.json");
    let live = AttentionRouteSupportExport::from_corpus(
        "support-export:attention-router-beta:001",
        "2026-05-20T00:00:00Z",
        &corpus,
    );
    assert_eq!(on_disk, live, "support export must match the seeded corpus");
    assert!(on_disk.raw_private_material_excluded);
    assert_eq!(on_disk.rows.len(), corpus.cases.len());

    // The export carries support-safe enums, never user-facing copy: the
    // serialized export must not echo any case's summary label.
    let export_json = serde_json::to_string(&on_disk).unwrap();
    for case in &corpus.cases {
        assert!(
            !export_json.contains(&case.outcome.summary_label),
            "support export leaked summary copy for {}",
            case.case_id
        );
    }
}

#[test]
fn companion_handoff_stays_summary_first_with_forbidden_shortcuts() {
    let corpus: AttentionRoutingCorpus = load("corpus.json");
    // At least one delivered companion fanout and one policy-blocked fanout.
    assert!(corpus.summary.companion_handoff_classes_covered.contains(
        &CompanionHandoffClass::SummaryFanoutDelivered
    ));
    assert!(corpus
        .summary
        .companion_handoff_classes_covered
        .contains(&CompanionHandoffClass::SummaryFanoutPolicyBlocked));
    for case in &corpus.cases {
        let handoff = &case.outcome.companion_handoff;
        assert!(handoff.summary_only, "{}: handoff not summary-only", case.case_id);
        assert!(
            handoff.reopen_into_durable_object_required,
            "{}: handoff does not require durable reopen",
            case.case_id
        );
        assert!(
            handoff.privileged_detail_requires_in_product,
            "{}: handoff allows privileged detail off the summary",
            case.case_id
        );
        assert!(
            !handoff.forbidden_shortcut_action_classes.is_empty(),
            "{}: handoff publishes no forbidden shortcut classes",
            case.case_id
        );
    }
}
