//! Fixture replay for the collection-truth corpus packet.
//!
//! Fixtures live under `fixtures/ux/m3/collection_truth_corpus/` and
//! are generated by the `aureline_shell_collection_truth_corpus`
//! headless inspector. The matrix is duplicated under
//! `artifacts/qe/m3/collection_truth_matrix.json` so QE can pivot
//! without re-running the binary.

use aureline_shell::collection_truth::CollectionTruthSurfaceFamily;
use aureline_shell::collection_truth_corpus::{
    render_collection_truth_corpus_drills_markdown, render_collection_truth_corpus_report_markdown,
    seeded_collection_truth_corpus_packet, validate_collection_truth_corpus_packet,
    CollectionTruthAccessibilityDrill, CollectionTruthAccessibilityDrillClass,
    CollectionTruthCorpusCase, CollectionTruthCorpusPacket, CollectionTruthEdgeCaseClass,
    CollectionTruthMatrix, CollectionTruthSupportExport, SavedViewMigrationCase,
    SavedViewMigrationCaseClass, COLLECTION_TRUTH_CORPUS_SCHEMA_VERSION,
    COLLECTION_TRUTH_CORPUS_SHARED_CONTRACT_REF,
};

const FIXTURE_DIR: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../fixtures/ux/m3/collection_truth_corpus"
);

const ARTIFACT_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../../artifacts/qe/m3");

const DOCS_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../../docs/qe/m3");

fn load<T: serde::de::DeserializeOwned>(path: &str) -> T {
    let body =
        std::fs::read_to_string(path).unwrap_or_else(|err| panic!("failed to read {path}: {err}"));
    serde_json::from_str(&body).unwrap_or_else(|err| panic!("failed to parse {path}: {err}"))
}

#[test]
fn fixture_packet_matches_seeded_builder() {
    let on_disk: CollectionTruthCorpusPacket = load(&format!("{FIXTURE_DIR}/packet.json"));
    let live = seeded_collection_truth_corpus_packet();
    assert_eq!(
        on_disk, live,
        "fixture corpus packet must match the seeded packet"
    );
    assert_eq!(
        on_disk.shared_contract_ref,
        COLLECTION_TRUTH_CORPUS_SHARED_CONTRACT_REF
    );
    assert_eq!(
        on_disk.schema_version,
        COLLECTION_TRUTH_CORPUS_SCHEMA_VERSION
    );
    validate_collection_truth_corpus_packet(&on_disk).expect("fixture corpus packet must validate");
}

#[test]
fn per_record_fixture_files_round_trip_through_shared_types() {
    let packet = seeded_collection_truth_corpus_packet();
    let cases: Vec<CollectionTruthCorpusCase> = load(&format!("{FIXTURE_DIR}/corpus_cases.json"));
    let migrations: Vec<SavedViewMigrationCase> =
        load(&format!("{FIXTURE_DIR}/saved_view_migrations.json"));
    let drills: Vec<CollectionTruthAccessibilityDrill> =
        load(&format!("{FIXTURE_DIR}/accessibility_drills.json"));
    let support_export: CollectionTruthSupportExport =
        load(&format!("{FIXTURE_DIR}/support_export.json"));
    let matrix: CollectionTruthMatrix = load(&format!("{FIXTURE_DIR}/matrix.json"));
    assert_eq!(cases, packet.corpus_cases);
    assert_eq!(migrations, packet.saved_view_migrations);
    assert_eq!(drills, packet.accessibility_drills);
    assert_eq!(support_export, packet.support_export);
    assert_eq!(matrix, packet.matrix);
}

#[test]
fn fixtures_cover_every_surface_family_edge_case_class_and_drill() {
    let packet: CollectionTruthCorpusPacket = load(&format!("{FIXTURE_DIR}/packet.json"));
    for required in CollectionTruthSurfaceFamily::all() {
        assert!(
            packet
                .coverage_summary
                .surface_families_present
                .contains(&required),
            "missing surface family {}",
            required.as_str()
        );
    }
    for required in CollectionTruthEdgeCaseClass::all() {
        assert!(
            packet
                .coverage_summary
                .edge_case_classes_present
                .contains(&required),
            "missing edge case class {}",
            required.as_str()
        );
    }
    for required in SavedViewMigrationCaseClass::all() {
        assert!(
            packet
                .coverage_summary
                .saved_view_migration_classes_present
                .contains(&required),
            "missing migration class {}",
            required.as_str()
        );
    }
    for required in CollectionTruthAccessibilityDrillClass::all() {
        assert!(
            packet
                .coverage_summary
                .drill_classes_present
                .contains(&required),
            "missing drill class {}",
            required.as_str()
        );
    }
}

#[test]
fn matrix_artifact_matches_corpus_matrix_fixture() {
    let fixture_matrix: CollectionTruthMatrix = load(&format!("{FIXTURE_DIR}/matrix.json"));
    let artifact_matrix: CollectionTruthMatrix =
        load(&format!("{ARTIFACT_DIR}/collection_truth_matrix.json"));
    assert_eq!(
        fixture_matrix, artifact_matrix,
        "fixture matrix and artifact matrix must stay in sync"
    );
}

#[test]
fn report_markdown_artifact_matches_seeded_render() {
    let packet = seeded_collection_truth_corpus_packet();
    let expected = render_collection_truth_corpus_report_markdown(&packet);
    let on_disk = std::fs::read_to_string(format!("{ARTIFACT_DIR}/collection_truth_report.md"))
        .expect("collection_truth_report.md must exist");
    assert_eq!(
        on_disk, expected,
        "checked-in collection_truth_report.md must match the seeded render"
    );
}

#[test]
fn drills_markdown_artifact_matches_seeded_render() {
    let packet = seeded_collection_truth_corpus_packet();
    let expected = render_collection_truth_corpus_drills_markdown(&packet);
    let on_disk = std::fs::read_to_string(format!("{DOCS_DIR}/collection_truth_drills.md"))
        .expect("collection_truth_drills.md must exist");
    assert_eq!(
        on_disk, expected,
        "checked-in collection_truth_drills.md must match the seeded render"
    );
}

#[test]
fn support_export_leaks_no_sensitive_payload() {
    let packet: CollectionTruthCorpusPacket = load(&format!("{FIXTURE_DIR}/packet.json"));
    assert!(packet.support_export.no_sensitive_payload);
    for row in &packet.support_export.selected_id_classes {
        for id in row
            .selected_row_ids
            .iter()
            .chain(row.hidden_selected_row_ids.iter())
        {
            assert!(
                id.starts_with("row:") && !id.contains('\n'),
                "selected row ids must be redaction-safe slugs, not payloads: {id}"
            );
        }
    }
    for row in &packet.support_export.blocked_or_skipped_reasoning {
        for id in &row.blocked_row_ids {
            assert!(
                id.starts_with("row:"),
                "blocked row ids must be redaction-safe slugs: {id}"
            );
        }
    }
}
