//! Protected fixture checks for the beta command-palette diagnostics pack.
//!
//! The checked-in JSON under `fixtures/ux/m3/command_palette_diagnostics/`
//! is generated by `aureline_shell_command_palette_diagnostics`, then replayed
//! here through the shared Rust types so docs, fixtures, support export, and
//! parity examples cannot drift.

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

use aureline_shell::palette::{
    seeded_beta_command_palette_diagnostics_pack,
    seeded_beta_command_palette_diagnostics_support_export,
    seeded_beta_palette_parity_examples_artifact, validate_beta_command_palette_diagnostics_pack,
    validate_beta_command_palette_diagnostics_support_export,
    validate_beta_palette_parity_examples_artifact, BetaCommandPaletteDiagnosticRow,
    BetaCommandPaletteDiagnosticsPack, BetaCommandPaletteDiagnosticsSupportExport,
    BetaPaletteParityExamplesArtifact, COMMAND_PALETTE_DIAGNOSTICS_RECORD_KIND,
    COMMAND_PALETTE_DIAGNOSTICS_SUPPORT_EXPORT_RECORD_KIND, PALETTE_PARITY_EXAMPLES_RECORD_KIND,
};

fn fixture_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../fixtures/ux/m3/command_palette_diagnostics")
}

fn artifact_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../artifacts/commands/m3")
}

fn docs_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../docs/ux/m3")
}

fn load_fixture<T: serde::de::DeserializeOwned>(filename: &str) -> T {
    let path = fixture_root().join(filename);
    let payload = std::fs::read_to_string(&path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", path.display()));
    serde_json::from_str(&payload)
        .unwrap_or_else(|err| panic!("failed to parse {}: {err}", path.display()))
}

fn load_artifact<T: serde::de::DeserializeOwned>(filename: &str) -> T {
    let path = artifact_root().join(filename);
    let payload = std::fs::read_to_string(&path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", path.display()));
    serde_json::from_str(&payload)
        .unwrap_or_else(|err| panic!("failed to parse {}: {err}", path.display()))
}

fn row_by_case<'a>(
    pack: &'a BetaCommandPaletteDiagnosticsPack,
    case_id: &str,
) -> &'a BetaCommandPaletteDiagnosticRow {
    pack.rows
        .iter()
        .find(|row| row.case_id == case_id)
        .unwrap_or_else(|| panic!("missing row case {case_id}"))
}

#[test]
fn fixtures_are_bit_for_bit_equal_to_seeded_records() {
    let pack: BetaCommandPaletteDiagnosticsPack = load_fixture("page.json");
    let support_export: BetaCommandPaletteDiagnosticsSupportExport =
        load_fixture("support_export.json");
    let parity_examples: BetaPaletteParityExamplesArtifact =
        load_artifact("palette_parity_examples.json");

    assert_eq!(pack, seeded_beta_command_palette_diagnostics_pack());
    assert_eq!(
        support_export,
        seeded_beta_command_palette_diagnostics_support_export()
    );
    assert_eq!(
        parity_examples,
        seeded_beta_palette_parity_examples_artifact()
    );
    assert_eq!(pack.record_kind, COMMAND_PALETTE_DIAGNOSTICS_RECORD_KIND);
    assert_eq!(
        support_export.record_kind,
        COMMAND_PALETTE_DIAGNOSTICS_SUPPORT_EXPORT_RECORD_KIND
    );
    assert_eq!(
        parity_examples.record_kind,
        PALETTE_PARITY_EXAMPLES_RECORD_KIND
    );
}

#[test]
fn fixture_pack_passes_acceptance_contract() {
    let pack: BetaCommandPaletteDiagnosticsPack = load_fixture("page.json");
    validate_beta_command_palette_diagnostics_pack(&pack).expect("pack fixture must validate");

    assert_eq!(pack.summary.row_count, 7);
    assert_eq!(pack.summary.command_row_count, pack.rows.len());
    assert_eq!(pack.summary.deep_link_review_count, 3);
    assert_eq!(pack.warm_open_budget.target_ms, 50);
    assert!(pack.warm_open_budget.claimed_rows_under_budget);
    assert!(pack.history_policy.local_first);
    assert!(pack.history_policy.support_export_omits_raw_query_text);

    let cause_families = pack
        .summary
        .disabled_cause_families
        .iter()
        .map(String::as_str)
        .collect::<BTreeSet<_>>();
    for required in [
        "trust",
        "policy",
        "missing_dependency",
        "degraded_provider",
        "wrong_focus",
        "preview_or_approval",
        "unsupported_surface",
    ] {
        assert!(cause_families.contains(required), "missing {required}");
    }

    let modifier_actions = pack
        .summary
        .modifier_action_classes
        .iter()
        .map(String::as_str)
        .collect::<BTreeSet<_>>();
    for required in [
        "primary_run_or_open",
        "open_invocation_preview",
        "split_or_alternate_open",
        "copy_command_id",
        "copy_cli_headless_form",
        "add_to_recipe",
        "inspect_why_not_automatable",
    ] {
        assert!(modifier_actions.contains(required), "missing {required}");
    }
}

#[test]
fn rows_preserve_anatomy_footer_and_preview_truth() {
    let pack: BetaCommandPaletteDiagnosticsPack = load_fixture("page.json");

    for row in &pack.rows {
        assert!(row.command_id.starts_with("cmd:"), "{}", row.case_id);
        assert!(!row.label.trim().is_empty(), "{}", row.case_id);
        assert!(!row.category_or_path.trim().is_empty(), "{}", row.case_id);
        assert!(
            !row.origin_source_badge.trim().is_empty(),
            "{}",
            row.case_id
        );
        assert!(!row.winning_keybinding.trim().is_empty(), "{}", row.case_id);
        assert!(
            !row.dominant_side_effect_class.trim().is_empty(),
            "{}",
            row.case_id
        );
        assert!(!row.automation_labels.is_empty(), "{}", row.case_id);
        assert!(!row.automation_cues.is_empty(), "{}", row.case_id);
        assert_eq!(
            row.preview.descriptor_command_id.as_deref(),
            Some(row.command_id.as_str())
        );
        assert_eq!(
            row.preview.side_effect_class,
            row.dominant_side_effect_class
        );
        assert_eq!(
            row.action_footer.copy_command_id.copy_payload.as_deref(),
            Some(row.command_id.as_str())
        );

        if row.disabled_reason_code.is_some() {
            assert!(
                row.action_footer.command_diagnostics_sheet_available,
                "{} must expose diagnostics sheet",
                row.case_id
            );
        }
    }

    let open = row_by_case(&pack, "palette-diagnostics:row:enabled_open_folder");
    assert_eq!(open.winning_keybinding, "Cmd+O");
    assert_eq!(open.availability_class, "enabled");
    assert!(!open.action_footer.inspect_why_not_automatable.enabled);
    assert_eq!(
        open.action_footer
            .inspect_why_not_automatable
            .unavailable_reason
            .as_deref(),
        Some("command_is_automation_safe")
    );

    let missing = row_by_case(
        &pack,
        "palette-diagnostics:row:missing_execution_context_open_folder",
    );
    assert_eq!(
        missing.disabled_reason_code.as_deref(),
        Some("execution_context_unavailable")
    );
    assert!(missing.action_footer.command_diagnostics_sheet_available);

    let provider = row_by_case(&pack, "palette-diagnostics:row:degraded_provider_clone");
    assert_eq!(
        provider.disabled_reason_code.as_deref(),
        Some("required_provider_unlinked")
    );
    assert_eq!(provider.winning_keybinding, "Unassigned");

    let import = row_by_case(
        &pack,
        "palette-diagnostics:row:preview_required_import_profile",
    );
    assert_eq!(import.availability_class, "preview_required");
    assert!(import.action_footer.invocation_preview_required);
    assert_eq!(
        import.action_footer.default_action.action_class,
        "open_invocation_preview"
    );
    assert!(import
        .automation_labels
        .iter()
        .any(|label| label == "approval_required"));
}

#[test]
fn deep_links_preserve_no_bypass_guards() {
    let pack: BetaCommandPaletteDiagnosticsPack = load_fixture("page.json");
    assert!(pack.summary.every_deep_link_preserves_no_bypass_guards);

    for review in &pack.deep_link_reviews {
        assert!(review.no_bypass_guards.trust_revalidation_required);
        assert!(review.no_bypass_guards.policy_revalidation_required);
        assert!(
            review
                .no_bypass_guards
                .permission_prompt_revalidation_required
        );
        assert!(review.no_bypass_guards.preview_path_preserved);
        assert!(review.no_bypass_guards.approval_path_preserved);
        assert!(
            review
                .no_bypass_guards
                .credential_broker_revalidation_required
        );
        assert!(
            review
                .no_bypass_guards
                .execution_context_revalidation_required
        );
        assert!(
            review
                .no_bypass_guards
                .freshness_floor_revalidation_required
        );
        assert!(review.no_bypass_guards.capability_class_may_not_widen);
        assert!(review.no_bypass_guards.result_schema_may_not_be_replaced);
        assert_ne!(
            review.route_outcome_class,
            "dispatch_allowed_without_preflight"
        );
    }

    let preview = pack
        .deep_link_reviews
        .iter()
        .find(|review| {
            review.case_id == "palette-diagnostics:deeplink:preview_required_import_profile"
        })
        .expect("preview deep-link review");
    assert!(preview.invocation_preview_sheet_present);
    assert_eq!(preview.preview_shown, Some(true));
    assert_eq!(preview.approval_state.as_deref(), Some("approval_pending"));
}

#[test]
fn support_export_is_metadata_safe_and_reopenable() {
    let export: BetaCommandPaletteDiagnosticsSupportExport = load_fixture("support_export.json");
    validate_beta_command_palette_diagnostics_support_export(&export)
        .expect("support export fixture must validate");
    assert_eq!(export.row_count, 7);
    assert!(export
        .disabled_reason_codes
        .iter()
        .any(|reason| reason == "client_scope_excludes_surface"));
    assert!(export
        .disabled_reason_codes
        .iter()
        .any(|reason| reason == "execution_context_unavailable"));
    assert!(export
        .reopen_refs
        .iter()
        .any(|item| item == "docs/ux/m3/command_palette_diagnostics_beta.md"));

    let path = fixture_root().join("support_export.json");
    let raw_value: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(&path)
            .unwrap_or_else(|err| panic!("failed to read {}: {err}", path.display())),
    )
    .expect("support export must parse as JSON");
    assert!(
        !value_has_object_key(&raw_value, "raw_query_text"),
        "support export must not expose a raw_query_text field"
    );
}

#[test]
fn parity_examples_validate_and_use_unique_ids() {
    let artifact: BetaPaletteParityExamplesArtifact = load_artifact("palette_parity_examples.json");
    validate_beta_palette_parity_examples_artifact(&artifact)
        .expect("parity artifact fixture must validate");
    assert_eq!(artifact.examples.len(), 7);

    let mut ids = BTreeSet::new();
    for example in &artifact.examples {
        assert!(ids.insert(example.example_id.as_str()));
        assert!(example.preview_and_approval_preserved);
        assert!(example.disabled_reason_explainable);
        for surface in [
            "command_palette",
            "menu_or_button",
            "keybinding_help",
            "onboarding_hint",
            "cli_headless",
            "ai_tool_surface",
            "support_export",
        ] {
            assert!(
                example.surface_families.iter().any(|item| item == surface),
                "{} missing {surface}",
                example.example_id
            );
        }
    }
}

#[test]
fn docs_and_readme_quote_the_generated_artifacts() {
    let doc_path = docs_root().join("command_palette_diagnostics_beta.md");
    let doc = std::fs::read_to_string(&doc_path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", doc_path.display()));
    for needle in [
        "fixtures/ux/m3/command_palette_diagnostics/page.json",
        "fixtures/ux/m3/command_palette_diagnostics/support_export.json",
        "artifacts/commands/m3/palette_parity_examples.json",
        "aureline_shell_command_palette_diagnostics -- validate",
    ] {
        assert!(doc.contains(needle), "doc missing {needle}");
    }

    let readme_path = fixture_root().join("README.md");
    let readme = std::fs::read_to_string(&readme_path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", readme_path.display()));
    assert!(readme.contains("page.json"));
    assert!(readme.contains("support_export.json"));
    assert!(readme.contains("palette_parity_examples.json"));
}

fn value_has_object_key(value: &serde_json::Value, key: &str) -> bool {
    match value {
        serde_json::Value::Object(map) => {
            map.contains_key(key) || map.values().any(|value| value_has_object_key(value, key))
        }
        serde_json::Value::Array(values) => {
            values.iter().any(|value| value_has_object_key(value, key))
        }
        _ => false,
    }
}
