//! Fixture replay for the scoped companion and desktop-handoff beta contract.
//!
//! The fixtures live under `fixtures/ux/m3/companion_scope/` and are
//! generated by the `aureline_shell_companion_scope` headless inspector so the
//! checked-in JSON stays a literal projection of the seeded
//! `CompanionScopeBetaPage`.

use aureline_shell::companion_handoff::{
    audit_companion_scope_beta_rows, seeded_companion_scope_beta_page,
    validate_companion_scope_beta_page, validate_companion_scope_beta_support_export,
    ApprovalOwnerSurfaceClass, CompanionFreshnessClass, CompanionScopeBetaPage,
    CompanionScopeBetaRow, CompanionScopeBetaSupportExport, CompanionScopeBetaSupportRow,
    CompanionScopeDefectKind, CompanionWorkflowClass, DesktopHandoffRequirementClass,
    COMPANION_SCOPE_BETA_SCHEMA_VERSION, COMPANION_SCOPE_BETA_SHARED_CONTRACT_REF,
};

const FIXTURE_DIR: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../fixtures/ux/m3/companion_scope"
);

fn load<T: serde::de::DeserializeOwned>(filename: &str) -> T {
    let path = format!("{}/{}", FIXTURE_DIR, filename);
    let body =
        std::fs::read_to_string(&path).unwrap_or_else(|err| panic!("failed to read {path}: {err}"));
    serde_json::from_str(&body).unwrap_or_else(|err| panic!("failed to parse {path}: {err}"))
}

#[test]
fn page_fixture_matches_seeded_builder() {
    let from_file: CompanionScopeBetaPage = load("page.json");
    let from_code = seeded_companion_scope_beta_page();
    assert_eq!(
        from_file, from_code,
        "fixture must be a literal projection of the seeded page; regenerate through the headless inspector"
    );
}

#[test]
fn page_fixture_validates_and_covers_claimed_rows() {
    let page: CompanionScopeBetaPage = load("page.json");
    assert_eq!(
        page.shared_contract_ref,
        COMPANION_SCOPE_BETA_SHARED_CONTRACT_REF
    );
    assert_eq!(page.schema_version, COMPANION_SCOPE_BETA_SCHEMA_VERSION);
    assert!(page.defects.is_empty());
    assert!(page.covers_required_workflows());
    validate_companion_scope_beta_page(&page).expect("page must validate");

    for required in [
        CompanionWorkflowClass::ReviewTriage,
        CompanionWorkflowClass::DocsAndHelp,
        CompanionWorkflowClass::LightRemoteEdit,
        CompanionWorkflowClass::RemoteSessionJoin,
        CompanionWorkflowClass::CiStatus,
        CompanionWorkflowClass::IncidentAwareness,
    ] {
        assert!(
            page.rows.iter().any(|row| row.workflow == required),
            "page must include workflow {}",
            required.as_str()
        );
    }
}

#[test]
fn rows_keep_scope_target_freshness_and_non_promises_visible() {
    let rows: Vec<CompanionScopeBetaRow> = load("rows.json");
    assert_eq!(rows.len(), 6);

    for row in &rows {
        assert_eq!(
            row.shared_contract_ref,
            COMPANION_SCOPE_BETA_SHARED_CONTRACT_REF
        );
        assert_eq!(row.workflow_token, row.workflow.as_str());
        assert_eq!(row.client_scope_token, row.client_scope_label.as_str());
        assert!(row.labels.client_scope_label_visible);
        assert!(row.target_identity.target_identity_label_visible);
        assert!(row.labels.target_identity_label_visible);
        assert!(!row.target_identity.target_object_ref.is_empty());
        assert!(!row.target_identity.execution_context_ref.is_empty());
        assert!(row.raw_private_material_excluded);

        assert!(!row.explicit_non_promises.desktop_parity_claimed);
        assert!(!row.explicit_non_promises.unmanaged_secret_entry_allowed);
        assert!(!row.explicit_non_promises.deep_local_project_editing_allowed);
        assert!(
            !row.explicit_non_promises
                .terminal_or_debugger_parity_claimed
        );
        assert!(!row.explicit_non_promises.admin_console_replacement_claimed);

        if !matches!(
            row.freshness.freshness_class,
            CompanionFreshnessClass::LiveAuthoritativeFreshWithinGrace
        ) {
            assert!(
                row.freshness.stale_or_offline_label_visible,
                "{} must show stale/offline/warm snapshot truth",
                row.row_id
            );
            assert!(row.labels.freshness_label_visible);
            assert!(!row.freshness.live_claim_permitted);
        }

        assert!(
            row.labels.read_only_label_visible || row.labels.desktop_handoff_label_visible,
            "{} must show read-only or desktop-handoff state",
            row.row_id
        );
    }
}

#[test]
fn desktop_handoff_is_mandatory_for_high_authority_reasons() {
    let rows: Vec<CompanionScopeBetaRow> = load("rows.json");
    for row in &rows {
        let high_authority = row.desktop_handoff.reason_classes.iter().any(|reason| {
            matches!(
                reason,
                DesktopHandoffRequirementClass::BroadMutation
                    | DesktopHandoffRequirementClass::ProtectedApproval
                    | DesktopHandoffRequirementClass::SensitiveAdminFlow
                    | DesktopHandoffRequirementClass::HighRiskPublish
                    | DesktopHandoffRequirementClass::UnmanagedSecretEntry
                    | DesktopHandoffRequirementClass::DeepLocalProjectEditing
                    | DesktopHandoffRequirementClass::NativeDepthWorkflow
            )
        });
        if high_authority {
            assert!(row.desktop_handoff.mandatory_desktop_handoff);
            assert!(row.desktop_handoff.desktop_handoff_ref.is_some());
            assert!(row.desktop_handoff.handoff_preserves_target_identity);
            assert_eq!(
                row.authority.step_up.approval_owner_surface,
                ApprovalOwnerSurfaceClass::NativeDesktopReviewSurface
            );
            assert!(!row.authority.companion_can_grant_approval);
        }
    }
}

#[test]
fn companion_fanout_inherits_device_policy_and_quiet_hours() {
    let rows: Vec<CompanionScopeBetaRow> = load("rows.json");
    for row in &rows {
        assert!(row.notification_fanout.device_policy_inherited);
        assert!(row.notification_fanout.quiet_hours_inherited);
        assert!(row.notification_fanout.hidden_attention_spam_prevented);
        assert!(row.notification_fanout.shortcut_bypass_forbidden);
        assert!(!row.notification_fanout.fanout_dedupe_key_ref.is_empty());
        assert!(!row.notification_fanout.exact_reopen_target_ref.is_empty());
    }
}

#[test]
fn support_export_preserves_reconstruction_provenance() {
    let page: CompanionScopeBetaPage = load("page.json");
    let support_rows: Vec<CompanionScopeBetaSupportRow> = load("support_rows.json");
    assert_eq!(support_rows, page.support_rows);

    for support in &support_rows {
        let row = page
            .rows
            .iter()
            .find(|row| row.row_id == support.row_id)
            .unwrap_or_else(|| panic!("support row {} missing source row", support.row_id));
        assert_eq!(
            support.target_object_ref,
            row.target_identity.target_object_ref
        );
        assert_eq!(
            support.canonical_event_id_ref,
            row.provenance.canonical_event_id_ref
        );
        assert_eq!(
            support.approval_owner_surface_token,
            row.authority.step_up.approval_owner_surface.as_str()
        );
        assert_eq!(
            support.desktop_handoff_destination_ref,
            row.provenance.desktop_handoff_destination_ref
        );
    }

    let export: CompanionScopeBetaSupportExport = load("support_export.json");
    validate_companion_scope_beta_support_export(&export).expect("support export must validate");
    assert!(export.raw_private_material_excluded);
    assert!(export.defect_kinds_present.is_empty());
    assert_eq!(export.rows, page.support_rows);
}

#[test]
fn drill_fixtures_replay_typed_defects() {
    let stale: CompanionScopeBetaPage = load("drill_stale_label_missing.json");
    let stale_defects = audit_companion_scope_beta_rows(&stale.rows, &stale.support_rows);
    assert_eq!(stale_defects, stale.defects);
    assert!(stale_defects
        .iter()
        .any(|defect| defect.defect_kind == CompanionScopeDefectKind::StaleOfflineLabelMissing));

    let approval: CompanionScopeBetaPage = load("drill_companion_owns_protected_approval.json");
    let approval_defects = audit_companion_scope_beta_rows(&approval.rows, &approval.support_rows);
    assert_eq!(approval_defects, approval.defects);
    assert!(approval_defects.iter().any(|defect| {
        defect.defect_kind == CompanionScopeDefectKind::CompanionOwnsProtectedApproval
    }));
}
