//! Fixture replay for the beta debugger daily-use surfaces.
//!
//! The fixtures under `fixtures/runtime/m3/debug_ui/` are generated by
//! the `aureline_shell_debug_ui` headless inspector so the checked-in
//! JSON stays a literal projection of the seeded module (no
//! hand-written drift). This test rebuilds each seed from code,
//! diff-checks the fixture, and exercises the three named failure
//! drills referenced by the beta exit gate.

use aureline_shell::debug_ui::{
    seeded_no_session_drill_projection, seeded_protected_walk_projection,
    seeded_reconnect_drill_projection, validate_debug_ui_projection, DebugUiAvailabilityClass,
    DebugUiDefectKind, DebugUiFocusReturnClass, DebugUiProjection, DebugUiSupportExport,
    DebugUiSurfaceClass, SourceJumpStabilityClass, DEBUG_UI_BETA_PROJECTION_RECORD_KIND,
    DEBUG_UI_BETA_SHARED_CONTRACT_REF, DEBUG_UI_BETA_SUPPORT_EXPORT_RECORD_KIND,
};

const FIXTURE_DIR: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../fixtures/runtime/m3/debug_ui"
);

fn load<T: serde::de::DeserializeOwned>(filename: &str) -> T {
    let path = format!("{}/{}", FIXTURE_DIR, filename);
    let body = std::fs::read_to_string(&path)
        .unwrap_or_else(|err| panic!("failed to read {path}: {err}"));
    serde_json::from_str(&body).unwrap_or_else(|err| panic!("failed to parse {path}: {err}"))
}

#[test]
fn protected_walk_fixture_matches_seeded_builder() {
    let from_file: DebugUiProjection = load("protected_walk_paused.json");
    let from_code = seeded_protected_walk_projection();
    assert_eq!(
        from_file, from_code,
        "fixture must be a literal projection of the seeded module; regenerate via the headless bin"
    );
    assert_eq!(from_file.record_kind, DEBUG_UI_BETA_PROJECTION_RECORD_KIND);
    assert_eq!(from_file.shared_contract_ref, DEBUG_UI_BETA_SHARED_CONTRACT_REF);
    validate_debug_ui_projection(&from_file).expect("protected walk validates");
}

#[test]
fn reconnect_fixture_matches_seeded_builder_and_blanks_surfaces() {
    let from_file: DebugUiProjection = load("reconnecting_after_adapter_crash.json");
    let from_code = seeded_reconnect_drill_projection();
    assert_eq!(from_file, from_code);
    for row in &from_file.surfaces {
        assert!(matches!(
            row.availability_class,
            DebugUiAvailabilityClass::UnavailableDuringReconnect
        ));
        assert!(matches!(
            row.source_jump_stability_class,
            SourceJumpStabilityClass::UnstableDuringReconnect
        ));
        assert!(matches!(
            row.focus_return_class,
            DebugUiFocusReturnClass::SessionCard
        ));
        assert_eq!(row.content_row_count, 0);
    }
    assert!(from_file.honesty_marker_present);
    validate_debug_ui_projection(&from_file).expect("reconnect drill validates");
}

#[test]
fn no_session_fixture_matches_seeded_builder_and_offers_no_jumps() {
    let from_file: DebugUiProjection = load("no_active_session.json");
    let from_code = seeded_no_session_drill_projection();
    assert_eq!(from_file, from_code);
    assert!(from_file.active_binding.is_empty());
    for row in &from_file.surfaces {
        assert!(matches!(
            row.availability_class,
            DebugUiAvailabilityClass::UnavailableNoActiveSession
        ));
        assert!(matches!(
            row.source_jump_stability_class,
            SourceJumpStabilityClass::NotOfferedNoSession
        ));
    }
    assert!(!from_file.honesty_marker_present);
    validate_debug_ui_projection(&from_file).expect("no-session drill validates");
}

#[test]
fn protected_walk_fixture_keeps_content_bound_to_active_session() {
    let projection: DebugUiProjection = load("protected_walk_paused.json");
    let binding = &projection.active_binding;
    assert!(!binding.session_id.is_empty());
    assert!(!binding.canonical_target_id.is_empty());
    for row in &projection.breakpoints {
        assert_eq!(row.session_id, binding.session_id);
        assert_eq!(row.canonical_target_id, binding.canonical_target_id);
    }
    for row in &projection.call_stack_frames {
        assert_eq!(row.session_id, binding.session_id);
        assert_eq!(row.canonical_target_id, binding.canonical_target_id);
    }
    for row in &projection.variable_scopes {
        assert_eq!(row.session_id, binding.session_id);
        assert_eq!(row.canonical_target_id, binding.canonical_target_id);
    }
    for row in &projection.watch_expressions {
        assert_eq!(row.session_id, binding.session_id);
        assert_eq!(row.canonical_target_id, binding.canonical_target_id);
    }
    for row in &projection.evaluate_requests {
        assert_eq!(row.session_id, binding.session_id);
        assert_eq!(row.canonical_target_id, binding.canonical_target_id);
    }
    for row in &projection.console_lines {
        assert_eq!(row.session_id, binding.session_id);
        assert_eq!(row.canonical_target_id, binding.canonical_target_id);
    }
}

#[test]
fn fixtures_cover_every_required_surface_in_canonical_order() {
    let projection: DebugUiProjection = load("protected_walk_paused.json");
    let actual: Vec<DebugUiSurfaceClass> = projection
        .surfaces
        .iter()
        .map(|r| r.surface_class)
        .collect();
    assert_eq!(actual, DebugUiSurfaceClass::required_surfaces().to_vec());
}

#[test]
fn support_export_fixture_round_trips_through_typed_wrapper() {
    let from_file: DebugUiSupportExport = load("support_export.json");
    assert_eq!(from_file.record_kind, DEBUG_UI_BETA_SUPPORT_EXPORT_RECORD_KIND);
    assert!(from_file.raw_private_material_excluded);
    assert_eq!(from_file.projection, seeded_protected_walk_projection());
    assert_eq!(
        from_file
            .availability_counts
            .get("available")
            .copied()
            .unwrap_or_default()
            + from_file
                .availability_counts
                .get("narrowed_by_dropped_capability")
                .copied()
                .unwrap_or_default(),
        6
    );
}

#[test]
fn drill_hidden_capability_downgrade_is_detected() {
    let mut projection: DebugUiProjection = load("protected_walk_paused.json");
    for row in projection.surfaces.iter_mut() {
        if row.surface_class_token == "breakpoints" {
            row.availability_class = DebugUiAvailabilityClass::Available;
            row.availability_class_token =
                DebugUiAvailabilityClass::Available.as_str().to_owned();
        }
    }
    let defects = validate_debug_ui_projection(&projection)
        .expect_err("validator must flag the hidden downgrade");
    assert!(defects.iter().any(|d| matches!(
        d.defect_kind,
        DebugUiDefectKind::HiddenCapabilityDowngrade
    )));
}

#[test]
fn drill_unsafe_focus_during_reconnect_is_detected() {
    let mut projection: DebugUiProjection = load("reconnecting_after_adapter_crash.json");
    for row in projection.surfaces.iter_mut() {
        if row.surface_class_token == "call_stack" {
            row.focus_return_class = DebugUiFocusReturnClass::InvokingSurface;
            row.focus_return_class_token =
                DebugUiFocusReturnClass::InvokingSurface.as_str().to_owned();
            row.source_jump_stability_class = SourceJumpStabilityClass::Stable;
            row.source_jump_stability_class_token =
                SourceJumpStabilityClass::Stable.as_str().to_owned();
        }
    }
    let defects = validate_debug_ui_projection(&projection)
        .expect_err("validator must flag unsafe focus / source posture");
    assert!(defects.iter().any(|d| matches!(
        d.defect_kind,
        DebugUiDefectKind::UnsafeFocusReturnDuringNonSteadyState
    )));
    assert!(defects.iter().any(|d| matches!(
        d.defect_kind,
        DebugUiDefectKind::UnsafeSourceJumpDuringNonSteadyState
    )));
}

#[test]
fn drill_content_kept_on_unavailable_surface_is_detected() {
    let mut projection: DebugUiProjection = load("reconnecting_after_adapter_crash.json");
    // Force the breakpoints surface to claim it still has content rows
    // while remaining unavailable_during_reconnect.
    for row in projection.surfaces.iter_mut() {
        if row.surface_class_token == "breakpoints" {
            row.content_row_count = 3;
        }
    }
    let defects = validate_debug_ui_projection(&projection)
        .expect_err("validator must flag kept content on unavailable surface");
    assert!(defects.iter().any(|d| matches!(
        d.defect_kind,
        DebugUiDefectKind::ContentKeptOnUnavailableSurface
    )));
}
