//! Fixture replay for the durable-attention beta conformance packet.
//!
//! The fixtures live under `fixtures/ux/m3/activity_center_corpus/`
//! and are generated by the `aureline_shell_durable_attention` CLI bin
//! so the checked-in JSON stays a literal projection of the seeded
//! `DurableAttentionBetaPacket`.

use aureline_shell::durable_attention_beta::{
    seeded_durable_attention_beta_packet, validate_durable_attention_beta_packet,
    BadgeClassAuditRow, BadgeSourceClass, DurableAttentionBetaPacket,
    DurableAttentionConformanceCase, DurableAttentionJobFamily, DurableJobRowStateClass,
    ExactReopenClass, ExactReopenProof, QuietHoursDecisionClass, QuietHoursSuppressionAuditRow,
    SupportExportLineageRow, DURABLE_ATTENTION_BETA_SCHEMA_VERSION,
    DURABLE_ATTENTION_BETA_SHARED_CONTRACT_REF,
};
use aureline_shell::notifications::envelope::DedupeKeyScheme;

const FIXTURE_DIR: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../fixtures/ux/m3/activity_center_corpus"
);

fn load<T: serde::de::DeserializeOwned>(filename: &str) -> T {
    let path = format!("{}/{}", FIXTURE_DIR, filename);
    let body =
        std::fs::read_to_string(&path).unwrap_or_else(|err| panic!("failed to read {path}: {err}"));
    serde_json::from_str(&body).unwrap_or_else(|err| panic!("failed to parse {path}: {err}"))
}

#[test]
fn fixtures_round_trip_through_shared_types() {
    let packet: DurableAttentionBetaPacket = load("packet.json");
    assert_eq!(
        packet.shared_contract_ref,
        DURABLE_ATTENTION_BETA_SHARED_CONTRACT_REF
    );
    assert_eq!(packet.schema_version, DURABLE_ATTENTION_BETA_SCHEMA_VERSION);
    validate_durable_attention_beta_packet(&packet).expect("packet must validate");

    let cases: Vec<DurableAttentionConformanceCase> = load("cases.json");
    let badge_audit: Vec<BadgeClassAuditRow> = load("badge_audit.json");
    let quiet_hours_audit: Vec<QuietHoursSuppressionAuditRow> = load("quiet_hours_audit.json");
    let reopen_proofs: Vec<ExactReopenProof> = load("exact_reopen_proofs.json");
    let support_lineage: Vec<SupportExportLineageRow> = load("support_export_lineage.json");

    assert_eq!(cases, packet.cases);
    assert_eq!(badge_audit, packet.badge_audit);
    assert_eq!(quiet_hours_audit, packet.quiet_hours_audit);
    assert_eq!(reopen_proofs, packet.exact_reopen_proofs);
    assert_eq!(support_lineage, packet.support_export_lineage);

    for required in [
        DurableAttentionJobFamily::Indexing,
        DurableAttentionJobFamily::Restore,
        DurableAttentionJobFamily::InstallUpdateDownload,
        DurableAttentionJobFamily::RemoteReconnect,
        DurableAttentionJobFamily::TaskRun,
        DurableAttentionJobFamily::TestRun,
        DurableAttentionJobFamily::DebugSession,
        DurableAttentionJobFamily::AiReview,
        DurableAttentionJobFamily::GitReview,
        DurableAttentionJobFamily::CompanionHandoff,
        DurableAttentionJobFamily::AdminPolicy,
    ] {
        assert!(
            packet.summary.job_families_present.contains(&required),
            "packet must cover job family {}",
            required.as_str()
        );
    }

    for required in [
        DurableJobRowStateClass::Running,
        DurableJobRowStateClass::QueuedWaiting,
        DurableJobRowStateClass::NeedsApproval,
        DurableJobRowStateClass::Completed,
        DurableJobRowStateClass::Failed,
        DurableJobRowStateClass::Cancelled,
        DurableJobRowStateClass::HistoryOnly,
    ] {
        assert!(
            packet.summary.state_classes_present.contains(&required),
            "packet must exercise state class {}",
            required.as_str()
        );
    }
}

#[test]
fn fixtures_match_seeded_builder() {
    let on_disk: DurableAttentionBetaPacket = load("packet.json");
    let live = seeded_durable_attention_beta_packet();
    assert_eq!(
        on_disk, live,
        "fixtures must match the seeded durable-attention packet; regenerate with the headless inspector"
    );
}

#[test]
fn repeated_failures_coalesce_and_badges_stay_classed() {
    let packet: DurableAttentionBetaPacket = load("packet.json");
    let repeated = packet
        .cases
        .iter()
        .filter(|case| case.repeated_failure_root_cause_count > 1)
        .collect::<Vec<_>>();
    assert!(
        !repeated.is_empty(),
        "packet must include repeated-failure coalescing cases"
    );
    for case in repeated {
        assert!(case.repeated_failures_coalesced);
        assert!(matches!(
            case.dedupe_key_scheme,
            DedupeKeyScheme::GroupedBurstId | DedupeKeyScheme::SubsystemPlusObjectPlusPhase
        ));
    }

    for audit in &packet.badge_audit {
        assert!(audit.mixed_class_count_denied);
        assert!(audit.maps_to_authoritative_object);
        if matches!(audit.badge_source_class, BadgeSourceClass::NotABadgeSource) {
            assert_eq!(audit.active_count_delta, 0);
            assert_eq!(audit.held_or_suppressed_count_delta, 0);
        }
    }
}

#[test]
fn quiet_hours_and_reopen_proofs_preserve_truth() {
    let packet: DurableAttentionBetaPacket = load("packet.json");
    assert!(
        packet
            .quiet_hours_audit
            .iter()
            .any(|row| matches!(row.decision_class, QuietHoursDecisionClass::HeldQuietHours)),
        "packet must include a quiet-hours held audit row"
    );
    assert!(
        packet
            .quiet_hours_audit
            .iter()
            .any(|row| matches!(row.decision_class, QuietHoursDecisionClass::AdminSuppressed)),
        "packet must include an admin suppression audit row"
    );
    for audit in &packet.quiet_hours_audit {
        assert!(audit.durable_history_preserved);
        assert!(audit.suppression_audit_trail_present);
    }

    assert!(
        packet
            .exact_reopen_proofs
            .iter()
            .any(|proof| matches!(proof.reopen_class, ExactReopenClass::TruthfulPlaceholder)),
        "packet must prove truthful placeholder reopen"
    );
    assert!(
        packet.exact_reopen_proofs.iter().any(|proof| matches!(
            proof.reopen_class,
            ExactReopenClass::DeniedRequiresRevalidation
        )),
        "packet must prove denied or revalidated reopen"
    );
    for proof in &packet.exact_reopen_proofs {
        assert!(proof.generic_home_fallback_denied);
        assert!(proof.preserves_preview_approval_trust_logic);
    }
}
