//! Fixture replay for the embedded-boundary toolkit projection.
//!
//! The fixtures under `fixtures/ux/m3/embedded_boundary/` are generated by
//! the `aureline_shell_embedded_boundary_toolkit` headless inspector so the
//! checked JSON stays aligned with the Rust toolkit records.

use aureline_shell::embedded::boundary_card::SurfaceFamily;
use aureline_shell::embedded_boundary::{
    seeded_embedded_boundary_toolkit_page, validate_embedded_boundary_toolkit_page,
    EmbeddedBoundaryToolkitDefect, EmbeddedBoundaryToolkitDefectKind, EmbeddedBoundaryToolkitEvent,
    EmbeddedBoundaryToolkitEventClass, EmbeddedBoundaryToolkitPage, EmbeddedBoundaryToolkitRow,
    EmbeddedBoundaryToolkitSupportExport, EMBEDDED_BOUNDARY_TOOLKIT_SCHEMA_VERSION,
    EMBEDDED_BOUNDARY_TOOLKIT_SHARED_CONTRACT_REF,
};

const FIXTURE_DIR: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../fixtures/ux/m3/embedded_boundary"
);

fn load<T: serde::de::DeserializeOwned>(filename: &str) -> T {
    let path = format!("{}/{}", FIXTURE_DIR, filename);
    let body =
        std::fs::read_to_string(&path).unwrap_or_else(|err| panic!("failed to read {path}: {err}"));
    serde_json::from_str(&body).unwrap_or_else(|err| panic!("failed to parse {path}: {err}"))
}

#[test]
fn fixture_page_matches_seeded_toolkit_builder() {
    let from_file: EmbeddedBoundaryToolkitPage = load("page.json");
    let from_code = seeded_embedded_boundary_toolkit_page();
    assert_eq!(
        from_file, from_code,
        "fixture must be a literal projection of the seeded toolkit page"
    );
    validate_embedded_boundary_toolkit_page(&from_file).expect("fixture page validates");
}

#[test]
fn fixtures_round_trip_rows_events_defects_and_support_export() {
    let rows: Vec<EmbeddedBoundaryToolkitRow> = load("rows.json");
    assert_eq!(rows.len(), 5);
    for row in &rows {
        assert_eq!(
            row.shared_contract_ref,
            EMBEDDED_BOUNDARY_TOOLKIT_SHARED_CONTRACT_REF
        );
        assert_eq!(row.schema_version, EMBEDDED_BOUNDARY_TOOLKIT_SCHEMA_VERSION);
        assert!(!row.owner_label.is_empty());
        assert!(!row.host_or_domain_label.is_empty());
        assert!(row.native_approval_fence_active);
        assert!(row.support_export_parity_checked);
    }

    let events: Vec<EmbeddedBoundaryToolkitEvent> = load("event_log.json");
    assert!(events.len() >= rows.len() * 3);
    for event in &events {
        assert_eq!(
            event.shared_contract_ref,
            EMBEDDED_BOUNDARY_TOOLKIT_SHARED_CONTRACT_REF
        );
        assert_eq!(event.native_approval_owner_token, "host_product_native");
        assert!(!event.embedded_content_owner_label.is_empty());
        assert!(!event.embedded_origin_label.is_empty());
    }

    let defects: Vec<EmbeddedBoundaryToolkitDefect> = load("defects.json");
    assert!(defects.is_empty(), "seeded fixture must have no defects");

    let export: EmbeddedBoundaryToolkitSupportExport = load("support_export.json");
    assert_eq!(
        export.shared_contract_ref,
        EMBEDDED_BOUNDARY_TOOLKIT_SHARED_CONTRACT_REF
    );
    assert!(export.raw_private_material_excluded);
    assert_eq!(export.rows.len(), rows.len());
    assert_eq!(export.event_log.len(), events.len());
}

#[test]
fn fixtures_keep_system_browser_default_for_auth_and_handoff_events() {
    let page: EmbeddedBoundaryToolkitPage = load("page.json");
    let auth = page
        .rows
        .iter()
        .find(|row| row.surface_family == SurfaceFamily::EmbeddedAuthConfirmation)
        .expect("auth confirmation row exists");
    assert!(auth.system_browser_auth_default);
    assert_eq!(auth.auth_reason_code, "system_browser_primary");
    assert_eq!(
        auth.browser_handoff_packet_ref.as_deref(),
        Some("id:browser-handoff:auth:github")
    );
    assert!(page.event_log.iter().any(|event| {
        event.toolkit_row_id_ref == auth.toolkit_row_id
            && event.event_class == EmbeddedBoundaryToolkitEventClass::AuthHandoffDefaultRecorded
            && event.browser_handoff_packet_ref == auth.browser_handoff_packet_ref
    }));
}

#[test]
fn fixtures_keep_native_approval_fences_on_every_surface() {
    let page: EmbeddedBoundaryToolkitPage = load("page.json");
    let required = [
        "product_security_messaging",
        "update_verification",
        "workspace_trust_elevation",
        "rollback_or_restore_confirmation",
        "ai_apply_review",
        "high_risk_approval_sheet",
    ];
    for row in &page.rows {
        for token in required {
            assert!(
                row.native_approval_surface_tokens
                    .iter()
                    .any(|candidate| candidate == token),
                "{} must keep {} host-owned",
                row.toolkit_row_id,
                token
            );
        }
    }
}

#[test]
fn validator_drill_flags_missing_browser_handoff_event() {
    let mut page = seeded_embedded_boundary_toolkit_page();
    let row_id = page
        .rows
        .iter()
        .find(|row| row.browser_handoff_packet_ref.is_some())
        .expect("handoff row")
        .toolkit_row_id
        .clone();
    page.event_log.retain(|event| {
        !(event.toolkit_row_id_ref == row_id
            && event.event_class == EmbeddedBoundaryToolkitEventClass::BrowserHandoffDeclared)
    });
    page.support_export.event_log = page.event_log.clone();
    let defects = validate_embedded_boundary_toolkit_page(&page).unwrap_err();
    assert!(defects.iter().any(|defect| defect.defect_kind
        == EmbeddedBoundaryToolkitDefectKind::MissingBrowserHandoffEvent));
}
