//! Fixture replay for the beta embedded-surface boundary audit.
//!
//! The fixtures live under `fixtures/ux/m3/embedded_boundary_audit/` and
//! are generated by the `aureline_shell_embedded_boundary_audit` headless
//! inspector so the checked-in JSON stays a literal projection of the
//! seeded `EmbeddedBoundaryAuditPage` (no hand-written drift).

use aureline_shell::embedded::boundary_card::{
    BoundaryState, BrowserFallbackPostureClass, PermissionClass, SurfaceFamily,
};
use aureline_shell::embedded_boundary_audit::{
    audit_rows, seeded_embedded_boundary_audit_page, validate_embedded_boundary_audit_page,
    EmbeddedBoundaryAuditAxis, EmbeddedBoundaryAuditDefect, EmbeddedBoundaryAuditDefectKind,
    EmbeddedBoundaryAuditPage, EmbeddedBoundaryAuditRow, EmbeddedBoundaryAuditSupportExport,
    EmbeddedBoundaryAuditSupportRow, EMBEDDED_BOUNDARY_AUDIT_BETA_SCHEMA_VERSION,
    EMBEDDED_BOUNDARY_AUDIT_BETA_SHARED_CONTRACT_REF,
};

const FIXTURE_DIR: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../fixtures/ux/m3/embedded_boundary_audit"
);

fn load<T: serde::de::DeserializeOwned>(filename: &str) -> T {
    let path = format!("{}/{}", FIXTURE_DIR, filename);
    let body =
        std::fs::read_to_string(&path).unwrap_or_else(|err| panic!("failed to read {path}: {err}"));
    serde_json::from_str(&body).unwrap_or_else(|err| panic!("failed to parse {path}: {err}"))
}

#[test]
fn fixtures_round_trip_through_shared_types() {
    let rows: Vec<EmbeddedBoundaryAuditRow> = load("rows.json");
    assert!(!rows.is_empty(), "rows fixture must seed at least one row");
    for row in &rows {
        assert_eq!(
            row.shared_contract_ref,
            EMBEDDED_BOUNDARY_AUDIT_BETA_SHARED_CONTRACT_REF
        );
        assert_eq!(row.schema_version, EMBEDDED_BOUNDARY_AUDIT_BETA_SCHEMA_VERSION);
        assert!(
            !row.owner_label.is_empty(),
            "{} must quote an owner label",
            row.row_id
        );
        assert!(
            !row.host_or_domain_label.is_empty(),
            "{} must quote an origin host/domain label",
            row.row_id
        );
        assert!(
            row.promised_audit_axes
                .contains(&EmbeddedBoundaryAuditAxis::HostOwnedHighRiskApproval),
            "{} must promise host_owned_high_risk_approval",
            row.row_id
        );
    }

    let support_rows: Vec<EmbeddedBoundaryAuditSupportRow> = load("support_rows.json");
    assert_eq!(rows.len(), support_rows.len());
    for support in &support_rows {
        assert_eq!(
            support.shared_contract_ref,
            EMBEDDED_BOUNDARY_AUDIT_BETA_SHARED_CONTRACT_REF
        );
        assert_eq!(
            support.schema_version,
            EMBEDDED_BOUNDARY_AUDIT_BETA_SCHEMA_VERSION
        );
    }

    let defects: Vec<EmbeddedBoundaryAuditDefect> = load("defects.json");
    assert!(
        defects.is_empty(),
        "defects fixture must seed zero defects (got {})",
        defects.len()
    );

    let page: EmbeddedBoundaryAuditPage = load("page.json");
    assert_eq!(
        page.shared_contract_ref,
        EMBEDDED_BOUNDARY_AUDIT_BETA_SHARED_CONTRACT_REF
    );
    assert_eq!(page.rows.len(), rows.len());
    assert_eq!(page.support_rows.len(), support_rows.len());
    assert!(page.defects.is_empty());
    assert!(page.covers_required_surface_families());
    validate_embedded_boundary_audit_page(&page).expect("page must validate");

    let export: EmbeddedBoundaryAuditSupportExport = load("support_export.json");
    assert_eq!(
        export.shared_contract_ref,
        EMBEDDED_BOUNDARY_AUDIT_BETA_SHARED_CONTRACT_REF
    );
    assert!(export.raw_private_material_excluded);
    assert!(export.defect_kinds_present.is_empty());
    assert!(export.defect_counts_by_kind.is_empty());
    assert_eq!(export.page.rows.len(), page.rows.len());
}

#[test]
fn page_fixture_matches_seeded_builder() {
    let from_file: EmbeddedBoundaryAuditPage = load("page.json");
    let from_code = seeded_embedded_boundary_audit_page();
    assert_eq!(
        from_file, from_code,
        "fixture must be a literal projection of the seeded page; regenerate via the headless bin"
    );
}

#[test]
fn fixtures_cover_every_embedded_surface_family() {
    let page: EmbeddedBoundaryAuditPage = load("page.json");
    for required in [
        SurfaceFamily::EmbeddedDocsHelp,
        SurfaceFamily::ExtensionHostedSurface,
        SurfaceFamily::EmbeddedMarketplaceOrAccount,
        SurfaceFamily::EmbeddedServiceDashboard,
        SurfaceFamily::EmbeddedAuthConfirmation,
    ] {
        assert!(
            page.summary.surface_families_present.contains(&required),
            "fixture must cover surface family {required:?}"
        );
    }
}

#[test]
fn fixtures_keep_safe_baseline_posture_on_every_identity_or_risky_row() {
    let page: EmbeddedBoundaryAuditPage = load("page.json");
    let safe_baseline = [
        "system_browser_first",
        "device_code_fallback_offered",
        "external_open_blocked_by_policy",
        "external_open_unavailable_offline",
    ];
    for row in page.rows.iter().filter(|r| {
        matches!(
            r.surface_family,
            SurfaceFamily::EmbeddedAuthConfirmation
                | SurfaceFamily::EmbeddedMarketplaceOrAccount
                | SurfaceFamily::EmbeddedServiceDashboard
                | SurfaceFamily::ExtensionHostedSurface
        )
    }) {
        assert!(
            safe_baseline.contains(&row.browser_fallback_posture_token.as_str()),
            "identity or risky row {} must quote a safe-baseline posture token (got {})",
            row.row_id,
            row.browser_fallback_posture_token
        );
    }
}

#[test]
fn fixtures_keep_high_risk_approval_host_owned_on_every_row() {
    let page: EmbeddedBoundaryAuditPage = load("page.json");
    let required = [
        "product_security_messaging",
        "update_verification",
        "workspace_trust_elevation",
        "rollback_or_restore_confirmation",
        "ai_apply_review",
        "high_risk_approval_sheet",
    ];
    for row in &page.rows {
        for token in required {
            assert!(
                row.native_reserved_surface_tokens.iter().any(|t| t == token),
                "row {} must keep {} on host-owned set",
                row.row_id,
                token
            );
        }
    }
}

#[test]
fn fixtures_keep_support_export_in_lockstep_with_live_rows() {
    let page: EmbeddedBoundaryAuditPage = load("page.json");
    for row in &page.rows {
        let support = page
            .support_rows
            .iter()
            .find(|s| s.row_id == row.row_id)
            .unwrap_or_else(|| panic!("missing support row for {}", row.row_id));
        assert_eq!(support.surface_family_token, row.surface_family_token);
        assert_eq!(support.boundary_state_token, row.boundary_state_token);
        assert_eq!(support.permission_class_token, row.permission_class_token);
        assert_eq!(
            support.browser_fallback_posture_token,
            row.browser_fallback_posture_token
        );
        assert_eq!(
            support.fallback_target_class_token,
            row.fallback_target_class_token
        );
        assert_eq!(support.owner_label, row.owner_label);
        assert_eq!(support.host_or_domain_label, row.host_or_domain_label);
        assert_eq!(support.identity_mode_token, row.identity_mode_token);
        assert_eq!(support.trust_state_token, row.trust_state_token);
        assert_eq!(
            support.browser_handoff_packet_ref,
            row.browser_handoff_packet_ref
        );
    }
}

#[test]
fn validator_flags_missing_owner_label_drill() {
    let mut page = seeded_embedded_boundary_audit_page();
    page.rows[0].owner_label.clear();
    let defects = audit_rows(&page.rows, &page.support_rows);
    assert!(
        defects
            .iter()
            .any(|d| d.defect_kind == EmbeddedBoundaryAuditDefectKind::MissingOwnerLabel),
        "validator must surface MissingOwnerLabel when owner_label is dropped"
    );
}

#[test]
fn validator_flags_system_browser_baseline_drill_on_identity_row() {
    let mut page = seeded_embedded_boundary_audit_page();
    let row = page
        .rows
        .iter_mut()
        .find(|r| r.surface_family == SurfaceFamily::EmbeddedAuthConfirmation)
        .expect("seed has an auth confirmation row");
    row.browser_fallback_posture_token = "browser_fallback_not_applicable".to_owned();
    let defects = audit_rows(&page.rows, &page.support_rows);
    assert!(
        defects.iter().any(|d| d.defect_kind
            == EmbeddedBoundaryAuditDefectKind::SystemBrowserNotBaselineOnIdentityOrRiskyWeb),
        "validator must surface SystemBrowserNotBaselineOnIdentityOrRiskyWeb on auth row"
    );
}

#[test]
fn validator_flags_dropped_native_reserved_surface_drill() {
    let mut page = seeded_embedded_boundary_audit_page();
    page.rows[0]
        .native_reserved_surface_tokens
        .retain(|t| t != "ai_apply_review");
    let defects = audit_rows(&page.rows, &page.support_rows);
    assert!(
        defects.iter().any(|d| d.defect_kind
            == EmbeddedBoundaryAuditDefectKind::EmbeddedMintedNativeReservedSurface),
        "validator must surface EmbeddedMintedNativeReservedSurface when ai_apply_review is dropped"
    );
}

#[test]
fn fixtures_include_a_stale_or_policy_blocked_row() {
    let page: EmbeddedBoundaryAuditPage = load("page.json");
    assert!(
        page.summary
            .boundary_states_present
            .contains(&BoundaryState::StaleSnapshot)
            || page
                .summary
                .boundary_states_present
                .contains(&BoundaryState::PolicyBlocked),
        "fixture must exercise at least one stale or policy-blocked boundary state"
    );
}

#[test]
fn fixtures_exercise_step_up_permission_for_auth_confirmation() {
    let page: EmbeddedBoundaryAuditPage = load("page.json");
    let auth_row = page
        .rows
        .iter()
        .find(|r| r.surface_family == SurfaceFamily::EmbeddedAuthConfirmation)
        .expect("auth confirmation row");
    assert_eq!(
        auth_row.permission_class_token, "host_owned_with_native_step_up_required",
        "auth confirmation row must require native step-up"
    );
    assert!(matches!(
        auth_row.permission_class_token.as_str(),
        "host_owned_with_native_step_up_required"
    ));
    let _: Option<PermissionClass> =
        Some(PermissionClass::HostOwnedWithNativeStepUpRequired);
    let _: Option<BrowserFallbackPostureClass> =
        Some(BrowserFallbackPostureClass::SystemBrowserFirst);
}
