//! Fixture replay for the embedded-surface boundary audit corpus.
//!
//! Fixtures live under `fixtures/ux/m3/embedded_boundary_corpus/` and are
//! generated by the `aureline_shell_embedded_boundary_corpus` headless
//! inspector, so the checked-in JSON stays a literal projection of the
//! seeded packet. The report and beta-doc artifacts under
//! `artifacts/ux/m3/` and `docs/ux/m3/` are minted from the same packet.

use aureline_shell::embedded::boundary_card::SurfaceFamily;
use aureline_shell::embedded_boundary_corpus::{
    render_embedded_boundary_corpus_doc_markdown, render_embedded_boundary_corpus_report_markdown,
    seeded_embedded_boundary_corpus_packet, validate_embedded_boundary_corpus_packet,
    EmbeddedBoundaryCorpusBoundaryDrill, EmbeddedBoundaryCorpusCase, EmbeddedBoundaryCorpusDenial,
    EmbeddedBoundaryCorpusExpectation, EmbeddedBoundaryCorpusMatrix, EmbeddedBoundaryCorpusPacket,
    EmbeddedBoundaryCorpusSupportExport, EMBEDDED_BOUNDARY_CORPUS_SCHEMA_VERSION,
    EMBEDDED_BOUNDARY_CORPUS_SHARED_CONTRACT_REF,
};

const FIXTURE_DIR: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../fixtures/ux/m3/embedded_boundary_corpus"
);

const REPORT_PATH: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../artifacts/ux/m3/embedded_boundary_audit_report.md"
);

const DOC_PATH: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../docs/ux/m3/embedded_boundary_audit_beta.md"
);

fn load<T: serde::de::DeserializeOwned>(filename: &str) -> T {
    let path = format!("{FIXTURE_DIR}/{filename}");
    let body =
        std::fs::read_to_string(&path).unwrap_or_else(|err| panic!("failed to read {path}: {err}"));
    serde_json::from_str(&body).unwrap_or_else(|err| panic!("failed to parse {path}: {err}"))
}

#[test]
fn packet_fixture_matches_seeded_builder() {
    let on_disk: EmbeddedBoundaryCorpusPacket = load("packet.json");
    let live = seeded_embedded_boundary_corpus_packet();
    assert_eq!(
        on_disk, live,
        "fixture packet must be a literal projection of the seeded packet; regenerate via the headless bin"
    );
    assert_eq!(
        on_disk.shared_contract_ref,
        EMBEDDED_BOUNDARY_CORPUS_SHARED_CONTRACT_REF
    );
    assert_eq!(
        on_disk.schema_version,
        EMBEDDED_BOUNDARY_CORPUS_SCHEMA_VERSION
    );
    validate_embedded_boundary_corpus_packet(&on_disk).expect("fixture packet must validate");
}

#[test]
fn per_record_fixtures_round_trip_through_shared_types() {
    let packet = seeded_embedded_boundary_corpus_packet();
    let cases: Vec<EmbeddedBoundaryCorpusCase> = load("corpus_cases.json");
    let matrix: EmbeddedBoundaryCorpusMatrix = load("matrix.json");
    let support_export: EmbeddedBoundaryCorpusSupportExport = load("support_export.json");
    assert_eq!(cases, packet.corpus_cases);
    assert_eq!(matrix, packet.matrix);
    assert_eq!(support_export, packet.support_export);
}

#[test]
fn fixtures_cover_every_surface_family_boundary_drill_and_denial() {
    let packet: EmbeddedBoundaryCorpusPacket = load("packet.json");
    for required in [
        SurfaceFamily::EmbeddedDocsHelp,
        SurfaceFamily::ExtensionHostedSurface,
        SurfaceFamily::EmbeddedMarketplaceOrAccount,
        SurfaceFamily::EmbeddedServiceDashboard,
        SurfaceFamily::EmbeddedAuthConfirmation,
    ] {
        assert!(
            packet
                .coverage_summary
                .surface_families_present
                .contains(&required),
            "missing surface family {required:?}"
        );
    }
    for required in EmbeddedBoundaryCorpusBoundaryDrill::all() {
        assert!(
            packet
                .coverage_summary
                .boundary_drills_present
                .contains(&required),
            "missing boundary drill {}",
            required.as_str()
        );
    }
    for required in EmbeddedBoundaryCorpusDenial::all() {
        assert!(
            packet.coverage_summary.denials_present.contains(&required),
            "missing denial {}",
            required.as_str()
        );
    }
}

#[test]
fn every_recorded_verdict_holds() {
    let packet: EmbeddedBoundaryCorpusPacket = load("packet.json");
    assert!(packet.coverage_summary.all_verdicts_hold);
    for case in &packet.corpus_cases {
        assert!(
            case.verdict_holds,
            "case {} verdict must hold (expected {:?}, gate produced {:?})",
            case.case_id, case.expectation, case.actual_denial_reason_tokens
        );
    }
}

#[test]
fn conformant_cases_pass_clean_and_denial_cases_fire_their_gate_tokens() {
    let packet: EmbeddedBoundaryCorpusPacket = load("packet.json");
    for case in &packet.corpus_cases {
        match case.expectation {
            EmbeddedBoundaryCorpusExpectation::Conformant => {
                assert!(
                    case.actual_denial_reason_tokens.is_empty(),
                    "conformant case {} unexpectedly produced {:?}",
                    case.case_id,
                    case.actual_denial_reason_tokens
                );
                assert!(case.denial.is_none());
                assert!(!case.boundary_drills.is_empty());
            }
            EmbeddedBoundaryCorpusExpectation::Denied => {
                assert!(
                    !case.actual_denial_reason_tokens.is_empty(),
                    "denial case {} produced no gate denial",
                    case.case_id
                );
                assert!(case.denial.is_some());
                for token in &case.expected_denial_reason_tokens {
                    assert!(
                        case.actual_denial_reason_tokens.contains(token),
                        "denial case {} missing expected gate token {}",
                        case.case_id,
                        token
                    );
                }
            }
        }
    }
}

#[test]
fn report_artifact_matches_seeded_render() {
    let packet = seeded_embedded_boundary_corpus_packet();
    let expected = render_embedded_boundary_corpus_report_markdown(&packet);
    let on_disk =
        std::fs::read_to_string(REPORT_PATH).expect("embedded_boundary_audit_report.md must exist");
    assert_eq!(
        on_disk, expected,
        "checked-in embedded_boundary_audit_report.md must match the seeded render"
    );
}

#[test]
fn doc_artifact_matches_seeded_render() {
    let packet = seeded_embedded_boundary_corpus_packet();
    let expected = render_embedded_boundary_corpus_doc_markdown(&packet);
    let on_disk =
        std::fs::read_to_string(DOC_PATH).expect("embedded_boundary_audit_beta.md must exist");
    assert_eq!(
        on_disk, expected,
        "checked-in embedded_boundary_audit_beta.md must match the seeded render"
    );
}

#[test]
fn support_export_reconstructs_owner_boundary_and_approval_without_payload() {
    let packet: EmbeddedBoundaryCorpusPacket = load("packet.json");
    assert!(packet.support_export.no_sensitive_payload);
    assert_eq!(packet.support_export.rows.len(), packet.corpus_cases.len());
    for row in &packet.support_export.rows {
        // The export must reconstruct owner, boundary state, and approval
        // origin (permission class) from stable tokens.
        assert!(!row.surface_family_token.is_empty());
        assert!(!row.boundary_state_token.is_empty());
        assert!(!row.permission_class_token.is_empty());
        // No newline-bearing free text that would imply a raw payload.
        assert!(!row.host_or_domain_label.contains('\n'));
        assert!(!row.owner_label.contains('\n'));
    }
}
