//! Fixture replay for the interaction-transfer beta packet.
//!
//! Fixtures live under `fixtures/ux/m3/clipboard_dragdrop_history/` and are
//! generated by the `aureline_shell_interaction_transfer` headless inspector.

use std::collections::BTreeSet;

use aureline_shell::interaction_transfer::{
    record_counts_by_kind, seeded_interaction_transfer_beta_packet,
    validate_interaction_transfer_beta_packet, BackForwardDirection, BackForwardEntryRecord,
    ClipboardPayloadClassRecord, DropIntentRecord, DropVerb, InteractionSurfaceClass,
    InteractionTransferBetaPacket, InteractionTransferCoverageSummary,
    InteractionTransferSupportExport, PayloadRepresentationClass, ReopenHistoryEntryRecord,
    ReopenSourceClass, UndoGroupAttributionRecord, INTERACTION_TRANSFER_BETA_SCHEMA_VERSION,
    INTERACTION_TRANSFER_SHARED_CONTRACT_REF,
};

const FIXTURE_DIR: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../fixtures/ux/m3/clipboard_dragdrop_history"
);

fn load<T: serde::de::DeserializeOwned>(filename: &str) -> T {
    let path = format!("{}/{}", FIXTURE_DIR, filename);
    let body =
        std::fs::read_to_string(&path).unwrap_or_else(|err| panic!("failed to read {path}: {err}"));
    serde_json::from_str(&body).unwrap_or_else(|err| panic!("failed to parse {path}: {err}"))
}

#[test]
fn fixtures_round_trip_through_shared_types() {
    let packet: InteractionTransferBetaPacket = load("packet.json");
    assert_eq!(
        packet.shared_contract_ref,
        INTERACTION_TRANSFER_SHARED_CONTRACT_REF
    );
    assert_eq!(
        packet.schema_version,
        INTERACTION_TRANSFER_BETA_SCHEMA_VERSION
    );
    validate_interaction_transfer_beta_packet(&packet).expect("packet must validate");

    let clipboard_payloads: Vec<ClipboardPayloadClassRecord> = load("clipboard_payloads.json");
    let drop_intents: Vec<DropIntentRecord> = load("drop_intents.json");
    let undo_groups: Vec<UndoGroupAttributionRecord> = load("undo_groups.json");
    let back_forward: Vec<BackForwardEntryRecord> = load("back_forward.json");
    let reopen_history: Vec<ReopenHistoryEntryRecord> = load("reopen_history.json");
    let support_export: InteractionTransferSupportExport = load("support_export.json");
    let summary: InteractionTransferCoverageSummary = load("summary.json");

    assert_eq!(clipboard_payloads, packet.clipboard_payload_classes);
    assert_eq!(drop_intents, packet.drop_intents);
    assert_eq!(undo_groups, packet.undo_groups);
    assert_eq!(back_forward, packet.back_forward_entries);
    assert_eq!(reopen_history, packet.reopen_history_entries);
    assert_eq!(support_export, packet.support_export);
    assert_eq!(summary, packet.summary);
}

#[test]
fn fixture_packet_matches_seeded_builder() {
    let on_disk: InteractionTransferBetaPacket = load("packet.json");
    let live = seeded_interaction_transfer_beta_packet();
    assert_eq!(
        on_disk, live,
        "fixtures must match the seeded interaction-transfer packet"
    );
}

#[test]
fn every_surface_has_a_default_plain_text_copy() {
    let packet: InteractionTransferBetaPacket = load("packet.json");
    let surfaces_with_default: BTreeSet<InteractionSurfaceClass> = packet
        .clipboard_payload_classes
        .iter()
        .filter(|row| row.default_representation_class == PayloadRepresentationClass::PlainText)
        .map(|row| row.surface_class)
        .collect();
    for required in [
        InteractionSurfaceClass::Editor,
        InteractionSurfaceClass::Diff,
        InteractionSurfaceClass::Review,
        InteractionSurfaceClass::ResultGrid,
        InteractionSurfaceClass::ProviderLinked,
    ] {
        assert!(
            surfaces_with_default.contains(&required),
            "surface {} must have a plain-text default copy",
            required.as_str()
        );
    }
}

#[test]
fn drop_intents_cover_move_copy_attach_open_import_split() {
    let packet: InteractionTransferBetaPacket = load("packet.json");
    let verbs: BTreeSet<DropVerb> = packet
        .drop_intents
        .iter()
        .map(|row| row.advertised_verb)
        .collect();
    for required in [
        DropVerb::Move,
        DropVerb::Copy,
        DropVerb::Attach,
        DropVerb::Open,
        DropVerb::Import,
        DropVerb::Split,
    ] {
        assert!(
            verbs.contains(&required),
            "drop intents must cover verb {}",
            required.as_str()
        );
    }
}

#[test]
fn reopen_history_distinguishes_intentional_from_recovery() {
    let packet: InteractionTransferBetaPacket = load("packet.json");
    let sources: BTreeSet<ReopenSourceClass> = packet
        .reopen_history_entries
        .iter()
        .map(|row| row.source_class)
        .collect();
    assert!(sources.contains(&ReopenSourceClass::ClosedIntentionally));
    assert!(
        sources.contains(&ReopenSourceClass::CrashRecovery)
            || sources.contains(&ReopenSourceClass::DisconnectRecovery),
        "reopen history must cover crash or disconnect recovery"
    );
    assert!(sources.contains(&ReopenSourceClass::PlaceholderReopen));
    assert!(sources.contains(&ReopenSourceClass::BackForwardNavigation));
}

#[test]
fn back_forward_entries_cover_both_directions() {
    let packet: InteractionTransferBetaPacket = load("packet.json");
    let directions: BTreeSet<BackForwardDirection> = packet
        .back_forward_entries
        .iter()
        .map(|row| row.direction)
        .collect();
    assert!(directions.contains(&BackForwardDirection::Back));
    assert!(directions.contains(&BackForwardDirection::Forward));
}

#[test]
fn support_export_is_metadata_only_and_id_complete() {
    let packet: InteractionTransferBetaPacket = load("packet.json");
    let export = &packet.support_export;
    assert!(!export.raw_payload_bodies_included);
    assert_eq!(
        export.clipboard_payload_class_ids.len(),
        packet.clipboard_payload_classes.len()
    );
    assert_eq!(export.drop_intent_ids.len(), packet.drop_intents.len());
    assert_eq!(export.undo_group_ids.len(), packet.undo_groups.len());
    assert_eq!(
        export.back_forward_entry_ids.len(),
        packet.back_forward_entries.len()
    );
    assert_eq!(
        export.reopen_history_entry_ids.len(),
        packet.reopen_history_entries.len()
    );
}

#[test]
fn record_counts_match_fixture() {
    let packet: InteractionTransferBetaPacket = load("packet.json");
    let counts = record_counts_by_kind(&packet);
    assert_eq!(counts.values().sum::<usize>(), 26);
}
