//! Fixture replay for the interaction-integrity beta packet.
//!
//! Fixtures live under `fixtures/shell/m3/interaction_integrity/` and are
//! generated by the `aureline_shell_interaction_integrity` headless inspector.

use std::collections::BTreeSet;

use aureline_shell::interaction_integrity::{
    seeded_interaction_integrity_beta_packet, validate_interaction_integrity_beta_packet,
    BatchScopeTruthRecord, FocusReturnRuleRecord, IdentityCueRole, InteractionIntegrityBetaPacket,
    InteractionIntegrityReplayFixture, InteractionIntegritySupportExport,
    ObjectInteractionStateRecord, ObjectInteractionToken, ReplayDrillClass, ShellIdentityCueRecord,
    VocabularyParityRecord, INTERACTION_INTEGRITY_BETA_SCHEMA_VERSION,
    INTERACTION_INTEGRITY_SHARED_CONTRACT_REF,
};

const FIXTURE_DIR: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../fixtures/shell/m3/interaction_integrity"
);

fn load<T: serde::de::DeserializeOwned>(filename: &str) -> T {
    let path = format!("{}/{}", FIXTURE_DIR, filename);
    let body =
        std::fs::read_to_string(&path).unwrap_or_else(|err| panic!("failed to read {path}: {err}"));
    serde_json::from_str(&body).unwrap_or_else(|err| panic!("failed to parse {path}: {err}"))
}

#[test]
fn fixtures_round_trip_through_shared_types() {
    let packet: InteractionIntegrityBetaPacket = load("packet.json");
    assert_eq!(
        packet.shared_contract_ref,
        INTERACTION_INTEGRITY_SHARED_CONTRACT_REF
    );
    assert_eq!(
        packet.schema_version,
        INTERACTION_INTEGRITY_BETA_SCHEMA_VERSION
    );
    validate_interaction_integrity_beta_packet(&packet).expect("packet must validate");

    let state_model: Vec<ObjectInteractionStateRecord> = load("state_model.json");
    let batch_reviews: Vec<BatchScopeTruthRecord> = load("batch_reviews.json");
    let identity_cues: Vec<ShellIdentityCueRecord> = load("identity_cues.json");
    let focus_return: Vec<FocusReturnRuleRecord> = load("focus_return.json");
    let vocabulary: Vec<VocabularyParityRecord> = load("vocabulary.json");
    let support_export: InteractionIntegritySupportExport = load("support_export.json");
    let replay_fixtures: Vec<InteractionIntegrityReplayFixture> = load("replay_fixtures.json");

    assert_eq!(state_model, packet.object_states);
    assert_eq!(batch_reviews, packet.batch_scope_reviews);
    assert_eq!(identity_cues, packet.identity_cues);
    assert_eq!(focus_return, packet.focus_return_rules);
    assert_eq!(vocabulary, packet.vocabulary_parity);
    assert_eq!(support_export, packet.support_export);
    assert_eq!(replay_fixtures, packet.replay_fixtures);

    for required in [
        ObjectInteractionToken::Focused,
        ObjectInteractionToken::Active,
        ObjectInteractionToken::Selected,
        ObjectInteractionToken::Pending,
        ObjectInteractionToken::Disabled,
        ObjectInteractionToken::Filtered,
        ObjectInteractionToken::Hidden,
        ObjectInteractionToken::Blocked,
    ] {
        assert!(
            packet.summary.state_tokens_present.contains(&required),
            "packet must cover state token {}",
            required.as_str()
        );
    }
}

#[test]
fn fixture_packet_matches_seeded_builder() {
    let on_disk: InteractionIntegrityBetaPacket = load("packet.json");
    let live = seeded_interaction_integrity_beta_packet();
    assert_eq!(
        on_disk, live,
        "fixtures must match the seeded interaction-integrity packet"
    );
}

#[test]
fn destructive_and_publish_batches_exclude_hidden_filtered_and_blocked_targets() {
    let packet: InteractionIntegrityBetaPacket = load("packet.json");
    let unsafe_selected = packet
        .object_states
        .iter()
        .filter(|row| {
            row.selected
                && (row.hidden || row.filtered || row.blocked || row.disabled || row.pending)
        })
        .map(|row| row.object_id_ref.clone())
        .collect::<BTreeSet<_>>();
    let targets = packet
        .batch_scope_reviews
        .iter()
        .flat_map(|review| review.resulting_target_id_refs.iter().cloned())
        .collect::<BTreeSet<_>>();

    assert!(!unsafe_selected.is_empty());
    assert!(unsafe_selected.is_disjoint(&targets));

    for review in packet
        .batch_scope_reviews
        .iter()
        .filter(|review| review.action_is_destructive_or_publish_capable)
    {
        assert!(review.batch_review_sheet.review_required);
        assert!(review.hidden_or_filtered_silently_included_denied);
        assert!(review.stable_object_identity_visible);
        assert!(review.batch_review_summary_label.contains("included"));
        assert!(review.batch_review_summary_label.contains("filtered"));
        assert!(review
            .resulting_target_id_refs
            .iter()
            .all(|id| !review.filtered_item_id_refs.contains(id)));
        assert!(review
            .resulting_target_id_refs
            .iter()
            .all(|id| !review.hidden_item_id_refs.contains(id)));
    }
}

#[test]
fn identity_cues_and_focus_return_cover_responsive_shell_roles() {
    let packet: InteractionIntegrityBetaPacket = load("packet.json");
    let cue_roles = packet
        .identity_cues
        .iter()
        .map(|cue| cue.cue_role)
        .collect::<BTreeSet<_>>();
    for required in [
        IdentityCueRole::Breadcrumb,
        IdentityCueRole::StatusItem,
        IdentityCueRole::TabIdentity,
        IdentityCueRole::InspectorHeader,
        IdentityCueRole::TerminalHeader,
    ] {
        assert!(
            cue_roles.contains(&required),
            "identity cues must cover {}",
            required.as_str()
        );
    }
    for cue in &packet.identity_cues {
        assert!(cue.stable_under_resize);
        assert!(cue.stable_under_split);
        assert!(cue.stable_under_detach);
        assert!(cue.stable_under_multi_window_fallback);
        assert!(!cue.responsive_fallback_modes.is_empty());
    }

    for rule in &packet.focus_return_rules {
        assert!(rule.focus_return_explicit);
        assert!(rule.never_returns_to_hidden_or_offscreen);
        assert!(rule.preserves_selection_or_cursor_state);
        assert!(!rule.screen_reader_announcement.trim().is_empty());
    }
}

#[test]
fn support_export_is_metadata_only_and_replay_covers_required_drills() {
    let packet: InteractionIntegrityBetaPacket = load("packet.json");
    let export = &packet.support_export;
    assert!(!export.raw_filter_literals_included);
    assert!(!export.raw_object_payloads_included);
    assert!(!export.raw_private_labels_included);
    assert_eq!(
        export.support_export_state_tokens,
        vec![
            ObjectInteractionToken::Focused,
            ObjectInteractionToken::Active,
            ObjectInteractionToken::Selected,
            ObjectInteractionToken::Pending,
            ObjectInteractionToken::Disabled,
            ObjectInteractionToken::Filtered,
            ObjectInteractionToken::Hidden,
            ObjectInteractionToken::Blocked,
        ]
    );

    let replay_classes = packet
        .replay_fixtures
        .iter()
        .map(|fixture| fixture.drill_class)
        .collect::<BTreeSet<_>>();
    for required in [
        ReplayDrillClass::VirtualizedSelection,
        ReplayDrillClass::BatchScopeReview,
        ReplayDrillClass::ResponsiveIdentityCue,
        ReplayDrillClass::FocusReturn,
        ReplayDrillClass::SupportExport,
    ] {
        assert!(
            replay_classes.contains(&required),
            "replay fixtures must cover {}",
            required.as_str()
        );
    }
}
