//! Fixture replay for the M5 depth-import migration & compatibility report.
//!
//! The fixtures live under `fixtures/migration/m5_depth/` and are generated by
//! the `aureline_shell_m5_depth_imports` headless inspector so the checked-in
//! JSON stays a literal projection of the seeded `DepthImportReport`.

use aureline_shell::m5_depth_imports::{
    seeded_m5_depth_import_report, validate_m5_depth_import_report, ClassCoverageSummary,
    ContinuityScope, DepthArtifactClass, DepthImportReport, DepthImportRow,
    DepthImportSupportExport, InteropOutcome, M5_DEPTH_IMPORT_SCHEMA_VERSION,
    M5_DEPTH_IMPORT_SHARED_CONTRACT_REF,
};

const FIXTURE_DIR: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../fixtures/migration/m5_depth"
);

fn load<T: serde::de::DeserializeOwned>(filename: &str) -> T {
    let path = format!("{}/{}", FIXTURE_DIR, filename);
    let body =
        std::fs::read_to_string(&path).unwrap_or_else(|err| panic!("failed to read {path}: {err}"));
    serde_json::from_str(&body).unwrap_or_else(|err| panic!("failed to parse {path}: {err}"))
}

#[test]
fn report_fixture_matches_seeded_builder() {
    let from_file: DepthImportReport = load("report.json");
    let from_code = seeded_m5_depth_import_report();
    assert_eq!(
        from_file, from_code,
        "fixture must be a literal projection of the seeded report; regenerate through the headless inspector"
    );
}

#[test]
fn report_fixture_validates_and_covers_every_class() {
    let report: DepthImportReport = load("report.json");
    assert_eq!(
        report.shared_contract_ref,
        M5_DEPTH_IMPORT_SHARED_CONTRACT_REF
    );
    assert_eq!(report.schema_version, M5_DEPTH_IMPORT_SCHEMA_VERSION);
    assert!(report.covers_every_class());
    validate_m5_depth_import_report(&report).expect("report must validate");

    for class in DepthArtifactClass::required_classes() {
        assert!(
            report.rows.iter().any(|row| row.artifact_class == class),
            "report must include class {}",
            class.as_str()
        );
    }
}

#[test]
fn rows_keep_diff_first_checkpointed_and_honest_scope() {
    let rows: Vec<DepthImportRow> = load("rows.json");
    assert_eq!(rows.len(), DepthArtifactClass::required_classes().len());

    for row in &rows {
        assert_eq!(row.shared_contract_ref, M5_DEPTH_IMPORT_SHARED_CONTRACT_REF);
        // Diff-first + checkpointed: a mutating apply is always reversible.
        assert!(
            row.apply_is_reversible(),
            "{} mutates durable state without a checkpoint",
            row.row_id
        );
        // No non-native lane is marketed as native parity.
        if row.continuity_scope.claims_native_parity() {
            assert!(matches!(
                row.outcome,
                InteropOutcome::Imported | InteropOutcome::Mapped
            ));
        } else {
            assert!(
                row.compatibility_note.is_some(),
                "non-native row {} must disclose a compatibility note",
                row.row_id
            );
        }
        // Bridge rows carry their bridge requirement.
        if matches!(row.outcome, InteropOutcome::BridgeRequired) {
            assert!(
                row.bridge_requirement.is_some(),
                "{} is bridge_required but carries no bridge requirement",
                row.row_id
            );
        }
        assert!(
            !row.docs_help_refs.is_empty(),
            "{} must carry a docs/help ref",
            row.row_id
        );
    }
}

#[test]
fn coverage_fixture_matches_rows() {
    let coverage: ClassCoverageSummary = load("coverage.json");
    let rows: Vec<DepthImportRow> = load("rows.json");
    assert_eq!(coverage.covered_classes.len(), rows.len());
    assert!(coverage.covers_every_class());
}

#[test]
fn support_export_collects_row_and_checkpoint_ids() {
    let export: DepthImportSupportExport = load("support_export.json");
    let report = seeded_m5_depth_import_report();
    assert_eq!(export.report, report);
    assert!(export.case_ids.contains(&report.report_id));
    for row in &report.rows {
        assert!(export.case_ids.contains(&row.row_id));
        if let Some(checkpoint) = &row.restore_checkpoint {
            assert!(export.case_ids.contains(&checkpoint.checkpoint_id));
        }
    }
}

#[test]
fn at_least_one_non_native_scope_is_disclosed() {
    // The lane is honest about not claiming broad parity: at least one family
    // is inspect-only, bridge, or export-bundle continuity.
    let rows: Vec<DepthImportRow> = load("rows.json");
    assert!(rows.iter().any(|row| matches!(
        row.continuity_scope,
        ContinuityScope::InspectOnly | ContinuityScope::Bridge | ContinuityScope::ExportBundle
    )));
}
