//! Fixture replay for the M5 start-center / switcher parity packet.
//!
//! The fixtures live under `fixtures/aureline-shell/m5-start-center-and-switcher/`
//! and are generated by the `aureline_shell_m5_start_center_and_switcher` headless
//! inspector so the checked-in JSON stays a literal projection of the seeded
//! `M5StartCenterSwitcherPacket`.

use aureline_shell::m5_start_center_and_switcher::{
    seeded_m5_start_center_and_switcher_packet, validate_m5_start_center_and_switcher_packet,
    M5DiagnosticClass, M5EntryDiagnostic, M5EntrySurfaceClass, M5StartCenterSwitcherPacket,
    M5StartCenterSwitcherRow, M5StartCenterSwitcherSupportExport, SurfaceClassCoverageSummary,
    M5_START_CENTER_AND_SWITCHER_SCHEMA_VERSION, M5_START_CENTER_AND_SWITCHER_SHARED_CONTRACT_REF,
};

const FIXTURE_DIR: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../fixtures/aureline-shell/m5-start-center-and-switcher"
);

fn load<T: serde::de::DeserializeOwned>(filename: &str) -> T {
    let path = format!("{}/{}", FIXTURE_DIR, filename);
    let body =
        std::fs::read_to_string(&path).unwrap_or_else(|err| panic!("failed to read {path}: {err}"));
    serde_json::from_str(&body).unwrap_or_else(|err| panic!("failed to parse {path}: {err}"))
}

#[test]
fn packet_fixture_matches_seeded_builder() {
    let from_file: M5StartCenterSwitcherPacket = load("packet.json");
    let from_code = seeded_m5_start_center_and_switcher_packet();
    assert_eq!(
        from_file, from_code,
        "fixture must be a literal projection of the seeded packet; regenerate through the headless inspector"
    );
}

#[test]
fn packet_fixture_validates_and_covers_every_class() {
    let packet: M5StartCenterSwitcherPacket = load("packet.json");
    assert_eq!(
        packet.shared_contract_ref,
        M5_START_CENTER_AND_SWITCHER_SHARED_CONTRACT_REF
    );
    assert_eq!(
        packet.schema_version,
        M5_START_CENTER_AND_SWITCHER_SCHEMA_VERSION
    );
    assert!(packet.covers_every_class());
    assert!(packet.full_parity);
    assert!(packet.no_target_kind_collapsed);
    assert!(packet.no_trust_widened);
    validate_m5_start_center_and_switcher_packet(&packet).expect("packet must validate");

    for class in M5EntrySurfaceClass::required_classes() {
        assert!(
            packet.rows.iter().any(|row| row.surface_class == class),
            "packet must include surface class {}",
            class.as_str()
        );
    }
}

#[test]
fn rows_keep_target_kind_trust_and_restore_parity() {
    let rows: Vec<M5StartCenterSwitcherRow> = load("rows.json");
    assert_eq!(
        rows.len(),
        seeded_m5_start_center_and_switcher_packet().rows.len()
    );

    for row in &rows {
        assert_eq!(
            row.shared_contract_ref,
            M5_START_CENTER_AND_SWITCHER_SHARED_CONTRACT_REF
        );
        assert!(row.present_in_start_center);
        assert!(row.present_in_switcher);
        assert!(
            row.parity_complete(),
            "{} must hold full parity",
            row.recent_work_id
        );
        assert!(
            row.trust_not_widened(),
            "{} must not widen trust",
            row.recent_work_id
        );
        assert!(row.pin_action_available);
        assert!(row.keyboard_complete);
        assert_eq!(
            M5EntrySurfaceClass::from_target_kind(row.target_kind),
            Some(row.surface_class),
            "{} collapsed its target kind",
            row.recent_work_id
        );
        if !row.root_resolved() {
            assert!(
                row.reconnect_or_locate_available,
                "{} is unresolved but exposes no recovery path",
                row.recent_work_id
            );
        }
    }
}

#[test]
fn diagnostics_cover_every_class_and_stay_export_safe() {
    let diagnostics: Vec<M5EntryDiagnostic> = load("diagnostics.json");
    for class in M5DiagnosticClass::required_classes() {
        assert!(
            diagnostics
                .iter()
                .any(|diagnostic| diagnostic.diagnostic_class == class),
            "diagnostics must cover {}",
            class.as_str()
        );
    }
    for diagnostic in &diagnostics {
        assert!(diagnostic.export_safe);
        assert_eq!(
            diagnostic.redacted_location,
            diagnostic.target_kind.surface_label()
        );
        assert!(!diagnostic.redacted_location.contains('/'));
    }
}

#[test]
fn coverage_fixture_matches_rows() {
    let coverage: SurfaceClassCoverageSummary = load("coverage.json");
    let rows: Vec<M5StartCenterSwitcherRow> = load("rows.json");
    assert_eq!(coverage, SurfaceClassCoverageSummary::from_rows(&rows));
    assert!(coverage.covers_every_class());
}

#[test]
fn support_export_collects_row_and_diagnostic_ids() {
    let export: M5StartCenterSwitcherSupportExport = load("support_export.json");
    let packet = seeded_m5_start_center_and_switcher_packet();
    assert_eq!(export.packet, packet);
    assert!(export.case_ids.contains(&packet.packet_id));
    for row in &packet.rows {
        assert!(export.case_ids.contains(&row.recent_work_id));
    }
    for diagnostic in &packet.diagnostics {
        assert!(export.case_ids.contains(&diagnostic.diagnostic_id));
    }
}
