//! Fixture replay for the beta migration center / learnability surface.
//!
//! The fixtures live under `fixtures/ux/m3/migration_center/` and are
//! generated by the `aureline_shell_migration_center` headless inspector
//! so the checked-in JSON stays a literal projection of the seeded
//! `MigrationCenterPage` (no hand-written drift).

use std::path::{Path, PathBuf};

use aureline_shell::migration_center::{
    audit_migration_center_rows, seeded_migration_center_page, validate_migration_center_page,
    EntryKind, FreshnessClass, KeyboardReachClass, MigrationCenterDefect,
    MigrationCenterDefectKind, MigrationCenterEntryPoint, MigrationCenterPage,
    MigrationCenterSection, MigrationCenterSupportExport, MigrationCenterSupportRow, SectionKind,
    MIGRATION_CENTER_BETA_SCHEMA_VERSION, MIGRATION_CENTER_BETA_SHARED_CONTRACT_REF,
    MIGRATION_CENTER_PAGE_ID,
};

fn fixtures_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../fixtures/ux/m3/migration_center")
}

fn load<T: serde::de::DeserializeOwned>(file: &str) -> T {
    let path = fixtures_root().join(file);
    let body = std::fs::read_to_string(&path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", path.display()));
    serde_json::from_str(&body)
        .unwrap_or_else(|err| panic!("failed to parse {}: {err}", path.display()))
}

#[test]
fn page_fixture_matches_seeded_builder() {
    let from_file: MigrationCenterPage = load("page.json");
    let from_code = seeded_migration_center_page();
    assert_eq!(
        from_file, from_code,
        "fixture must be a literal projection of the seeded page; regenerate via the headless bin"
    );
    assert_eq!(from_file.page_id, MIGRATION_CENTER_PAGE_ID);
    assert_eq!(
        from_file.shared_contract_ref,
        MIGRATION_CENTER_BETA_SHARED_CONTRACT_REF
    );
    assert_eq!(
        from_file.schema_version,
        MIGRATION_CENTER_BETA_SCHEMA_VERSION
    );
}

#[test]
fn page_fixture_passes_validation() {
    let page: MigrationCenterPage = load("page.json");
    validate_migration_center_page(&page).expect("fixture page must validate");
    assert!(
        page.defects.is_empty(),
        "defects fixture must seed zero defects"
    );
}

#[test]
fn fixtures_cover_every_required_section_kind() {
    let page: MigrationCenterPage = load("page.json");
    for required in SectionKind::required_sections() {
        assert!(
            page.sections.iter().any(|s| s.section_kind == required),
            "fixture must include section kind {}",
            required.as_str()
        );
    }
}

#[test]
fn fixtures_round_trip_section_and_entry_files() {
    let page: MigrationCenterPage = load("page.json");
    let sections: Vec<MigrationCenterSection> = load("sections.json");
    let entries: Vec<MigrationCenterEntryPoint> = load("entries.json");
    let support_rows: Vec<MigrationCenterSupportRow> = load("support_rows.json");
    let defects: Vec<MigrationCenterDefect> = load("defects.json");
    assert_eq!(sections, page.sections);
    assert_eq!(entries, page.entries);
    assert_eq!(support_rows, page.support_rows);
    assert_eq!(defects, page.defects);
    assert!(defects.is_empty());
}

#[test]
fn fixtures_keep_support_rows_in_lockstep_with_entries() {
    let page: MigrationCenterPage = load("page.json");
    for entry in &page.entries {
        let support = page
            .support_rows
            .iter()
            .find(|s| s.entry_id == entry.entry_id)
            .unwrap_or_else(|| panic!("missing support row for {}", entry.entry_id));
        assert_eq!(support.section_kind_token, entry.section_kind_token);
        assert_eq!(support.entry_kind_token, entry.entry_kind_token);
        assert_eq!(support.keyboard_reach_token, entry.keyboard_reach_token);
        assert_eq!(
            support.claim_class_token,
            entry.learnability_claim.claim_class_token
        );
        assert_eq!(
            support.lifecycle_class_token,
            entry.learnability_claim.lifecycle_class_token
        );
        assert_eq!(
            support.freshness_class_token,
            entry.learnability_claim.freshness_class_token
        );
        assert_eq!(support.command_id, entry.command_id);
        assert_eq!(support.docs_help_anchor_ref, entry.docs_help_anchor_ref);
        assert_eq!(support.migration_report_ref, entry.migration_report_ref);
        assert_eq!(support.known_limit_ref, entry.known_limit_ref);
        assert_eq!(
            support.recovery_route_class_token,
            entry.recovery_route_class_token
        );
        assert!(!support.raw_body_exported);
    }
}

#[test]
fn fixtures_have_no_account_or_marketplace_detours() {
    let page: MigrationCenterPage = load("page.json");
    for entry in &page.entries {
        assert!(
            !entry.requires_account_detour,
            "{} must not require account detour",
            entry.entry_id
        );
        assert!(
            !entry.requires_marketplace_detour,
            "{} must not require marketplace detour",
            entry.entry_id
        );
    }
}

#[test]
fn fixtures_keep_every_keyboard_first_entry_anchored_to_a_command_id() {
    let page: MigrationCenterPage = load("page.json");
    for entry in &page.entries {
        if entry.keyboard_reach == KeyboardReachClass::KeyboardFirstCommandInvocation {
            let cmd = entry
                .command_id
                .as_deref()
                .unwrap_or_else(|| panic!("{} must quote a command_id", entry.entry_id));
            assert!(
                cmd.starts_with("cmd:"),
                "{} must use cmd: prefix",
                entry.entry_id
            );
        }
    }
}

#[test]
fn fixtures_include_recovery_routes_and_migration_reports() {
    let page: MigrationCenterPage = load("page.json");
    assert!(page
        .entries
        .iter()
        .any(|e| e.entry_kind == EntryKind::RecoveryAction));
    assert!(page
        .entries
        .iter()
        .any(|e| e.entry_kind == EntryKind::MigrationReportReopen));
    assert!(page
        .entries
        .iter()
        .any(|e| e.entry_kind == EntryKind::KnownLimitsLane));
    assert!(page
        .entries
        .iter()
        .any(|e| e.entry_kind == EntryKind::DocsHelpAnchor));
    assert!(page
        .entries
        .iter()
        .any(|e| e.entry_kind == EntryKind::GlossaryAnchor));
}

#[test]
fn fixtures_keep_support_export_redacted() {
    let page: MigrationCenterPage = load("page.json");
    let export: MigrationCenterSupportExport = load("support_export.json");
    assert!(export.raw_private_material_excluded);
    assert!(export.defect_kinds_present.is_empty());
    assert!(export.case_ids.contains(&page.page_id));
    for entry in &page.entries {
        assert!(export.case_ids.contains(&entry.entry_id));
        assert!(export.case_ids.contains(&entry.support_row_id));
    }
}

#[test]
fn drill_account_detour_emits_defect() {
    let mut page = seeded_migration_center_page();
    page.entries[0].requires_account_detour = true;
    let defects = audit_migration_center_rows(&page.sections, &page.entries, &page.support_rows);
    assert!(defects
        .iter()
        .any(|d| d.defect_kind == MigrationCenterDefectKind::EntryRequiresAccountDetour));
}

#[test]
fn drill_missing_command_id_emits_defect() {
    let mut page = seeded_migration_center_page();
    let idx = page
        .entries
        .iter()
        .position(|e| e.keyboard_reach == KeyboardReachClass::KeyboardFirstCommandInvocation)
        .expect("seeded page must include a keyboard-first entry");
    page.entries[idx].command_id = None;
    let defects = audit_migration_center_rows(&page.sections, &page.entries, &page.support_rows);
    assert!(defects
        .iter()
        .any(|d| d.defect_kind == MigrationCenterDefectKind::EntryCommandIdMissing));
}

#[test]
fn drill_review_overdue_emits_defect() {
    let mut page = seeded_migration_center_page();
    page.entries[0].learnability_claim.freshness_class = FreshnessClass::ReviewOverdue;
    page.entries[0].learnability_claim.freshness_class_token =
        FreshnessClass::ReviewOverdue.as_str().to_owned();
    let defects = audit_migration_center_rows(&page.sections, &page.entries, &page.support_rows);
    assert!(defects
        .iter()
        .any(|d| d.defect_kind == MigrationCenterDefectKind::FreshnessReviewOverdueOnClaimedRow));
}
