//! Fixture replay for the beta notification-privacy projection.
//!
//! The fixtures live under `fixtures/ux/m3/notification_privacy/` and
//! are generated by the `aureline_shell_notification_privacy` CLI bin
//! so the checked-in JSON stays a literal projection of the seeded
//! `NotificationPrivacyBetaPage` (no hand-written drift).

use aureline_shell::notifications::actions::BadgeClass;
use aureline_shell::notifications::beta::{
    seeded_notification_privacy_beta_page, validate_notification_privacy_beta_page,
    validate_notification_privacy_beta_support_export, LockScreenPosture,
    NotificationPrivacyBetaBadge, NotificationPrivacyBetaPage, NotificationPrivacyBetaRow,
    NotificationPrivacyBetaRowClass, NotificationPrivacyBetaSupportExport,
    NOTIFICATION_PRIVACY_BETA_SCHEMA_VERSION, NOTIFICATION_PRIVACY_BETA_SHARED_CONTRACT_REF,
};
use aureline_shell::notifications::envelope::{
    DedupeKeyScheme, PrivacyPayloadClass, SeverityClass,
};
use aureline_shell::notifications::quiet_hours::DurableBadgeProjection;

const FIXTURE_DIR: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../fixtures/ux/m3/notification_privacy"
);

fn load<T: serde::de::DeserializeOwned>(filename: &str) -> T {
    let path = format!("{}/{}", FIXTURE_DIR, filename);
    let body =
        std::fs::read_to_string(&path).unwrap_or_else(|err| panic!("failed to read {path}: {err}"));
    serde_json::from_str(&body).unwrap_or_else(|err| panic!("failed to parse {path}: {err}"))
}

#[test]
fn fixtures_round_trip_through_shared_types() {
    let rows: Vec<NotificationPrivacyBetaRow> = load("rows.json");
    assert!(!rows.is_empty(), "rows fixture must seed at least one row");
    for row in &rows {
        assert_eq!(
            row.shared_contract_ref,
            NOTIFICATION_PRIVACY_BETA_SHARED_CONTRACT_REF
        );
        assert_eq!(row.schema_version, NOTIFICATION_PRIVACY_BETA_SCHEMA_VERSION);
        assert!(
            row.raw_private_material_excluded,
            "{} must exclude raw private material",
            row.row_id
        );
        // Lock-screen posture must mirror the payload class.
        let projected = LockScreenPosture::from_payload_class(row.privacy_payload_class);
        assert_eq!(
            projected, row.lock_screen_posture,
            "{} lock-screen posture must mirror payload class",
            row.row_id
        );
        // Retry coalescing must use a coalescing-friendly dedupe scheme.
        if row.expected_coalescing_posture.coalesces_retry_burst {
            assert!(
                matches!(
                    row.dedupe_key_scheme,
                    DedupeKeyScheme::GroupedBurstId
                        | DedupeKeyScheme::SubsystemPlusObjectPlusPhase
                ),
                "{} retry coalescing requires grouped_burst_id or subsystem_plus_object_plus_phase",
                row.row_id
            );
        }
        // Cross-client siblings require the cross-client scheme.
        if !row.cross_client_posture.sibling_scopes.is_empty() {
            assert!(matches!(
                row.dedupe_key_scheme,
                DedupeKeyScheme::CrossClientCanonicalEventId
            ));
            assert!(row.cross_client_posture.cross_client_dedupe_in_effect);
        }
        // Critical severity may never admit a hold.
        if matches!(row.severity_class, SeverityClass::Critical) {
            assert!(
                !row.quiet_hours_posture.holds_attention_surfaces,
                "{} critical severity must never hold an attention surface",
                row.row_id
            );
            assert!(
                row.quiet_hours_posture.durable_truth_preserved,
                "{} critical severity must preserve durable truth",
                row.row_id
            );
        }
        // Forbidden-shortcut list must enumerate the closed thirteen.
        assert_eq!(
            row.forbidden_shortcut_posture.forbidden_classes.len(),
            13,
            "{} forbidden shortcut list must enumerate the closed thirteen classes",
            row.row_id
        );
        assert!(row.forbidden_shortcut_posture.exact_reopen_only);
        assert!(row
            .forbidden_shortcut_posture
            .mutation_routes_through_review_path);
    }

    let badges: Vec<NotificationPrivacyBetaBadge> = load("badges.json");
    assert_eq!(
        badges.len(),
        rows.len(),
        "badge mirror must cover every row exactly once"
    );
    for badge in &badges {
        let row = rows
            .iter()
            .find(|r| r.row_id == badge.row_id)
            .unwrap_or_else(|| panic!("badge {} has no matching row", badge.row_id));
        assert_eq!(badge.badge_class, row.badge_class);
        assert_eq!(badge.severity_class, row.severity_class);
        assert_eq!(badge.privacy_class, row.privacy_class);
        assert_eq!(
            badge.os_app_icon_visible,
            !row.quiet_hours_posture.os_app_icon_badge_suppressed
        );
    }

    // Row-class coverage: the seeded page must exercise every required
    // beta row class so a reviewer can confirm posture on every claimed
    // scenario.
    for required in [
        NotificationPrivacyBetaRowClass::DeliveredSummarySafe,
        NotificationPrivacyBetaRowClass::CoalescedRepeatedFailure,
        NotificationPrivacyBetaRowClass::LockScreenSafeGenericPayload,
        NotificationPrivacyBetaRowClass::LockScreenSafeScopedPayload,
        NotificationPrivacyBetaRowClass::LockScreenForbiddenSecurityCritical,
        NotificationPrivacyBetaRowClass::QuietHoursHeld,
        NotificationPrivacyBetaRowClass::AdminPolicySuppressed,
        NotificationPrivacyBetaRowClass::CriticalSafetyEscalation,
        NotificationPrivacyBetaRowClass::CompanionCrossClientFanout,
        NotificationPrivacyBetaRowClass::ForbiddenShortcutBypassRefused,
    ] {
        assert!(
            rows.iter().any(|r| r.row_class == required),
            "rows must cover required row class {}",
            required.as_str()
        );
    }

    let page: NotificationPrivacyBetaPage = load("page.json");
    assert_eq!(
        page.shared_contract_ref,
        NOTIFICATION_PRIVACY_BETA_SHARED_CONTRACT_REF
    );
    assert_eq!(page.rows.len(), rows.len());
    assert_eq!(page.badges.len(), badges.len());
    assert!(page.covers_required_row_classes());
    validate_notification_privacy_beta_page(&page).expect("page must validate");

    let projection: DurableBadgeProjection = load("badge_projection.json");
    assert_eq!(projection.durable_count as usize, rows.len());

    let export: NotificationPrivacyBetaSupportExport = load("support_export.json");
    assert_eq!(
        export.shared_contract_ref,
        NOTIFICATION_PRIVACY_BETA_SHARED_CONTRACT_REF
    );
    assert_eq!(export.rows.len(), page.rows.len());
    assert_eq!(export.case_ids.len(), page.rows.len());
    assert!(export.raw_private_material_excluded);
    validate_notification_privacy_beta_support_export(&export)
        .expect("support export must validate against its embedded page");
}

#[test]
fn fixtures_match_live_seed_byte_for_byte() {
    // The fixtures must be a literal projection of the seeded page.
    let live = seeded_notification_privacy_beta_page();
    let on_disk: NotificationPrivacyBetaPage = load("page.json");
    assert_eq!(
        on_disk, live,
        "fixtures/ux/m3/notification_privacy/page.json must match the seeded page exactly"
    );
}

#[test]
fn coalesced_row_dedupes_repeats_into_one_failed_run() {
    let rows: Vec<NotificationPrivacyBetaRow> = load("rows.json");
    let row = rows
        .iter()
        .find(|r| {
            matches!(
                r.row_class,
                NotificationPrivacyBetaRowClass::CoalescedRepeatedFailure
            )
        })
        .expect("seed has the coalesced row");
    assert!(matches!(row.badge_class, BadgeClass::FailedRuns));
    assert!(row.is_dedupe_repeat);
    assert!(row.occurrence_count >= 2);
}

#[test]
fn lock_screen_forbidden_row_denies_lock_screen_payload() {
    let rows: Vec<NotificationPrivacyBetaRow> = load("rows.json");
    let row = rows
        .iter()
        .find(|r| {
            matches!(
                r.row_class,
                NotificationPrivacyBetaRowClass::LockScreenForbiddenSecurityCritical
            )
        })
        .expect("seed has a lock-screen-forbidden row");
    assert!(matches!(
        row.privacy_payload_class,
        PrivacyPayloadClass::PolicyForbiddenOnLockScreen
    ));
    assert!(matches!(
        row.lock_screen_posture,
        LockScreenPosture::PolicyForbiddenOnLockScreen
    ));
}
