//! Fixture replay for the durable-notification routing corpus.
//!
//! Fixtures live under `fixtures/ux/m3/notification_envelope_corpus/` and are
//! generated by the `aureline_shell_notification_envelope_corpus` headless
//! inspector, so the checked-in JSON stays a literal projection of the seeded
//! packet. The privacy/route audit, the support route/outcome export report,
//! and the conformance doc are minted from the same packet.
//!
//! These tests guard the exit-gate contract: every marketed beta attention
//! family has current evidence proving privacy-safe routing, exact-target
//! reopen, quiet-hours/admin suppression, and export-safe route/outcome truth
//! — and wrong-target reopen, lock-screen leakage, badge inflation, and
//! quiet-hours drift fail the lane and produce actionable diff artifacts.

use aureline_shell::attention_router::ChannelResolutionClass;
use aureline_shell::notification_envelope_corpus::{
    render_notification_privacy_and_route_audit_markdown,
    render_notification_route_conformance_markdown,
    render_notification_route_outcome_export_report_markdown, route_outcome_violations,
    seeded_notification_envelope_corpus_packet, validate_notification_envelope_corpus_packet,
    BadgeIntegrityProbe, BetaAttentionFamily, NotificationEnvelopeCorpusCase,
    NotificationEnvelopeCorpusPacket, NotificationRouteOutcomeExport, OverlayParityProof,
    ReopenProofClass, RouteDriftDrill, RouteDriftViolation,
    NOTIFICATION_ENVELOPE_CORPUS_SCHEMA_VERSION, NOTIFICATION_ENVELOPE_CORPUS_SHARED_CONTRACT_REF,
};
use aureline_shell::notifications::envelope::{FanoutSurfaceClass, PrivacyPayloadClass};

const FIXTURE_DIR: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../fixtures/ux/m3/notification_envelope_corpus"
);

const AUDIT_PATH: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../artifacts/ux/m3/notification_privacy_and_route_audit.md"
);

const EXPORT_REPORT_PATH: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../artifacts/support/m3/notification_route_outcome_export_report.md"
);

const CONFORMANCE_DOC_PATH: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../docs/ux/m3/notification_route_conformance.md"
);

fn load<T: serde::de::DeserializeOwned>(filename: &str) -> T {
    let path = format!("{FIXTURE_DIR}/{filename}");
    let body =
        std::fs::read_to_string(&path).unwrap_or_else(|err| panic!("failed to read {path}: {err}"));
    serde_json::from_str(&body).unwrap_or_else(|err| panic!("failed to parse {path}: {err}"))
}

#[test]
fn packet_fixture_matches_seeded_builder() {
    let on_disk: NotificationEnvelopeCorpusPacket = load("packet.json");
    let live = seeded_notification_envelope_corpus_packet();
    assert_eq!(
        on_disk, live,
        "fixture packet must be a literal projection of the seeded packet; regenerate via the \
         headless bin (aureline_shell_notification_envelope_corpus -- packet)"
    );
    assert_eq!(
        on_disk.shared_contract_ref,
        NOTIFICATION_ENVELOPE_CORPUS_SHARED_CONTRACT_REF
    );
    assert_eq!(
        on_disk.schema_version,
        NOTIFICATION_ENVELOPE_CORPUS_SCHEMA_VERSION
    );
    validate_notification_envelope_corpus_packet(&on_disk).expect("fixture packet must validate");
}

#[test]
fn per_record_fixtures_round_trip_through_shared_types() {
    let packet = seeded_notification_envelope_corpus_packet();
    let cases: Vec<NotificationEnvelopeCorpusCase> = load("cases.json");
    let drills: Vec<RouteDriftDrill> = load("drift_drills.json");
    let probes: Vec<BadgeIntegrityProbe> = load("badge_probes.json");
    let overlays: Vec<OverlayParityProof> = load("overlay_parity.json");
    let export: NotificationRouteOutcomeExport = load("support_export.json");
    assert_eq!(cases, packet.cases);
    assert_eq!(drills, packet.drift_drills);
    assert_eq!(probes, packet.badge_probes);
    assert_eq!(overlays, packet.overlay_parity);
    assert_eq!(export, packet.support_export);
}

#[test]
fn corpus_covers_every_beta_attention_family() {
    let packet: NotificationEnvelopeCorpusPacket = load("packet.json");
    assert!(packet.coverage.all_families_present);
    for family in BetaAttentionFamily::all() {
        assert!(
            packet.cases.iter().any(|c| c.attention_family == family),
            "missing beta attention family {}",
            family.as_str()
        );
    }
}

#[test]
fn corpus_covers_the_full_resolution_class_and_reopen_proof_set() {
    let packet: NotificationEnvelopeCorpusPacket = load("packet.json");
    for class in [
        ChannelResolutionClass::DeliveredInApp,
        ChannelResolutionClass::DeliveredExternalSummary,
        ChannelResolutionClass::SuppressedForegroundRedundant,
        ChannelResolutionClass::LockScreenNotApplicable,
        ChannelResolutionClass::CompanionUnavailable,
        ChannelResolutionClass::CompanionPolicyBlocked,
        ChannelResolutionClass::HeldByQuietHoursOrFocus,
        ChannelResolutionClass::SuppressedByPolicy,
        ChannelResolutionClass::DedupedRepeat,
    ] {
        assert!(
            packet.coverage.resolution_classes_covered.contains(&class),
            "missing resolution class {}",
            class.as_str()
        );
    }
    for proof in [
        ReopenProofClass::ExactTarget,
        ReopenProofClass::TruthfulPlaceholder,
        ReopenProofClass::DeniedRequiresRevalidation,
    ] {
        assert!(
            packet
                .coverage
                .reopen_proof_classes_covered
                .contains(&proof),
            "missing reopen proof {}",
            proof.as_str()
        );
    }
}

#[test]
fn every_case_keeps_one_reopen_target_durable_truth_and_no_generic_home() {
    let packet: NotificationEnvelopeCorpusPacket = load("packet.json");
    for case in &packet.cases {
        // The conformance lane re-derives invariants from the routes; no case
        // may produce a violation.
        assert!(
            route_outcome_violations(&case.outcome).is_empty(),
            "{}: conformance lane flagged {:?}",
            case.case_id,
            route_outcome_violations(&case.outcome)
        );
        let outcome = &case.outcome;
        assert!(
            outcome.all_routes_preserve_reopen_target,
            "{}",
            case.case_id
        );
        assert!(outcome.durable_truth_preserved, "{}", case.case_id);
        assert!(outcome.no_generic_home_reopen, "{}", case.case_id);
        for route in &outcome.resolved_surface_routes {
            assert_eq!(
                route.reopen_target_ref,
                outcome.reopen_target.reopen_target_ref,
                "{}: surface {} diverged",
                case.case_id,
                route.fanout_surface_class.as_str()
            );
        }
    }
}

#[test]
fn drift_drills_fail_the_lane_and_carry_actionable_diffs() {
    let packet: NotificationEnvelopeCorpusPacket = load("packet.json");
    for required in RouteDriftViolation::all() {
        assert!(
            packet
                .drift_drills
                .iter()
                .any(|d| d.violation_class == required),
            "missing drift drill {}",
            required.as_str()
        );
    }
    for drill in &packet.drift_drills {
        assert!(
            drill.conforming_passes_clean,
            "{} baseline did not pass the lane clean",
            drill.drill_id
        );
        assert!(
            drill.lane_rejects_regression,
            "{} regression slipped through the lane",
            drill.drill_id
        );
        assert!(
            !drill.rejection_reason_tokens.is_empty(),
            "{} produced no rejection reason tokens",
            drill.drill_id
        );
        // The diff is actionable: it names a field and differing observations.
        assert!(!drill.diff.diff_field.is_empty(), "{}", drill.drill_id);
        assert_ne!(
            drill.diff.conforming_observation, drill.diff.regressed_observation,
            "{}: diff has no observable difference",
            drill.drill_id
        );
    }
}

#[test]
fn badge_probes_never_inflate_under_a_retry_storm() {
    let packet: NotificationEnvelopeCorpusPacket = load("packet.json");
    assert!(packet.coverage.badge_never_inflates);
    assert!(!packet.badge_probes.is_empty());
    for probe in &packet.badge_probes {
        assert!(
            probe.raw_emissions > 1,
            "{}: probe must exercise a retry storm",
            probe.probe_id
        );
        assert_eq!(
            probe.durable_badge_count, 1,
            "{}: retry storm must collapse to one durable item",
            probe.probe_id
        );
        assert!(probe.inflation_prevented, "{}", probe.probe_id);
    }
}

#[test]
fn overlays_keep_durable_semantics_and_reopen_on_claimed_rows() {
    let packet: NotificationEnvelopeCorpusPacket = load("packet.json");
    assert!(packet.coverage.all_overlays_preserve_durable_semantics);
    for overlay in &packet.overlay_parity {
        assert!(
            overlay.durable_resolution_matches_baseline,
            "{} diverged durable resolution",
            overlay.parity_id
        );
        assert!(
            overlay.reopen_target_matches_baseline,
            "{} diverged reopen target",
            overlay.parity_id
        );
    }
}

#[test]
fn support_export_reconstructs_route_and_outcome_without_copy() {
    let packet: NotificationEnvelopeCorpusPacket = load("packet.json");
    let export = &packet.support_export;
    assert!(export.raw_user_facing_copy_excluded);
    assert_eq!(export.rows.len(), packet.cases.len());

    // Every row reconstructs class, route, suppression, and resolution from
    // stable enums; no surface row is empty.
    for row in &export.rows {
        assert!(!row.surface_resolutions.is_empty(), "{}", row.case_id);
    }

    // The export must not echo any case's user-facing summary copy.
    let export_json = serde_json::to_string(export).unwrap();
    for case in &packet.cases {
        assert!(
            !export_json.contains(&case.outcome.summary_label),
            "support export leaked summary copy for {}",
            case.case_id
        );
    }
}

#[test]
fn lock_screen_summary_never_renders_when_payload_forbids_it() {
    let packet: NotificationEnvelopeCorpusPacket = load("packet.json");
    for case in &packet.cases {
        if matches!(
            case.outcome.privacy_payload_class,
            PrivacyPayloadClass::PolicyForbiddenOnLockScreen
        ) {
            for route in &case.outcome.resolved_surface_routes {
                if matches!(
                    route.fanout_surface_class,
                    FanoutSurfaceClass::LockScreenSummary
                ) {
                    assert!(
                        !route.visible,
                        "{}: forbidden lock-screen summary rendered",
                        case.case_id
                    );
                }
            }
        }
    }
}

#[test]
fn audit_artifact_matches_seeded_render() {
    let packet = seeded_notification_envelope_corpus_packet();
    let expected = render_notification_privacy_and_route_audit_markdown(&packet);
    let on_disk = std::fs::read_to_string(AUDIT_PATH)
        .expect("notification_privacy_and_route_audit.md must exist");
    assert_eq!(
        on_disk, expected,
        "checked-in notification_privacy_and_route_audit.md must match the seeded render"
    );
}

#[test]
fn export_report_artifact_matches_seeded_render() {
    let packet = seeded_notification_envelope_corpus_packet();
    let expected = render_notification_route_outcome_export_report_markdown(&packet);
    let on_disk = std::fs::read_to_string(EXPORT_REPORT_PATH)
        .expect("notification_route_outcome_export_report.md must exist");
    assert_eq!(
        on_disk, expected,
        "checked-in notification_route_outcome_export_report.md must match the seeded render"
    );
}

#[test]
fn conformance_doc_matches_seeded_render() {
    let packet = seeded_notification_envelope_corpus_packet();
    let expected = render_notification_route_conformance_markdown(&packet);
    let on_disk = std::fs::read_to_string(CONFORMANCE_DOC_PATH)
        .expect("notification_route_conformance.md must exist");
    assert_eq!(
        on_disk, expected,
        "checked-in notification_route_conformance.md must match the seeded render"
    );
}
