//! Fixture replay for the beta onboarding/help-pack manifest.
//!
//! The checked-in files under `fixtures/help/m3/onboarding_help_packs/`
//! are generated by `aureline_shell_onboarding_help_pack_beta`, then replayed
//! here so runtime, docs, and support-export evidence stay aligned.

use std::path::{Path, PathBuf};

use aureline_commands::registry::seeded_registry;
use aureline_shell::help_packs::onboarding_beta::{
    seeded_onboarding_help_pack_beta_manifest, seeded_onboarding_help_pack_beta_support_export,
    seeded_onboarding_help_pack_beta_surface_projection, validate_seeded_onboarding_help_pack_beta,
    OnboardingHelpPackBetaManifest, OnboardingHelpPackBetaSupportExport,
    OnboardingHelpPackBetaSurfaceProjection, ONBOARDING_HELP_PACK_BETA_MANIFEST_ID,
    ONBOARDING_HELP_PACK_BETA_SCHEMA_VERSION, ONBOARDING_HELP_PACK_BETA_VERSION_REF,
};
use aureline_shell::migration_center::{
    seeded_migration_center_page, validate_migration_center_page, EntryKind,
};

fn fixtures_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../fixtures/help/m3/onboarding_help_packs")
}

fn load_json<T: serde::de::DeserializeOwned>(file: &str) -> T {
    let path = fixtures_root().join(file);
    let body = std::fs::read_to_string(&path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", path.display()));
    serde_json::from_str(&body)
        .unwrap_or_else(|err| panic!("failed to parse {}: {err}", path.display()))
}

fn load_yaml(file: &str) -> serde_yaml::Value {
    let path = fixtures_root().join(file);
    let body = std::fs::read_to_string(&path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", path.display()));
    serde_yaml::from_str(&body)
        .unwrap_or_else(|err| panic!("failed to parse {}: {err}", path.display()))
}

#[test]
fn manifest_fixture_matches_seeded_builder() {
    let from_file: OnboardingHelpPackBetaManifest = load_json("manifest.json");
    let from_code = seeded_onboarding_help_pack_beta_manifest();
    assert_eq!(from_file, from_code);
    assert_eq!(
        from_file.schema_version,
        ONBOARDING_HELP_PACK_BETA_SCHEMA_VERSION
    );
    assert_eq!(from_file.manifest_id, ONBOARDING_HELP_PACK_BETA_MANIFEST_ID);
    assert_eq!(
        from_file.manifest_version_ref,
        ONBOARDING_HELP_PACK_BETA_VERSION_REF
    );
}

#[test]
fn generated_records_validate() {
    validate_seeded_onboarding_help_pack_beta(seeded_registry())
        .expect("seeded beta help-pack records validate");
    let manifest: OnboardingHelpPackBetaManifest = load_json("manifest.json");
    manifest
        .validate_against_registry(seeded_registry())
        .expect("fixture manifest validates");
}

#[test]
fn support_export_fixture_matches_seeded_builder() {
    let from_file: OnboardingHelpPackBetaSupportExport = load_json("support_export.json");
    let from_code = seeded_onboarding_help_pack_beta_support_export();
    assert_eq!(from_file, from_code);
    let manifest = seeded_onboarding_help_pack_beta_manifest();
    from_file
        .validate_against_manifest(&manifest)
        .expect("support export fixture validates");
    assert!(!from_file.raw_body_exported);
    assert!(from_file
        .omitted_material_classes
        .iter()
        .any(|class| class == "raw_article_body"));
}

#[test]
fn surface_projection_covers_required_surfaces() {
    let projection: OnboardingHelpPackBetaSurfaceProjection = load_json("surface_projection.json");
    assert_eq!(
        projection,
        seeded_onboarding_help_pack_beta_surface_projection()
    );
    for surface in [
        "surface:start_center:first_run",
        "surface:migration_center:beta",
        "surface:help_search:onboarding",
        "surface:contextual_why_now:onboarding",
        "surface:recovery_first:onboarding",
    ] {
        assert!(
            projection
                .coverage
                .covered_surface_refs
                .iter()
                .any(|covered| covered == surface),
            "missing surface {surface}"
        );
    }
}

#[test]
fn source_language_fallback_fixture_matches_manifest() {
    let manifest = seeded_onboarding_help_pack_beta_manifest();
    let fixture = load_yaml("source_language_fallback.yaml");
    let expected = &fixture["expected"];
    let item_ref = expected["item_ref"].as_str().expect("item ref");
    let item = manifest.item(item_ref).expect("item exists");

    assert_eq!(item.pack_id, expected["pack_id"].as_str().expect("pack id"));
    assert_eq!(
        item.locale.requested_locale,
        expected["requested_locale"]
            .as_str()
            .expect("requested locale")
    );
    assert_eq!(
        item.locale.effective_locale,
        expected["effective_locale"]
            .as_str()
            .expect("effective locale")
    );
    assert_eq!(
        item.source_language_fallback.fallback_class,
        expected["fallback_class"].as_str().expect("fallback class")
    );
    assert_eq!(
        item.command_hint.command_id,
        expected["command_id"].as_str().expect("command id")
    );
    assert!(item.locale.unresolved_locale_fallback);
    assert!(item.source_language_fallback.unresolved_source_fallback);
    assert!(!item.source_truth.citation_refs.is_empty());
}

#[test]
fn offline_mirror_fixture_matches_manifest() {
    let manifest = seeded_onboarding_help_pack_beta_manifest();
    let fixture = load_yaml("offline_mirror_fallback.yaml");
    let expected = &fixture["expected"];
    let item = manifest
        .item(expected["item_ref"].as_str().expect("item ref"))
        .expect("item exists");
    let pack = manifest.pack(&item.pack_id).expect("pack exists");

    assert_eq!(
        pack.source_class,
        expected["source_class"].as_str().unwrap()
    );
    assert_eq!(
        pack.mirror_posture,
        expected["mirror_posture"].as_str().unwrap()
    );
    assert_eq!(
        pack.offline_posture,
        expected["offline_posture"].as_str().unwrap()
    );
    assert_eq!(
        item.offline_fallback.fallback_behavior,
        expected["fallback_behavior"].as_str().unwrap()
    );
    assert_eq!(
        item.command_hint.command_id,
        expected["command_id"].as_str().unwrap()
    );
    assert!(item.offline_fallback.explicit_user_visible_state);
}

#[test]
fn migration_center_entries_quote_help_pack_refs() {
    let page = seeded_migration_center_page();
    validate_migration_center_page(&page).expect("migration center validates");
    for entry in &page.entries {
        assert!(
            entry.help_pack_item_ref.is_some(),
            "{} must quote a help-pack item",
            entry.entry_id
        );
        let support = page
            .support_rows
            .iter()
            .find(|row| row.entry_id == entry.entry_id)
            .expect("support row exists");
        assert_eq!(support.help_pack_item_ref, entry.help_pack_item_ref);
        assert_eq!(support.help_pack_version_ref, entry.help_pack_version_ref);
    }
    assert!(page.entries.iter().any(|entry| {
        entry.entry_kind == EntryKind::GlossaryAnchor
            && entry.help_pack_item_ref.as_deref() == Some("ohp:item:glossary.release_truth")
    }));
    assert!(page.entries.iter().any(|entry| {
        entry.entry_kind == EntryKind::RecoveryAction
            && entry.help_pack_item_ref.as_deref() == Some("ohp:item:recovery.support_export")
    }));
}
