//! Fixture replay for the beta passkey-capable step-up, reauth, and recovery
//! lane projection.
//!
//! The fixtures live under `fixtures/auth/m3/passkey_step_up/` and are
//! generated by the `aureline_shell_passkey_step_up_beta` headless inspector
//! so the checked-in JSON stays a literal projection of the seeded
//! `PasskeyStepUpBetaPage` (no hand-written drift).

use aureline_shell::passkey_step_up_beta::{
    audit_passkey_step_up_beta_rows, seeded_passkey_step_up_beta_page,
    validate_passkey_step_up_beta_page, PasskeyAuthorityScopeClass, PasskeyBetaLaneClass,
    PasskeyLifecycleStateClass, PasskeyStepUpBetaDefect, PasskeyStepUpBetaDefectKind,
    PasskeyStepUpBetaPage, PasskeyStepUpBetaRenderSummary, PasskeyStepUpBetaRow,
    PasskeyStepUpBetaSupportExport, PasskeyStepUpBetaSupportRow,
    PASSKEY_STEP_UP_BETA_SCHEMA_VERSION, PASSKEY_STEP_UP_BETA_SHARED_CONTRACT_REF,
};

const FIXTURE_DIR: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../fixtures/auth/m3/passkey_step_up"
);

fn load<T: serde::de::DeserializeOwned>(filename: &str) -> T {
    let path = format!("{}/{}", FIXTURE_DIR, filename);
    let body =
        std::fs::read_to_string(&path).unwrap_or_else(|err| panic!("failed to read {path}: {err}"));
    serde_json::from_str(&body).unwrap_or_else(|err| panic!("failed to parse {path}: {err}"))
}

#[test]
fn page_fixture_matches_seeded_builder() {
    let from_file: PasskeyStepUpBetaPage = load("page.json");
    let from_code = seeded_passkey_step_up_beta_page();
    assert_eq!(
        from_file, from_code,
        "fixture must be a literal projection of the seeded page; regenerate via the headless bin"
    );
}

#[test]
fn page_fixture_validates_with_zero_defects() {
    let page: PasskeyStepUpBetaPage = load("page.json");
    assert_eq!(
        page.shared_contract_ref,
        PASSKEY_STEP_UP_BETA_SHARED_CONTRACT_REF
    );
    assert_eq!(page.schema_version, PASSKEY_STEP_UP_BETA_SCHEMA_VERSION);
    assert!(page.defects.is_empty());
    validate_passkey_step_up_beta_page(&page).expect("seeded page must validate");

    let recomputed = audit_passkey_step_up_beta_rows(&page.rows, &page.support_rows);
    assert!(
        recomputed.is_empty(),
        "validator must agree with the empty defects array on the seeded fixture"
    );

    assert!(page.reauth_and_recovery_preserve_target_action_identity());
    assert!(page.fallback_named_when_passkey_unavailable());
}

#[test]
fn rows_and_support_rows_round_trip() {
    let rows: Vec<PasskeyStepUpBetaRow> = load("rows.json");
    let support: Vec<PasskeyStepUpBetaSupportRow> = load("support_rows.json");
    let defects: Vec<PasskeyStepUpBetaDefect> = load("defects.json");

    assert_eq!(rows.len(), support.len(), "support row count must match");
    assert!(defects.is_empty(), "defects fixture must seed zero defects");

    for row in &rows {
        assert_eq!(
            row.shared_contract_ref,
            PASSKEY_STEP_UP_BETA_SHARED_CONTRACT_REF
        );
        assert!(!row.row_id.is_empty());
        assert!(!row.case_id.is_empty());
        assert!(!row.lane.lane_token.is_empty());
        assert!(!row.lifecycle.state_token.is_empty());
        assert!(!row.lifecycle.client_scope_token.is_empty());
        assert!(!row.outcome.outcome_token.is_empty());
        assert!(!row.outcome.fallback_token.is_empty());
        assert!(!row.target_action_preservation.preservation_token.is_empty());
    }

    for support in &support {
        assert!(rows.iter().any(|r| r.row_id == support.row_id));
    }

    let recomputed = audit_passkey_step_up_beta_rows(&rows, &support);
    assert!(recomputed.is_empty(), "recomputed defects must be empty");
}

#[test]
fn fixture_includes_step_up_lane_satisfied_by_passkey() {
    let page: PasskeyStepUpBetaPage = load("page.json");
    let row = page
        .rows
        .iter()
        .find(|r| r.lane.lane_token == PasskeyBetaLaneClass::StepUpLane.as_str())
        .expect("fixture must include a step-up lane row");
    assert_eq!(
        row.lifecycle.state_token,
        PasskeyLifecycleStateClass::ActiveOnThisDevice.as_str()
    );
    assert_eq!(row.outcome.outcome_token, "step_up_satisfied");
    assert_eq!(row.outcome.fallback_token, "no_fallback_required");
    assert_eq!(
        row.requested_authority_scope_token,
        PasskeyAuthorityScopeClass::StepUpScope.as_str()
    );
    assert_eq!(
        row.granted_authority_scope_token,
        PasskeyAuthorityScopeClass::StepUpScope.as_str()
    );
}

#[test]
fn fixture_includes_reauth_lane_with_named_fallback() {
    let page: PasskeyStepUpBetaPage = load("page.json");
    let row = page
        .rows
        .iter()
        .find(|r| r.lane.lane_token == PasskeyBetaLaneClass::ReauthLane.as_str())
        .expect("fixture must include a reauth lane row");
    assert_eq!(
        row.lifecycle.state_token,
        PasskeyLifecycleStateClass::UnavailableThisPlatform.as_str()
    );
    assert_ne!(row.outcome.fallback_token, "no_fallback_required");
    assert_eq!(
        row.target_action_preservation.preservation_token,
        "target_action_preserved_exact"
    );
}

#[test]
fn fixture_includes_recovery_lane_with_admin_policy_deny() {
    let page: PasskeyStepUpBetaPage = load("page.json");
    let row = page
        .rows
        .iter()
        .find(|r| r.lane.lane_token == PasskeyBetaLaneClass::RecoveryLane.as_str())
        .expect("fixture must include a recovery lane row");
    assert!(row.admin_policy_denies_passkey);
    assert_eq!(row.outcome.fallback_token, "contact_admin_for_recovery");
    // Recovery downscoped read-only — preserved without widening.
    assert_eq!(
        row.target_action_preservation.preservation_token,
        "target_action_downscoped"
    );
    assert_eq!(
        row.requested_authority_scope_token,
        PasskeyAuthorityScopeClass::ReadWriteScope.as_str()
    );
    assert_eq!(
        row.granted_authority_scope_token,
        PasskeyAuthorityScopeClass::ReadOnlyScope.as_str()
    );
}

#[test]
fn fixture_includes_account_free_local_row_with_no_lane() {
    let page: PasskeyStepUpBetaPage = load("page.json");
    let row = page
        .rows
        .iter()
        .find(|r| {
            r.lane.lane_token == PasskeyBetaLaneClass::NotApplicableAccountFreeLocal.as_str()
        })
        .expect("fixture must include an account-free local row");
    assert!(row.lane.target_label.is_empty());
    assert!(row.lane.requested_action_label.is_empty());
    assert_eq!(row.outcome.fallback_token, "not_applicable_account_free_local");
}

#[test]
fn support_export_round_trips_through_validator() {
    let export: PasskeyStepUpBetaSupportExport = load("support_export.json");
    assert!(export.raw_private_material_excluded);
    assert!(export.defect_kinds_present.is_empty());
    assert!(export.defect_counts_by_kind.is_empty());
    assert_eq!(
        export.shared_contract_ref,
        PASSKEY_STEP_UP_BETA_SHARED_CONTRACT_REF
    );
}

#[test]
fn drill_recovery_rerouted_replays_typed_defect() {
    let page: PasskeyStepUpBetaPage = load("drill_recovery_rerouted.json");
    let recomputed = audit_passkey_step_up_beta_rows(&page.rows, &page.support_rows);
    assert_eq!(
        recomputed, page.defects,
        "fixture defects must equal the live validator output"
    );
    assert!(recomputed
        .iter()
        .any(|d| d.defect_kind == PasskeyStepUpBetaDefectKind::ReauthOrRecoveryRerouted));
}

#[test]
fn drill_reauth_widened_replays_typed_defect() {
    let page: PasskeyStepUpBetaPage = load("drill_reauth_widened.json");
    let recomputed = audit_passkey_step_up_beta_rows(&page.rows, &page.support_rows);
    assert_eq!(recomputed, page.defects);
    assert!(recomputed
        .iter()
        .any(|d| d.defect_kind == PasskeyStepUpBetaDefectKind::ReauthOrRecoveryWidened));
}

#[test]
fn drill_reauth_without_fallback_replays_typed_defect() {
    let page: PasskeyStepUpBetaPage = load("drill_reauth_without_fallback.json");
    let recomputed = audit_passkey_step_up_beta_rows(&page.rows, &page.support_rows);
    assert_eq!(recomputed, page.defects);
    assert!(recomputed.iter().any(|d| {
        d.defect_kind == PasskeyStepUpBetaDefectKind::OutcomeUnsatisfiedWithoutFallback
            || d.defect_kind == PasskeyStepUpBetaDefectKind::LifecycleStateRequiresFallback
    }));
}

#[test]
fn drill_step_up_widens_authority_replays_typed_defect() {
    let page: PasskeyStepUpBetaPage = load("drill_step_up_widens_authority.json");
    let recomputed = audit_passkey_step_up_beta_rows(&page.rows, &page.support_rows);
    assert_eq!(recomputed, page.defects);
    assert!(recomputed
        .iter()
        .any(|d| d.defect_kind == PasskeyStepUpBetaDefectKind::GrantedAuthorityWidensRequested));
}

#[test]
fn render_summary_matches_page_summary() {
    let from_file: PasskeyStepUpBetaRenderSummary = load("render_summary.json");
    let page: PasskeyStepUpBetaPage = load("page.json");
    let from_page = PasskeyStepUpBetaRenderSummary::from_page(&page);
    assert_eq!(from_file, from_page);
}
