//! Fixture replay for the beta policy-pack inspection projection.
//!
//! The fixtures live under `fixtures/security/m3/policy_packs/` and are
//! generated by the `aureline_shell_policy_pack_beta` headless inspector,
//! so checked-in JSON stays a literal projection of the seeded
//! `PolicyPackBetaPage`.

use aureline_shell::policy_pack_beta::{
    audit_policy_pack_beta_page, seeded_policy_pack_beta_page, validate_policy_pack_beta_page,
    PolicyPackBetaDefectKind, PolicyPackBetaDenialTrace, PolicyPackBetaDiff,
    PolicyPackBetaImportReceipt, PolicyPackBetaPack, PolicyPackBetaPage,
    PolicyPackBetaRenderSummary, PolicyPackBetaSupportExport, PolicyPackSourceClass,
    POLICY_PACK_BETA_SCHEMA_VERSION, POLICY_PACK_BETA_SHARED_CONTRACT_REF,
};

const FIXTURE_DIR: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../fixtures/security/m3/policy_packs"
);

fn load<T: serde::de::DeserializeOwned>(filename: &str) -> T {
    let path = format!("{}/{}", FIXTURE_DIR, filename);
    let body =
        std::fs::read_to_string(&path).unwrap_or_else(|err| panic!("failed to read {path}: {err}"));
    serde_json::from_str(&body).unwrap_or_else(|err| panic!("failed to parse {path}: {err}"))
}

#[test]
fn page_fixture_matches_seeded_builder() {
    let from_file: PolicyPackBetaPage = load("page.json");
    let from_code = seeded_policy_pack_beta_page();
    assert_eq!(
        from_file, from_code,
        "fixture must be a literal projection of the seeded page; regenerate via the headless bin"
    );
}

#[test]
fn page_fixture_validates_with_zero_defects() {
    let page: PolicyPackBetaPage = load("page.json");
    assert_eq!(
        page.shared_contract_ref,
        POLICY_PACK_BETA_SHARED_CONTRACT_REF
    );
    assert_eq!(page.schema_version, POLICY_PACK_BETA_SCHEMA_VERSION);
    assert!(page.defects.is_empty());
    validate_policy_pack_beta_page(&page).expect("seeded page must validate");
}

#[test]
fn packs_and_receipts_round_trip() {
    let page: PolicyPackBetaPage = load("page.json");
    let packs: Vec<PolicyPackBetaPack> = load("packs.json");
    let receipts: Vec<PolicyPackBetaImportReceipt> = load("import_receipts.json");
    assert_eq!(page.packs, packs);
    assert_eq!(page.import_receipts, receipts);

    assert!(packs.iter().any(|pack| pack.source_class
        == PolicyPackSourceClass::SignedMirrorOrigin
        && pack.applies_to_profiles.contains(&"mirror_only".to_owned())));
    assert!(receipts.iter().all(|receipt| receipt.preserves_signature_blob
        && receipt.preserves_provenance
        && receipt.preserves_explanation));
}

#[test]
fn diffs_round_trip_and_cover_added_and_changed_rules() {
    let page: PolicyPackBetaPage = load("page.json");
    let diffs: Vec<PolicyPackBetaDiff> = load("diffs.json");
    assert_eq!(page.diffs, diffs);
    let connected = diffs
        .iter()
        .find(|diff| diff.profile_token == "connected")
        .expect("connected diff");
    let kinds: Vec<&str> = connected
        .entries
        .iter()
        .map(|entry| entry.kind_token.as_str())
        .collect();
    assert!(kinds.contains(&"added"));
    assert!(kinds.contains(&"effect_changed"));
    assert!(kinds.contains(&"scope_changed"));
    assert!(kinds.contains(&"reason_changed"));
}

#[test]
fn denial_traces_round_trip_and_resolve_to_pack_rules() {
    let page: PolicyPackBetaPage = load("page.json");
    let traces: Vec<PolicyPackBetaDenialTrace> = load("denial_traces.json");
    assert_eq!(page.denial_traces, traces);
    for trace in &traces {
        let pack = page
            .packs
            .iter()
            .find(|pack| pack.pack_id == trace.pack_id)
            .expect("trace pack");
        let rule = pack
            .rules
            .iter()
            .find(|rule| rule.rule_id == trace.rule_id)
            .expect("trace rule");
        assert_eq!(rule.reason_token, trace.reason_token);
        assert_eq!(rule.surface_family_token, trace.surface_family_token);
    }
}

#[test]
fn support_export_round_trips_through_validator() {
    let export: PolicyPackBetaSupportExport = load("support_export.json");
    assert!(export.raw_private_material_excluded);
    assert!(export.defect_kinds_present.is_empty());
    assert_eq!(
        export.shared_contract_ref,
        POLICY_PACK_BETA_SHARED_CONTRACT_REF
    );
}

#[test]
fn drill_signature_dropped_replays_typed_defect() {
    let page: PolicyPackBetaPage = load("drill_signature_dropped.json");
    let recomputed = audit_policy_pack_beta_page(
        &page.packs,
        &page.diffs,
        &page.denial_traces,
        &page.import_receipts,
    );
    assert_eq!(recomputed, page.defects);
    assert!(recomputed.iter().any(|defect| defect.defect_kind
        == PolicyPackBetaDefectKind::MirrorOrImportSignatureBlobDropped));
}

#[test]
fn drill_denial_unresolvable_replays_typed_defect() {
    let page: PolicyPackBetaPage = load("drill_denial_unresolvable.json");
    let recomputed = audit_policy_pack_beta_page(
        &page.packs,
        &page.diffs,
        &page.denial_traces,
        &page.import_receipts,
    );
    assert_eq!(recomputed, page.defects);
    assert!(recomputed.iter().any(|defect| defect.defect_kind
        == PolicyPackBetaDefectKind::DenialTraceUnresolvable));
}

#[test]
fn drill_public_fallback_replays_typed_defect() {
    let page: PolicyPackBetaPage = load("drill_public_fallback.json");
    let recomputed = audit_policy_pack_beta_page(
        &page.packs,
        &page.diffs,
        &page.denial_traces,
        &page.import_receipts,
    );
    assert_eq!(recomputed, page.defects);
    assert!(recomputed.iter().any(|defect| defect.defect_kind
        == PolicyPackBetaDefectKind::HiddenPublicEndpointFallback));
}

#[test]
fn render_summary_matches_page_summary() {
    let from_file: PolicyPackBetaRenderSummary = load("render_summary.json");
    let page: PolicyPackBetaPage = load("page.json");
    let from_page = PolicyPackBetaRenderSummary::from_page(&page);
    assert_eq!(from_file, from_page);
}
