//! Fixture replay for the beta presentation-mode corpus.
//!
//! The fixtures live under `fixtures/help/m3/presentation_mode/` and are
//! generated by the `aureline_shell_presentation_mode` CLI bin, so the
//! checked-in JSON stays a literal projection of the seeded
//! [`PresentationModeCorpus`]. These tests guard the exit-gate contract:
//! presentation mode is a thin, reversible layer over existing surfaces, with
//! explicit follow / breakaway / return truth, local-only-by-default speaker
//! notes, preserved provenance, keyboard-complete controls, and no widened
//! authority.

use aureline_shell::presentation_mode::{
    seeded_presentation_mode_corpus, validate_presentation_mode_corpus, AudienceScope,
    BoundaryLabel, LeaderFollowState, PresentationModeCorpus, PresentationModeSupportExport,
    PresentationSessionCase, RestoreOutcome, RestoreTrigger, SpeakerNoteScope,
    WalkthroughSurfaceKind, PRESENTATION_MODE_BETA_SCHEMA_VERSION,
    PRESENTATION_MODE_BETA_SHARED_CONTRACT_REF,
};

const FIXTURE_DIR: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../fixtures/help/m3/presentation_mode"
);

fn load<T: serde::de::DeserializeOwned>(filename: &str) -> T {
    let path = format!("{FIXTURE_DIR}/{filename}");
    let body =
        std::fs::read_to_string(&path).unwrap_or_else(|err| panic!("failed to read {path}: {err}"));
    serde_json::from_str(&body).unwrap_or_else(|err| panic!("failed to parse {path}: {err}"))
}

#[test]
fn corpus_fixture_matches_seeded_builder() {
    let on_disk: PresentationModeCorpus = load("corpus.json");
    let live = seeded_presentation_mode_corpus();
    assert_eq!(
        on_disk, live,
        "fixtures must match the seeded corpus; regenerate with the headless inspector \
         (cargo run -p aureline-shell --bin aureline_shell_presentation_mode -- corpus)"
    );
}

#[test]
fn corpus_fixture_validates_and_carries_shared_contract() {
    let corpus: PresentationModeCorpus = load("corpus.json");
    assert_eq!(corpus.schema_version, PRESENTATION_MODE_BETA_SCHEMA_VERSION);
    assert_eq!(
        corpus.shared_contract_ref,
        PRESENTATION_MODE_BETA_SHARED_CONTRACT_REF
    );
    validate_presentation_mode_corpus(&corpus).expect("corpus fixture must validate");

    // The sessions fixture is the same case vector the corpus carries.
    let sessions: Vec<PresentationSessionCase> = load("sessions.json");
    assert_eq!(sessions, corpus.sessions);

    // The restore-outcomes fixture matches the corpus's restore outcomes.
    let restore_outcomes: Vec<RestoreOutcome> = load("restore_outcomes.json");
    assert_eq!(restore_outcomes, corpus.restore_outcomes);
}

#[test]
fn every_session_is_a_thin_reversible_layer_without_widened_authority() {
    let corpus: PresentationModeCorpus = load("corpus.json");
    for case in &corpus.sessions {
        let s = &case.session;
        // Reuses existing surfaces; never duplicates them into a new artifact.
        assert!(
            s.reuses_existing_surfaces_only,
            "{}: session does not declare surface reuse",
            case.case_id
        );
        for w in &s.waypoints {
            assert!(
                w.reuses_existing_surface && !w.creates_parallel_artifact,
                "{}: waypoint {} duplicates a surface",
                case.case_id,
                w.waypoint_id
            );
        }
        // No hidden authority, control escalation, or private ownership.
        assert!(
            !s.grants_mutation_authority,
            "{}: session grants mutation authority",
            case.case_id
        );
        assert!(
            !s.grants_control_authority,
            "{}: session grants control authority",
            case.case_id
        );
        assert!(
            !s.establishes_private_data_ownership,
            "{}: session claims private data ownership",
            case.case_id
        );
        // Provenance survives the overlay.
        assert!(
            s.preserves_source_provenance
                && case.overlay.provenance_strip.source_identity_preserved,
            "{}: provenance was not preserved",
            case.case_id
        );
        // Restore affordance is complete.
        let restore = &case.overlay.restore_affordance;
        assert!(
            restore.restores_prior_layout
                && restore.restores_prior_focus
                && restore.restores_on_crash_recovery,
            "{}: restore affordance is incomplete",
            case.case_id
        );
    }
}

#[test]
fn speaker_notes_default_local_and_shared_notes_are_explicit() {
    let corpus: PresentationModeCorpus = load("corpus.json");
    let mut saw_local = false;
    let mut saw_explicit_shared = false;
    for case in &corpus.sessions {
        assert!(
            case.session.speaker_notes_default_local_only,
            "{}: notes do not default local-only",
            case.case_id
        );
        for w in &case.session.waypoints {
            if let Some(note) = &w.speaker_note {
                match note.scope {
                    SpeakerNoteScope::Local => {
                        saw_local = true;
                        assert!(
                            !note.shared_promotion_explicit,
                            "{}: local note {} is marked promoted",
                            case.case_id, note.note_id
                        );
                    }
                    SpeakerNoteScope::Shared => {
                        saw_explicit_shared = true;
                        assert!(
                            note.shared_promotion_explicit,
                            "{}: shared note {} lacks an explicit promotion",
                            case.case_id, note.note_id
                        );
                    }
                }
            }
        }
    }
    assert!(saw_local, "corpus must include local-only notes");
    assert!(
        saw_explicit_shared,
        "corpus must include at least one explicitly shared note"
    );
}

#[test]
fn follow_breakaway_return_states_stay_explicit_and_attributable() {
    let corpus: PresentationModeCorpus = load("corpus.json");
    for case in &corpus.sessions {
        let overlay = &case.overlay;
        let broken_away = matches!(
            case.session.leader_follow_state,
            LeaderFollowState::BrokenAway
        );
        // A broken-away local user always sees the explicit banner and a return.
        if broken_away {
            let banner = overlay
                .breakaway_banner
                .as_ref()
                .unwrap_or_else(|| panic!("{}: missing breakaway banner", case.case_id));
            assert_eq!(banner.state_label, "You are browsing independently");
            assert!(!banner.return_to_presenter_action.command_id.is_empty());
        } else {
            assert!(
                overlay.breakaway_banner.is_none(),
                "{}: non-broken-away session shows a breakaway banner",
                case.case_id
            );
        }
        // The follow chip always exposes follow / break-away / return verbs.
        let chip_commands: Vec<&str> = overlay
            .audience_strip
            .follow_chip
            .actions
            .iter()
            .map(|a| a.command_id.as_str())
            .collect();
        for required in [
            "cmd:presentation.follow_presenter",
            "cmd:presentation.break_away",
            "cmd:presentation.return_to_presenter",
        ] {
            assert!(
                chip_commands.contains(&required),
                "{}: follow chip missing {required}",
                case.case_id
            );
        }
        // Participant counts on the strip agree with the session participants.
        assert_eq!(
            overlay.audience_strip.participant_count as usize,
            case.session.audience_participants.len(),
            "{}: audience strip count diverges",
            case.case_id
        );
    }
}

#[test]
fn every_overlay_control_is_keyboard_reachable_and_attention_only() {
    let corpus: PresentationModeCorpus = load("corpus.json");
    for case in &corpus.sessions {
        let overlay = &case.overlay;
        assert!(
            overlay.keyboard_complete,
            "{}: not keyboard-complete",
            case.case_id
        );
        assert!(
            !overlay.pointer_only,
            "{}: declares pointer-only",
            case.case_id
        );
        assert!(
            overlay.screen_reader_reachable,
            "{}: not screen-reader reachable",
            case.case_id
        );
        for action in overlay.all_actions() {
            assert!(
                !action.command_id.is_empty()
                    && !action.key_binding_ref.is_empty()
                    && !action.accessible_label.is_empty(),
                "{}: action {} missing reachability metadata",
                case.case_id,
                action.action_id
            );
            assert!(
                !action.is_destructive && !action.mutates_workspace,
                "{}: action {} is not attention-only",
                case.case_id,
                action.action_id
            );
        }
    }
}

#[test]
fn corpus_covers_every_surface_state_scope_and_restore_trigger() {
    let corpus: PresentationModeCorpus = load("corpus.json");
    for kind in [
        WalkthroughSurfaceKind::Editor,
        WalkthroughSurfaceKind::Diff,
        WalkthroughSurfaceKind::Docs,
        WalkthroughSurfaceKind::Graph,
        WalkthroughSurfaceKind::Notebook,
    ] {
        assert!(
            corpus.summary.surface_kinds_covered.contains(&kind),
            "corpus must cover surface kind {}",
            kind.as_str()
        );
    }
    for state in [
        LeaderFollowState::Presenting,
        LeaderFollowState::FollowingPresenter,
        LeaderFollowState::BrokenAway,
        LeaderFollowState::RequestingFollow,
    ] {
        assert!(
            corpus.summary.leader_follow_states_covered.contains(&state),
            "corpus must cover leader/follow state {}",
            state.as_str()
        );
    }
    for scope in [
        AudienceScope::SoloRehearsal,
        AudienceScope::SharedWorkspace,
        AudienceScope::InvitedGuests,
    ] {
        assert!(
            corpus.summary.audience_scopes_covered.contains(&scope),
            "corpus must cover audience scope {}",
            scope.as_str()
        );
    }
    for label in [
        BoundaryLabel::Local,
        BoundaryLabel::Remote,
        BoundaryLabel::Shared,
    ] {
        assert!(
            corpus.summary.boundary_labels_covered.contains(&label),
            "corpus must cover boundary label {}",
            label.as_str()
        );
    }
    for trigger in [
        RestoreTrigger::Exit,
        RestoreTrigger::Cancel,
        RestoreTrigger::CrashRecovery,
    ] {
        assert!(
            corpus.summary.restore_triggers_covered.contains(&trigger),
            "corpus must cover restore trigger {}",
            trigger.as_str()
        );
    }
}

#[test]
fn restore_outcomes_return_the_prior_environment_for_every_trigger() {
    let corpus: PresentationModeCorpus = load("corpus.json");
    let mut triggers = std::collections::BTreeSet::new();
    for outcome in &corpus.restore_outcomes {
        triggers.insert(outcome.trigger);
        assert!(
            outcome.matches_checkpoint,
            "{}: restore did not match the checkpoint",
            outcome.session_id
        );
        assert!(
            !outcome.left_in_improvised_shell,
            "{}: restore left an improvised shell",
            outcome.session_id
        );
        // The restored refs trace back to a real session's checkpoint.
        let session = corpus
            .sessions
            .iter()
            .find(|c| c.session.session_id == outcome.session_id)
            .map(|c| &c.session)
            .unwrap_or_else(|| panic!("restore outcome references unknown session"));
        assert_eq!(
            outcome.restored_layout_ref,
            session.restore_checkpoint.prior_layout_ref
        );
        assert_eq!(
            outcome.restored_focus_ref,
            session.restore_checkpoint.prior_focus_ref
        );
    }
    assert_eq!(
        triggers.len(),
        3,
        "restore outcomes must cover all three triggers"
    );
}

#[test]
fn support_export_is_privacy_safe_and_row_aligned() {
    let corpus: PresentationModeCorpus = load("corpus.json");
    let on_disk: PresentationModeSupportExport = load("support_export.json");
    let live = PresentationModeSupportExport::from_corpus(
        "support-export:presentation-mode-beta:001",
        "2026-05-20T00:00:00Z",
        &corpus,
    );
    assert_eq!(on_disk, live, "support export must match the seeded corpus");
    assert!(on_disk.raw_private_material_excluded);
    assert_eq!(on_disk.rows.len(), corpus.sessions.len());

    // The export carries support-safe enums and counts, never note bodies,
    // step titles, scenario copy, or raw file paths.
    let export_json = serde_json::to_string(&on_disk).unwrap();
    for case in &corpus.sessions {
        assert!(
            !export_json.contains(&case.scenario_label),
            "support export leaked scenario copy for {}",
            case.case_id
        );
        for w in &case.session.waypoints {
            assert!(
                !export_json.contains(&w.step_title),
                "support export leaked step title for {}",
                case.case_id
            );
            if let Some(path) = &w.file_path_ref {
                assert!(
                    !export_json.contains(path),
                    "support export leaked file path for {}",
                    case.case_id
                );
            }
            if let Some(note) = &w.speaker_note {
                if let Some(body) = &note.body_label {
                    assert!(
                        !export_json.contains(body),
                        "support export leaked note body for {}",
                        case.case_id
                    );
                }
            }
        }
    }
}
