//! Fixture replay for the beta runtime-adaptation projection.
//!
//! The fixtures live under `fixtures/ux/m3/desktop_continuity_matrix/`
//! and are generated by the `aureline_shell_runtime_adaptation` CLI
//! bin so the checked-in JSON stays a literal projection of the
//! seeded `RuntimeAdaptationPage` (no hand-written drift).

use aureline_shell::runtime_adaptation::{
    seeded_runtime_adaptation_page, validate_runtime_adaptation_page, DesktopMatrixRow,
    ForegroundProtectionRow, HostOsClass, MonitorContinuityRow, PowerPostureRow,
    RuntimeAdaptationPage, RuntimeAdaptationSupportExport, SuspendResumeRow,
    RUNTIME_ADAPTATION_SCHEMA_VERSION, RUNTIME_ADAPTATION_SHARED_CONTRACT_REF,
};

const FIXTURE_DIR: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../fixtures/ux/m3/desktop_continuity_matrix"
);

fn load<T: serde::de::DeserializeOwned>(filename: &str) -> T {
    let path = format!("{}/{}", FIXTURE_DIR, filename);
    let body =
        std::fs::read_to_string(&path).unwrap_or_else(|err| panic!("failed to read {path}: {err}"));
    serde_json::from_str(&body).unwrap_or_else(|err| panic!("failed to parse {path}: {err}"))
}

#[test]
fn fixtures_round_trip_through_shared_types() {
    let postures: Vec<PowerPostureRow> = load("power_posture_rows.json");
    assert!(
        !postures.is_empty(),
        "posture fixtures must seed at least one row"
    );
    for record in &postures {
        assert_eq!(
            record.shared_contract_ref,
            RUNTIME_ADAPTATION_SHARED_CONTRACT_REF
        );
        assert_eq!(record.schema_version, RUNTIME_ADAPTATION_SCHEMA_VERSION);
        assert!(
            record.foreground_responsiveness_preserved,
            "{} must preserve foreground responsiveness",
            record.case_id
        );
    }

    let suspends: Vec<SuspendResumeRow> = load("suspend_resume_rows.json");
    assert!(
        suspends.len() >= 3,
        "suspend-resume fixtures must cover macOS, Windows, and Linux"
    );
    let mut has_macos = false;
    let mut has_windows = false;
    let mut has_linux = false;
    for record in &suspends {
        assert_eq!(
            record.shared_contract_ref,
            RUNTIME_ADAPTATION_SHARED_CONTRACT_REF
        );
        assert!(
            record.no_silent_rerun_or_authority_reuse,
            "{} must forbid silent rerun",
            record.case_id
        );
        assert!(
            record.user_visible_resume_summary_required,
            "{} must require a user-visible resume summary",
            record.case_id
        );
        match record.host_os {
            HostOsClass::Macos => has_macos = true,
            HostOsClass::Windows => has_windows = true,
            HostOsClass::Linux => has_linux = true,
        }
    }
    assert!(has_macos && has_windows && has_linux);

    let monitors: Vec<MonitorContinuityRow> = load("monitor_continuity_rows.json");
    assert!(
        monitors.len() >= 3,
        "monitor fixtures must cover macOS, Windows, and Linux"
    );
    for record in &monitors {
        assert!(
            record.visible_bounds_preserved && record.focus_intent_preserved,
            "{} must preserve bounds and focus",
            record.case_id
        );
        assert!(
            record.user_visible_topology_summary_required,
            "{} must require a user-visible topology summary",
            record.case_id
        );
    }

    let foreground: Vec<ForegroundProtectionRow> = load("foreground_protection_rows.json");
    assert!(
        foreground.len() >= 3,
        "foreground-protection fixtures must cover macOS, Windows, and Linux"
    );
    for record in &foreground {
        assert!(
            record.remains_responsive && record.no_input_event_drops && record.no_blocking_dialog,
            "{} must keep foreground actions responsive and unblocked",
            record.case_id
        );
    }

    let matrix: Vec<DesktopMatrixRow> = load("desktop_matrix_rows.json");
    let mut covered_os: Vec<HostOsClass> = Vec::new();
    for record in &matrix {
        assert!(
            !record.named_downgrade_behaviors.is_empty(),
            "{} must carry named downgrade behaviors",
            record.case_id
        );
        assert!(
            record.foreground_responsiveness_held && record.no_silent_rerun_or_authority_reuse,
            "{} must hold foreground and forbid silent rerun",
            record.case_id
        );
        covered_os.push(record.host_os);
    }
    for required in [HostOsClass::Macos, HostOsClass::Windows, HostOsClass::Linux] {
        assert!(
            covered_os.contains(&required),
            "matrix must cover {}",
            required.as_str()
        );
    }

    let page: RuntimeAdaptationPage = load("page.json");
    assert_eq!(
        page.shared_contract_ref,
        RUNTIME_ADAPTATION_SHARED_CONTRACT_REF
    );
    assert_eq!(page.power_posture_rows.len(), postures.len());
    assert_eq!(page.suspend_resume_rows.len(), suspends.len());
    assert_eq!(page.monitor_continuity_rows.len(), monitors.len());
    assert_eq!(page.foreground_protection_rows.len(), foreground.len());
    assert_eq!(page.desktop_matrix_rows.len(), matrix.len());
    validate_runtime_adaptation_page(&page).expect("seeded page must validate");

    let export: RuntimeAdaptationSupportExport = load("support_export.json");
    assert_eq!(
        export.shared_contract_ref,
        RUNTIME_ADAPTATION_SHARED_CONTRACT_REF
    );
    let mut all_case_ids: Vec<String> = Vec::new();
    for r in &page.power_posture_rows {
        all_case_ids.push(r.case_id.clone());
    }
    for r in &page.suspend_resume_rows {
        all_case_ids.push(r.case_id.clone());
    }
    for r in &page.monitor_continuity_rows {
        all_case_ids.push(r.case_id.clone());
    }
    for r in &page.foreground_protection_rows {
        all_case_ids.push(r.case_id.clone());
    }
    for r in &page.desktop_matrix_rows {
        all_case_ids.push(r.case_id.clone());
    }
    assert_eq!(
        export.case_ids, all_case_ids,
        "support export case ids must echo the page record order"
    );
}

#[test]
fn page_fixture_matches_seeded_builder() {
    let from_file: RuntimeAdaptationPage = load("page.json");
    let from_code = seeded_runtime_adaptation_page();
    assert_eq!(
        from_file, from_code,
        "fixture must be a literal projection of the seeded page; regenerate via the headless bin"
    );
}
