//! Fixture replay for the beta Start Center and workspace-switcher projection.
//!
//! The fixtures under `fixtures/ux/m3/start_center/` are generated by the
//! `aureline_shell_start_center` CLI bin so the checked-in JSON remains a
//! literal projection of the seeded beta page.

use aureline_shell::start_center::beta::{
    seeded_start_center_switcher_beta_page, validate_start_center_switcher_beta_page,
    validate_start_center_switcher_beta_support_export, StartCenterBetaPrimaryActionRecord,
    StartCenterSwitcherBetaPage, StartCenterSwitcherBetaPrivacyModeRecord,
    StartCenterSwitcherBetaSupportExport, StartCenterSwitcherBetaWorkRow,
    START_CENTER_SWITCHER_BETA_SCHEMA_VERSION, START_CENTER_SWITCHER_BETA_SHARED_CONTRACT_REF,
};
use aureline_workspace::{RecentWorkFailureState, SafeRecoveryAction, TargetKind};

const FIXTURE_DIR: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../fixtures/ux/m3/start_center"
);

fn load<T: serde::de::DeserializeOwned>(filename: &str) -> T {
    let path = format!("{}/{}", FIXTURE_DIR, filename);
    let body =
        std::fs::read_to_string(&path).unwrap_or_else(|err| panic!("failed to read {path}: {err}"));
    serde_json::from_str(&body).unwrap_or_else(|err| panic!("failed to parse {path}: {err}"))
}

#[test]
fn fixtures_round_trip_through_shared_types() {
    let actions: Vec<StartCenterBetaPrimaryActionRecord> = load("primary_actions.json");
    assert_eq!(actions.len(), 5);
    for action in &actions {
        assert_eq!(
            action.shared_contract_ref,
            START_CENTER_SWITCHER_BETA_SHARED_CONTRACT_REF
        );
        assert_eq!(
            action.schema_version,
            START_CENTER_SWITCHER_BETA_SCHEMA_VERSION
        );
        assert!(!action.sign_in_required_before_render);
        assert!(!action.network_required_before_render);
        assert_eq!(action.start_center_zone, "primary_work_resume");
    }

    let rows: Vec<StartCenterSwitcherBetaWorkRow> = load("rows.json");
    let switcher_rows: Vec<StartCenterSwitcherBetaWorkRow> = load("switcher_rows.json");
    assert_eq!(rows.len(), switcher_rows.len());
    assert!(rows
        .iter()
        .any(|row| row.target_kind == TargetKind::LocalFolder));
    assert!(rows
        .iter()
        .any(|row| row.target_kind == TargetKind::WorkspaceManifest));
    assert!(rows
        .iter()
        .any(|row| row.target_kind == TargetKind::SshWorkspace));
    assert!(rows
        .iter()
        .any(|row| row.target_kind == TargetKind::DevcontainerWorkspace));
    assert!(rows
        .iter()
        .any(|row| row.target_kind == TargetKind::ManagedCloudWorkspace));
    assert!(rows
        .iter()
        .any(|row| row.failure_state == RecentWorkFailureState::MissingPath));
    assert!(rows
        .iter()
        .any(|row| row.failure_state == RecentWorkFailureState::MovedRoot));
    assert!(rows
        .iter()
        .any(|row| row.failure_state == RecentWorkFailureState::ReconnectRequired));

    for row in &rows {
        if matches!(
            row.failure_state,
            RecentWorkFailureState::MissingPath | RecentWorkFailureState::MovedRoot
        ) {
            let action_ids: Vec<&str> = row
                .row_actions
                .iter()
                .map(|action| action.action_id.as_str())
                .collect();
            assert!(action_ids.contains(&SafeRecoveryAction::LocateMissingTarget.as_str()));
            assert!(action_ids.contains(&SafeRecoveryAction::OpenWithoutRestore.as_str()));
            assert!(action_ids.contains(&SafeRecoveryAction::RemoveFromRecents.as_str()));
        }
    }

    let privacy_modes: Vec<StartCenterSwitcherBetaPrivacyModeRecord> = load("privacy_modes.json");
    assert!(privacy_modes
        .iter()
        .any(|mode| mode.privacy_mode == "hide_paths" && mode.privacy_redaction_applied_count > 0));
    assert!(privacy_modes
        .iter()
        .any(|mode| mode.privacy_mode == "hide_recent_work"
            && mode.metadata_hidden
            && mode.local_open_still_available
            && mode.workspace_open_still_available));

    let page: StartCenterSwitcherBetaPage = load("page.json");
    validate_start_center_switcher_beta_page(&page).expect("page fixture must validate");
    assert_eq!(page.primary_actions, actions);
    assert_eq!(page.start_center_rows, rows);
    assert_eq!(page.workspace_switcher_rows, switcher_rows);
    assert_eq!(page.privacy_modes, privacy_modes);

    let export: StartCenterSwitcherBetaSupportExport = load("support_export.json");
    validate_start_center_switcher_beta_support_export(&export)
        .expect("support export fixture must validate");
    assert_eq!(export.page, page);
    assert_eq!(export.rows, page.support_rows);
    assert!(export.raw_secret_material_excluded);
}

#[test]
fn page_fixture_matches_seeded_builder() {
    let from_file: StartCenterSwitcherBetaPage = load("page.json");
    let from_code = seeded_start_center_switcher_beta_page();
    assert_eq!(
        from_file, from_code,
        "fixture must be generated from the headless Start Center inspector"
    );
}
