//! Fixture replay for the beta system-browser return-paths projection.
//!
//! The fixtures live under `fixtures/auth/m3/system_browser_return_paths/`
//! and are generated by the `aureline_shell_system_browser_return_paths`
//! headless inspector so the checked-in JSON stays a literal projection of
//! the seeded `SystemBrowserReturnPathsBetaPage` (no hand-written drift).

use aureline_shell::system_browser_return_paths::{
    audit_system_browser_return_paths_beta_rows, seeded_system_browser_return_paths_beta_page,
    validate_system_browser_return_paths_beta_page, AuthorityScopeClass, PasskeyStepUpPostureClass,
    SystemBrowserPolicyExceptionClass, SystemBrowserReturnPathBetaDefect,
    SystemBrowserReturnPathBetaDefectKind, SystemBrowserReturnPathBetaRow,
    SystemBrowserReturnPathBetaSupportRow, SystemBrowserReturnPathsBetaPage,
    SystemBrowserReturnPathsBetaSupportExport, SYSTEM_BROWSER_RETURN_PATHS_BETA_SCHEMA_VERSION,
    SYSTEM_BROWSER_RETURN_PATHS_BETA_SHARED_CONTRACT_REF,
};

const FIXTURE_DIR: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../fixtures/auth/m3/system_browser_return_paths"
);

fn load<T: serde::de::DeserializeOwned>(filename: &str) -> T {
    let path = format!("{}/{}", FIXTURE_DIR, filename);
    let body =
        std::fs::read_to_string(&path).unwrap_or_else(|err| panic!("failed to read {path}: {err}"));
    serde_json::from_str(&body).unwrap_or_else(|err| panic!("failed to parse {path}: {err}"))
}

#[test]
fn page_fixture_matches_seeded_builder() {
    let from_file: SystemBrowserReturnPathsBetaPage = load("page.json");
    let from_code = seeded_system_browser_return_paths_beta_page();
    assert_eq!(
        from_file, from_code,
        "fixture must be a literal projection of the seeded page; regenerate via the headless bin"
    );
}

#[test]
fn page_fixture_validates_with_zero_defects() {
    let page: SystemBrowserReturnPathsBetaPage = load("page.json");
    assert_eq!(
        page.shared_contract_ref,
        SYSTEM_BROWSER_RETURN_PATHS_BETA_SHARED_CONTRACT_REF
    );
    assert_eq!(
        page.schema_version,
        SYSTEM_BROWSER_RETURN_PATHS_BETA_SCHEMA_VERSION
    );
    assert!(page.defects.is_empty());
    validate_system_browser_return_paths_beta_page(&page).expect("seeded page must validate");

    let recomputed = audit_system_browser_return_paths_beta_rows(&page.rows, &page.support_rows);
    assert!(
        recomputed.is_empty(),
        "validator must agree with the empty defects array on the seeded fixture"
    );

    assert!(page.defaults_to_system_browser_or_explicit_exception());
    assert!(page.passkey_step_up_present_when_claimed());
}

#[test]
fn rows_and_support_rows_round_trip() {
    let rows: Vec<SystemBrowserReturnPathBetaRow> = load("rows.json");
    let support: Vec<SystemBrowserReturnPathBetaSupportRow> = load("support_rows.json");
    let defects: Vec<SystemBrowserReturnPathBetaDefect> = load("defects.json");

    assert_eq!(rows.len(), support.len(), "support row count must match");
    assert!(defects.is_empty(), "defects fixture must seed zero defects");

    for row in &rows {
        assert_eq!(
            row.shared_contract_ref,
            SYSTEM_BROWSER_RETURN_PATHS_BETA_SHARED_CONTRACT_REF
        );
        assert!(!row.row_id.is_empty());
        assert!(!row.case_id.is_empty());
        assert!(!row.source_claim_row_ref.is_empty());
        assert!(!row.default_action_token.is_empty());
        assert!(!row.policy_exception_token.is_empty());
        assert!(!row.passkey_step_up.posture_token.is_empty());
        assert!(!row.return_path_label.return_mode_token.is_empty());
        assert!(!row.return_path_label.target_label.is_empty());
        assert!(!row.return_path_label.requested_action_label.is_empty());
    }

    for support in &support {
        assert!(rows.iter().any(|r| r.row_id == support.row_id));
    }

    let recomputed = audit_system_browser_return_paths_beta_rows(&rows, &support);
    assert!(recomputed.is_empty(), "recomputed defects must be empty");
}

#[test]
fn fixture_includes_passkey_capable_row_with_offered_posture() {
    let page: SystemBrowserReturnPathsBetaPage = load("page.json");
    let row = page
        .rows
        .iter()
        .find(|r| r.passkey_capability_claimed)
        .expect("fixture must include at least one passkey-capable row");
    assert_eq!(
        row.passkey_step_up.posture_token,
        PasskeyStepUpPostureClass::PasskeyCapableOffered.as_str()
    );
    assert!(row.passkey_step_up.fallback_retry_path_token.is_some());
    assert!(row.system_browser_default);
    assert_eq!(
        row.policy_exception_token,
        SystemBrowserPolicyExceptionClass::SystemBrowserDefaultNoException.as_str()
    );
}

#[test]
fn fixture_includes_explicit_admin_policy_exception_row() {
    let page: SystemBrowserReturnPathsBetaPage = load("page.json");
    let row = page
        .rows
        .iter()
        .find(|r| {
            r.policy_exception_token
                == SystemBrowserPolicyExceptionClass::AdminPolicyDeviceCodeRequired.as_str()
        })
        .expect("fixture must include the admin-policy exception row");
    assert!(!row.system_browser_default);
    assert!(!row.policy_exception_label.is_empty());
    assert_eq!(
        row.requested_authority_scope_token,
        AuthorityScopeClass::ReadOnlyScope.as_str()
    );
    assert_eq!(
        row.granted_authority_scope_token,
        AuthorityScopeClass::ReadOnlyScope.as_str()
    );
}

#[test]
fn support_export_round_trips_through_validator() {
    let export: SystemBrowserReturnPathsBetaSupportExport = load("support_export.json");
    assert!(export.raw_private_material_excluded);
    assert!(export.defect_kinds_present.is_empty());
    assert!(export.defect_counts_by_kind.is_empty());
    assert_eq!(
        export.shared_contract_ref,
        SYSTEM_BROWSER_RETURN_PATHS_BETA_SHARED_CONTRACT_REF
    );
}

#[test]
fn drill_widening_authority_scope_replays_typed_defect() {
    let page: SystemBrowserReturnPathsBetaPage = load("drill_widening_authority_scope.json");
    let recomputed = audit_system_browser_return_paths_beta_rows(&page.rows, &page.support_rows);
    assert_eq!(
        recomputed, page.defects,
        "fixture defects must equal the live validator output"
    );
    assert!(recomputed.iter().any(|d| d.defect_kind
        == SystemBrowserReturnPathBetaDefectKind::ReturnWidensAuthorityScope));
}

#[test]
fn drill_passkey_unavailable_replays_typed_defect() {
    let page: SystemBrowserReturnPathsBetaPage =
        load("drill_passkey_unavailable_without_fallback.json");
    let recomputed = audit_system_browser_return_paths_beta_rows(&page.rows, &page.support_rows);
    assert_eq!(recomputed, page.defects);
    assert!(recomputed.iter().any(|d| d.defect_kind
        == SystemBrowserReturnPathBetaDefectKind::PasskeyUnavailableWithoutHonestFallback));
}

#[test]
fn drill_system_browser_not_default_replays_typed_defect() {
    let page: SystemBrowserReturnPathsBetaPage =
        load("drill_system_browser_not_default_without_exception.json");
    let recomputed = audit_system_browser_return_paths_beta_rows(&page.rows, &page.support_rows);
    assert_eq!(recomputed, page.defects);
    assert!(recomputed.iter().any(|d| d.defect_kind
        == SystemBrowserReturnPathBetaDefectKind::SystemBrowserNotDefaultWithoutExplicitException));
}

#[test]
fn render_summary_matches_page_summary() {
    use aureline_shell::system_browser_return_paths::SystemBrowserReturnPathsRenderSummary;
    let from_file: SystemBrowserReturnPathsRenderSummary = load("render_summary.json");
    let page: SystemBrowserReturnPathsBetaPage = load("page.json");
    let from_page = SystemBrowserReturnPathsRenderSummary::from_page(&page);
    assert_eq!(from_file, from_page);
}
