//! Fixture replay for the beta teaching/classroom conformance corpus.
//!
//! The fixtures live under `fixtures/help/m3/teaching_classroom/` and are
//! generated by the `aureline_shell_teaching_session` CLI bin, so the checked-in
//! JSON stays a literal projection of the seeded [`TeachingClassroomCorpus`].
//! These tests guard the exit-gate contract: teaching/classroom sessions are a
//! thin, reversible layer over learning mode, role-aware, cited, non-mutating by
//! default, honest about offline/cached docs-pack states, and restored on exit,
//! leave, or crash recovery without widening authority.

use aureline_shell::teaching_session::{
    seeded_teaching_classroom_corpus, validate_teaching_classroom_corpus, ClientClass,
    DemonstrationKind, DocsPackState, ReplayPolicy, RetentionClass, SegmentKind, SessionKind,
    TeachingClassroomCorpus, TeachingClassroomSessionCase, TeachingClassroomSupportExport,
    TeachingRestoreOutcome, TeachingRole, RestoreTrigger, TEACHING_SESSION_BETA_SCHEMA_VERSION,
    TEACHING_SESSION_BETA_SHARED_CONTRACT_REF,
};

const FIXTURE_DIR: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../fixtures/help/m3/teaching_classroom"
);

fn load<T: serde::de::DeserializeOwned>(filename: &str) -> T {
    let path = format!("{FIXTURE_DIR}/{filename}");
    let body =
        std::fs::read_to_string(&path).unwrap_or_else(|err| panic!("failed to read {path}: {err}"));
    serde_json::from_str(&body).unwrap_or_else(|err| panic!("failed to parse {path}: {err}"))
}

#[test]
fn corpus_fixture_matches_seeded_builder() {
    let on_disk: TeachingClassroomCorpus = load("corpus.json");
    let live = seeded_teaching_classroom_corpus();
    assert_eq!(
        on_disk, live,
        "fixtures must match the seeded corpus; regenerate with the headless inspector \
         (cargo run -p aureline-shell --bin aureline_shell_teaching_session -- corpus)"
    );
}

#[test]
fn corpus_fixture_validates_and_carries_shared_contract() {
    let corpus: TeachingClassroomCorpus = load("corpus.json");
    assert_eq!(corpus.schema_version, TEACHING_SESSION_BETA_SCHEMA_VERSION);
    assert_eq!(
        corpus.shared_contract_ref,
        TEACHING_SESSION_BETA_SHARED_CONTRACT_REF
    );
    validate_teaching_classroom_corpus(&corpus).expect("corpus fixture must validate");

    // The sessions fixture is the same case vector the corpus carries.
    let sessions: Vec<TeachingClassroomSessionCase> = load("sessions.json");
    assert_eq!(sessions, corpus.sessions);

    // The restore-outcomes fixture matches the corpus's restore outcomes.
    let restore_outcomes: Vec<TeachingRestoreOutcome> = load("restore_outcomes.json");
    assert_eq!(restore_outcomes, corpus.restore_outcomes);
}

#[test]
fn every_session_is_a_thin_reversible_layer_without_widened_authority() {
    let corpus: TeachingClassroomCorpus = load("corpus.json");
    for case in &corpus.sessions {
        let s = &case.session;
        // No widened authority, no terminal/debug grant, no hidden model.
        assert!(!s.grants_mutation_authority, "{}", case.case_id);
        assert!(!s.grants_terminal_or_debug_control, "{}", case.case_id);
        assert!(
            !s.grants_broader_authority_than_workspace,
            "{}",
            case.case_id
        );
        assert!(!s.establishes_private_data_ownership, "{}", case.case_id);
        assert!(!s.creates_hidden_progress_model, "{}", case.case_id);
        assert!(!s.creates_cohort_or_grading_flow, "{}", case.case_id);
        // Reuses learning-mode objects; every segment cites a real source.
        assert!(s.reuses_learning_mode_objects_only, "{}", case.case_id);
        assert!(s.segments_cite_learning_mode(), "{}", case.case_id);
        // Resumable across restart and reconnect.
        assert!(s.segments_are_resumable(), "{}", case.case_id);
        // Restore-on-exit is guaranteed.
        assert!(s.restore_on_exit_guaranteed, "{}", case.case_id);
    }
}

#[test]
fn demonstrations_are_non_mutating_by_default_and_mutations_reuse_the_command_path() {
    let corpus: TeachingClassroomCorpus = load("corpus.json");
    let mut saw_mutation = false;
    for case in &corpus.sessions {
        assert!(
            case.session.demonstrations_non_mutating_by_default,
            "{}",
            case.case_id
        );
        assert!(case.session.demonstrations_are_fenced(), "{}", case.case_id);
        for seg in &case.session.segments {
            if let Some(action) = &seg.demonstrated_action {
                assert!(
                    action.reuses_ordinary_command_path,
                    "{}: demonstration {} bypasses the command path",
                    case.case_id, action.action_id
                );
                if action.mutates_workspace {
                    saw_mutation = true;
                    assert_eq!(action.kind, DemonstrationKind::MutationThroughFences);
                    assert!(
                        action.is_properly_fenced(),
                        "{}: mutation {} is not properly fenced",
                        case.case_id, action.action_id
                    );
                    assert!(action.command_id.is_some());
                    assert!(action.preview_sheet_ref.is_some());
                    assert!(action.approval_path_ref.is_some());
                    assert!(action.rollback_semantics_ref.is_some());
                }
            }
        }
    }
    assert!(
        saw_mutation,
        "corpus must include at least one fenced mutation demonstration"
    );
}

#[test]
fn degraded_docs_pack_states_stay_visible_and_disclosed() {
    let corpus: TeachingClassroomCorpus = load("corpus.json");
    let mut saw_offline = false;
    let mut saw_not_installed = false;
    for case in &corpus.sessions {
        assert!(case.session.docs_pack_states_disclosed(), "{}", case.case_id);
        for seg in &case.session.segments {
            match seg.docs_pack_state {
                DocsPackState::Installed => {
                    assert!(seg.docs_pack_disclosure_ref.is_none(), "{}", seg.segment_id);
                }
                state => {
                    assert!(
                        seg.docs_pack_disclosure_ref.is_some(),
                        "{}: degraded state {} hides its disclosure",
                        seg.segment_id,
                        state.as_str()
                    );
                    if state == DocsPackState::Offline {
                        saw_offline = true;
                        assert!(state.requires_reconnect());
                    }
                    if state == DocsPackState::NotInstalled {
                        saw_not_installed = true;
                        assert!(state.requires_install());
                    }
                }
            }
        }
    }
    assert!(saw_offline, "corpus must exercise an offline docs pack");
    assert!(
        saw_not_installed,
        "corpus must exercise a not-installed docs pack"
    );
}

#[test]
fn roles_stay_separate_from_terminal_debug_control_and_drive_is_moderator_only() {
    let corpus: TeachingClassroomCorpus = load("corpus.json");
    for case in &corpus.sessions {
        let aff = &case.affordances;
        assert!(!aff.exposes_terminal_or_debug_control, "{}", case.case_id);
        assert!(!aff.exposes_misleading_control, "{}", case.case_id);
        for view in &aff.participant_views {
            assert!(
                !view.exposes_terminal_or_debug_control,
                "{}: {} exposes terminal/debug control",
                case.case_id, view.participant_id
            );
            // Only the moderator drives.
            if view.exposes_drive_control {
                assert_eq!(
                    view.role,
                    TeachingRole::Moderator,
                    "{}: {} drives without the moderator role",
                    case.case_id,
                    view.participant_id
                );
            }
            // Observers and scribes never see a mutation affordance.
            if matches!(view.role, TeachingRole::Observer | TeachingRole::Scribe) {
                assert!(
                    !view.exposes_mutation_affordance,
                    "{}: {} ({}) sees a mutation affordance",
                    case.case_id,
                    view.participant_id,
                    view.role.as_str()
                );
            }
            // Every mutation affordance reuses the ordinary command path.
            for a in &view.affordances {
                if a.mutates_workspace {
                    assert!(
                        a.routes_through_ordinary_command_path,
                        "{}: affordance {} bypasses the command path",
                        case.case_id, a.affordance_id
                    );
                }
                assert!(a.actionable, "{}: {} is broken", case.case_id, a.affordance_id);
                assert!(!a.is_terminal_or_debug_control);
            }
        }
    }
}

#[test]
fn constrained_clients_join_safe_without_broken_or_misleading_controls() {
    let corpus: TeachingClassroomCorpus = load("corpus.json");
    let mut saw_limited = false;
    let mut saw_low_bandwidth = false;
    for case in &corpus.sessions {
        let aff = &case.affordances;
        assert!(aff.all_constrained_clients_join_safe, "{}", case.case_id);
        assert!(aff.keyboard_complete, "{}", case.case_id);
        assert!(!aff.pointer_only, "{}", case.case_id);
        assert!(aff.screen_reader_reachable, "{}", case.case_id);
        for view in &aff.participant_views {
            if view.client_class.is_constrained() {
                if view.client_class == ClientClass::Limited {
                    saw_limited = true;
                }
                if view.client_class == ClientClass::LowBandwidth {
                    saw_low_bandwidth = true;
                }
                assert!(
                    !view.exposes_drive_control && !view.exposes_mutation_affordance,
                    "{}: constrained client {} sees a heavy control",
                    case.case_id, view.participant_id
                );
                assert!(view.constrained_client_join_safe, "{}", view.participant_id);
            }
        }
    }
    assert!(saw_limited, "corpus must include a limited client");
    assert!(saw_low_bandwidth, "corpus must include a low-bandwidth client");
}

#[test]
fn corpus_covers_every_role_state_pack_and_restore_trigger() {
    let corpus: TeachingClassroomCorpus = load("corpus.json");
    for role in [
        TeachingRole::Moderator,
        TeachingRole::Participant,
        TeachingRole::Observer,
        TeachingRole::Approver,
        TeachingRole::Scribe,
    ] {
        assert!(
            corpus.summary.roles_covered.contains(&role),
            "missing role {}",
            role.as_str()
        );
    }
    for class in [ClientClass::Full, ClientClass::Limited, ClientClass::LowBandwidth] {
        assert!(
            corpus.summary.client_classes_covered.contains(&class),
            "missing client class {}",
            class.as_str()
        );
    }
    for state in [
        DocsPackState::Installed,
        DocsPackState::Cached,
        DocsPackState::Mirrored,
        DocsPackState::Offline,
        DocsPackState::NotInstalled,
    ] {
        assert!(
            corpus.summary.docs_pack_states_covered.contains(&state),
            "missing docs-pack state {}",
            state.as_str()
        );
    }
    for kind in [
        SegmentKind::Tour,
        SegmentKind::ExercisePack,
        SegmentKind::GlossaryCard,
        SegmentKind::SpeakerNote,
    ] {
        assert!(
            corpus.summary.segment_kinds_covered.contains(&kind),
            "missing segment kind {}",
            kind.as_str()
        );
    }
    for kind in [
        DemonstrationKind::Explain,
        DemonstrationKind::OpenDocs,
        DemonstrationKind::PreviewOnly,
        DemonstrationKind::MutationThroughFences,
    ] {
        assert!(
            corpus.summary.demonstration_kinds_covered.contains(&kind),
            "missing demonstration kind {}",
            kind.as_str()
        );
    }
    for policy in [
        ReplayPolicy::Ephemeral,
        ReplayPolicy::LocalReplayUserOwned,
        ReplayPolicy::SharedArchiveOptIn,
    ] {
        assert!(
            corpus.summary.replay_policies_covered.contains(&policy),
            "missing replay policy {}",
            policy.as_str()
        );
    }
    for class in [
        RetentionClass::DiscardOnExit,
        RetentionClass::LocalUserOwned,
        RetentionClass::SharedWorkspaceRetained,
    ] {
        assert!(
            corpus.summary.retention_classes_covered.contains(&class),
            "missing retention class {}",
            class.as_str()
        );
    }
    for kind in [SessionKind::Teaching, SessionKind::Classroom] {
        assert!(
            corpus.summary.session_kinds_covered.contains(&kind),
            "missing session kind {}",
            kind.as_str()
        );
    }
    for trigger in [
        RestoreTrigger::Exit,
        RestoreTrigger::Leave,
        RestoreTrigger::CrashRecovery,
    ] {
        assert!(
            corpus.summary.restore_triggers_covered.contains(&trigger),
            "missing restore trigger {}",
            trigger.as_str()
        );
    }
}

#[test]
fn restore_outcomes_return_the_prior_environment_for_every_trigger() {
    let corpus: TeachingClassroomCorpus = load("corpus.json");
    let mut triggers = std::collections::BTreeSet::new();
    for outcome in &corpus.restore_outcomes {
        triggers.insert(outcome.trigger);
        assert!(outcome.matches_checkpoint, "{}", outcome.session_id);
        assert!(!outcome.left_in_improvised_shell, "{}", outcome.session_id);
        let session = corpus
            .sessions
            .iter()
            .find(|c| c.session.session_id == outcome.session_id)
            .map(|c| &c.session)
            .unwrap_or_else(|| panic!("restore outcome references unknown session"));
        assert_eq!(
            outcome.restored_layout_ref,
            session.restore_checkpoint.prior_layout_ref
        );
        assert_eq!(
            outcome.restored_focus_ref,
            session.restore_checkpoint.prior_focus_ref
        );
        assert_eq!(
            outcome.restored_panel_visibility_ref,
            session.restore_checkpoint.prior_panel_visibility_ref
        );
        assert_eq!(
            outcome.restored_accessibility_posture_ref,
            session.restore_checkpoint.accessibility_posture_ref
        );
    }
    assert_eq!(triggers.len(), 3, "restore outcomes must cover all three triggers");
}

#[test]
fn support_export_is_privacy_safe_and_row_aligned() {
    let corpus: TeachingClassroomCorpus = load("corpus.json");
    let on_disk: TeachingClassroomSupportExport = load("support_export.json");
    let live = TeachingClassroomSupportExport::from_corpus(
        "support-export:teaching-classroom-beta:001",
        "2026-05-20T00:00:00Z",
        &corpus,
    );
    assert_eq!(on_disk, live, "support export must match the seeded corpus");
    assert!(on_disk.raw_private_material_excluded);
    assert_eq!(on_disk.rows.len(), corpus.sessions.len());

    // The export carries support-safe enums and counts, never scenario copy or
    // segment titles.
    let export_json = serde_json::to_string(&on_disk).unwrap();
    for case in &corpus.sessions {
        assert!(
            !export_json.contains(&case.scenario_label),
            "support export leaked scenario copy for {}",
            case.case_id
        );
        for seg in &case.session.segments {
            assert!(
                !export_json.contains(&seg.title),
                "support export leaked segment title for {}",
                case.case_id
            );
        }
    }
}
