//! Fixture replay for the beta token / state / density / motion / theme audit.
//!
//! The fixtures live under `fixtures/ux/m3/theme_density_motion/` and
//! are generated by the `aureline_shell_token_state_audit` headless
//! inspector so the checked-in JSON stays a literal projection of the
//! seeded `TokenStateAuditPage` (no hand-written drift).

use aureline_shell::token_state_audit::{
    audit_rows, seeded_token_state_audit_page, validate_token_state_audit_page,
    LaunchCriticalSurfaceClass, SemanticPromise, TokenStateAuditDefect, TokenStateAuditPage,
    TokenStateAuditRow, TokenStateAuditSupportExport, TOKEN_STATE_AUDIT_BETA_SCHEMA_VERSION,
    TOKEN_STATE_AUDIT_BETA_SHARED_CONTRACT_REF,
};
use aureline_ui::components::state_registry::ComponentStateClass;
use aureline_ui::density::DensityClass;
use aureline_ui::themes::AccessibilityPostureClass;
use aureline_ui::tokens::ThemeClass;

const FIXTURE_DIR: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../fixtures/ux/m3/theme_density_motion"
);

fn load<T: serde::de::DeserializeOwned>(filename: &str) -> T {
    let path = format!("{}/{}", FIXTURE_DIR, filename);
    let body =
        std::fs::read_to_string(&path).unwrap_or_else(|err| panic!("failed to read {path}: {err}"));
    serde_json::from_str(&body).unwrap_or_else(|err| panic!("failed to parse {path}: {err}"))
}

#[test]
fn fixtures_round_trip_through_shared_types() {
    let rows: Vec<TokenStateAuditRow> = load("rows.json");
    assert!(!rows.is_empty(), "rows fixture must seed at least one row");
    for row in &rows {
        assert_eq!(
            row.shared_contract_ref,
            TOKEN_STATE_AUDIT_BETA_SHARED_CONTRACT_REF
        );
        assert_eq!(row.schema_version, TOKEN_STATE_AUDIT_BETA_SCHEMA_VERSION);
        assert!(
            !row.motion_preservation.motion_preset_ref.is_empty(),
            "{} must name a motion preset reference",
            row.row_id
        );
        if row
            .promised_semantics
            .contains(&SemanticPromise::FocusLegible)
        {
            assert!(
                row.required_component_states
                    .contains(&ComponentStateClass::FocusVisible),
                "{} promised focus_legible but did not declare FocusVisible",
                row.row_id
            );
        }
    }

    let defects: Vec<TokenStateAuditDefect> = load("defects.json");
    assert!(
        defects.is_empty(),
        "defects fixture must seed zero defects (got {})",
        defects.len()
    );

    let page: TokenStateAuditPage = load("page.json");
    assert_eq!(
        page.shared_contract_ref,
        TOKEN_STATE_AUDIT_BETA_SHARED_CONTRACT_REF
    );
    assert_eq!(page.rows.len(), rows.len());
    assert!(page.defects.is_empty());
    assert!(page.covers_required_themes());
    assert!(page.covers_required_densities());
    assert!(page.covers_required_postures());
    validate_token_state_audit_page(&page).expect("page must validate");

    let export: TokenStateAuditSupportExport = load("support_export.json");
    assert_eq!(
        export.shared_contract_ref,
        TOKEN_STATE_AUDIT_BETA_SHARED_CONTRACT_REF
    );
    assert!(export.raw_private_material_excluded);
    assert!(export.defect_kinds_present.is_empty());
    assert!(export.defect_counts_by_kind.is_empty());
    assert_eq!(export.page.rows.len(), page.rows.len());
}

#[test]
fn page_fixture_matches_seeded_builder() {
    let from_file: TokenStateAuditPage = load("page.json");
    let from_code = seeded_token_state_audit_page();
    assert_eq!(
        from_file, from_code,
        "fixture must be a literal projection of the seeded page; regenerate via the headless bin"
    );
}

#[test]
fn fixtures_cover_every_launch_critical_surface() {
    let page: TokenStateAuditPage = load("page.json");
    for required in [
        LaunchCriticalSurfaceClass::ShellChrome,
        LaunchCriticalSurfaceClass::StartCenter,
        LaunchCriticalSurfaceClass::CommandPalette,
        LaunchCriticalSurfaceClass::ScopeTruthChip,
        LaunchCriticalSurfaceClass::ActivityCenterRow,
        LaunchCriticalSurfaceClass::NotificationEnvelope,
        LaunchCriticalSurfaceClass::TrustPromptSheet,
        LaunchCriticalSurfaceClass::SettingsRoot,
    ] {
        assert!(
            page.summary.surfaces_present.contains(&required),
            "fixture must cover surface {}",
            required.as_str()
        );
    }
}

#[test]
fn fixtures_exercise_every_theme_density_and_posture_variant() {
    let page: TokenStateAuditPage = load("page.json");
    for theme in [
        ThemeClass::DarkReference,
        ThemeClass::LightParity,
        ThemeClass::HighContrastDark,
        ThemeClass::HighContrastLight,
    ] {
        assert!(
            page.summary.themes_present.contains(&theme),
            "fixture must exercise theme {}",
            theme.token()
        );
    }
    for density in [
        DensityClass::Compact,
        DensityClass::Standard,
        DensityClass::Comfortable,
    ] {
        assert!(
            page.summary.densities_present.contains(&density),
            "fixture must exercise density {}",
            density.token()
        );
    }
    for posture in [
        AccessibilityPostureClass::MotionStandard,
        AccessibilityPostureClass::MotionReduced,
        AccessibilityPostureClass::MotionLowMotion,
        AccessibilityPostureClass::MotionPowerSaver,
        AccessibilityPostureClass::MotionCriticalHotPath,
    ] {
        assert!(
            page.summary.postures_present.contains(&posture),
            "fixture must exercise posture {}",
            posture.token()
        );
    }
}

#[test]
fn validator_flags_drift_when_a_required_token_is_dropped() {
    let mut page = seeded_token_state_audit_page();
    page.rows[0].required_color_tokens.clear();
    let defects = audit_rows(&page.rows);
    assert!(
        !defects.is_empty(),
        "validator must surface defects when a required token is dropped"
    );
}
