//! Fixture replay for the beta workspace-management projection.
//!
//! The fixtures live under `fixtures/ux/m3/window_topology/` and are
//! generated by the `aureline_shell_windows` CLI bin so the checked-in
//! JSON stays a literal projection of the seeded `WindowsBetaPage`
//! (no hand-written drift).

use aureline_shell::windows::{
    seeded_windows_beta_page, validate_windows_beta_page, CrossWindowMoveIntent, PaneDetachIntent,
    RestoreFidelityClass, RestoreTopologyOutcome, SplitWindowIntent, SurfaceKindClass,
    TopologyChangeClass, WindowsBetaPage, WindowsBetaSupportExport, WINDOWS_BETA_SCHEMA_VERSION,
    WINDOWS_BETA_SHARED_CONTRACT_REF,
};

const FIXTURE_DIR: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../fixtures/ux/m3/window_topology"
);

fn load<T: serde::de::DeserializeOwned>(filename: &str) -> T {
    let path = format!("{}/{}", FIXTURE_DIR, filename);
    let body =
        std::fs::read_to_string(&path).unwrap_or_else(|err| panic!("failed to read {path}: {err}"));
    serde_json::from_str(&body).unwrap_or_else(|err| panic!("failed to parse {path}: {err}"))
}

#[test]
fn fixtures_round_trip_through_shared_types() {
    let split: Vec<SplitWindowIntent> = load("split_intents.json");
    assert!(
        !split.is_empty(),
        "split fixtures must seed at least one intent"
    );
    for record in &split {
        assert_eq!(record.shared_contract_ref, WINDOWS_BETA_SHARED_CONTRACT_REF);
        assert_eq!(record.schema_version, WINDOWS_BETA_SCHEMA_VERSION);
        assert!(record.first_weight > 0 && record.second_weight > 0);
        assert!(
            record.focus_owner_after_split == record.pane_ref
                || record.focus_owner_after_split == record.new_pane_ref,
            "split focus must remain in the split tree"
        );
    }

    let detach: Vec<PaneDetachIntent> = load("detach_intents.json");
    assert!(
        !detach.is_empty(),
        "detach fixtures must seed at least one intent"
    );
    for record in &detach {
        assert_eq!(record.shared_contract_ref, WINDOWS_BETA_SHARED_CONTRACT_REF);
        assert!(
            record.source_close_attributed_to_detach,
            "detach must not be attributed as an accidental tab close"
        );
        assert!(record.continuity.trust_badge_visible);
        assert!(record.continuity.host_badge_visible);
        assert!(record.continuity.recovery_cues_visible);
    }

    let moves: Vec<CrossWindowMoveIntent> = load("move_intents.json");
    assert!(
        moves.len() >= 3,
        "move fixtures must cover tab, review, and inspector"
    );
    let mut has_tab = false;
    let mut has_diff = false;
    let mut has_inspector = false;
    for record in &moves {
        assert_eq!(record.shared_contract_ref, WINDOWS_BETA_SHARED_CONTRACT_REF);
        assert!(
            record.canonical_workspace_truth_preserved,
            "cross-window move must preserve canonical workspace truth"
        );
        match record.surface_kind {
            SurfaceKindClass::EditorTab => has_tab = true,
            SurfaceKindClass::DiffReview => has_diff = true,
            SurfaceKindClass::Inspector => has_inspector = true,
            _ => {}
        }
    }
    assert!(has_tab, "move corpus must include a tab transfer");
    assert!(has_diff, "move corpus must include a diff/review transfer");
    assert!(
        has_inspector,
        "move corpus must include an inspector transfer"
    );

    let outcomes: Vec<RestoreTopologyOutcome> = load("restore_outcomes.json");
    assert!(
        outcomes.len() >= 3,
        "restore corpus must include mixed-DPI, display detach, and docking cases"
    );
    let mut has_scale = false;
    let mut has_display_removed = false;
    let mut has_docking = false;
    for outcome in &outcomes {
        assert_eq!(
            outcome.shared_contract_ref,
            WINDOWS_BETA_SHARED_CONTRACT_REF
        );
        if !matches!(outcome.restore_fidelity, RestoreFidelityClass::Exact) {
            assert!(
                outcome.user_visible_layout_adjusted_note_required,
                "{} must surface the layout-adjusted note when fidelity drops",
                outcome.case_id
            );
        }
        assert!(
            outcome.recovery_chrome.all_satisfied(),
            "{} must keep recovery-critical chrome reachable",
            outcome.case_id
        );
        for class in &outcome.topology_change_classes {
            match class {
                TopologyChangeClass::ScaleChanged => has_scale = true,
                TopologyChangeClass::DisplayRemoved => has_display_removed = true,
                TopologyChangeClass::DockingChanged => has_docking = true,
                _ => {}
            }
        }
        for pane in &outcome.pane_outcomes {
            if matches!(
                pane.surface_kind,
                SurfaceKindClass::Terminal | SurfaceKindClass::Notebook
            ) && pane.restore_posture == "evidence_only_placeholder"
            {
                assert!(
                    pane.requires_explicit_rerun,
                    "live-capability pane {} must require explicit rerun",
                    pane.pane_ref
                );
            }
        }
    }
    assert!(
        has_scale,
        "restore corpus must include a scale_changed case"
    );
    assert!(
        has_display_removed,
        "restore corpus must include a display_removed case"
    );
    assert!(
        has_docking,
        "restore corpus must include a docking_changed case"
    );

    let page: WindowsBetaPage = load("page.json");
    assert_eq!(page.shared_contract_ref, WINDOWS_BETA_SHARED_CONTRACT_REF);
    assert_eq!(page.split_intents.len(), split.len());
    assert_eq!(page.detach_intents.len(), detach.len());
    assert_eq!(page.move_intents.len(), moves.len());
    assert_eq!(page.restore_outcomes.len(), outcomes.len());
    validate_windows_beta_page(&page).expect("seeded page must pass validation");

    let export: WindowsBetaSupportExport = load("support_export.json");
    assert_eq!(export.shared_contract_ref, WINDOWS_BETA_SHARED_CONTRACT_REF);
    let mut all_case_ids: Vec<String> = Vec::new();
    for record in &page.split_intents {
        all_case_ids.push(record.case_id.clone());
    }
    for record in &page.detach_intents {
        all_case_ids.push(record.case_id.clone());
    }
    for record in &page.move_intents {
        all_case_ids.push(record.case_id.clone());
    }
    for record in &page.restore_outcomes {
        all_case_ids.push(record.case_id.clone());
    }
    assert_eq!(
        export.case_ids, all_case_ids,
        "support export case ids must echo the page record order"
    );
}

#[test]
fn page_fixture_matches_seeded_builder() {
    let from_file: WindowsBetaPage = load("page.json");
    let from_code = seeded_windows_beta_page();
    assert_eq!(
        from_file, from_code,
        "fixture must be a literal projection of the seeded page; regenerate via the headless bin"
    );
}
