//! Deterministic seeded catalog used by the live shell form host, the
//! markdown report, and the JSON fixtures checked in under
//! `fixtures/ux/m3/parameter_forms_and_invocation_review/`.
//!
//! Every field is pinned to a constant so the seed mints the same record
//! on every host, every revision, every OS. Scenarios cover the six
//! workpackages the spec calls out (WP-01 / WP-05 / WP-07 / WP-08 / WP-11 /
//! WP-14): destructive bulk replace (template/generator wedge), debug
//! attach to running process (run/debug profiles), outbound request issue
//! (request workspace), policy-pinned recipe step (automation recipe),
//! secret-bearing publish (irreversible publish), and a repair flow that
//! is blocked on a runtime prompt.

use super::{
    ApprovalPostureClass, ArgumentKind, BlockedPrerequisite, BlockedPrerequisiteClass,
    CapabilityScopeClass, ClientScope, CommandFormBundle, CommandFormsCatalog,
    CountTruthClass, ExecutionIntentClass, FieldProvenanceSummaryEntry, FieldStateClass,
    FieldStateRecord, FormLevelValidationRollup, FormSurfaceClass, InvocationReviewSheetRecord,
    NetworkActionClass, ParameterFormStateRecord, PolicyContext, PreviewClass,
    PreviewOrDryRunClass, ProcessActionClass, RedactionClass, RemoteActionClass, RepairHookRef,
    RestartOrReloadClass, ReviewSurfaceClass, RollbackClass, ScopeAxisClass, ScopeAxisRecord,
    SecretHandlingSummary, SideEffectClass, SourceLayerClass, TrustState,
    UnsupportedFieldClass, ValidationFinding, ValidationFindingClass, ValidationSeverity,
    ValueVisibilityClass, COMMAND_DESCRIPTOR_SCHEMA_REF, COMMAND_FORMS_CATALOG_ID,
    COMMAND_FORMS_CATALOG_RECORD_KIND, COMMAND_FORMS_GENERATED_AT,
    COMMAND_FORMS_SHARED_CONTRACT_REF, INVOCATION_REVIEW_SHEET_RECORD_KIND,
    INVOCATION_REVIEW_SHEET_SCHEMA_REF, INVOCATION_REVIEW_SHEET_SCHEMA_VERSION,
    PARAMETER_FORM_STATE_RECORD_KIND, PARAMETER_FORM_STATE_SCHEMA_REF,
    PARAMETER_FORM_STATE_SCHEMA_VERSION,
};

fn policy_context(
    epoch: &str,
    trust_state: TrustState,
    execution_context_id: Option<&str>,
) -> PolicyContext {
    PolicyContext {
        policy_epoch: epoch.to_owned(),
        trust_state,
        execution_context_id: execution_context_id.map(str::to_owned),
    }
}

fn label_ref(layer: SourceLayerClass) -> String {
    format!("label:source_layer:{}", layer.as_str())
}

fn form_state(
    form_state_id: &str,
    command_id: &str,
    command_revision_ref: &str,
    surface: FormSurfaceClass,
    client_scope: ClientScope,
    fields: Vec<FieldStateRecord>,
    rollup: FormLevelValidationRollup,
    policy: PolicyContext,
    redaction: RedactionClass,
    supports_secret_handle_swap: bool,
) -> ParameterFormStateRecord {
    ParameterFormStateRecord {
        record_kind: PARAMETER_FORM_STATE_RECORD_KIND.to_owned(),
        parameter_form_state_schema_version: PARAMETER_FORM_STATE_SCHEMA_VERSION,
        form_state_id: form_state_id.to_owned(),
        command_id: command_id.to_owned(),
        command_revision_ref: command_revision_ref.to_owned(),
        form_surface_class: surface,
        client_scope,
        fields,
        validation_rollup: rollup,
        policy_context: policy,
        redaction_class: redaction,
        supports_secret_handle_swap,
        minted_at: COMMAND_FORMS_GENERATED_AT.to_owned(),
    }
}

#[allow(clippy::too_many_arguments)]
fn review_sheet(
    review_sheet_id: &str,
    command_id: &str,
    command_revision_ref: &str,
    form_state_id: &str,
    invocation_session_id: Option<&str>,
    review_surface_class: ReviewSurfaceClass,
    capability_scope: CapabilityScopeClass,
    preview_class: PreviewClass,
    approval_posture: ApprovalPostureClass,
    execution_intent: ExecutionIntentClass,
    scope_axes: Vec<ScopeAxisRecord>,
    side_effects: Vec<SideEffectClass>,
    process_actions: Vec<ProcessActionClass>,
    network_actions: Vec<NetworkActionClass>,
    remote_actions: Vec<RemoteActionClass>,
    rollback_class: RollbackClass,
    preview_or_dry_run_class: PreviewOrDryRunClass,
    preview_or_dry_run_available: bool,
    blocked_prerequisites: Vec<BlockedPrerequisite>,
    field_provenance_summary: Vec<FieldProvenanceSummaryEntry>,
    secret_handling_summary: Option<SecretHandlingSummary>,
    policy: PolicyContext,
    redaction: RedactionClass,
) -> InvocationReviewSheetRecord {
    InvocationReviewSheetRecord {
        record_kind: INVOCATION_REVIEW_SHEET_RECORD_KIND.to_owned(),
        invocation_review_sheet_schema_version: INVOCATION_REVIEW_SHEET_SCHEMA_VERSION,
        review_sheet_id: review_sheet_id.to_owned(),
        command_id: command_id.to_owned(),
        command_revision_ref: command_revision_ref.to_owned(),
        form_state_id: form_state_id.to_owned(),
        invocation_session_id: invocation_session_id.map(str::to_owned),
        review_surface_class,
        capability_scope_class: capability_scope,
        preview_class_declared: preview_class,
        approval_posture_class: approval_posture,
        execution_intent,
        scope_axes,
        side_effects,
        process_actions,
        network_actions,
        remote_actions,
        rollback_class,
        preview_or_dry_run_class,
        preview_or_dry_run_available,
        blocked_prerequisites,
        field_provenance_summary,
        secret_handling_summary,
        policy_context: policy,
        redaction_class: redaction,
        minted_at: COMMAND_FORMS_GENERATED_AT.to_owned(),
    }
}

fn bulk_replace_bundle() -> CommandFormBundle {
    let command_id = "cmd:workspace.bulk_replace_in_files.apply".to_owned();
    let command_revision_ref = "cmd-rev:workspace.bulk_replace_in_files:2026.05.18-01".to_owned();
    let form_state_id = "form-state:bulk_replace:desktop:scenario-01".to_owned();
    let review_sheet_id = "review-sheet:bulk_replace:desktop:scenario-01".to_owned();

    let fields = vec![
        FieldStateRecord {
            argument_name: "scope_glob".to_owned(),
            argument_kind: ArgumentKind::GlobExpression,
            is_required: true,
            field_state_class: FieldStateClass::Editable,
            source_layer_class: SourceLayerClass::UserOverride,
            source_layer_label_ref: label_ref(SourceLayerClass::UserOverride),
            originating_layer_chain: vec![
                SourceLayerClass::DescriptorDefault,
                SourceLayerClass::WorkspaceValue,
                SourceLayerClass::UserOverride,
            ],
            resolved_value_ref: Some("value:scope_glob:src_double_star_rs".to_owned()),
            default_value_ref: Some("value:scope_glob:double_star".to_owned()),
            value_visibility: ValueVisibilityClass::ValueVisible,
            redaction_class: RedactionClass::MetadataSafeDefault,
            restart_or_reload_class: RestartOrReloadClass::PreviewRecomputeRequired,
            enum_value_refs: Vec::new(),
            minimum_inclusive: None,
            maximum_inclusive: None,
            unsupported_field_class: None,
            unsupported_for_client_scopes: Vec::new(),
            narration_label_ref: "label:bulk_replace:argument:scope_glob".to_owned(),
            validation_findings: Vec::new(),
            supports_runtime_reveal: false,
            policy_pinned_when_trust_state_is: Vec::new(),
        },
        FieldStateRecord {
            argument_name: "find_pattern_ref".to_owned(),
            argument_kind: ArgumentKind::OpaqueIdRef,
            is_required: true,
            field_state_class: FieldStateClass::Editable,
            source_layer_class: SourceLayerClass::UserOverride,
            source_layer_label_ref: label_ref(SourceLayerClass::UserOverride),
            originating_layer_chain: vec![SourceLayerClass::UserOverride],
            resolved_value_ref: Some("value:find_pattern:legacy_api_call".to_owned()),
            default_value_ref: None,
            value_visibility: ValueVisibilityClass::ValueVisible,
            redaction_class: RedactionClass::MetadataSafeDefault,
            restart_or_reload_class: RestartOrReloadClass::PreviewRecomputeRequired,
            enum_value_refs: Vec::new(),
            minimum_inclusive: None,
            maximum_inclusive: None,
            unsupported_field_class: None,
            unsupported_for_client_scopes: Vec::new(),
            narration_label_ref: "label:bulk_replace:argument:find_pattern_ref".to_owned(),
            validation_findings: Vec::new(),
            supports_runtime_reveal: false,
            policy_pinned_when_trust_state_is: Vec::new(),
        },
        FieldStateRecord {
            argument_name: "replace_template_ref".to_owned(),
            argument_kind: ArgumentKind::OpaqueIdRef,
            is_required: true,
            field_state_class: FieldStateClass::Editable,
            source_layer_class: SourceLayerClass::UserOverride,
            source_layer_label_ref: label_ref(SourceLayerClass::UserOverride),
            originating_layer_chain: vec![SourceLayerClass::UserOverride],
            resolved_value_ref: Some("value:replace_template:modern_api_call".to_owned()),
            default_value_ref: None,
            value_visibility: ValueVisibilityClass::ValueVisible,
            redaction_class: RedactionClass::MetadataSafeDefault,
            restart_or_reload_class: RestartOrReloadClass::PreviewRecomputeRequired,
            enum_value_refs: Vec::new(),
            minimum_inclusive: None,
            maximum_inclusive: None,
            unsupported_field_class: None,
            unsupported_for_client_scopes: Vec::new(),
            narration_label_ref: "label:bulk_replace:argument:replace_template_ref".to_owned(),
            validation_findings: Vec::new(),
            supports_runtime_reveal: false,
            policy_pinned_when_trust_state_is: Vec::new(),
        },
        FieldStateRecord {
            argument_name: "case_sensitive".to_owned(),
            argument_kind: ArgumentKind::BooleanFlag,
            is_required: false,
            field_state_class: FieldStateClass::Editable,
            source_layer_class: SourceLayerClass::DescriptorDefault,
            source_layer_label_ref: label_ref(SourceLayerClass::DescriptorDefault),
            originating_layer_chain: vec![SourceLayerClass::DescriptorDefault],
            resolved_value_ref: Some("value:bool:true".to_owned()),
            default_value_ref: Some("value:bool:true".to_owned()),
            value_visibility: ValueVisibilityClass::ValueVisible,
            redaction_class: RedactionClass::MetadataSafeDefault,
            restart_or_reload_class: RestartOrReloadClass::PreviewRecomputeRequired,
            enum_value_refs: Vec::new(),
            minimum_inclusive: None,
            maximum_inclusive: None,
            unsupported_field_class: None,
            unsupported_for_client_scopes: Vec::new(),
            narration_label_ref: "label:bulk_replace:argument:case_sensitive".to_owned(),
            validation_findings: Vec::new(),
            supports_runtime_reveal: false,
            policy_pinned_when_trust_state_is: Vec::new(),
        },
    ];

    let form = form_state(
        &form_state_id,
        &command_id,
        &command_revision_ref,
        FormSurfaceClass::TemplateOrGeneratorForm,
        ClientScope::DesktopProduct,
        fields,
        FormLevelValidationRollup {
            overall_severity: ValidationSeverity::Informational,
            blocking_finding_count: 0,
            warning_finding_count: 0,
            informational_finding_count: 0,
        },
        policy_context("policy-epoch:2026.05.18", TrustState::Trusted, Some("exec:bulk_replace:proposal-01")),
        RedactionClass::MetadataSafeDefault,
        false,
    );

    let review = review_sheet(
        &review_sheet_id,
        &command_id,
        &command_revision_ref,
        &form_state_id,
        Some("invocation-session:bulk_replace:scenario-01"),
        ReviewSurfaceClass::TemplateOrGeneratorReview,
        CapabilityScopeClass::RecoverableDurableMutation,
        PreviewClass::DestructiveBulkMutationPreview,
        ApprovalPostureClass::ExplicitConfirmationRequired,
        ExecutionIntentClass::ApplyAfterPreview,
        vec![
            ScopeAxisRecord {
                axis_class: ScopeAxisClass::SelectedFilesOrGlobs,
                included_count: 42,
                excluded_count: 7,
                hidden_or_blocked_count: 0,
                count_truth_class: CountTruthClass::Exact,
                scope_narration_ref: "narration:bulk_replace:files".to_owned(),
                selected_scope_refs: vec![
                    "scope:file:src/api/legacy.rs".to_owned(),
                    "scope:file:src/api/migration.rs".to_owned(),
                ],
            },
            ScopeAxisRecord {
                axis_class: ScopeAxisClass::WorkspaceRoot,
                included_count: 1,
                excluded_count: 0,
                hidden_or_blocked_count: 0,
                count_truth_class: CountTruthClass::Exact,
                scope_narration_ref: "narration:bulk_replace:workspace".to_owned(),
                selected_scope_refs: vec!["scope:workspace:primary".to_owned()],
            },
        ],
        vec![
            SideEffectClass::LocalFilesystemMutation,
            SideEffectClass::WorkspaceStateMutation,
        ],
        vec![ProcessActionClass::NoProcessAction],
        vec![NetworkActionClass::NoNetworkAction],
        vec![RemoteActionClass::NoRemoteAction],
        RollbackClass::CheckpointBackedRevert,
        PreviewOrDryRunClass::PreviewStructuredDiff,
        true,
        Vec::new(),
        vec![
            FieldProvenanceSummaryEntry {
                argument_name: "scope_glob".to_owned(),
                source_layer_label_ref: label_ref(SourceLayerClass::UserOverride),
                value_visibility: ValueVisibilityClass::ValueVisible,
                narration_ref: Some("narration:bulk_replace:scope_glob".to_owned()),
            },
            FieldProvenanceSummaryEntry {
                argument_name: "find_pattern_ref".to_owned(),
                source_layer_label_ref: label_ref(SourceLayerClass::UserOverride),
                value_visibility: ValueVisibilityClass::ValueVisible,
                narration_ref: Some("narration:bulk_replace:find_pattern_ref".to_owned()),
            },
            FieldProvenanceSummaryEntry {
                argument_name: "replace_template_ref".to_owned(),
                source_layer_label_ref: label_ref(SourceLayerClass::UserOverride),
                value_visibility: ValueVisibilityClass::ValueVisible,
                narration_ref: Some("narration:bulk_replace:replace_template_ref".to_owned()),
            },
            FieldProvenanceSummaryEntry {
                argument_name: "case_sensitive".to_owned(),
                source_layer_label_ref: label_ref(SourceLayerClass::DescriptorDefault),
                value_visibility: ValueVisibilityClass::ValueVisible,
                narration_ref: Some("narration:bulk_replace:case_sensitive".to_owned()),
            },
        ],
        Some(SecretHandlingSummary {
            any_secret_bearing_field: false,
            all_handle_only: true,
            any_runtime_reveal_armed: false,
            redaction_class: RedactionClass::MetadataSafeDefault,
        }),
        policy_context("policy-epoch:2026.05.18", TrustState::Trusted, Some("exec:bulk_replace:proposal-01")),
        RedactionClass::MetadataSafeDefault,
    );

    CommandFormBundle {
        bundle_id: "bundle:bulk_replace:scenario-01".to_owned(),
        scenario_id: "bulk_replace_in_files_desktop_apply".to_owned(),
        form_state: form,
        review_sheet: review,
    }
}

fn debug_attach_bundle() -> CommandFormBundle {
    let command_id = "cmd:debug.attach_to_process".to_owned();
    let command_revision_ref = "cmd-rev:debug.attach_to_process:2026.05.18-01".to_owned();
    let form_state_id = "form-state:debug_attach:desktop:scenario-02".to_owned();
    let review_sheet_id = "review-sheet:debug_attach:desktop:scenario-02".to_owned();

    let fields = vec![
        FieldStateRecord {
            argument_name: "target_process_ref".to_owned(),
            argument_kind: ArgumentKind::OpaqueIdRef,
            is_required: true,
            field_state_class: FieldStateClass::Editable,
            source_layer_class: SourceLayerClass::SelectionInferred,
            source_layer_label_ref: label_ref(SourceLayerClass::SelectionInferred),
            originating_layer_chain: vec![SourceLayerClass::SelectionInferred],
            resolved_value_ref: Some("value:process:pid-58231".to_owned()),
            default_value_ref: None,
            value_visibility: ValueVisibilityClass::ValueVisible,
            redaction_class: RedactionClass::MetadataSafeDefault,
            restart_or_reload_class: RestartOrReloadClass::DebuggerRestartRequired,
            enum_value_refs: Vec::new(),
            minimum_inclusive: None,
            maximum_inclusive: None,
            unsupported_field_class: None,
            unsupported_for_client_scopes: Vec::new(),
            narration_label_ref: "label:debug_attach:argument:target_process_ref".to_owned(),
            validation_findings: Vec::new(),
            supports_runtime_reveal: false,
            policy_pinned_when_trust_state_is: Vec::new(),
        },
        FieldStateRecord {
            argument_name: "debugger_profile_ref".to_owned(),
            argument_kind: ArgumentKind::OpaqueIdRef,
            is_required: true,
            field_state_class: FieldStateClass::Editable,
            source_layer_class: SourceLayerClass::WorkspaceValue,
            source_layer_label_ref: label_ref(SourceLayerClass::WorkspaceValue),
            originating_layer_chain: vec![
                SourceLayerClass::DescriptorDefault,
                SourceLayerClass::WorkspaceValue,
            ],
            resolved_value_ref: Some("value:debugger_profile:lldb_attach_default".to_owned()),
            default_value_ref: Some("value:debugger_profile:auto".to_owned()),
            value_visibility: ValueVisibilityClass::ValueVisible,
            redaction_class: RedactionClass::MetadataSafeDefault,
            restart_or_reload_class: RestartOrReloadClass::DebuggerRestartRequired,
            enum_value_refs: Vec::new(),
            minimum_inclusive: None,
            maximum_inclusive: None,
            unsupported_field_class: None,
            unsupported_for_client_scopes: Vec::new(),
            narration_label_ref: "label:debug_attach:argument:debugger_profile_ref".to_owned(),
            validation_findings: Vec::new(),
            supports_runtime_reveal: false,
            policy_pinned_when_trust_state_is: Vec::new(),
        },
        FieldStateRecord {
            argument_name: "request_capability_token_ref".to_owned(),
            argument_kind: ArgumentKind::CapabilityRef,
            is_required: true,
            field_state_class: FieldStateClass::PolicyPinnedReadOnly,
            source_layer_class: SourceLayerClass::OrgPolicyPinned,
            source_layer_label_ref: label_ref(SourceLayerClass::OrgPolicyPinned),
            originating_layer_chain: vec![SourceLayerClass::OrgPolicyPinned],
            resolved_value_ref: Some("value:capability:debug_attach_managed".to_owned()),
            default_value_ref: None,
            value_visibility: ValueVisibilityClass::ValueHandleOnly,
            redaction_class: RedactionClass::OperatorOnlyRestricted,
            restart_or_reload_class: RestartOrReloadClass::NoRestartRequired,
            enum_value_refs: Vec::new(),
            minimum_inclusive: None,
            maximum_inclusive: None,
            unsupported_field_class: None,
            unsupported_for_client_scopes: Vec::new(),
            narration_label_ref: "label:debug_attach:argument:request_capability_token_ref"
                .to_owned(),
            validation_findings: Vec::new(),
            supports_runtime_reveal: false,
            policy_pinned_when_trust_state_is: vec![TrustState::Restricted, TrustState::Trusted],
        },
        FieldStateRecord {
            argument_name: "stop_on_attach".to_owned(),
            argument_kind: ArgumentKind::BooleanFlag,
            is_required: false,
            field_state_class: FieldStateClass::Editable,
            source_layer_class: SourceLayerClass::DescriptorDefault,
            source_layer_label_ref: label_ref(SourceLayerClass::DescriptorDefault),
            originating_layer_chain: vec![SourceLayerClass::DescriptorDefault],
            resolved_value_ref: Some("value:bool:true".to_owned()),
            default_value_ref: Some("value:bool:true".to_owned()),
            value_visibility: ValueVisibilityClass::ValueVisible,
            redaction_class: RedactionClass::MetadataSafeDefault,
            restart_or_reload_class: RestartOrReloadClass::NoRestartRequired,
            enum_value_refs: Vec::new(),
            minimum_inclusive: None,
            maximum_inclusive: None,
            unsupported_field_class: None,
            unsupported_for_client_scopes: Vec::new(),
            narration_label_ref: "label:debug_attach:argument:stop_on_attach".to_owned(),
            validation_findings: Vec::new(),
            supports_runtime_reveal: false,
            policy_pinned_when_trust_state_is: Vec::new(),
        },
    ];

    let form = form_state(
        &form_state_id,
        &command_id,
        &command_revision_ref,
        FormSurfaceClass::RunDebugProfileForm,
        ClientScope::DesktopProduct,
        fields,
        FormLevelValidationRollup {
            overall_severity: ValidationSeverity::Informational,
            blocking_finding_count: 0,
            warning_finding_count: 0,
            informational_finding_count: 0,
        },
        policy_context("policy-epoch:2026.05.18", TrustState::Trusted, Some("exec:debug_attach:proposal-01")),
        RedactionClass::OperatorOnlyRestricted,
        false,
    );

    let review = review_sheet(
        &review_sheet_id,
        &command_id,
        &command_revision_ref,
        &form_state_id,
        Some("invocation-session:debug_attach:scenario-02"),
        ReviewSurfaceClass::RunDebugReview,
        CapabilityScopeClass::ManagedWorkspaceControl,
        PreviewClass::RemoteAttachPreview,
        ApprovalPostureClass::StepUpAuthenticationRequired,
        ExecutionIntentClass::ApplyWithApproval,
        vec![ScopeAxisRecord {
            axis_class: ScopeAxisClass::SelectedRunsOrSessions,
            included_count: 1,
            excluded_count: 0,
            hidden_or_blocked_count: 0,
            count_truth_class: CountTruthClass::Exact,
            scope_narration_ref: "narration:debug_attach:target".to_owned(),
            selected_scope_refs: vec!["scope:process:pid-58231".to_owned()],
        }],
        vec![
            SideEffectClass::ProcessSpawnLocal,
            SideEffectClass::CredentialOrSecretUse,
        ],
        vec![ProcessActionClass::AttachToRunningProcess],
        vec![NetworkActionClass::InboundListenLocalLoopback],
        vec![RemoteActionClass::NoRemoteAction],
        RollbackClass::AutoRevertOnFailure,
        PreviewOrDryRunClass::PreviewInlineSummary,
        true,
        Vec::new(),
        vec![
            FieldProvenanceSummaryEntry {
                argument_name: "target_process_ref".to_owned(),
                source_layer_label_ref: label_ref(SourceLayerClass::SelectionInferred),
                value_visibility: ValueVisibilityClass::ValueVisible,
                narration_ref: Some("narration:debug_attach:target".to_owned()),
            },
            FieldProvenanceSummaryEntry {
                argument_name: "debugger_profile_ref".to_owned(),
                source_layer_label_ref: label_ref(SourceLayerClass::WorkspaceValue),
                value_visibility: ValueVisibilityClass::ValueVisible,
                narration_ref: Some("narration:debug_attach:profile".to_owned()),
            },
            FieldProvenanceSummaryEntry {
                argument_name: "request_capability_token_ref".to_owned(),
                source_layer_label_ref: label_ref(SourceLayerClass::OrgPolicyPinned),
                value_visibility: ValueVisibilityClass::ValueHandleOnly,
                narration_ref: Some("narration:debug_attach:capability".to_owned()),
            },
            FieldProvenanceSummaryEntry {
                argument_name: "stop_on_attach".to_owned(),
                source_layer_label_ref: label_ref(SourceLayerClass::DescriptorDefault),
                value_visibility: ValueVisibilityClass::ValueVisible,
                narration_ref: Some("narration:debug_attach:stop".to_owned()),
            },
        ],
        Some(SecretHandlingSummary {
            any_secret_bearing_field: true,
            all_handle_only: true,
            any_runtime_reveal_armed: false,
            redaction_class: RedactionClass::OperatorOnlyRestricted,
        }),
        policy_context("policy-epoch:2026.05.18", TrustState::Trusted, Some("exec:debug_attach:proposal-01")),
        RedactionClass::OperatorOnlyRestricted,
    );

    CommandFormBundle {
        bundle_id: "bundle:debug_attach:scenario-02".to_owned(),
        scenario_id: "debug_attach_to_process_desktop".to_owned(),
        form_state: form,
        review_sheet: review,
    }
}

fn outbound_request_bundle() -> CommandFormBundle {
    let command_id = "cmd:request_workspace.send_request".to_owned();
    let command_revision_ref =
        "cmd-rev:request_workspace.send_request:2026.05.18-01".to_owned();
    let form_state_id = "form-state:send_request:desktop:scenario-03".to_owned();
    let review_sheet_id = "review-sheet:send_request:desktop:scenario-03".to_owned();

    let fields = vec![
        FieldStateRecord {
            argument_name: "endpoint_ref".to_owned(),
            argument_kind: ArgumentKind::ProviderRef,
            is_required: true,
            field_state_class: FieldStateClass::Editable,
            source_layer_class: SourceLayerClass::UserOverride,
            source_layer_label_ref: label_ref(SourceLayerClass::UserOverride),
            originating_layer_chain: vec![
                SourceLayerClass::DescriptorDefault,
                SourceLayerClass::UserOverride,
            ],
            resolved_value_ref: Some("value:endpoint:api_staging".to_owned()),
            default_value_ref: Some("value:endpoint:api_default".to_owned()),
            value_visibility: ValueVisibilityClass::ValueVisible,
            redaction_class: RedactionClass::MetadataSafeDefault,
            restart_or_reload_class: RestartOrReloadClass::RequestReissueRequired,
            enum_value_refs: Vec::new(),
            minimum_inclusive: None,
            maximum_inclusive: None,
            unsupported_field_class: None,
            unsupported_for_client_scopes: Vec::new(),
            narration_label_ref: "label:send_request:argument:endpoint_ref".to_owned(),
            validation_findings: Vec::new(),
            supports_runtime_reveal: false,
            policy_pinned_when_trust_state_is: Vec::new(),
        },
        FieldStateRecord {
            argument_name: "method".to_owned(),
            argument_kind: ArgumentKind::StringEnum,
            is_required: true,
            field_state_class: FieldStateClass::Editable,
            source_layer_class: SourceLayerClass::UserOverride,
            source_layer_label_ref: label_ref(SourceLayerClass::UserOverride),
            originating_layer_chain: vec![SourceLayerClass::UserOverride],
            resolved_value_ref: Some("value:method:post".to_owned()),
            default_value_ref: Some("value:method:get".to_owned()),
            value_visibility: ValueVisibilityClass::ValueVisible,
            redaction_class: RedactionClass::MetadataSafeDefault,
            restart_or_reload_class: RestartOrReloadClass::RequestReissueRequired,
            enum_value_refs: vec![
                "value:method:get".to_owned(),
                "value:method:post".to_owned(),
                "value:method:put".to_owned(),
                "value:method:patch".to_owned(),
                "value:method:delete".to_owned(),
            ],
            minimum_inclusive: None,
            maximum_inclusive: None,
            unsupported_field_class: None,
            unsupported_for_client_scopes: Vec::new(),
            narration_label_ref: "label:send_request:argument:method".to_owned(),
            validation_findings: Vec::new(),
            supports_runtime_reveal: false,
            policy_pinned_when_trust_state_is: Vec::new(),
        },
        FieldStateRecord {
            argument_name: "auth_handle_ref".to_owned(),
            argument_kind: ArgumentKind::CredentialHandleRef,
            is_required: true,
            field_state_class: FieldStateClass::SecretHandleSwapOnly,
            source_layer_class: SourceLayerClass::SecretHandleReference,
            source_layer_label_ref: label_ref(SourceLayerClass::SecretHandleReference),
            originating_layer_chain: vec![SourceLayerClass::SecretHandleReference],
            resolved_value_ref: Some("handle:secret:api_staging_token".to_owned()),
            default_value_ref: None,
            value_visibility: ValueVisibilityClass::ValueHandleOnly,
            redaction_class: RedactionClass::OperatorOnlyRestricted,
            restart_or_reload_class: RestartOrReloadClass::RequestReissueRequired,
            enum_value_refs: Vec::new(),
            minimum_inclusive: None,
            maximum_inclusive: None,
            unsupported_field_class: None,
            unsupported_for_client_scopes: Vec::new(),
            narration_label_ref: "label:send_request:argument:auth_handle_ref".to_owned(),
            validation_findings: Vec::new(),
            supports_runtime_reveal: true,
            policy_pinned_when_trust_state_is: Vec::new(),
        },
        FieldStateRecord {
            argument_name: "request_body_ref".to_owned(),
            argument_kind: ArgumentKind::OpaqueIdRef,
            is_required: false,
            field_state_class: FieldStateClass::Editable,
            source_layer_class: SourceLayerClass::WorkspaceValue,
            source_layer_label_ref: label_ref(SourceLayerClass::WorkspaceValue),
            originating_layer_chain: vec![SourceLayerClass::WorkspaceValue],
            resolved_value_ref: Some("value:request_body:create_user_payload".to_owned()),
            default_value_ref: None,
            value_visibility: ValueVisibilityClass::ValueVisible,
            redaction_class: RedactionClass::MetadataSafeDefault,
            restart_or_reload_class: RestartOrReloadClass::RequestReissueRequired,
            enum_value_refs: Vec::new(),
            minimum_inclusive: None,
            maximum_inclusive: None,
            unsupported_field_class: None,
            unsupported_for_client_scopes: Vec::new(),
            narration_label_ref: "label:send_request:argument:request_body_ref".to_owned(),
            validation_findings: Vec::new(),
            supports_runtime_reveal: false,
            policy_pinned_when_trust_state_is: Vec::new(),
        },
        FieldStateRecord {
            argument_name: "include_response_in_history".to_owned(),
            argument_kind: ArgumentKind::BooleanFlag,
            is_required: false,
            field_state_class: FieldStateClass::Editable,
            source_layer_class: SourceLayerClass::WorkspaceValue,
            source_layer_label_ref: label_ref(SourceLayerClass::WorkspaceValue),
            originating_layer_chain: vec![SourceLayerClass::WorkspaceValue],
            resolved_value_ref: Some("value:bool:false".to_owned()),
            default_value_ref: Some("value:bool:true".to_owned()),
            value_visibility: ValueVisibilityClass::ValueVisible,
            redaction_class: RedactionClass::MetadataSafeDefault,
            restart_or_reload_class: RestartOrReloadClass::NoRestartRequired,
            enum_value_refs: Vec::new(),
            minimum_inclusive: None,
            maximum_inclusive: None,
            unsupported_field_class: None,
            unsupported_for_client_scopes: Vec::new(),
            narration_label_ref:
                "label:send_request:argument:include_response_in_history".to_owned(),
            validation_findings: Vec::new(),
            supports_runtime_reveal: false,
            policy_pinned_when_trust_state_is: Vec::new(),
        },
    ];

    let form = form_state(
        &form_state_id,
        &command_id,
        &command_revision_ref,
        FormSurfaceClass::RequestWorkspaceForm,
        ClientScope::DesktopProduct,
        fields,
        FormLevelValidationRollup {
            overall_severity: ValidationSeverity::Informational,
            blocking_finding_count: 0,
            warning_finding_count: 0,
            informational_finding_count: 0,
        },
        policy_context("policy-epoch:2026.05.18", TrustState::Trusted, Some("exec:send_request:proposal-01")),
        RedactionClass::OperatorOnlyRestricted,
        true,
    );

    let review = review_sheet(
        &review_sheet_id,
        &command_id,
        &command_revision_ref,
        &form_state_id,
        Some("invocation-session:send_request:scenario-03"),
        ReviewSurfaceClass::RequestWorkspaceReview,
        CapabilityScopeClass::ExternallyVisibleMutation,
        PreviewClass::ExternallyMutatingPreview,
        ApprovalPostureClass::ExplicitConfirmationRequired,
        ExecutionIntentClass::ApplyAfterPreview,
        vec![
            ScopeAxisRecord {
                axis_class: ScopeAxisClass::SelectedRequestsOrEndpoints,
                included_count: 1,
                excluded_count: 0,
                hidden_or_blocked_count: 0,
                count_truth_class: CountTruthClass::Exact,
                scope_narration_ref: "narration:send_request:endpoint".to_owned(),
                selected_scope_refs: vec!["scope:endpoint:api_staging".to_owned()],
            },
        ],
        vec![
            SideEffectClass::NetworkRequestOutbound,
            SideEffectClass::CredentialOrSecretUse,
        ],
        vec![ProcessActionClass::NoProcessAction],
        vec![NetworkActionClass::OutboundRequestExternalProvider],
        vec![RemoteActionClass::NoRemoteAction],
        RollbackClass::CompensatingActionRequired,
        PreviewOrDryRunClass::PreviewSimulateDryRun,
        true,
        Vec::new(),
        vec![
            FieldProvenanceSummaryEntry {
                argument_name: "endpoint_ref".to_owned(),
                source_layer_label_ref: label_ref(SourceLayerClass::UserOverride),
                value_visibility: ValueVisibilityClass::ValueVisible,
                narration_ref: Some("narration:send_request:endpoint".to_owned()),
            },
            FieldProvenanceSummaryEntry {
                argument_name: "method".to_owned(),
                source_layer_label_ref: label_ref(SourceLayerClass::UserOverride),
                value_visibility: ValueVisibilityClass::ValueVisible,
                narration_ref: Some("narration:send_request:method".to_owned()),
            },
            FieldProvenanceSummaryEntry {
                argument_name: "auth_handle_ref".to_owned(),
                source_layer_label_ref: label_ref(SourceLayerClass::SecretHandleReference),
                value_visibility: ValueVisibilityClass::ValueHandleOnly,
                narration_ref: Some("narration:send_request:auth_handle".to_owned()),
            },
            FieldProvenanceSummaryEntry {
                argument_name: "request_body_ref".to_owned(),
                source_layer_label_ref: label_ref(SourceLayerClass::WorkspaceValue),
                value_visibility: ValueVisibilityClass::ValueVisible,
                narration_ref: Some("narration:send_request:body".to_owned()),
            },
            FieldProvenanceSummaryEntry {
                argument_name: "include_response_in_history".to_owned(),
                source_layer_label_ref: label_ref(SourceLayerClass::WorkspaceValue),
                value_visibility: ValueVisibilityClass::ValueVisible,
                narration_ref: Some("narration:send_request:history".to_owned()),
            },
        ],
        Some(SecretHandlingSummary {
            any_secret_bearing_field: true,
            all_handle_only: true,
            any_runtime_reveal_armed: false,
            redaction_class: RedactionClass::OperatorOnlyRestricted,
        }),
        policy_context("policy-epoch:2026.05.18", TrustState::Trusted, Some("exec:send_request:proposal-01")),
        RedactionClass::OperatorOnlyRestricted,
    );

    CommandFormBundle {
        bundle_id: "bundle:send_request:scenario-03".to_owned(),
        scenario_id: "request_workspace_send_request_desktop".to_owned(),
        form_state: form,
        review_sheet: review,
    }
}

fn recipe_step_blocked_bundle() -> CommandFormBundle {
    let command_id = "cmd:automation.recipe_run_step".to_owned();
    let command_revision_ref = "cmd-rev:automation.recipe_run_step:2026.05.18-01".to_owned();
    let form_state_id = "form-state:recipe_run:desktop:scenario-04".to_owned();
    let review_sheet_id = "review-sheet:recipe_run:desktop:scenario-04".to_owned();

    let blocking_finding = ValidationFinding {
        finding_class: ValidationFindingClass::ValueFailedPolicyPin,
        severity: ValidationSeverity::Blocking,
        narration_ref: "narration:recipe_run:policy_pin_blocked".to_owned(),
        repair_hint_ref: Some("repair:recipe_run:request_policy_change".to_owned()),
        docs_anchor_ref: Some("docs:anchor:recipe_run:policy_pin".to_owned()),
    };

    let fields = vec![
        FieldStateRecord {
            argument_name: "recipe_ref".to_owned(),
            argument_kind: ArgumentKind::OpaqueIdRef,
            is_required: true,
            field_state_class: FieldStateClass::Editable,
            source_layer_class: SourceLayerClass::AutomationRecipeSupplied,
            source_layer_label_ref: label_ref(SourceLayerClass::AutomationRecipeSupplied),
            originating_layer_chain: vec![SourceLayerClass::AutomationRecipeSupplied],
            resolved_value_ref: Some("value:recipe:onboard_new_service".to_owned()),
            default_value_ref: None,
            value_visibility: ValueVisibilityClass::ValueVisible,
            redaction_class: RedactionClass::MetadataSafeDefault,
            restart_or_reload_class: RestartOrReloadClass::NoRestartRequired,
            enum_value_refs: Vec::new(),
            minimum_inclusive: None,
            maximum_inclusive: None,
            unsupported_field_class: None,
            unsupported_for_client_scopes: Vec::new(),
            narration_label_ref: "label:recipe_run:argument:recipe_ref".to_owned(),
            validation_findings: Vec::new(),
            supports_runtime_reveal: false,
            policy_pinned_when_trust_state_is: Vec::new(),
        },
        FieldStateRecord {
            argument_name: "target_branch_ref".to_owned(),
            argument_kind: ArgumentKind::WorkspaceScopeRef,
            is_required: true,
            field_state_class: FieldStateClass::PolicyPinnedReadOnly,
            source_layer_class: SourceLayerClass::OrgPolicyPinned,
            source_layer_label_ref: label_ref(SourceLayerClass::OrgPolicyPinned),
            originating_layer_chain: vec![
                SourceLayerClass::AutomationRecipeSupplied,
                SourceLayerClass::OrgPolicyPinned,
            ],
            resolved_value_ref: Some("value:branch:main".to_owned()),
            default_value_ref: Some("value:branch:auto".to_owned()),
            value_visibility: ValueVisibilityClass::ValueVisible,
            redaction_class: RedactionClass::MetadataSafeDefault,
            restart_or_reload_class: RestartOrReloadClass::NoRestartRequired,
            enum_value_refs: Vec::new(),
            minimum_inclusive: None,
            maximum_inclusive: None,
            unsupported_field_class: None,
            unsupported_for_client_scopes: Vec::new(),
            narration_label_ref: "label:recipe_run:argument:target_branch_ref".to_owned(),
            validation_findings: vec![blocking_finding.clone()],
            supports_runtime_reveal: false,
            policy_pinned_when_trust_state_is: vec![TrustState::Trusted, TrustState::Restricted],
        },
        FieldStateRecord {
            argument_name: "auto_apply".to_owned(),
            argument_kind: ArgumentKind::BooleanFlag,
            is_required: false,
            field_state_class: FieldStateClass::Editable,
            source_layer_class: SourceLayerClass::AutomationRecipeSupplied,
            source_layer_label_ref: label_ref(SourceLayerClass::AutomationRecipeSupplied),
            originating_layer_chain: vec![SourceLayerClass::AutomationRecipeSupplied],
            resolved_value_ref: Some("value:bool:false".to_owned()),
            default_value_ref: Some("value:bool:false".to_owned()),
            value_visibility: ValueVisibilityClass::ValueVisible,
            redaction_class: RedactionClass::MetadataSafeDefault,
            restart_or_reload_class: RestartOrReloadClass::NoRestartRequired,
            enum_value_refs: Vec::new(),
            minimum_inclusive: None,
            maximum_inclusive: None,
            unsupported_field_class: None,
            unsupported_for_client_scopes: Vec::new(),
            narration_label_ref: "label:recipe_run:argument:auto_apply".to_owned(),
            validation_findings: Vec::new(),
            supports_runtime_reveal: false,
            policy_pinned_when_trust_state_is: Vec::new(),
        },
    ];

    let form = form_state(
        &form_state_id,
        &command_id,
        &command_revision_ref,
        FormSurfaceClass::AutomationRecipeStepEditor,
        ClientScope::DesktopProduct,
        fields,
        FormLevelValidationRollup {
            overall_severity: ValidationSeverity::Blocking,
            blocking_finding_count: 1,
            warning_finding_count: 0,
            informational_finding_count: 0,
        },
        policy_context("policy-epoch:2026.05.18", TrustState::Trusted, Some("exec:recipe_run:proposal-01")),
        RedactionClass::MetadataSafeDefault,
        false,
    );

    let review = review_sheet(
        &review_sheet_id,
        &command_id,
        &command_revision_ref,
        &form_state_id,
        None,
        ReviewSurfaceClass::AutomationRecipeReview,
        CapabilityScopeClass::RecoverableDurableMutation,
        PreviewClass::BatchScopePreview,
        ApprovalPostureClass::AdminPolicyApprovalRequired,
        ExecutionIntentClass::ProposePreviewOnly,
        vec![ScopeAxisRecord {
            axis_class: ScopeAxisClass::SelectedRecipeSteps,
            included_count: 5,
            excluded_count: 0,
            hidden_or_blocked_count: 1,
            count_truth_class: CountTruthClass::Exact,
            scope_narration_ref: "narration:recipe_run:steps".to_owned(),
            selected_scope_refs: vec![
                "scope:recipe:onboard_new_service:step-1".to_owned(),
                "scope:recipe:onboard_new_service:step-2".to_owned(),
            ],
        }],
        vec![SideEffectClass::WorkspaceStateMutation],
        vec![ProcessActionClass::NoProcessAction],
        vec![NetworkActionClass::NoNetworkAction],
        vec![RemoteActionClass::NoRemoteAction],
        RollbackClass::NamedUndoGroupRevert,
        PreviewOrDryRunClass::PreviewBatchScope,
        true,
        vec![BlockedPrerequisite {
            class: BlockedPrerequisiteClass::MissingPolicyAdmission,
            narration_ref: "narration:recipe_run:policy_blocker".to_owned(),
            repair_hook_ref: RepairHookRef {
                hook_kind: "request_admin_policy_change".to_owned(),
                hook_id: "hook:recipe_run:request_admin_policy".to_owned(),
                display_label: Some("Request policy change".to_owned()),
            },
            disabled_reason_code: Some("policy_blocked_in_context".to_owned()),
        }],
        vec![
            FieldProvenanceSummaryEntry {
                argument_name: "recipe_ref".to_owned(),
                source_layer_label_ref: label_ref(SourceLayerClass::AutomationRecipeSupplied),
                value_visibility: ValueVisibilityClass::ValueVisible,
                narration_ref: Some("narration:recipe_run:recipe_ref".to_owned()),
            },
            FieldProvenanceSummaryEntry {
                argument_name: "target_branch_ref".to_owned(),
                source_layer_label_ref: label_ref(SourceLayerClass::OrgPolicyPinned),
                value_visibility: ValueVisibilityClass::ValueVisible,
                narration_ref: Some("narration:recipe_run:branch".to_owned()),
            },
            FieldProvenanceSummaryEntry {
                argument_name: "auto_apply".to_owned(),
                source_layer_label_ref: label_ref(SourceLayerClass::AutomationRecipeSupplied),
                value_visibility: ValueVisibilityClass::ValueVisible,
                narration_ref: Some("narration:recipe_run:auto_apply".to_owned()),
            },
        ],
        Some(SecretHandlingSummary {
            any_secret_bearing_field: false,
            all_handle_only: true,
            any_runtime_reveal_armed: false,
            redaction_class: RedactionClass::MetadataSafeDefault,
        }),
        policy_context("policy-epoch:2026.05.18", TrustState::Trusted, Some("exec:recipe_run:proposal-01")),
        RedactionClass::MetadataSafeDefault,
    );

    CommandFormBundle {
        bundle_id: "bundle:recipe_run:scenario-04".to_owned(),
        scenario_id: "recipe_run_blocked_by_policy".to_owned(),
        form_state: form,
        review_sheet: review,
    }
}

fn publish_release_bundle() -> CommandFormBundle {
    let command_id = "cmd:release.publish_artifact".to_owned();
    let command_revision_ref = "cmd-rev:release.publish_artifact:2026.05.18-01".to_owned();
    let form_state_id = "form-state:publish:desktop:scenario-05".to_owned();
    let review_sheet_id = "review-sheet:publish:desktop:scenario-05".to_owned();

    let fields = vec![
        FieldStateRecord {
            argument_name: "artifact_ref".to_owned(),
            argument_kind: ArgumentKind::OpaqueIdRef,
            is_required: true,
            field_state_class: FieldStateClass::Editable,
            source_layer_class: SourceLayerClass::UserOverride,
            source_layer_label_ref: label_ref(SourceLayerClass::UserOverride),
            originating_layer_chain: vec![SourceLayerClass::UserOverride],
            resolved_value_ref: Some("value:artifact:release_2026_05_18".to_owned()),
            default_value_ref: None,
            value_visibility: ValueVisibilityClass::ValueVisible,
            redaction_class: RedactionClass::MetadataSafeDefault,
            restart_or_reload_class: RestartOrReloadClass::PreviewRecomputeRequired,
            enum_value_refs: Vec::new(),
            minimum_inclusive: None,
            maximum_inclusive: None,
            unsupported_field_class: None,
            unsupported_for_client_scopes: Vec::new(),
            narration_label_ref: "label:publish:argument:artifact_ref".to_owned(),
            validation_findings: Vec::new(),
            supports_runtime_reveal: false,
            policy_pinned_when_trust_state_is: Vec::new(),
        },
        FieldStateRecord {
            argument_name: "signing_credential_handle_ref".to_owned(),
            argument_kind: ArgumentKind::CredentialHandleRef,
            is_required: true,
            field_state_class: FieldStateClass::SecretHandleSwapOnly,
            source_layer_class: SourceLayerClass::SecretHandleReference,
            source_layer_label_ref: label_ref(SourceLayerClass::SecretHandleReference),
            originating_layer_chain: vec![SourceLayerClass::SecretHandleReference],
            resolved_value_ref: Some("handle:secret:release_signing_key".to_owned()),
            default_value_ref: None,
            value_visibility: ValueVisibilityClass::ValueHandleOnly,
            redaction_class: RedactionClass::SigningEvidenceOnly,
            restart_or_reload_class: RestartOrReloadClass::NoRestartRequired,
            enum_value_refs: Vec::new(),
            minimum_inclusive: None,
            maximum_inclusive: None,
            unsupported_field_class: None,
            unsupported_for_client_scopes: Vec::new(),
            narration_label_ref:
                "label:publish:argument:signing_credential_handle_ref".to_owned(),
            validation_findings: Vec::new(),
            supports_runtime_reveal: false,
            policy_pinned_when_trust_state_is: Vec::new(),
        },
        FieldStateRecord {
            argument_name: "target_channel".to_owned(),
            argument_kind: ArgumentKind::StringEnum,
            is_required: true,
            field_state_class: FieldStateClass::Editable,
            source_layer_class: SourceLayerClass::UserOverride,
            source_layer_label_ref: label_ref(SourceLayerClass::UserOverride),
            originating_layer_chain: vec![
                SourceLayerClass::DescriptorDefault,
                SourceLayerClass::UserOverride,
            ],
            resolved_value_ref: Some("value:channel:preview".to_owned()),
            default_value_ref: Some("value:channel:preview".to_owned()),
            value_visibility: ValueVisibilityClass::ValueVisible,
            redaction_class: RedactionClass::MetadataSafeDefault,
            restart_or_reload_class: RestartOrReloadClass::PreviewRecomputeRequired,
            enum_value_refs: vec![
                "value:channel:nightly".to_owned(),
                "value:channel:preview".to_owned(),
                "value:channel:stable".to_owned(),
            ],
            minimum_inclusive: None,
            maximum_inclusive: None,
            unsupported_field_class: None,
            unsupported_for_client_scopes: Vec::new(),
            narration_label_ref: "label:publish:argument:target_channel".to_owned(),
            validation_findings: Vec::new(),
            supports_runtime_reveal: false,
            policy_pinned_when_trust_state_is: Vec::new(),
        },
        FieldStateRecord {
            argument_name: "release_notes_anchor".to_owned(),
            argument_kind: ArgumentKind::DocsAnchorRef,
            is_required: true,
            field_state_class: FieldStateClass::Editable,
            source_layer_class: SourceLayerClass::WorkspaceValue,
            source_layer_label_ref: label_ref(SourceLayerClass::WorkspaceValue),
            originating_layer_chain: vec![SourceLayerClass::WorkspaceValue],
            resolved_value_ref: Some("value:release_notes:2026.05.18".to_owned()),
            default_value_ref: None,
            value_visibility: ValueVisibilityClass::ValueVisible,
            redaction_class: RedactionClass::MetadataSafeDefault,
            restart_or_reload_class: RestartOrReloadClass::NoRestartRequired,
            enum_value_refs: Vec::new(),
            minimum_inclusive: None,
            maximum_inclusive: None,
            unsupported_field_class: None,
            unsupported_for_client_scopes: Vec::new(),
            narration_label_ref: "label:publish:argument:release_notes_anchor".to_owned(),
            validation_findings: Vec::new(),
            supports_runtime_reveal: false,
            policy_pinned_when_trust_state_is: Vec::new(),
        },
    ];

    let form = form_state(
        &form_state_id,
        &command_id,
        &command_revision_ref,
        FormSurfaceClass::DesktopParameterForm,
        ClientScope::DesktopProduct,
        fields,
        FormLevelValidationRollup {
            overall_severity: ValidationSeverity::Informational,
            blocking_finding_count: 0,
            warning_finding_count: 0,
            informational_finding_count: 0,
        },
        policy_context("policy-epoch:2026.05.18", TrustState::Trusted, Some("exec:publish:proposal-01")),
        RedactionClass::SigningEvidenceOnly,
        true,
    );

    let review = review_sheet(
        &review_sheet_id,
        &command_id,
        &command_revision_ref,
        &form_state_id,
        Some("invocation-session:publish:scenario-05"),
        ReviewSurfaceClass::DesktopReviewSheet,
        CapabilityScopeClass::IrreversibleHighBlastMutation,
        PreviewClass::IrreversiblePublishPreview,
        ApprovalPostureClass::SecondPartyReviewRequired,
        ExecutionIntentClass::ApplyWithApproval,
        vec![
            ScopeAxisRecord {
                axis_class: ScopeAxisClass::SelectedRemotesOrOrigins,
                included_count: 1,
                excluded_count: 0,
                hidden_or_blocked_count: 0,
                count_truth_class: CountTruthClass::Exact,
                scope_narration_ref: "narration:publish:remote".to_owned(),
                selected_scope_refs: vec!["scope:remote:release_registry".to_owned()],
            },
        ],
        vec![
            SideEffectClass::CredentialOrSecretUse,
            SideEffectClass::NetworkRequestOutbound,
            SideEffectClass::GitRemoteMutation,
        ],
        vec![ProcessActionClass::NoProcessAction],
        vec![NetworkActionClass::OutboundRequestExternalProvider],
        vec![RemoteActionClass::RemotePublishArtifact],
        RollbackClass::IrreversibleNoRevertPossible,
        PreviewOrDryRunClass::PreviewInlineSummary,
        true,
        Vec::new(),
        vec![
            FieldProvenanceSummaryEntry {
                argument_name: "artifact_ref".to_owned(),
                source_layer_label_ref: label_ref(SourceLayerClass::UserOverride),
                value_visibility: ValueVisibilityClass::ValueVisible,
                narration_ref: Some("narration:publish:artifact".to_owned()),
            },
            FieldProvenanceSummaryEntry {
                argument_name: "signing_credential_handle_ref".to_owned(),
                source_layer_label_ref: label_ref(SourceLayerClass::SecretHandleReference),
                value_visibility: ValueVisibilityClass::ValueHandleOnly,
                narration_ref: Some("narration:publish:signing".to_owned()),
            },
            FieldProvenanceSummaryEntry {
                argument_name: "target_channel".to_owned(),
                source_layer_label_ref: label_ref(SourceLayerClass::UserOverride),
                value_visibility: ValueVisibilityClass::ValueVisible,
                narration_ref: Some("narration:publish:channel".to_owned()),
            },
            FieldProvenanceSummaryEntry {
                argument_name: "release_notes_anchor".to_owned(),
                source_layer_label_ref: label_ref(SourceLayerClass::WorkspaceValue),
                value_visibility: ValueVisibilityClass::ValueVisible,
                narration_ref: Some("narration:publish:release_notes".to_owned()),
            },
        ],
        Some(SecretHandlingSummary {
            any_secret_bearing_field: true,
            all_handle_only: true,
            any_runtime_reveal_armed: false,
            redaction_class: RedactionClass::SigningEvidenceOnly,
        }),
        policy_context("policy-epoch:2026.05.18", TrustState::Trusted, Some("exec:publish:proposal-01")),
        RedactionClass::SigningEvidenceOnly,
    );

    CommandFormBundle {
        bundle_id: "bundle:publish:scenario-05".to_owned(),
        scenario_id: "release_publish_artifact_desktop".to_owned(),
        form_state: form,
        review_sheet: review,
    }
}

fn repair_runtime_prompt_bundle() -> CommandFormBundle {
    let command_id = "cmd:doctor.repair_workspace_health".to_owned();
    let command_revision_ref =
        "cmd-rev:doctor.repair_workspace_health:2026.05.18-01".to_owned();
    let form_state_id = "form-state:repair:cli:scenario-06".to_owned();
    let review_sheet_id = "review-sheet:repair:cli:scenario-06".to_owned();

    let missing_value_finding = ValidationFinding {
        finding_class: ValidationFindingClass::RequiredValueMissing,
        severity: ValidationSeverity::Blocking,
        narration_ref: "narration:repair:confirmation_required".to_owned(),
        repair_hint_ref: Some("repair:repair_workspace:supply_confirmation".to_owned()),
        docs_anchor_ref: Some("docs:anchor:repair_workspace:confirmation".to_owned()),
    };

    let fields = vec![
        FieldStateRecord {
            argument_name: "repair_action_ref".to_owned(),
            argument_kind: ArgumentKind::OpaqueIdRef,
            is_required: true,
            field_state_class: FieldStateClass::Editable,
            source_layer_class: SourceLayerClass::CliArgvSupplied,
            source_layer_label_ref: label_ref(SourceLayerClass::CliArgvSupplied),
            originating_layer_chain: vec![SourceLayerClass::CliArgvSupplied],
            resolved_value_ref: Some("value:repair_action:reset_workspace_indexer".to_owned()),
            default_value_ref: None,
            value_visibility: ValueVisibilityClass::ValueVisible,
            redaction_class: RedactionClass::MetadataSafeDefault,
            restart_or_reload_class: RestartOrReloadClass::WorkspaceReloadRequired,
            enum_value_refs: Vec::new(),
            minimum_inclusive: None,
            maximum_inclusive: None,
            unsupported_field_class: None,
            unsupported_for_client_scopes: Vec::new(),
            narration_label_ref: "label:repair:argument:repair_action_ref".to_owned(),
            validation_findings: Vec::new(),
            supports_runtime_reveal: false,
            policy_pinned_when_trust_state_is: Vec::new(),
        },
        FieldStateRecord {
            argument_name: "confirmation_phrase".to_owned(),
            argument_kind: ArgumentKind::StringFreeForm,
            is_required: true,
            field_state_class: FieldStateClass::RuntimePromptRequired,
            source_layer_class: SourceLayerClass::RuntimePrompt,
            source_layer_label_ref: label_ref(SourceLayerClass::RuntimePrompt),
            originating_layer_chain: vec![SourceLayerClass::RuntimePrompt],
            resolved_value_ref: None,
            default_value_ref: None,
            value_visibility: ValueVisibilityClass::ValueVisible,
            redaction_class: RedactionClass::MetadataSafeDefault,
            restart_or_reload_class: RestartOrReloadClass::NoRestartRequired,
            enum_value_refs: Vec::new(),
            minimum_inclusive: None,
            maximum_inclusive: None,
            unsupported_field_class: None,
            unsupported_for_client_scopes: Vec::new(),
            narration_label_ref: "label:repair:argument:confirmation_phrase".to_owned(),
            validation_findings: vec![missing_value_finding],
            supports_runtime_reveal: false,
            policy_pinned_when_trust_state_is: Vec::new(),
        },
        FieldStateRecord {
            argument_name: "include_remote_caches".to_owned(),
            argument_kind: ArgumentKind::BooleanFlag,
            is_required: false,
            field_state_class: FieldStateClass::UnsupportedInClientScope,
            source_layer_class: SourceLayerClass::DescriptorDefault,
            source_layer_label_ref: label_ref(SourceLayerClass::DescriptorDefault),
            originating_layer_chain: vec![SourceLayerClass::DescriptorDefault],
            resolved_value_ref: None,
            default_value_ref: Some("value:bool:true".to_owned()),
            value_visibility: ValueVisibilityClass::ValueOmittedForRedaction,
            redaction_class: RedactionClass::MetadataSafeDefault,
            restart_or_reload_class: RestartOrReloadClass::NoRestartRequired,
            enum_value_refs: Vec::new(),
            minimum_inclusive: None,
            maximum_inclusive: None,
            unsupported_field_class: Some(UnsupportedFieldClass::NotSupportedInHeadlessInspect),
            unsupported_for_client_scopes: vec![ClientScope::Cli, ClientScope::CompanionSurface],
            narration_label_ref: "label:repair:argument:include_remote_caches".to_owned(),
            validation_findings: Vec::new(),
            supports_runtime_reveal: false,
            policy_pinned_when_trust_state_is: Vec::new(),
        },
    ];

    let form = form_state(
        &form_state_id,
        &command_id,
        &command_revision_ref,
        FormSurfaceClass::CliInspectSurface,
        ClientScope::Cli,
        fields,
        FormLevelValidationRollup {
            overall_severity: ValidationSeverity::Blocking,
            blocking_finding_count: 1,
            warning_finding_count: 0,
            informational_finding_count: 0,
        },
        policy_context("policy-epoch:2026.05.18", TrustState::Trusted, Some("exec:repair:proposal-01")),
        RedactionClass::MetadataSafeDefault,
        false,
    );

    let review = review_sheet(
        &review_sheet_id,
        &command_id,
        &command_revision_ref,
        &form_state_id,
        None,
        ReviewSurfaceClass::CliInspectReview,
        CapabilityScopeClass::RecoverableDurableMutation,
        PreviewClass::BroadWorkspaceScopePreview,
        ApprovalPostureClass::ExplicitConfirmationRequired,
        ExecutionIntentClass::ProposePreviewOnly,
        vec![ScopeAxisRecord {
            axis_class: ScopeAxisClass::SelectedRepairTargets,
            included_count: 1,
            excluded_count: 0,
            hidden_or_blocked_count: 0,
            count_truth_class: CountTruthClass::Exact,
            scope_narration_ref: "narration:repair:target".to_owned(),
            selected_scope_refs: vec!["scope:repair:workspace_indexer".to_owned()],
        }],
        vec![
            SideEffectClass::WorkspaceStateMutation,
            SideEffectClass::LocalFilesystemMutation,
        ],
        vec![ProcessActionClass::NoProcessAction],
        vec![NetworkActionClass::NoNetworkAction],
        vec![RemoteActionClass::NoRemoteAction],
        RollbackClass::CheckpointBackedRevert,
        PreviewOrDryRunClass::PreviewSimulateDryRun,
        true,
        vec![BlockedPrerequisite {
            class: BlockedPrerequisiteClass::MissingRuntimePromptValue,
            narration_ref: "narration:repair:confirmation_blocker".to_owned(),
            repair_hook_ref: RepairHookRef {
                hook_kind: "refresh_freshness".to_owned(),
                hook_id: "hook:repair:supply_confirmation".to_owned(),
                display_label: Some("Supply confirmation phrase".to_owned()),
            },
            disabled_reason_code: Some("required_argument_unresolved".to_owned()),
        }],
        vec![
            FieldProvenanceSummaryEntry {
                argument_name: "repair_action_ref".to_owned(),
                source_layer_label_ref: label_ref(SourceLayerClass::CliArgvSupplied),
                value_visibility: ValueVisibilityClass::ValueVisible,
                narration_ref: Some("narration:repair:action".to_owned()),
            },
            FieldProvenanceSummaryEntry {
                argument_name: "confirmation_phrase".to_owned(),
                source_layer_label_ref: label_ref(SourceLayerClass::RuntimePrompt),
                value_visibility: ValueVisibilityClass::ValueVisible,
                narration_ref: Some("narration:repair:confirmation".to_owned()),
            },
            FieldProvenanceSummaryEntry {
                argument_name: "include_remote_caches".to_owned(),
                source_layer_label_ref: label_ref(SourceLayerClass::DescriptorDefault),
                value_visibility: ValueVisibilityClass::ValueOmittedForRedaction,
                narration_ref: Some("narration:repair:remote_caches_unsupported".to_owned()),
            },
        ],
        Some(SecretHandlingSummary {
            any_secret_bearing_field: false,
            all_handle_only: true,
            any_runtime_reveal_armed: false,
            redaction_class: RedactionClass::MetadataSafeDefault,
        }),
        policy_context("policy-epoch:2026.05.18", TrustState::Trusted, Some("exec:repair:proposal-01")),
        RedactionClass::MetadataSafeDefault,
    );

    CommandFormBundle {
        bundle_id: "bundle:repair:scenario-06".to_owned(),
        scenario_id: "repair_workspace_blocked_on_runtime_prompt".to_owned(),
        form_state: form,
        review_sheet: review,
    }
}

/// Returns the deterministic seeded command-forms catalog.
pub fn seeded_command_forms_catalog() -> CommandFormsCatalog {
    CommandFormsCatalog {
        record_kind: COMMAND_FORMS_CATALOG_RECORD_KIND.to_owned(),
        schema_version: PARAMETER_FORM_STATE_SCHEMA_VERSION,
        shared_contract_ref: COMMAND_FORMS_SHARED_CONTRACT_REF.to_owned(),
        catalog_id: COMMAND_FORMS_CATALOG_ID.to_owned(),
        source_descriptor_schema_ref: COMMAND_DESCRIPTOR_SCHEMA_REF.to_owned(),
        source_form_schema_ref: PARAMETER_FORM_STATE_SCHEMA_REF.to_owned(),
        source_review_schema_ref: INVOCATION_REVIEW_SHEET_SCHEMA_REF.to_owned(),
        bundles: vec![
            bulk_replace_bundle(),
            debug_attach_bundle(),
            outbound_request_bundle(),
            recipe_step_blocked_bundle(),
            publish_release_bundle(),
            repair_runtime_prompt_bundle(),
        ],
        generated_at: COMMAND_FORMS_GENERATED_AT.to_owned(),
    }
}
