//! AI review evidence, finding cards, and review-pack integration with change objects.
//!
//! This module implements the canonical M5 truth packet that binds AI-produced
//! review evidence to the finding cards a reviewer reads and to the review pack
//! and explicit change objects those cards are scoped against. It folds three
//! pillars into one export-safe record:
//!
//! - **AI review evidence** — each [`EvidenceCardEvidenceRow`] records a piece of
//!   review evidence with an explicit source class, freshness state, and
//!   provenance label, so a reviewer always knows what produced an observation
//!   and how fresh it is relative to the diff.
//! - **Finding cards** — each [`EvidenceCardFindingRow`] is the card a reviewer
//!   reads: it carries a severity, a status, the durable anchor it attaches to,
//!   the evidence it cites, the apply posture for any suggestion, and the change
//!   object it is scoped to.
//! - **Review-pack integration with change objects** — each
//!   [`EvidenceCardReviewPackBindingRow`] binds a review pack to an explicit
//!   change object, records required-check coverage, and labels detachment rather
//!   than silently dropping the binding.
//!
//! The packet references the upstream AI-evidence, review-pack, and
//! change-object contracts by id rather than embedding their content. Raw diff
//! bodies, raw model prompts or completions, raw build logs, raw provider
//! payloads, credentials, and live provider responses stay outside the support
//! boundary.
//!
//! The boundary schema is
//! [`schemas/review/ship-ai-review-evidence-finding-cards-and-review-pack-integration-with-change-objects.schema.json`](../../../../schemas/review/ship-ai-review-evidence-finding-cards-and-review-pack-integration-with-change-objects.schema.json).
//! The contract doc is
//! [`docs/review/m5/ship_ai_review_evidence_finding_cards_and_review_pack_integration_with_change_objects.md`](../../../../docs/review/m5/ship_ai_review_evidence_finding_cards_and_review_pack_integration_with_change_objects.md).
//! The protected fixture directory is
//! [`fixtures/review/m5/ship_ai_review_evidence_finding_cards_and_review_pack_integration_with_change_objects/`](../../../../fixtures/review/m5/ship_ai_review_evidence_finding_cards_and_review_pack_integration_with_change_objects/).

#[cfg(test)]
mod tests;

use std::collections::BTreeSet;
use std::error::Error;
use std::fmt;

use serde::{Deserialize, Serialize};

/// Stable record-kind tag carried by [`EvidenceCardPacket`].
pub const EVIDENCE_CARD_RECORD_KIND: &str =
    "ai_review_evidence_finding_cards_and_review_pack_change_object_integration";

/// Schema version for AI review-evidence finding-card records.
pub const EVIDENCE_CARD_SCHEMA_VERSION: u32 = 1;

/// Repo-relative path of the boundary schema.
pub const EVIDENCE_CARD_SCHEMA_REF: &str =
    "schemas/review/ship-ai-review-evidence-finding-cards-and-review-pack-integration-with-change-objects.schema.json";

/// Repo-relative path of the finding-card contract doc.
pub const EVIDENCE_CARD_DOC_REF: &str =
    "docs/review/m5/ship_ai_review_evidence_finding_cards_and_review_pack_integration_with_change_objects.md";

/// Repo-relative path of the AI review-evidence contract this lane builds on.
pub const EVIDENCE_CARD_AI_EVIDENCE_CONTRACT_REF: &str =
    "schemas/review/ai_review_evidence.schema.json";

/// Repo-relative path of the review-pack contract finding cards bind into.
pub const EVIDENCE_CARD_REVIEW_PACK_CONTRACT_REF: &str = "schemas/review/review_pack.schema.json";

/// Repo-relative path of the change-object contract review packs are scoped to.
pub const EVIDENCE_CARD_CHANGE_OBJECT_CONTRACT_REF: &str =
    "schemas/review/change_object_orchestration.schema.json";

/// Repo-relative path of the protected fixture directory.
pub const EVIDENCE_CARD_FIXTURE_DIR: &str =
    "fixtures/review/m5/ship_ai_review_evidence_finding_cards_and_review_pack_integration_with_change_objects";

/// Repo-relative path of the checked support-export artifact.
pub const EVIDENCE_CARD_ARTIFACT_REF: &str =
    "artifacts/review/m5/ship_ai_review_evidence_finding_cards_and_review_pack_integration_with_change_objects/support_export.json";

/// Repo-relative path of the checked Markdown summary.
pub const EVIDENCE_CARD_SUMMARY_REF: &str =
    "artifacts/review/m5/ship_ai_review_evidence_finding_cards_and_review_pack_integration_with_change_objects.md";

/// Source class for a piece of AI review evidence.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum EvidenceSourceClass {
    /// Evidence generated by a review model.
    ModelGenerated,
    /// Evidence produced by static analysis.
    StaticAnalysis,
    /// Evidence produced by a local check or test run.
    LocalCheck,
    /// Evidence imported from a provider review surface.
    ProviderImported,
}

impl EvidenceSourceClass {
    /// Stable token recorded in the packet.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::ModelGenerated => "model_generated",
            Self::StaticAnalysis => "static_analysis",
            Self::LocalCheck => "local_check",
            Self::ProviderImported => "provider_imported",
        }
    }
}

/// Freshness of a piece of evidence relative to the diff it describes.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum EvidenceFreshnessClass {
    /// Evidence is current against the diff.
    Fresh,
    /// The diff advanced under the evidence; the evidence shows a stale-diff label.
    StaleDiff,
    /// Newer evidence superseded this row.
    Superseded,
    /// Freshness cannot be computed (for example, offline).
    Unavailable,
}

impl EvidenceFreshnessClass {
    /// Stable token recorded in the packet.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Fresh => "fresh",
            Self::StaleDiff => "stale_diff",
            Self::Superseded => "superseded",
            Self::Unavailable => "unavailable",
        }
    }

    /// Whether this class represents stale or superseded evidence that must be labeled.
    pub const fn is_stale(self) -> bool {
        matches!(self, Self::StaleDiff | Self::Superseded)
    }
}

/// Severity shown on a review finding card.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FindingSeverityClass {
    /// The finding blocks landing.
    Blocking,
    /// High-severity finding.
    High,
    /// Medium-severity finding.
    Medium,
    /// Low-severity finding.
    Low,
    /// Informational only.
    Info,
}

impl FindingSeverityClass {
    /// Stable token recorded in the packet.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Blocking => "blocking",
            Self::High => "high",
            Self::Medium => "medium",
            Self::Low => "low",
            Self::Info => "info",
        }
    }
}

/// Status shown on a review finding card.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FindingStatusClass {
    /// Finding is open and unaddressed.
    Open,
    /// Finding has been acknowledged but not resolved.
    Acknowledged,
    /// Finding has been resolved.
    Resolved,
    /// Finding was dismissed with a reason.
    Dismissed,
    /// Finding was superseded by newer evidence.
    Superseded,
}

impl FindingStatusClass {
    /// Stable token recorded in the packet.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Open => "open",
            Self::Acknowledged => "acknowledged",
            Self::Resolved => "resolved",
            Self::Dismissed => "dismissed",
            Self::Superseded => "superseded",
        }
    }
}

/// Apply posture for any suggestion attached to a finding card.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FindingApplyPosture {
    /// The finding carries no applicable suggestion.
    NoSuggestion,
    /// A suggestion may be applied through a previewed, checkpointed, reviewable apply.
    SafeApplyPreviewed,
    /// A suggestion exists but must be applied manually.
    ManualOnly,
    /// Apply is blocked (for example, policy or stale diff) and labeled.
    ApplyBlocked,
}

impl FindingApplyPosture {
    /// Stable token recorded in the packet.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::NoSuggestion => "no_suggestion",
            Self::SafeApplyPreviewed => "safe_apply_previewed",
            Self::ManualOnly => "manual_only",
            Self::ApplyBlocked => "apply_blocked",
        }
    }

    /// Whether this posture requires an explicit block reason label.
    pub const fn requires_block_label(self) -> bool {
        matches!(self, Self::ApplyBlocked)
    }
}

/// Binding state between a review pack and a change object.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ReviewPackBindingState {
    /// Review pack is bound to the change object and current.
    BoundCurrent,
    /// Bound, but the change object's base advanced; the binding shows a stale-base label.
    BoundStaleBase,
    /// Binding is pending and not yet attached.
    UnboundPending,
    /// Binding detached and was relabeled rather than silently dropped.
    DetachedRelabeled,
}

impl ReviewPackBindingState {
    /// Stable token recorded in the packet.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::BoundCurrent => "bound_current",
            Self::BoundStaleBase => "bound_stale_base",
            Self::UnboundPending => "unbound_pending",
            Self::DetachedRelabeled => "detached_relabeled",
        }
    }

    /// Whether this state requires an explicit detach label.
    pub const fn requires_detach_label(self) -> bool {
        matches!(self, Self::DetachedRelabeled)
    }
}

/// Required-check coverage recorded for a review-pack / change-object binding.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ReviewPackCheckCoverage {
    /// Every required check the pack declares is present.
    AllRequiredPresent,
    /// A required check is missing and the gap is labeled.
    RequiredMissingLabeled,
    /// Only advisory checks are present.
    AdvisoryOnly,
    /// Coverage cannot be computed because CI status is unavailable (for example, offline).
    UnavailableOffline,
}

impl ReviewPackCheckCoverage {
    /// Stable token recorded in the packet.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::AllRequiredPresent => "all_required_present",
            Self::RequiredMissingLabeled => "required_missing_labeled",
            Self::AdvisoryOnly => "advisory_only",
            Self::UnavailableOffline => "unavailable_offline",
        }
    }
}

/// Downgrade trigger that can narrow this lane below its claimed qualification.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum EvidenceCardDowngradeTrigger {
    /// Proof packet has gone stale.
    ProofStale,
    /// Policy or legal block applies.
    PolicyBlocked,
    /// Evidence went stale or superseded.
    EvidenceStale,
    /// A finding card cited evidence that is missing.
    FindingEvidenceMissing,
    /// A review pack detached from its change object without a label.
    BindingDetachUnlabeled,
    /// Workspace trust narrowed.
    TrustNarrowing,
    /// Scope expanded beyond the qualified review boundary.
    ScopeExpansionUnqualified,
    /// An upstream dependency lane narrowed.
    UpstreamDependencyNarrowed,
}

impl EvidenceCardDowngradeTrigger {
    /// Every trigger, in declaration order.
    pub const ALL: [Self; 8] = [
        Self::ProofStale,
        Self::PolicyBlocked,
        Self::EvidenceStale,
        Self::FindingEvidenceMissing,
        Self::BindingDetachUnlabeled,
        Self::TrustNarrowing,
        Self::ScopeExpansionUnqualified,
        Self::UpstreamDependencyNarrowed,
    ];

    /// Stable token recorded in the packet.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::ProofStale => "proof_stale",
            Self::PolicyBlocked => "policy_blocked",
            Self::EvidenceStale => "evidence_stale",
            Self::FindingEvidenceMissing => "finding_evidence_missing",
            Self::BindingDetachUnlabeled => "binding_detach_unlabeled",
            Self::TrustNarrowing => "trust_narrowing",
            Self::ScopeExpansionUnqualified => "scope_expansion_unqualified",
            Self::UpstreamDependencyNarrowed => "upstream_dependency_narrowed",
        }
    }
}

/// Consumer surface that must project this lane's truth.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum EvidenceCardConsumerSurface {
    /// Review workspace finding-card surface.
    ReviewWorkspaceFindings,
    /// Review-pack panel.
    ReviewPackPanel,
    /// Merge-queue panel.
    MergeQueuePanel,
    /// CLI / headless replay or JSON output.
    CliHeadless,
    /// Support / export packet.
    SupportExport,
    /// Diagnostics or telemetry surface.
    Diagnostics,
    /// Help / About surface.
    HelpAbout,
}

impl EvidenceCardConsumerSurface {
    /// Every surface, in declaration order.
    pub const ALL: [Self; 7] = [
        Self::ReviewWorkspaceFindings,
        Self::ReviewPackPanel,
        Self::MergeQueuePanel,
        Self::CliHeadless,
        Self::SupportExport,
        Self::Diagnostics,
        Self::HelpAbout,
    ];

    /// Stable token recorded in the packet.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::ReviewWorkspaceFindings => "review_workspace_findings",
            Self::ReviewPackPanel => "review_pack_panel",
            Self::MergeQueuePanel => "merge_queue_panel",
            Self::CliHeadless => "cli_headless",
            Self::SupportExport => "support_export",
            Self::Diagnostics => "diagnostics",
            Self::HelpAbout => "help_about",
        }
    }
}

/// One AI review-evidence row.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct EvidenceCardEvidenceRow {
    /// Stable evidence id, cited by finding cards.
    pub evidence_id: String,
    /// Source class that produced this evidence.
    pub source: EvidenceSourceClass,
    /// Freshness of this evidence relative to the diff it describes.
    pub freshness: EvidenceFreshnessClass,
    /// Human-readable provenance label (what produced this evidence).
    pub provenance_label: String,
    /// Human-readable summary of the evidence.
    pub summary_label: String,
    /// Source contract refs consumed by this evidence row.
    pub source_contract_refs: Vec<String>,
}

/// One review finding-card row.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct EvidenceCardFindingRow {
    /// Stable finding id.
    pub finding_id: String,
    /// Severity shown on the card.
    pub severity: FindingSeverityClass,
    /// Status shown on the card.
    pub status: FindingStatusClass,
    /// Durable review anchor the card attaches to.
    pub anchor_id: String,
    /// Evidence id this card cites; must be present in `evidence_rows`.
    pub evidence_ref: String,
    /// Apply posture for any suggestion attached to this card.
    pub apply_posture: FindingApplyPosture,
    /// Change object id this card is scoped to; must be bound by a review-pack binding.
    pub change_object_ref: String,
    /// Human-readable card title.
    pub title_label: String,
    /// Apply-block label; required and non-empty when the posture is `apply_blocked`.
    pub apply_block_label: String,
}

/// One review-pack / change-object binding row.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct EvidenceCardReviewPackBindingRow {
    /// Review pack id.
    pub review_pack_id: String,
    /// Change object id the pack is bound to.
    pub change_object_id: String,
    /// Binding state between the pack and the change object.
    pub binding_state: ReviewPackBindingState,
    /// Required-check coverage for this binding.
    pub required_check_coverage: ReviewPackCheckCoverage,
    /// Human-readable attribution label (who/what produced this binding).
    pub attribution_label: String,
    /// Detach label; required and non-empty when the state is `detached_relabeled`.
    pub detach_label: String,
}

/// Trust and provenance review block.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct EvidenceCardTrustReview {
    /// AI evidence carries an explicit source and provenance.
    pub ai_evidence_provenance_explicit: bool,
    /// Evidence freshness is labeled, never silently hidden.
    pub evidence_freshness_labeled_not_hidden: bool,
    /// Every finding card cites evidence that exists in the packet.
    pub finding_cards_cite_real_evidence: bool,
    /// Finding severity and status are explicit.
    pub finding_severity_and_status_explicit: bool,
    /// Apply posture is explicit and never triggers a silent write.
    pub apply_posture_explicit_no_silent_write: bool,
    /// Review packs bind to an explicit change object.
    pub review_pack_binds_to_change_object: bool,
    /// Binding detachment is labeled, never silently dropped.
    pub binding_detach_labeled_not_hidden: bool,
    /// Change-object binding carries explicit attribution.
    pub change_object_attribution_explicit: bool,
    /// No finding-card or binding surface creates hidden write scope.
    pub no_hidden_write_scope: bool,
    /// Downgrade narrows the claim rather than hiding the lane.
    pub downgrade_narrows_instead_of_hides: bool,
    /// Stale or underqualified rows automatically block promotion.
    pub stale_or_underqualified_blocks_promotion: bool,
}

impl EvidenceCardTrustReview {
    /// Whether every invariant holds.
    pub const fn all_hold(&self) -> bool {
        self.ai_evidence_provenance_explicit
            && self.evidence_freshness_labeled_not_hidden
            && self.finding_cards_cite_real_evidence
            && self.finding_severity_and_status_explicit
            && self.apply_posture_explicit_no_silent_write
            && self.review_pack_binds_to_change_object
            && self.binding_detach_labeled_not_hidden
            && self.change_object_attribution_explicit
            && self.no_hidden_write_scope
            && self.downgrade_narrows_instead_of_hides
            && self.stale_or_underqualified_blocks_promotion
    }
}

/// Consumer projection block.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct EvidenceCardConsumerProjection {
    /// Finding cards show severity and status.
    pub finding_cards_show_severity_status: bool,
    /// Finding cards show evidence source and provenance.
    pub finding_cards_show_evidence_provenance: bool,
    /// Finding cards show apply posture.
    pub finding_cards_show_apply_posture: bool,
    /// Review-pack surface shows the change-object binding.
    pub review_pack_shows_change_object_binding: bool,
    /// Binding surface shows the detach label.
    pub binding_shows_detach_label: bool,
    /// CLI / headless shows qualification truth.
    pub cli_headless_shows_truth: bool,
    /// Support export shows qualification truth.
    pub support_export_shows_truth: bool,
    /// Diagnostics shows qualification truth.
    pub diagnostics_shows_truth: bool,
    /// Help / About shows qualification truth.
    pub help_about_shows_truth: bool,
    /// Preview / Labs lanes are labeled when not covered by this packet.
    pub preview_labs_label_for_unqualified: bool,
}

impl EvidenceCardConsumerProjection {
    /// Whether every projection invariant holds.
    pub const fn all_hold(&self) -> bool {
        self.finding_cards_show_severity_status
            && self.finding_cards_show_evidence_provenance
            && self.finding_cards_show_apply_posture
            && self.review_pack_shows_change_object_binding
            && self.binding_shows_detach_label
            && self.cli_headless_shows_truth
            && self.support_export_shows_truth
            && self.diagnostics_shows_truth
            && self.help_about_shows_truth
            && self.preview_labs_label_for_unqualified
    }
}

/// Proof freshness block.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct EvidenceCardProofFreshness {
    /// Proof-freshness SLO in hours.
    pub proof_freshness_slo_hours: u32,
    /// RFC 3339 timestamp of the last proof refresh.
    pub last_proof_refresh: String,
    /// True when stale proof automatically narrows the lane.
    pub auto_narrow_on_stale: bool,
}

/// Constructor input for [`EvidenceCardPacket::new`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EvidenceCardPacketInput {
    /// Stable packet id.
    pub packet_id: String,
    /// Human-readable surface label.
    pub surface_label: String,
    /// AI review-evidence rows.
    pub evidence_rows: Vec<EvidenceCardEvidenceRow>,
    /// Review finding-card rows.
    pub finding_cards: Vec<EvidenceCardFindingRow>,
    /// Review-pack / change-object binding rows.
    pub review_pack_bindings: Vec<EvidenceCardReviewPackBindingRow>,
    /// Downgrade triggers that apply to this lane.
    pub downgrade_triggers: Vec<EvidenceCardDowngradeTrigger>,
    /// Consumer surfaces that must project this lane's truth.
    pub consumer_surfaces: Vec<EvidenceCardConsumerSurface>,
    /// Trust review block.
    pub trust_review: EvidenceCardTrustReview,
    /// Consumer projection block.
    pub consumer_projection: EvidenceCardConsumerProjection,
    /// Proof freshness block.
    pub proof_freshness: EvidenceCardProofFreshness,
    /// Canonical source contract refs.
    pub source_contract_refs: Vec<String>,
    /// Packet redaction class token.
    pub redaction_class_token: String,
    /// Packet mint timestamp.
    pub minted_at: String,
}

/// Export-safe AI review-evidence, finding-card, and review-pack/change-object packet.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct EvidenceCardPacket {
    /// Record kind; must equal [`EVIDENCE_CARD_RECORD_KIND`].
    pub record_kind: String,
    /// Schema version; must equal [`EVIDENCE_CARD_SCHEMA_VERSION`].
    pub schema_version: u32,
    /// Stable packet id.
    pub packet_id: String,
    /// Human-readable surface label.
    pub surface_label: String,
    /// AI review-evidence rows.
    pub evidence_rows: Vec<EvidenceCardEvidenceRow>,
    /// Review finding-card rows.
    pub finding_cards: Vec<EvidenceCardFindingRow>,
    /// Review-pack / change-object binding rows.
    pub review_pack_bindings: Vec<EvidenceCardReviewPackBindingRow>,
    /// Downgrade triggers that apply to this lane.
    pub downgrade_triggers: Vec<EvidenceCardDowngradeTrigger>,
    /// Consumer surfaces that must project this lane's truth.
    pub consumer_surfaces: Vec<EvidenceCardConsumerSurface>,
    /// Trust review block.
    pub trust_review: EvidenceCardTrustReview,
    /// Consumer projection block.
    pub consumer_projection: EvidenceCardConsumerProjection,
    /// Proof freshness block.
    pub proof_freshness: EvidenceCardProofFreshness,
    /// Canonical source contract refs.
    pub source_contract_refs: Vec<String>,
    /// Packet redaction class token.
    pub redaction_class_token: String,
    /// Packet mint timestamp.
    pub minted_at: String,
}

impl EvidenceCardPacket {
    /// Builds an AI review-evidence finding-card packet from stable-lane input.
    pub fn new(input: EvidenceCardPacketInput) -> Self {
        Self {
            record_kind: EVIDENCE_CARD_RECORD_KIND.to_owned(),
            schema_version: EVIDENCE_CARD_SCHEMA_VERSION,
            packet_id: input.packet_id,
            surface_label: input.surface_label,
            evidence_rows: input.evidence_rows,
            finding_cards: input.finding_cards,
            review_pack_bindings: input.review_pack_bindings,
            downgrade_triggers: input.downgrade_triggers,
            consumer_surfaces: input.consumer_surfaces,
            trust_review: input.trust_review,
            consumer_projection: input.consumer_projection,
            proof_freshness: input.proof_freshness,
            source_contract_refs: input.source_contract_refs,
            redaction_class_token: input.redaction_class_token,
            minted_at: input.minted_at,
        }
    }

    /// Validates the AI review-evidence finding-card invariants.
    pub fn validate(&self) -> Vec<EvidenceCardViolation> {
        let mut violations = Vec::new();

        if self.record_kind != EVIDENCE_CARD_RECORD_KIND {
            violations.push(EvidenceCardViolation::WrongRecordKind);
        }
        if self.schema_version != EVIDENCE_CARD_SCHEMA_VERSION {
            violations.push(EvidenceCardViolation::WrongSchemaVersion);
        }
        if self.packet_id.trim().is_empty()
            || self.surface_label.trim().is_empty()
            || self.redaction_class_token.trim().is_empty()
            || self.minted_at.trim().is_empty()
        {
            violations.push(EvidenceCardViolation::MissingIdentity);
        }
        if self.downgrade_triggers.is_empty() {
            violations.push(EvidenceCardViolation::DowngradeTriggersMissing);
        }
        if self.consumer_surfaces.is_empty() {
            violations.push(EvidenceCardViolation::ConsumerSurfacesMissing);
        }

        validate_source_contracts(self, &mut violations);
        validate_evidence_rows(self, &mut violations);
        validate_bindings(self, &mut violations);
        validate_finding_cards(self, &mut violations);

        if !self.trust_review.all_hold() {
            violations.push(EvidenceCardViolation::TrustReviewIncomplete);
        }
        if !self.consumer_projection.all_hold() {
            violations.push(EvidenceCardViolation::ConsumerProjectionIncomplete);
        }
        if self.proof_freshness.proof_freshness_slo_hours == 0
            || self.proof_freshness.last_proof_refresh.trim().is_empty()
        {
            violations.push(EvidenceCardViolation::ProofFreshnessIncomplete);
        }

        if json_contains_forbidden_boundary_material(
            &serde_json::to_value(self).expect("evidence-card packet serializes"),
        ) {
            violations.push(EvidenceCardViolation::RawBoundaryMaterialInExport);
        }

        violations
    }

    /// Deterministic export-safe JSON.
    ///
    /// # Panics
    ///
    /// Panics only if serializing this metadata-only packet fails.
    pub fn export_safe_json(&self) -> String {
        serde_json::to_string_pretty(self).expect("evidence-card packet serializes")
    }

    /// Deterministic Markdown summary for support, review, or release handoff.
    pub fn render_markdown_summary(&self) -> String {
        let stale_evidence = self
            .evidence_rows
            .iter()
            .filter(|row| row.freshness.is_stale())
            .count();
        let blocking_findings = self
            .finding_cards
            .iter()
            .filter(|row| row.severity == FindingSeverityClass::Blocking)
            .count();
        let detached_bindings = self
            .review_pack_bindings
            .iter()
            .filter(|row| row.binding_state.requires_detach_label())
            .count();

        let mut out = String::new();
        out.push_str(
            "# AI Review Evidence, Finding Cards, and Review-Pack Change-Object Integration\n\n",
        );
        out.push_str(&format!("- Packet: `{}`\n", self.packet_id));
        out.push_str(&format!("- Surface: `{}`\n", self.surface_label));
        out.push_str(&format!(
            "- Evidence rows: {} ({} stale or superseded and labeled)\n",
            self.evidence_rows.len(),
            stale_evidence
        ));
        out.push_str(&format!(
            "- Finding cards: {} ({} blocking)\n",
            self.finding_cards.len(),
            blocking_findings
        ));
        out.push_str(&format!(
            "- Review-pack bindings: {} ({} detached and relabeled)\n",
            self.review_pack_bindings.len(),
            detached_bindings
        ));
        out.push_str(&format!(
            "- Proof freshness SLO: {} hours (last refresh: {})\n",
            self.proof_freshness.proof_freshness_slo_hours, self.proof_freshness.last_proof_refresh
        ));

        out.push_str("\n## Evidence\n\n");
        for row in &self.evidence_rows {
            out.push_str(&format!(
                "- `{}` ({}): freshness `{}` — {}\n",
                row.evidence_id,
                row.source.as_str(),
                row.freshness.as_str(),
                row.provenance_label
            ));
        }

        out.push_str("\n## Finding cards\n\n");
        for row in &self.finding_cards {
            out.push_str(&format!(
                "- `{}` [{}/{}] → anchor `{}`, evidence `{}`, apply `{}`, change `{}`\n",
                row.finding_id,
                row.severity.as_str(),
                row.status.as_str(),
                row.anchor_id,
                row.evidence_ref,
                row.apply_posture.as_str(),
                row.change_object_ref
            ));
        }

        out.push_str("\n## Review-pack / change-object bindings\n\n");
        for row in &self.review_pack_bindings {
            out.push_str(&format!(
                "- pack `{}` ↔ change `{}`: {} ({})\n",
                row.review_pack_id,
                row.change_object_id,
                row.binding_state.as_str(),
                row.required_check_coverage.as_str()
            ));
        }
        out
    }
}

/// Errors emitted when reading the checked-in AI review-evidence finding-card export.
#[derive(Debug)]
pub enum EvidenceCardArtifactError {
    /// Support export failed to parse.
    SupportExport(serde_json::Error),
    /// Support export failed validation.
    Validation(Vec<EvidenceCardViolation>),
}

impl fmt::Display for EvidenceCardArtifactError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::SupportExport(error) => {
                write!(formatter, "evidence-card export parse failed: {error}")
            }
            Self::Validation(violations) => {
                let tokens = violations
                    .iter()
                    .map(|violation| violation.as_str())
                    .collect::<Vec<_>>()
                    .join(",");
                write!(
                    formatter,
                    "evidence-card export failed validation: {tokens}"
                )
            }
        }
    }
}

impl Error for EvidenceCardArtifactError {}

/// Validation failures emitted by [`EvidenceCardPacket::validate`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum EvidenceCardViolation {
    /// Packet record kind is wrong.
    WrongRecordKind,
    /// Packet schema version is wrong.
    WrongSchemaVersion,
    /// Required identity field is missing.
    MissingIdentity,
    /// Source contract refs are incomplete.
    MissingSourceContracts,
    /// No evidence rows are present.
    EvidenceRowsMissing,
    /// An evidence row is incomplete.
    EvidenceRowIncomplete,
    /// Two evidence rows share an id.
    EvidenceIdDuplicated,
    /// No finding cards are present.
    FindingCardsMissing,
    /// A finding card is incomplete.
    FindingCardIncomplete,
    /// A finding card cites evidence that is not present.
    FindingEvidenceRefMissing,
    /// A blocked-apply card is missing its block-reason label.
    ApplyBlockLabelMissing,
    /// A finding card is scoped to a change object that no binding covers.
    FindingChangeObjectUnbound,
    /// No review-pack bindings are present.
    ReviewPackBindingsMissing,
    /// A review-pack binding is incomplete.
    ReviewPackBindingIncomplete,
    /// A detached binding is missing its detach label.
    DetachLabelMissing,
    /// No downgrade triggers are present.
    DowngradeTriggersMissing,
    /// No consumer surfaces are present.
    ConsumerSurfacesMissing,
    /// Trust review does not satisfy required invariants.
    TrustReviewIncomplete,
    /// Consumer projection does not satisfy required invariants.
    ConsumerProjectionIncomplete,
    /// Proof freshness block is incomplete.
    ProofFreshnessIncomplete,
    /// Export contains raw boundary material.
    RawBoundaryMaterialInExport,
}

impl EvidenceCardViolation {
    /// Stable token used in tests and support exports.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::WrongRecordKind => "wrong_record_kind",
            Self::WrongSchemaVersion => "wrong_schema_version",
            Self::MissingIdentity => "missing_identity",
            Self::MissingSourceContracts => "missing_source_contracts",
            Self::EvidenceRowsMissing => "evidence_rows_missing",
            Self::EvidenceRowIncomplete => "evidence_row_incomplete",
            Self::EvidenceIdDuplicated => "evidence_id_duplicated",
            Self::FindingCardsMissing => "finding_cards_missing",
            Self::FindingCardIncomplete => "finding_card_incomplete",
            Self::FindingEvidenceRefMissing => "finding_evidence_ref_missing",
            Self::ApplyBlockLabelMissing => "apply_block_label_missing",
            Self::FindingChangeObjectUnbound => "finding_change_object_unbound",
            Self::ReviewPackBindingsMissing => "review_pack_bindings_missing",
            Self::ReviewPackBindingIncomplete => "review_pack_binding_incomplete",
            Self::DetachLabelMissing => "detach_label_missing",
            Self::DowngradeTriggersMissing => "downgrade_triggers_missing",
            Self::ConsumerSurfacesMissing => "consumer_surfaces_missing",
            Self::TrustReviewIncomplete => "trust_review_incomplete",
            Self::ConsumerProjectionIncomplete => "consumer_projection_incomplete",
            Self::ProofFreshnessIncomplete => "proof_freshness_incomplete",
            Self::RawBoundaryMaterialInExport => "raw_boundary_material_in_export",
        }
    }
}

/// Reads and validates the checked-in stable AI review-evidence finding-card export.
pub fn current_evidence_card_export() -> Result<EvidenceCardPacket, EvidenceCardArtifactError> {
    let packet: EvidenceCardPacket = serde_json::from_str(include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../artifacts/review/m5/ship_ai_review_evidence_finding_cards_and_review_pack_integration_with_change_objects/support_export.json"
    )))
    .map_err(EvidenceCardArtifactError::SupportExport)?;
    let violations = packet.validate();
    if violations.is_empty() {
        Ok(packet)
    } else {
        Err(EvidenceCardArtifactError::Validation(violations))
    }
}

fn validate_source_contracts(
    packet: &EvidenceCardPacket,
    violations: &mut Vec<EvidenceCardViolation>,
) {
    let refs: BTreeSet<&str> = packet
        .source_contract_refs
        .iter()
        .map(String::as_str)
        .collect();
    for required in [
        EVIDENCE_CARD_SCHEMA_REF,
        EVIDENCE_CARD_DOC_REF,
        EVIDENCE_CARD_AI_EVIDENCE_CONTRACT_REF,
        EVIDENCE_CARD_REVIEW_PACK_CONTRACT_REF,
        EVIDENCE_CARD_CHANGE_OBJECT_CONTRACT_REF,
    ] {
        if !refs.contains(required) {
            violations.push(EvidenceCardViolation::MissingSourceContracts);
            return;
        }
    }
}

fn validate_evidence_rows(
    packet: &EvidenceCardPacket,
    violations: &mut Vec<EvidenceCardViolation>,
) {
    if packet.evidence_rows.is_empty() {
        violations.push(EvidenceCardViolation::EvidenceRowsMissing);
        return;
    }

    let mut seen: BTreeSet<&str> = BTreeSet::new();
    for row in &packet.evidence_rows {
        if row.evidence_id.trim().is_empty()
            || row.provenance_label.trim().is_empty()
            || row.summary_label.trim().is_empty()
            || row.source_contract_refs.is_empty()
        {
            violations.push(EvidenceCardViolation::EvidenceRowIncomplete);
        }
        if !row.evidence_id.trim().is_empty() && !seen.insert(row.evidence_id.as_str()) {
            violations.push(EvidenceCardViolation::EvidenceIdDuplicated);
        }
    }
}

fn validate_bindings(packet: &EvidenceCardPacket, violations: &mut Vec<EvidenceCardViolation>) {
    if packet.review_pack_bindings.is_empty() {
        violations.push(EvidenceCardViolation::ReviewPackBindingsMissing);
        return;
    }

    for row in &packet.review_pack_bindings {
        if row.review_pack_id.trim().is_empty()
            || row.change_object_id.trim().is_empty()
            || row.attribution_label.trim().is_empty()
        {
            violations.push(EvidenceCardViolation::ReviewPackBindingIncomplete);
        }
        if row.binding_state.requires_detach_label() && row.detach_label.trim().is_empty() {
            violations.push(EvidenceCardViolation::DetachLabelMissing);
        }
    }
}

fn validate_finding_cards(
    packet: &EvidenceCardPacket,
    violations: &mut Vec<EvidenceCardViolation>,
) {
    if packet.finding_cards.is_empty() {
        violations.push(EvidenceCardViolation::FindingCardsMissing);
        return;
    }

    let evidence_ids: BTreeSet<&str> = packet
        .evidence_rows
        .iter()
        .map(|row| row.evidence_id.as_str())
        .collect();
    let bound_change_objects: BTreeSet<&str> = packet
        .review_pack_bindings
        .iter()
        .map(|row| row.change_object_id.as_str())
        .collect();

    for row in &packet.finding_cards {
        if row.finding_id.trim().is_empty()
            || row.anchor_id.trim().is_empty()
            || row.title_label.trim().is_empty()
            || row.evidence_ref.trim().is_empty()
            || row.change_object_ref.trim().is_empty()
        {
            violations.push(EvidenceCardViolation::FindingCardIncomplete);
        }
        if !row.evidence_ref.trim().is_empty() && !evidence_ids.contains(row.evidence_ref.as_str())
        {
            violations.push(EvidenceCardViolation::FindingEvidenceRefMissing);
        }
        if !row.change_object_ref.trim().is_empty()
            && !bound_change_objects.contains(row.change_object_ref.as_str())
        {
            violations.push(EvidenceCardViolation::FindingChangeObjectUnbound);
        }
        if row.apply_posture.requires_block_label() && row.apply_block_label.trim().is_empty() {
            violations.push(EvidenceCardViolation::ApplyBlockLabelMissing);
        }
    }
}

/// Heuristic that rejects obviously forbidden material in export-safe JSON.
fn json_contains_forbidden_boundary_material(value: &serde_json::Value) -> bool {
    match value {
        serde_json::Value::String(s) => {
            let lower = s.to_lowercase();
            lower.contains("api_key")
                || lower.contains("password")
                || lower.contains("secret")
                || lower.contains("bearer ")
        }
        serde_json::Value::Array(arr) => arr.iter().any(json_contains_forbidden_boundary_material),
        serde_json::Value::Object(map) => {
            map.values().any(json_contains_forbidden_boundary_material)
        }
        _ => false,
    }
}
