//! Beta distributed-compatibility skew-test harness verdict model.
//!
//! The generated distributed-compatibility manifests already decompose every
//! boundary row into supported / best-effort / untested / unsupported skew
//! cases, and the [`super::DistributedCompatibilitySupportExport`] projection
//! quotes the current and unsupported cases per row. This module promotes that
//! data into a single skew-test harness that drives the manifests across the
//! four named families (client/helper, client/extension, schema, provider) and
//! resolves every enumerated combination to one closed
//! [`DistributedSkewVerdict`] -- `compatible`, `probe_required`, or
//! `incompatible` -- with a repair or safe-continuation guidance path.
//!
//! The harness consumes the generated verdict corpus at
//! `/artifacts/release/m3/distributed_compatibility/skew_harness_verdict_corpus.json`.
//! That corpus is generated by `ci/check_beta_distributed_compatibility_skew_harness.py`
//! from the same family manifests and support-export projection, so this typed
//! consumer and the CI gate agree on every verdict without a cargo build in CI.
//!
//! The status -> verdict map is total and closed: an unhandled skew status has
//! no verdict, so [`DistributedSkewHarnessCase::resolve_verdict`] returns
//! `None` and [`DistributedSkewHarnessCorpus::validate`] reports it rather than
//! silently passing.

use std::collections::{BTreeMap, BTreeSet};

use serde::{Deserialize, Serialize};

use super::{DistributedCompatibilitySupportExport, DistributedCompatibilityViolation};

/// Schema version for the generated skew-harness verdict corpus.
pub const DISTRIBUTED_COMPATIBILITY_SKEW_HARNESS_CORPUS_SCHEMA_VERSION: u32 = 1;

/// Stable record-kind tag for the generated skew-harness verdict corpus.
pub const DISTRIBUTED_COMPATIBILITY_SKEW_HARNESS_CORPUS_RECORD_KIND: &str =
    "distributed_compatibility_skew_harness_corpus";

/// Repository-relative path to the generated skew-harness verdict corpus.
pub const CURRENT_DISTRIBUTED_COMPATIBILITY_SKEW_HARNESS_CORPUS_PATH: &str =
    "artifacts/release/m3/distributed_compatibility/skew_harness_verdict_corpus.json";

/// Guidance token recorded for a fully compatible pairing: nothing to repair,
/// continue inside the supported window.
pub const NO_REPAIR_REQUIRED_GUIDANCE: &str = "no_repair_required";

const REQUIRED_FAMILIES: &[&str] = &["client_helper", "client_extension", "schema", "provider"];

const CURRENT_DISTRIBUTED_COMPATIBILITY_SKEW_HARNESS_CORPUS_JSON: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../artifacts/release/m3/distributed_compatibility/skew_harness_verdict_corpus.json"
));

/// Loads the checked-in generated skew-harness verdict corpus.
///
/// # Errors
///
/// Returns a JSON parse error when the checked-in corpus no longer matches
/// [`DistributedSkewHarnessCorpus`].
pub fn current_distributed_compatibility_skew_harness_corpus(
) -> Result<DistributedSkewHarnessCorpus, serde_json::Error> {
    serde_json::from_str(CURRENT_DISTRIBUTED_COMPATIBILITY_SKEW_HARNESS_CORPUS_JSON)
}

/// Closed verdict a skew combination resolves to.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DistributedSkewVerdict {
    /// The pairing is inside the supported window; full mutation is admitted.
    Compatible,
    /// The pairing is best-effort or untested; a probe must resolve it before
    /// support is claimed and mutation is paused until then.
    ProbeRequired,
    /// The pairing is outside the supported window; the boundary refuses
    /// mutation and offers a typed repair path.
    Incompatible,
}

impl DistributedSkewVerdict {
    /// Every verdict, in declaration order.
    pub const ALL: [Self; 3] = [Self::Compatible, Self::ProbeRequired, Self::Incompatible];

    /// Stable token recorded in the corpus, gate, and exports.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Compatible => "compatible",
            Self::ProbeRequired => "probe_required",
            Self::Incompatible => "incompatible",
        }
    }

    /// Short reviewer-facing label.
    pub const fn label(self) -> &'static str {
        match self {
            Self::Compatible => "Compatible",
            Self::ProbeRequired => "Probe required",
            Self::Incompatible => "Incompatible",
        }
    }

    /// True when this verdict blocks mutating work on the boundary.
    pub const fn blocks_mutation(self) -> bool {
        !matches!(self, Self::Compatible)
    }

    /// Parses a stable verdict token, returning `None` for unknown tokens.
    pub fn from_token(token: &str) -> Option<Self> {
        Self::ALL
            .into_iter()
            .find(|verdict| verdict.as_str() == token)
    }
}

/// Closed skew-status vocabulary mirrored from the version-skew register.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DistributedSkewStatusClass {
    /// The current, supported window.
    Supported,
    /// A best-effort, explicitly caveated window.
    BestEffort,
    /// A reserved, untested window.
    Untested,
    /// An out-of-window, unsupported combination.
    Unsupported,
}

impl DistributedSkewStatusClass {
    /// Every status class, in declaration order.
    pub const ALL: [Self; 4] = [
        Self::Supported,
        Self::BestEffort,
        Self::Untested,
        Self::Unsupported,
    ];

    /// Stable token recorded in manifests, the register, and the corpus.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Supported => "supported",
            Self::BestEffort => "best_effort",
            Self::Untested => "untested",
            Self::Unsupported => "unsupported",
        }
    }

    /// Parses a stable status token, returning `None` for unknown tokens.
    pub fn from_token(token: &str) -> Option<Self> {
        Self::ALL
            .into_iter()
            .find(|status| status.as_str() == token)
    }

    /// The closed, total status -> verdict mapping. Adding a status class is a
    /// build-time signal because this match is exhaustive.
    pub const fn verdict(self) -> DistributedSkewVerdict {
        match self {
            Self::Supported => DistributedSkewVerdict::Compatible,
            Self::BestEffort | Self::Untested => DistributedSkewVerdict::ProbeRequired,
            Self::Unsupported => DistributedSkewVerdict::Incompatible,
        }
    }
}

/// One enumerated skew combination for one family/row pairing.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct DistributedSkewHarnessCase {
    /// Stable harness-case id.
    pub case_id: String,
    /// Manifest family token.
    pub manifest_family: String,
    /// Repository-relative family manifest ref.
    pub manifest_ref: String,
    /// Generated manifest row id.
    pub manifest_row_id: String,
    /// Seeded compatibility row ref.
    pub compatibility_row_ref: String,
    /// Skew-case ref from the version-skew register.
    pub skew_case_ref: String,
    /// Redaction-safe combination label.
    pub combination_label: String,
    /// Skew-status token for this combination.
    pub status: String,
    /// Verdict token this combination resolves to.
    pub verdict: String,
    /// Skew-window class for the row.
    pub window_class: String,
    /// Out-of-window posture for the row.
    pub out_of_window_posture: String,
    /// True when this combination is the row's current window.
    pub is_current_window: bool,
    /// True when this verdict blocks mutating work.
    pub mutation_blocked: bool,
    /// True when the support-export projection quotes this skew case.
    pub in_support_export: bool,
    /// Repair or safe-continuation guidance path; never empty.
    pub guidance_path: Vec<String>,
}

impl DistributedSkewHarnessCase {
    /// Resolves the verdict from the status token through the closed map.
    ///
    /// Returns `None` for an unhandled skew status, which the harness reports
    /// as a hard failure rather than treating as a silent pass.
    pub fn resolve_verdict(&self) -> Option<DistributedSkewVerdict> {
        DistributedSkewStatusClass::from_token(&self.status)
            .map(DistributedSkewStatusClass::verdict)
    }

    fn validate(&self, violations: &mut Vec<DistributedCompatibilityViolation>) {
        let Some(resolved) = self.resolve_verdict() else {
            push_violation(
                violations,
                "case.unhandled_skew_combination",
                &self.case_id,
                "skew status has no verdict in the closed status->verdict map",
            );
            return;
        };

        match DistributedSkewVerdict::from_token(&self.verdict) {
            Some(declared) if declared == resolved => {}
            _ => push_violation(
                violations,
                "case.verdict_mismatch",
                &self.case_id,
                "declared verdict does not match the mapped verdict",
            ),
        }

        if self.guidance_path.is_empty() {
            push_violation(
                violations,
                "case.guidance_path_empty",
                &self.case_id,
                "every pairing must carry a repair or safe-continuation guidance path",
            );
        } else if resolved == DistributedSkewVerdict::Compatible
            && self.guidance_path != [NO_REPAIR_REQUIRED_GUIDANCE]
        {
            push_violation(
                violations,
                "case.compatible_guidance",
                &self.case_id,
                "compatible pairings must carry the no_repair_required guidance token",
            );
        }

        if self.mutation_blocked != resolved.blocks_mutation() {
            push_violation(
                violations,
                "case.mutation_flag_mismatch",
                &self.case_id,
                "mutation_blocked must be set for every non-compatible verdict",
            );
        }

        if !REQUIRED_FAMILIES.contains(&self.manifest_family.as_str()) {
            push_violation(
                violations,
                "case.family_unknown",
                &self.case_id,
                "case manifest_family is not a distributed-compatibility family",
            );
        }
    }
}

/// Verdict totals shared by the corpus summary and validation.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct DistributedSkewHarnessCorpusSummary {
    /// Total enumerated cases.
    pub total_cases: u32,
    /// Cases resolving to `compatible`.
    pub compatible_cases: u32,
    /// Cases resolving to `probe_required`.
    pub probe_required_cases: u32,
    /// Cases resolving to `incompatible`.
    pub incompatible_cases: u32,
    /// Number of distinct families covered.
    pub families_covered: u32,
}

/// The generated skew-harness verdict corpus.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct DistributedSkewHarnessCorpus {
    /// Integer schema version for this corpus shape.
    pub schema_version: u32,
    /// Record-kind discriminator.
    pub record_kind: String,
    /// Stable corpus id.
    pub corpus_id: String,
    /// UTC generation timestamp.
    pub generated_at: String,
    /// Support-export projection ref the corpus cross-checks against.
    pub source_support_export_ref: String,
    /// Family manifest refs the corpus enumerates.
    pub source_manifest_refs: Vec<String>,
    /// Closed verdict vocabulary.
    pub verdict_vocabulary: Vec<String>,
    /// Closed skew-status vocabulary.
    pub status_vocabulary: Vec<String>,
    /// Guidance token used for compatible pairings.
    pub no_repair_required_guidance: String,
    /// Families covered by the corpus.
    pub families: Vec<String>,
    /// Every enumerated skew combination.
    pub cases: Vec<DistributedSkewHarnessCase>,
    /// Verdict totals.
    pub summary: DistributedSkewHarnessCorpusSummary,
}

impl DistributedSkewHarnessCorpus {
    /// Validates the corpus shape, the closed verdict map, per-case guidance,
    /// family/verdict coverage, and the summary totals.
    pub fn validate(&self) -> Vec<DistributedCompatibilityViolation> {
        let mut violations = Vec::new();

        if self.schema_version != DISTRIBUTED_COMPATIBILITY_SKEW_HARNESS_CORPUS_SCHEMA_VERSION {
            push_violation(
                &mut violations,
                "corpus.schema_version",
                &self.corpus_id,
                "skew harness corpus schema_version must be 1",
            );
        }
        if self.record_kind != DISTRIBUTED_COMPATIBILITY_SKEW_HARNESS_CORPUS_RECORD_KIND {
            push_violation(
                &mut violations,
                "corpus.record_kind",
                &self.corpus_id,
                "skew harness corpus record_kind is not supported",
            );
        }
        let expected_verdicts = DistributedSkewVerdict::ALL
            .iter()
            .map(|verdict| verdict.as_str().to_owned())
            .collect::<Vec<_>>();
        if self.verdict_vocabulary != expected_verdicts {
            push_violation(
                &mut violations,
                "corpus.verdict_vocabulary",
                &self.corpus_id,
                "verdict vocabulary must be compatible/probe_required/incompatible",
            );
        }
        let expected_statuses = DistributedSkewStatusClass::ALL
            .iter()
            .map(|status| status.as_str().to_owned())
            .collect::<Vec<_>>();
        if self.status_vocabulary != expected_statuses {
            push_violation(
                &mut violations,
                "corpus.status_vocabulary",
                &self.corpus_id,
                "status vocabulary must match the version-skew register vocabulary",
            );
        }
        if self.no_repair_required_guidance != NO_REPAIR_REQUIRED_GUIDANCE {
            push_violation(
                &mut violations,
                "corpus.no_repair_required_guidance",
                &self.corpus_id,
                "compatible-pairing guidance token must be no_repair_required",
            );
        }

        let families = self
            .families
            .iter()
            .map(String::as_str)
            .collect::<BTreeSet<_>>();
        for required in REQUIRED_FAMILIES {
            if !families.contains(required) {
                push_violation(
                    &mut violations,
                    "corpus.required_family_missing",
                    required,
                    "corpus must declare every distributed-compatibility family",
                );
            }
        }

        if self.cases.is_empty() {
            push_violation(
                &mut violations,
                "corpus.cases_empty",
                &self.corpus_id,
                "corpus must enumerate skew cases",
            );
        }

        let mut case_ids = BTreeSet::new();
        let mut skew_refs = BTreeSet::new();
        let mut coverage: BTreeMap<&str, BTreeSet<DistributedSkewVerdict>> = BTreeMap::new();
        for case in &self.cases {
            case.validate(&mut violations);
            if !case_ids.insert(case.case_id.as_str()) {
                push_violation(
                    &mut violations,
                    "case.duplicate_id",
                    &case.case_id,
                    "case ids must be unique",
                );
            }
            if !skew_refs.insert(case.skew_case_ref.as_str()) {
                push_violation(
                    &mut violations,
                    "case.duplicate_skew_case_ref",
                    &case.skew_case_ref,
                    "each skew case may appear once in the corpus",
                );
            }
            if let Some(verdict) = case.resolve_verdict() {
                coverage
                    .entry(case.manifest_family.as_str())
                    .or_default()
                    .insert(verdict);
            }
        }

        for required in REQUIRED_FAMILIES {
            let verdicts = coverage.get(required).cloned().unwrap_or_default();
            for verdict in [
                DistributedSkewVerdict::Compatible,
                DistributedSkewVerdict::Incompatible,
            ] {
                if !verdicts.contains(&verdict) {
                    push_violation(
                        &mut violations,
                        "coverage.missing_verdict",
                        required,
                        "family must enumerate at least one compatible and one incompatible pairing",
                    );
                }
            }
        }

        self.validate_summary(&mut violations);
        violations
    }

    fn validate_summary(&self, violations: &mut Vec<DistributedCompatibilityViolation>) {
        let count = |verdict: DistributedSkewVerdict| {
            self.cases
                .iter()
                .filter(|case| case.resolve_verdict() == Some(verdict))
                .count() as u32
        };
        let families_covered = self
            .cases
            .iter()
            .map(|case| case.manifest_family.as_str())
            .collect::<BTreeSet<_>>()
            .len() as u32;
        let expected = DistributedSkewHarnessCorpusSummary {
            total_cases: self.cases.len() as u32,
            compatible_cases: count(DistributedSkewVerdict::Compatible),
            probe_required_cases: count(DistributedSkewVerdict::ProbeRequired),
            incompatible_cases: count(DistributedSkewVerdict::Incompatible),
            families_covered,
        };
        if self.summary != expected {
            push_violation(
                violations,
                "summary.count_mismatch",
                &self.corpus_id,
                "summary totals must match the enumerated cases",
            );
        }
    }

    /// Cross-checks the harness against the support-export projection so the two
    /// surfaces agree on every verdict the support packet quotes: the current
    /// window resolves to `compatible`, and every unsupported case resolves to
    /// `incompatible` with the same repair hints.
    pub fn cross_check_support_export(
        &self,
        export: &DistributedCompatibilitySupportExport,
    ) -> Vec<DistributedCompatibilityViolation> {
        let mut violations = Vec::new();
        let cases_by_ref = self
            .cases
            .iter()
            .map(|case| (case.skew_case_ref.as_str(), case))
            .collect::<BTreeMap<_, _>>();

        for row in &export.support_rows {
            match cases_by_ref.get(row.current_skew_case_ref.as_str()) {
                Some(case) => expect_case(
                    case,
                    &row.support_row_id,
                    DistributedSkewVerdict::Compatible,
                    &row.manifest_family,
                    &row.compatibility_row_ref,
                    true,
                    &mut violations,
                ),
                None => push_violation(
                    &mut violations,
                    "support_export.current_case_unmatched",
                    &row.support_row_id,
                    "support row current skew case is not in the harness",
                ),
            }

            for unsupported_ref in &row.unsupported_case_refs {
                let Some(case) = cases_by_ref.get(unsupported_ref.as_str()) else {
                    push_violation(
                        &mut violations,
                        "support_export.unsupported_case_unmatched",
                        &row.support_row_id,
                        "support row unsupported skew case is not in the harness",
                    );
                    continue;
                };
                expect_case(
                    case,
                    &row.support_row_id,
                    DistributedSkewVerdict::Incompatible,
                    &row.manifest_family,
                    &row.compatibility_row_ref,
                    false,
                    &mut violations,
                );
                if case.guidance_path != row.repair_hints {
                    push_violation(
                        &mut violations,
                        "support_export.guidance_mismatch",
                        &row.support_row_id,
                        "incompatible harness guidance must equal the support row repair hints",
                    );
                }
            }
        }

        violations
    }
}

#[allow(clippy::too_many_arguments)]
fn expect_case(
    case: &DistributedSkewHarnessCase,
    row_id: &str,
    expected: DistributedSkewVerdict,
    family: &str,
    compat_ref: &str,
    expect_current: bool,
    violations: &mut Vec<DistributedCompatibilityViolation>,
) {
    if case.verdict != expected.as_str() {
        push_violation(
            violations,
            "support_export.verdict_disagreement",
            row_id,
            "support row case must resolve to the support-export verdict",
        );
    }
    if case.manifest_family != family {
        push_violation(
            violations,
            "support_export.family_mismatch",
            row_id,
            "harness case family must match the support row family",
        );
    }
    if case.compatibility_row_ref != compat_ref {
        push_violation(
            violations,
            "support_export.row_mismatch",
            row_id,
            "harness case compatibility row must match the support row",
        );
    }
    if !case.in_support_export {
        push_violation(
            violations,
            "support_export.flag_unset",
            row_id,
            "harness case quoted by the support export must set in_support_export",
        );
    }
    if expect_current && !case.is_current_window {
        push_violation(
            violations,
            "support_export.current_flag_unset",
            row_id,
            "support row current case must be flagged as the current window",
        );
    }
}

fn push_violation(
    violations: &mut Vec<DistributedCompatibilityViolation>,
    check_id: &str,
    subject: &str,
    message: &str,
) {
    violations.push(DistributedCompatibilityViolation {
        check_id: check_id.to_owned(),
        subject: subject.to_owned(),
        message: message.to_owned(),
    });
}
