//! Fixture replay for translated-pack locale overlays.
//!
//! The checked-in files under `fixtures/docs/m3/translated_pack_parity/`
//! are generated by `aureline_docs_locale_overlay_beta`, then replayed here
//! so runtime, docs, and support-export evidence stay aligned.

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

use aureline_docs::{
    seeded_translated_pack_locale_overlay_contract,
    seeded_translated_pack_locale_overlay_support_export,
    seeded_translated_pack_locale_overlay_surface_projection, LocaleOverlayBadgeClass,
    LocaleOverlayContract, LocaleOverlayCoverageState, LocaleOverlayPackKind,
    LocaleOverlaySupportExport, LocaleOverlaySurfaceProjection,
    OPEN_IN_SOURCE_LANGUAGE_ACTION_LABEL, TRANSLATED_PACK_LOCALE_OVERLAY_CONTRACT_ID,
    TRANSLATED_PACK_LOCALE_OVERLAY_VERSION_REF,
};

fn fixtures_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../fixtures/docs/m3/translated_pack_parity")
}

fn load_json<T: serde::de::DeserializeOwned>(file: &str) -> T {
    let path = fixtures_root().join(file);
    let body = std::fs::read_to_string(&path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", path.display()));
    serde_json::from_str(&body)
        .unwrap_or_else(|err| panic!("failed to parse {}: {err}", path.display()))
}

#[test]
fn manifest_fixture_matches_seeded_contract() {
    let from_file: LocaleOverlayContract = load_json("manifest.json");
    let from_code = seeded_translated_pack_locale_overlay_contract();

    assert_eq!(from_file, from_code);
    assert_eq!(from_file.contract_id, TRANSLATED_PACK_LOCALE_OVERLAY_CONTRACT_ID);
    assert_eq!(
        from_file.contract_version_ref,
        TRANSLATED_PACK_LOCALE_OVERLAY_VERSION_REF
    );
    assert!(from_file.validate().is_empty(), "{:?}", from_file.validate());
}

#[test]
fn surface_projection_fixture_matches_seeded_contract() {
    let from_file: LocaleOverlaySurfaceProjection = load_json("surface_projection.json");

    assert_eq!(
        from_file,
        seeded_translated_pack_locale_overlay_surface_projection()
    );
    for badge in [
        LocaleOverlayBadgeClass::Translated,
        LocaleOverlayBadgeClass::PartialTranslation,
        LocaleOverlayBadgeClass::StaleTranslation,
        LocaleOverlayBadgeClass::SourceLanguageFallback,
    ] {
        assert!(from_file.rows.iter().any(|row| row.badge_class == badge));
    }
    assert!(from_file
        .rows
        .iter()
        .all(|row| row.source_language_action_label == OPEN_IN_SOURCE_LANGUAGE_ACTION_LABEL));
}

#[test]
fn support_export_fixture_matches_seeded_contract() {
    let contract = seeded_translated_pack_locale_overlay_contract();
    let from_file: LocaleOverlaySupportExport = load_json("support_export.json");

    assert_eq!(from_file, seeded_translated_pack_locale_overlay_support_export());
    from_file
        .validate_against_contract(&contract)
        .expect("support export fixture validates");
    assert!(!from_file.raw_translated_bodies_exported);
    assert!(from_file
        .omitted_material_classes
        .iter()
        .any(|class| class == "raw_translated_body"));
}

#[test]
fn pack_family_and_coverage_requirements_are_represented() {
    let manifest: LocaleOverlayContract = load_json("manifest.json");
    let pack_kinds = manifest
        .overlays
        .iter()
        .map(|overlay| overlay.pack_kind)
        .collect::<BTreeSet<_>>();
    for required in [
        LocaleOverlayPackKind::DocsPack,
        LocaleOverlayPackKind::HelpPack,
        LocaleOverlayPackKind::GlossaryPack,
        LocaleOverlayPackKind::OnboardingPack,
        LocaleOverlayPackKind::GuidedTourPack,
        LocaleOverlayPackKind::TroubleshootingHelpPack,
    ] {
        assert!(pack_kinds.contains(&required));
    }

    let coverage_states = manifest
        .overlays
        .iter()
        .map(|overlay| overlay.coverage_state)
        .collect::<BTreeSet<_>>();
    for required in [
        LocaleOverlayCoverageState::TranslatedComplete,
        LocaleOverlayCoverageState::TranslatedPartial,
        LocaleOverlayCoverageState::TranslatedStale,
        LocaleOverlayCoverageState::SourceLanguageFallback,
        LocaleOverlayCoverageState::LocaleNotInstalled,
    ] {
        assert!(coverage_states.contains(&required));
    }
}

#[test]
fn every_overlay_preserves_integrity_refs() {
    let manifest: LocaleOverlayContract = load_json("manifest.json");

    for overlay in &manifest.overlays {
        assert!(
            overlay.preserves_identity_refs(),
            "{} must preserve citation, command, keyboard, and scope refs",
            overlay.overlay_id
        );
        assert_eq!(
            overlay.source_language_action.action_label,
            OPEN_IN_SOURCE_LANGUAGE_ACTION_LABEL
        );
        assert!(overlay.source_language_action.keyboard_reachable);
    }
}
