//! Graph-backed impact explainer packets with evidence-card projections.
//!
//! The packet types in this module consume [`crate::GraphQueryEnvelope`]
//! values directly. They preserve graph node and edge identity while adding the
//! compact evidence card, workset-scope disclosure, out-of-scope counts, and
//! non-canvas fallback that understanding surfaces need before a full topology
//! renderer exists.

use std::collections::BTreeSet;

use aureline_docs::{
    CitationAnchorAlpha, CitationAnchorAlphaInput, CitationAnchorAvailability,
    CitationConfidenceClass, CitationDrawerEvidenceView, CitationInferenceMarker,
    CitationLocalityClass, CitationSourceClass, DocsFreshnessClass, DocsNodeIdentity,
    DocsNodeIdentityInput, DocsNodeKind, DocsScopeClass, LocaleOverlayState, SourcePrecedenceClass,
    VersionMatchState,
};
use aureline_graph_proto::{
    AnchorKind, ConfidenceLevel, EdgeClass, EdgeEvidenceState, Freshness, GraphEdge, GraphNode,
    NodeBody, ProvenanceClass, QueryFamilyTag, SourceClass,
};
use serde::{Deserialize, Serialize};

use crate::{GraphAlphaQueryClass, GraphQueryEnvelope, GraphQueryRequest, GraphStore};

/// Schema version for alpha impact explainer packets.
pub const GRAPH_IMPACT_EXPLAINER_PACKET_SCHEMA_VERSION: u32 = 1;

/// Stable record-kind tag carried by impact explainer packets.
pub const GRAPH_IMPACT_EXPLAINER_PACKET_RECORD_KIND: &str = "graph_impact_explainer_packet";

/// Error returned when an impact explainer packet cannot be built.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum GraphExplainerError {
    /// The request targeted a query class the impact explainer cannot consume.
    UnsupportedQueryClass {
        /// Query class required by this packet builder.
        expected: GraphAlphaQueryClass,
        /// Query class supplied by the caller.
        actual: GraphAlphaQueryClass,
    },
    /// The impact request did not identify a subject graph node.
    MissingSubjectNodeId,
}

/// Whether an explainer or citation was generated by a producer or curated by a source artifact.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ExplainerSourceKind {
    /// Producer-generated evidence such as an inferred graph edge.
    Generated,
    /// Curated or authoritative source evidence such as source files, docs, or ownership rules.
    Curated,
}

impl ExplainerSourceKind {
    /// Returns the stable token used in exported packets.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Generated => "generated",
            Self::Curated => "curated",
        }
    }
}

/// Whether the active scope is fully loaded or intentionally sparse.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum WorksetScopeMode {
    /// The packet covers the declared scope fully.
    Full,
    /// The packet covers a sparse slice or hot-set subset.
    Sparse,
}

impl WorksetScopeMode {
    /// Returns the stable token used in exported packets.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Full => "full",
            Self::Sparse => "sparse",
        }
    }
}

/// Where the scope boundary was sourced from.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum WorksetScopeSource {
    /// Local workspace state supplied the scope boundary.
    Local,
    /// Managed or provider state supplied the scope boundary.
    Managed,
}

impl WorksetScopeSource {
    /// Returns the stable token used in exported packets.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Local => "local",
            Self::Managed => "managed",
        }
    }
}

/// Exactness class for an impact edge.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ImpactEdgeEvidenceClass {
    /// Direct or authoritative evidence supports the edge.
    Exact,
    /// The edge was hydrated from imported evidence.
    Imported,
    /// Heuristic, stale, or missing-anchor evidence supports the edge.
    Heuristic,
}

impl ImpactEdgeEvidenceClass {
    /// Returns the stable token used in exported packets.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Exact => "exact",
            Self::Imported => "imported",
            Self::Heuristic => "heuristic",
        }
    }
}

/// Open-detail action classes surfaced by the evidence card.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum OpenDetailActionClass {
    /// Open a source or docs anchor cited by the packet.
    OpenSourceAtAnchor,
    /// Inspect the canonical graph relation behind a row.
    InspectGraphRelation,
    /// Open the non-canvas topology table projection.
    OpenTopologyTable,
    /// Widen or change the active workset scope.
    WidenScope,
    /// Export the compact evidence card.
    ExportEvidenceCard,
}

impl OpenDetailActionClass {
    /// Returns the stable token used in exported packets.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::OpenSourceAtAnchor => "open_source_at_anchor",
            Self::InspectGraphRelation => "inspect_graph_relation",
            Self::OpenTopologyTable => "open_topology_table",
            Self::WidenScope => "widen_scope",
            Self::ExportEvidenceCard => "export_evidence_card",
        }
    }
}

/// Covered index counts for a workset scope.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct IndexCoverage {
    /// Number of graph nodes visible inside the active scope.
    pub covered_node_count: usize,
    /// Number of graph edges visible inside the active scope.
    pub covered_edge_count: usize,
    /// Number of graph objects known to be outside the loaded scope.
    pub not_loaded_count: usize,
    /// Compact coverage state token rendered by consumers.
    pub coverage_state: String,
}

/// Typed workset-scope disclosure carried by graph explainers.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct WorksetScopeDescriptor {
    /// Stable scope id that bounds the packet.
    pub scope_id: String,
    /// Scope class token copied from the graph scope vocabulary.
    pub scope_class: String,
    /// Included workspace roots or repository labels.
    pub included_roots_or_repos: Vec<String>,
    /// Whether the scope is full or sparse.
    pub scope_mode: WorksetScopeMode,
    /// Count of results hidden by workset, policy, or unloaded-scope boundaries.
    pub hidden_result_count: usize,
    /// Index coverage for the active scope.
    pub index_coverage: IndexCoverage,
    /// Whether the scope boundary came from local or managed state.
    pub scope_source: WorksetScopeSource,
}

impl WorksetScopeDescriptor {
    /// Builds a local full-scope descriptor.
    pub fn local_full(
        scope_id: impl Into<String>,
        scope_class: impl Into<String>,
        included_roots_or_repos: impl IntoIterator<Item = impl Into<String>>,
        covered_node_count: usize,
        covered_edge_count: usize,
    ) -> Self {
        Self {
            scope_id: scope_id.into(),
            scope_class: scope_class.into(),
            included_roots_or_repos: included_roots_or_repos
                .into_iter()
                .map(Into::into)
                .collect(),
            scope_mode: WorksetScopeMode::Full,
            hidden_result_count: 0,
            index_coverage: IndexCoverage {
                covered_node_count,
                covered_edge_count,
                not_loaded_count: 0,
                coverage_state: "fully_loaded".to_owned(),
            },
            scope_source: WorksetScopeSource::Local,
        }
    }

    /// Builds a local sparse-scope descriptor.
    pub fn local_sparse(
        scope_id: impl Into<String>,
        scope_class: impl Into<String>,
        included_roots_or_repos: impl IntoIterator<Item = impl Into<String>>,
        hidden_result_count: usize,
        covered_node_count: usize,
        covered_edge_count: usize,
        not_loaded_count: usize,
    ) -> Self {
        Self {
            scope_id: scope_id.into(),
            scope_class: scope_class.into(),
            included_roots_or_repos: included_roots_or_repos
                .into_iter()
                .map(Into::into)
                .collect(),
            scope_mode: WorksetScopeMode::Sparse,
            hidden_result_count,
            index_coverage: IndexCoverage {
                covered_node_count,
                covered_edge_count,
                not_loaded_count,
                coverage_state: "sparse_slice_loaded".to_owned(),
            },
            scope_source: WorksetScopeSource::Local,
        }
    }
}

/// One action exposed from an evidence card.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct OpenDetailAction {
    /// Stable action id inside the packet.
    pub action_id: String,
    /// Action class token.
    pub action_class: OpenDetailActionClass,
    /// Graph object, packet, or card this action opens.
    pub subject_ref: String,
    /// True when the action preserves the packet's active scope boundary.
    pub preserves_scope: bool,
}

/// One citation listed by an evidence card.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct EvidenceCitation {
    /// Stable citation id inside the card.
    pub citation_id: String,
    /// Citation subject kind, such as `graph_node_record` or `graph_edge_record`.
    pub subject_kind: String,
    /// Canonical graph or source ref cited by this entry.
    pub subject_ref: String,
    /// Generated-vs-curated source label for this citation.
    pub source_kind: ExplainerSourceKind,
    /// Redaction-aware display label.
    pub display_label: String,
    /// Freshness token copied from the graph object.
    pub freshness: String,
    /// Confidence token copied from the graph object.
    pub confidence: String,
    /// Edge evidence state when the citation points at a graph edge.
    pub evidence_state: Option<String>,
    /// Workspace-relative file path when a cited node resolves to a file.
    pub file_path: Option<String>,
    /// Stable symbol ref when a cited node resolves to a symbol.
    pub symbol_ref: Option<String>,
    /// Stable docs ref when a cited node resolves to a docs object.
    pub doc_ref: Option<String>,
    /// Canonical docs-node identity when the citation points at docs or help.
    pub docs_node_identity: Option<DocsNodeIdentity>,
}

/// Compact evidence card rendered beside an impact explainer packet.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct EvidenceCard {
    /// Stable record-kind tag for the card.
    pub record_kind: String,
    /// Stable card id.
    pub evidence_card_id: String,
    /// Generated-vs-curated source label for the packet as a whole.
    pub generated_vs_curated_source: ExplainerSourceKind,
    /// Packet-level freshness token.
    pub freshness: String,
    /// Packet-level confidence token.
    pub confidence: String,
    /// Count of cited file nodes.
    pub cited_file_count: usize,
    /// Count of cited symbol nodes.
    pub cited_symbol_count: usize,
    /// Count of cited docs nodes.
    pub cited_doc_count: usize,
    /// Ordered citations backing this card.
    pub citations: Vec<EvidenceCitation>,
    /// Canonical citation drawers for cited docs nodes.
    pub citation_evidence_views: Vec<CitationDrawerEvidenceView>,
    /// Open-detail actions exposed by this card.
    pub open_detail_actions: Vec<OpenDetailAction>,
}

/// One graph node projected into both visual and non-canvas views.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TopologyNodeProjection {
    /// Canonical graph node id.
    pub node_id: String,
    /// Node class token copied from the graph object.
    pub node_class: String,
    /// Redaction-aware node label.
    pub display_label: String,
    /// Freshness token copied from the graph object.
    pub freshness: String,
    /// Confidence token copied from the graph object.
    pub confidence: String,
}

/// One graph edge projected into both visual and non-canvas views.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TopologyEdgeProjection {
    /// Canonical graph edge id.
    pub edge_id: String,
    /// Edge class token copied from the graph object.
    pub edge_class: String,
    /// Canonical source node id.
    pub from_node_id: String,
    /// Canonical target node id.
    pub to_node_id: String,
    /// Edge evidence state copied from the graph object.
    pub evidence_state: String,
    /// Exact, imported, or heuristic impact class.
    pub edge_evidence_class: ImpactEdgeEvidenceClass,
    /// Freshness token copied from the graph object.
    pub freshness: String,
    /// Confidence token copied from the graph object.
    pub confidence: String,
}

/// Visual topology projection for the alpha impact explainer.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct VisualTopologyProjection {
    /// Stable projection id.
    pub projection_id: String,
    /// Presentation mode token, currently `map_canvas`.
    pub presentation_mode: String,
    /// Nodes visible to the visual projection.
    pub nodes: Vec<TopologyNodeProjection>,
    /// Edges visible to the visual projection.
    pub edges: Vec<TopologyEdgeProjection>,
    /// Identity rule the visual projection obeys.
    pub shared_identity_model: String,
}

/// One row in the non-canvas topology fallback.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TopologyFallbackRow {
    /// Canonical graph edge id.
    pub edge_id: String,
    /// Canonical source node id.
    pub from_node_id: String,
    /// Redaction-aware source node label.
    pub from_label: String,
    /// Edge class token copied from the graph object.
    pub edge_class: String,
    /// Canonical target node id.
    pub to_node_id: String,
    /// Redaction-aware target node label.
    pub to_label: String,
    /// Edge evidence state copied from the graph object.
    pub evidence_state: String,
    /// Exact, imported, or heuristic impact class.
    pub edge_evidence_class: ImpactEdgeEvidenceClass,
    /// Freshness token copied from the graph object.
    pub freshness: String,
    /// Confidence token copied from the graph object.
    pub confidence: String,
}

/// Non-canvas fallback projection for keyboard and screen-reader users.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct NonCanvasTopologyFallback {
    /// Stable projection id.
    pub projection_id: String,
    /// Presentation mode token, currently `edge_table_alternate`.
    pub presentation_mode: String,
    /// Table rows using the same graph identities as the visual projection.
    pub rows: Vec<TopologyFallbackRow>,
    /// Node ids shared with the visual projection.
    pub shared_node_ids: Vec<String>,
    /// Edge ids shared with the visual projection.
    pub shared_edge_ids: Vec<String>,
}

/// Impact counts and partial-scope disclosure for an impact explainer packet.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ImpactSummary {
    /// Number of impacted nodes visible inside the active scope.
    pub impacted_node_count: usize,
    /// Number of impact edges visible inside the active scope.
    pub visible_impact_edge_count: usize,
    /// Number of matching impact edges outside the active scope.
    pub out_of_scope_count: usize,
    /// Number of visible impact edges backed by exact evidence.
    pub exact_edge_count: usize,
    /// Number of visible impact edges backed by imported evidence.
    pub imported_edge_count: usize,
    /// Number of visible impact edges backed by heuristic, stale, or missing-anchor evidence.
    pub heuristic_edge_count: usize,
    /// True when no visible impact edge was found.
    pub no_impact_found: bool,
    /// Reason token explaining an empty visible result set.
    pub no_impact_reason: Option<String>,
}

/// Runtime packet consumed by graph-backed impact explainer surfaces.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ImpactExplainerPacket {
    /// Stable record-kind tag.
    pub record_kind: String,
    /// Integer schema version for this packet.
    pub schema_version: u32,
    /// Stable packet id for evidence joins.
    pub packet_id: String,
    /// Request id copied from the graph query envelope.
    pub query_request_id: String,
    /// Workspace id the packet answers.
    pub workspace_id: String,
    /// Workspace graph id used to answer.
    pub workspace_graph_id: String,
    /// Monotonic or fixture timestamp for export parity.
    pub emitted_at: String,
    /// Packet-level graph readiness token.
    pub readiness: String,
    /// Partial-truth cause tokens copied from the query envelope.
    pub partial_truth_causes: Vec<String>,
    /// Canonical graph node id the impact packet explains.
    pub subject_node_id: String,
    /// Typed workset scope visible to every consuming surface.
    pub workset_scope: WorksetScopeDescriptor,
    /// Explicit statement of the packet's bounded claim.
    pub coverage_claim: String,
    /// Impact counts and exact-vs-heuristic disclosure.
    pub impact_summary: ImpactSummary,
    /// Cited evidence card for the packet.
    pub evidence_card: EvidenceCard,
    /// Visual map-style projection.
    pub visual_projection: VisualTopologyProjection,
    /// Equivalent non-canvas table projection.
    pub non_canvas_fallback: NonCanvasTopologyFallback,
}

impl GraphStore {
    /// Builds an alpha impact explainer packet from an impact-seed query request.
    ///
    /// The packet preserves graph query identity and adds the evidence card,
    /// workset-scope disclosure, out-of-scope count, and non-canvas fallback
    /// required by graph-backed understanding surfaces.
    ///
    /// # Errors
    ///
    /// Returns [`GraphExplainerError::UnsupportedQueryClass`] when `request`
    /// is not an impact-seed request. Returns
    /// [`GraphExplainerError::MissingSubjectNodeId`] when the request does not
    /// carry a subject node id.
    pub fn build_impact_explainer_packet(
        &self,
        request: GraphQueryRequest,
        workset_scope: WorksetScopeDescriptor,
    ) -> Result<ImpactExplainerPacket, GraphExplainerError> {
        if request.query_class != GraphAlphaQueryClass::ImpactSeed {
            return Err(GraphExplainerError::UnsupportedQueryClass {
                expected: GraphAlphaQueryClass::ImpactSeed,
                actual: request.query_class,
            });
        }
        let subject_node_id = request
            .subject_node_id
            .clone()
            .ok_or(GraphExplainerError::MissingSubjectNodeId)?;
        let requested_scope_ids = request.scope_ids.clone();
        let envelope = self.query(request);
        Ok(ImpactExplainerPacket::from_graph_query_envelope(
            self,
            &envelope,
            subject_node_id,
            requested_scope_ids,
            workset_scope,
        ))
    }
}

impl ImpactExplainerPacket {
    fn from_graph_query_envelope(
        store: &GraphStore,
        envelope: &GraphQueryEnvelope,
        subject_node_id: String,
        requested_scope_ids: Vec<String>,
        workset_scope: WorksetScopeDescriptor,
    ) -> Self {
        let impact_edges = envelope
            .rows
            .iter()
            .filter(|row| row.edge_class == Some(EdgeClass::Impacts))
            .filter_map(|row| row.edge_id.as_deref())
            .filter_map(|edge_id| store.edge(edge_id))
            .collect::<Vec<_>>();
        let out_of_scope_count =
            matching_out_of_scope_impact_edges(store, &subject_node_id, &requested_scope_ids);

        let mut node_ids = BTreeSet::new();
        for row in &envelope.rows {
            if let Some(node_id) = &row.node_id {
                node_ids.insert(node_id.clone());
            }
        }
        for edge in &impact_edges {
            node_ids.insert(edge.from_node_id.clone());
            node_ids.insert(edge.to_node_id.clone());
        }

        let nodes = node_ids
            .iter()
            .filter_map(|node_id| store.node(node_id))
            .map(node_projection)
            .collect::<Vec<_>>();
        let edges = impact_edges
            .iter()
            .map(|edge| edge_projection(edge))
            .collect::<Vec<_>>();

        let impact_summary = impact_summary(&impact_edges, out_of_scope_count);
        let packet_id = format!("packet:impact_explainer:{}", envelope.query_request_id);
        let evidence_card = evidence_card_for_packet(store, envelope, &packet_id, &impact_summary);
        let visual_projection = VisualTopologyProjection {
            projection_id: format!(
                "projection:impact_explainer:{}:map",
                envelope.query_request_id
            ),
            presentation_mode: "map_canvas".to_owned(),
            nodes,
            edges,
            shared_identity_model: "graph_node_id_and_graph_edge_id".to_owned(),
        };
        let non_canvas_fallback =
            fallback_for_projection(store, envelope, &visual_projection, &impact_edges);

        Self {
            record_kind: GRAPH_IMPACT_EXPLAINER_PACKET_RECORD_KIND.to_owned(),
            schema_version: GRAPH_IMPACT_EXPLAINER_PACKET_SCHEMA_VERSION,
            packet_id,
            query_request_id: envelope.query_request_id.clone(),
            workspace_id: envelope.workspace_id.clone(),
            workspace_graph_id: envelope.workspace_graph_id.clone(),
            emitted_at: envelope.emitted_at.clone(),
            readiness: envelope.readiness.as_str().to_owned(),
            partial_truth_causes: envelope
                .partial_truth_causes
                .iter()
                .map(|cause| cause.as_str().to_owned())
                .collect(),
            subject_node_id,
            workset_scope,
            coverage_claim:
                "stored impact edges for the active workset only; full transitive repo impact is not claimed"
                    .to_owned(),
            impact_summary,
            evidence_card,
            visual_projection,
            non_canvas_fallback,
        }
    }
}

fn impact_summary(edges: &[&GraphEdge], out_of_scope_count: usize) -> ImpactSummary {
    let exact_edge_count = edges
        .iter()
        .filter(|edge| evidence_class(edge) == ImpactEdgeEvidenceClass::Exact)
        .count();
    let imported_edge_count = edges
        .iter()
        .filter(|edge| evidence_class(edge) == ImpactEdgeEvidenceClass::Imported)
        .count();
    let heuristic_edge_count = edges
        .iter()
        .filter(|edge| evidence_class(edge) == ImpactEdgeEvidenceClass::Heuristic)
        .count();
    let impacted_node_count = edges
        .iter()
        .map(|edge| edge.to_node_id.as_str())
        .collect::<BTreeSet<_>>()
        .len();
    let no_impact_found = edges.is_empty();
    let no_impact_reason = match (no_impact_found, out_of_scope_count) {
        (true, 0) => Some("no_stored_impact_edges_in_active_scope".to_owned()),
        (true, _) => Some("impact_edges_exist_outside_active_scope".to_owned()),
        (false, _) => None,
    };

    ImpactSummary {
        impacted_node_count,
        visible_impact_edge_count: edges.len(),
        out_of_scope_count,
        exact_edge_count,
        imported_edge_count,
        heuristic_edge_count,
        no_impact_found,
        no_impact_reason,
    }
}

fn matching_out_of_scope_impact_edges(
    store: &GraphStore,
    subject_node_id: &str,
    requested_scope_ids: &[String],
) -> usize {
    if requested_scope_ids.is_empty() {
        return 0;
    }
    store
        .all_edges()
        .filter(|edge| {
            edge.edge_class == EdgeClass::Impacts
                && edge
                    .query_family_tags
                    .contains(&QueryFamilyTag::ImpactExplorer)
                && (edge.from_node_id == subject_node_id || edge.to_node_id == subject_node_id)
                && !edge
                    .scope_refs
                    .iter()
                    .any(|scope| requested_scope_ids.contains(&scope.scope_id))
        })
        .count()
}

fn evidence_card_for_packet(
    store: &GraphStore,
    envelope: &GraphQueryEnvelope,
    packet_id: &str,
    impact_summary: &ImpactSummary,
) -> EvidenceCard {
    let citations = citations_for_envelope(store, envelope);
    let generated_vs_curated_source = if citations
        .iter()
        .any(|citation| citation.source_kind == ExplainerSourceKind::Generated)
    {
        ExplainerSourceKind::Generated
    } else {
        ExplainerSourceKind::Curated
    };
    let cited_file_count = citations
        .iter()
        .filter(|citation| citation.file_path.is_some())
        .count();
    let cited_symbol_count = citations
        .iter()
        .filter(|citation| citation.symbol_ref.is_some())
        .count();
    let cited_doc_count = citations
        .iter()
        .filter(|citation| citation.doc_ref.is_some())
        .count();

    EvidenceCard {
        record_kind: "graph_explainer_evidence_card".to_owned(),
        evidence_card_id: format!("{packet_id}:evidence_card"),
        generated_vs_curated_source,
        freshness: packet_freshness(&citations),
        confidence: packet_confidence(&citations),
        cited_file_count,
        cited_symbol_count,
        cited_doc_count,
        citation_evidence_views: citations
            .iter()
            .filter_map(|citation| docs_citation_view_for_evidence(citation, packet_id))
            .collect(),
        citations,
        open_detail_actions: open_detail_actions(envelope, packet_id, impact_summary),
    }
}

fn citations_for_envelope(
    store: &GraphStore,
    envelope: &GraphQueryEnvelope,
) -> Vec<EvidenceCitation> {
    let mut citations = Vec::new();
    for row in &envelope.rows {
        if let Some(edge_id) = &row.edge_id {
            if let Some(edge) = store.edge(edge_id) {
                citations.push(edge_citation(citations.len(), edge));
            }
        }
        if let Some(node_id) = &row.node_id {
            if let Some(node) = store.node(node_id) {
                citations.push(node_citation(citations.len(), node));
            }
        }
    }
    citations
}

fn open_detail_actions(
    envelope: &GraphQueryEnvelope,
    packet_id: &str,
    impact_summary: &ImpactSummary,
) -> Vec<OpenDetailAction> {
    let mut actions = Vec::new();
    for row in &envelope.rows {
        if let Some(edge_id) = &row.edge_id {
            actions.push(OpenDetailAction {
                action_id: format!("action:{edge_id}:inspect_graph_relation"),
                action_class: OpenDetailActionClass::InspectGraphRelation,
                subject_ref: edge_id.clone(),
                preserves_scope: true,
            });
        }
        if let Some(node_id) = &row.node_id {
            actions.push(OpenDetailAction {
                action_id: format!("action:{node_id}:open_source_at_anchor"),
                action_class: OpenDetailActionClass::OpenSourceAtAnchor,
                subject_ref: node_id.clone(),
                preserves_scope: true,
            });
        }
    }
    actions.push(OpenDetailAction {
        action_id: format!("action:{packet_id}:open_topology_table"),
        action_class: OpenDetailActionClass::OpenTopologyTable,
        subject_ref: packet_id.to_owned(),
        preserves_scope: true,
    });
    if impact_summary.out_of_scope_count > 0 {
        actions.push(OpenDetailAction {
            action_id: format!("action:{packet_id}:widen_scope"),
            action_class: OpenDetailActionClass::WidenScope,
            subject_ref: packet_id.to_owned(),
            preserves_scope: false,
        });
    }
    actions.push(OpenDetailAction {
        action_id: format!("action:{packet_id}:export_evidence_card"),
        action_class: OpenDetailActionClass::ExportEvidenceCard,
        subject_ref: format!("{packet_id}:evidence_card"),
        preserves_scope: true,
    });
    actions
}

fn fallback_for_projection(
    store: &GraphStore,
    envelope: &GraphQueryEnvelope,
    visual_projection: &VisualTopologyProjection,
    edges: &[&GraphEdge],
) -> NonCanvasTopologyFallback {
    let rows = edges
        .iter()
        .map(|edge| {
            let from_label = store
                .node(&edge.from_node_id)
                .map(display_label_for_node)
                .unwrap_or_else(|| edge.from_node_id.clone());
            let to_label = store
                .node(&edge.to_node_id)
                .map(display_label_for_node)
                .unwrap_or_else(|| edge.to_node_id.clone());
            TopologyFallbackRow {
                edge_id: edge.edge_id.clone(),
                from_node_id: edge.from_node_id.clone(),
                from_label,
                edge_class: edge.edge_class.as_str().to_owned(),
                to_node_id: edge.to_node_id.clone(),
                to_label,
                evidence_state: edge.evidence.evidence_state.as_str().to_owned(),
                edge_evidence_class: evidence_class(edge),
                freshness: edge.evidence.freshness_frame.freshness.as_str().to_owned(),
                confidence: edge.evidence.confidence_level.as_str().to_owned(),
            }
        })
        .collect();

    NonCanvasTopologyFallback {
        projection_id: format!(
            "projection:impact_explainer:{}:edge_table",
            envelope.query_request_id
        ),
        presentation_mode: "edge_table_alternate".to_owned(),
        rows,
        shared_node_ids: visual_projection
            .nodes
            .iter()
            .map(|node| node.node_id.clone())
            .collect(),
        shared_edge_ids: visual_projection
            .edges
            .iter()
            .map(|edge| edge.edge_id.clone())
            .collect(),
    }
}

fn node_projection(node: &GraphNode) -> TopologyNodeProjection {
    TopologyNodeProjection {
        node_id: node.node_id.clone(),
        node_class: node.node_class.as_str().to_owned(),
        display_label: display_label_for_node(node),
        freshness: node.freshness_frame.freshness.as_str().to_owned(),
        confidence: node.confidence_level.as_str().to_owned(),
    }
}

fn edge_projection(edge: &GraphEdge) -> TopologyEdgeProjection {
    TopologyEdgeProjection {
        edge_id: edge.edge_id.clone(),
        edge_class: edge.edge_class.as_str().to_owned(),
        from_node_id: edge.from_node_id.clone(),
        to_node_id: edge.to_node_id.clone(),
        evidence_state: edge.evidence.evidence_state.as_str().to_owned(),
        edge_evidence_class: evidence_class(edge),
        freshness: edge.evidence.freshness_frame.freshness.as_str().to_owned(),
        confidence: edge.evidence.confidence_level.as_str().to_owned(),
    }
}

fn node_citation(index: usize, node: &GraphNode) -> EvidenceCitation {
    EvidenceCitation {
        citation_id: format!("citation:node:{index}:{}", node.node_id),
        subject_kind: "graph_node_record".to_owned(),
        subject_ref: node.node_id.clone(),
        source_kind: source_kind_for_node(node),
        display_label: display_label_for_node(node),
        freshness: node.freshness_frame.freshness.as_str().to_owned(),
        confidence: node.confidence_level.as_str().to_owned(),
        evidence_state: None,
        file_path: file_path_for_node(node),
        symbol_ref: symbol_ref_for_node(node),
        doc_ref: doc_ref_for_node(node),
        docs_node_identity: docs_node_identity_for_node(node),
    }
}

fn edge_citation(index: usize, edge: &GraphEdge) -> EvidenceCitation {
    EvidenceCitation {
        citation_id: format!("citation:edge:{index}:{}", edge.edge_id),
        subject_kind: "graph_edge_record".to_owned(),
        subject_ref: edge.edge_id.clone(),
        source_kind: source_kind_for_edge(edge),
        display_label: display_label_for_edge(edge),
        freshness: edge.evidence.freshness_frame.freshness.as_str().to_owned(),
        confidence: edge.evidence.confidence_level.as_str().to_owned(),
        evidence_state: Some(edge.evidence.evidence_state.as_str().to_owned()),
        file_path: None,
        symbol_ref: None,
        doc_ref: None,
        docs_node_identity: None,
    }
}

fn evidence_class(edge: &GraphEdge) -> ImpactEdgeEvidenceClass {
    match edge.evidence.evidence_state {
        EdgeEvidenceState::DirectEvidence => ImpactEdgeEvidenceClass::Exact,
        EdgeEvidenceState::ImportedEvidence => ImpactEdgeEvidenceClass::Imported,
        EdgeEvidenceState::InferredRelation
        | EdgeEvidenceState::StaleRelation
        | EdgeEvidenceState::MissingAnchor => ImpactEdgeEvidenceClass::Heuristic,
    }
}

fn packet_freshness(citations: &[EvidenceCitation]) -> String {
    if citations
        .iter()
        .any(|citation| citation.freshness == Freshness::Warming.as_str())
    {
        return Freshness::Warming.as_str().to_owned();
    }
    for freshness in [
        Freshness::Stale,
        Freshness::Cached,
        Freshness::Imported,
        Freshness::Replayed,
    ] {
        if citations
            .iter()
            .any(|citation| citation.freshness == freshness.as_str())
        {
            return freshness.as_str().to_owned();
        }
    }
    Freshness::Authoritative.as_str().to_owned()
}

fn packet_confidence(citations: &[EvidenceCitation]) -> String {
    let has_low = citations
        .iter()
        .any(|citation| matches!(citation.confidence.as_str(), "low" | "unknown"));
    if has_low {
        return ConfidenceLevel::Low.as_str().to_owned();
    }
    let has_medium = citations
        .iter()
        .any(|citation| citation.confidence == ConfidenceLevel::Medium.as_str());
    if has_medium {
        return ConfidenceLevel::Medium.as_str().to_owned();
    }
    ConfidenceLevel::High.as_str().to_owned()
}

fn source_kind_for_node(node: &GraphNode) -> ExplainerSourceKind {
    source_kind_for_provenance(
        node.provenance_stamp.source_class,
        node.provenance_stamp.provenance_class,
    )
}

fn source_kind_for_edge(edge: &GraphEdge) -> ExplainerSourceKind {
    source_kind_for_provenance(
        edge.evidence.provenance_stamp.source_class,
        edge.evidence.provenance_stamp.provenance_class,
    )
}

fn source_kind_for_provenance(
    source_class: SourceClass,
    provenance_class: ProvenanceClass,
) -> ExplainerSourceKind {
    if matches!(source_class, SourceClass::AiInference)
        || matches!(provenance_class, ProvenanceClass::InferredByHeuristic)
    {
        ExplainerSourceKind::Generated
    } else {
        ExplainerSourceKind::Curated
    }
}

fn display_label_for_node(node: &GraphNode) -> String {
    if let Some(label) = &node.display_label {
        return label.clone();
    }
    match &node.node_body {
        NodeBody::File {
            filesystem_identity,
            ..
        }
        | NodeBody::Directory {
            filesystem_identity,
            ..
        } => filesystem_identity.presentation_path.clone(),
        NodeBody::Symbol { qualified_path, .. } => qualified_path.clone(),
        NodeBody::Doc { doc_ref, .. } => doc_ref.clone(),
        NodeBody::Ownership {
            display_label,
            ownership_ref,
            ..
        } => display_label
            .clone()
            .unwrap_or_else(|| ownership_ref.clone()),
        NodeBody::Topology { topology_ref, .. } => topology_ref.clone(),
        NodeBody::ProviderResource {
            resource_handle, ..
        } => resource_handle.clone(),
        NodeBody::GeneratedArtifact {
            lineage_record_ref, ..
        } => lineage_record_ref.clone(),
        NodeBody::ImportedRoot { import_ref, .. } => import_ref.clone(),
        NodeBody::WorksetScope {
            display_label,
            scope_ref,
        } => display_label
            .clone()
            .unwrap_or_else(|| scope_ref.scope_id.clone()),
        NodeBody::PolicyView { policy_ref, .. } => policy_ref.clone(),
        NodeBody::MissingAnchor { last_known_ref, .. } => last_known_ref
            .clone()
            .unwrap_or_else(|| node.node_id.clone()),
    }
}

fn display_label_for_edge(edge: &GraphEdge) -> String {
    format!(
        "{} {} {}",
        edge.from_node_id,
        edge.edge_class.as_str(),
        edge.to_node_id
    )
}

fn file_path_for_node(node: &GraphNode) -> Option<String> {
    match &node.node_body {
        NodeBody::File {
            filesystem_identity,
            ..
        }
        | NodeBody::Directory {
            filesystem_identity,
            ..
        } => Some(trim_workspace_prefix(
            &filesystem_identity.presentation_path,
        )),
        NodeBody::Doc {
            anchor_filesystem_identity,
            ..
        } => anchor_filesystem_identity
            .as_ref()
            .map(|identity| trim_workspace_prefix(&identity.presentation_path)),
        _ => None,
    }
}

fn symbol_ref_for_node(node: &GraphNode) -> Option<String> {
    match &node.node_body {
        NodeBody::Symbol { qualified_path, .. } => Some(qualified_path.clone()),
        _ => None,
    }
}

fn doc_ref_for_node(node: &GraphNode) -> Option<String> {
    match &node.node_body {
        NodeBody::Doc { doc_ref, .. } => Some(doc_ref.clone()),
        _ => None,
    }
}

fn docs_node_identity_for_node(node: &GraphNode) -> Option<DocsNodeIdentity> {
    let NodeBody::Doc {
        doc_kind, doc_ref, ..
    } = &node.node_body
    else {
        return None;
    };
    let exact_anchor_ref = first_source_anchor_ref(node);
    let citation_availability = if exact_anchor_ref.is_some() {
        CitationAnchorAvailability::ExactAnchorAvailable
    } else {
        CitationAnchorAvailability::AnchorUnavailableDisclosed
    };
    let source_pack_ref = node
        .provenance_stamp
        .imported_bundle_ref
        .clone()
        .or_else(|| node.provenance_stamp.producer_ref.clone())
        .unwrap_or_else(|| "graph-docs-pack:unknown".to_owned());
    let source_pack_revision_ref = node
        .provenance_stamp
        .producer_version
        .clone()
        .unwrap_or_else(|| node.provenance_stamp.recorded_at.clone());
    let hidden_or_omitted_note = if citation_availability.requires_note() {
        Some("graph docs node did not carry an exact source anchor".to_owned())
    } else {
        None
    };

    Some(DocsNodeIdentity::new(DocsNodeIdentityInput {
        docs_node_id: node.node_id.clone(),
        doc_kind: docs_node_kind_from_graph_doc_kind(doc_kind),
        source_class: citation_source_class_from_graph(node.provenance_stamp.source_class),
        scope_class: DocsScopeClass::Explainer,
        source_pack_ref,
        source_pack_revision_ref: source_pack_revision_ref.clone(),
        version_or_revision_ref: source_pack_revision_ref,
        version_match_state: version_match_from_graph_freshness(node.freshness_frame.freshness),
        freshness_class: freshness_from_graph(node.freshness_frame.freshness),
        locality_class: locality_from_graph_source(node.provenance_stamp.source_class),
        source_locale: "en".to_owned(),
        requested_locale: "en".to_owned(),
        effective_locale: "en".to_owned(),
        locale_overlay_state: LocaleOverlayState::SourceLanguageOriginal,
        source_language_fallback_ref: None,
        citation_availability,
        citation_anchor_refs: exact_anchor_ref.into_iter().collect(),
        exact_reopen_ref: format!("reopen:{doc_ref}"),
        hidden_or_omitted_note,
    }))
}

fn docs_citation_view_for_evidence(
    citation: &EvidenceCitation,
    packet_id: &str,
) -> Option<CitationDrawerEvidenceView> {
    let docs_node = citation.docs_node_identity.clone()?;
    let anchor_ref = docs_node
        .citation_anchor_refs
        .first()
        .cloned()
        .unwrap_or_else(|| format!("missing-anchor:{}", citation.subject_ref));
    let availability = docs_node.citation_availability;
    let anchor = CitationAnchorAlpha::new(CitationAnchorAlphaInput {
        anchor_id: anchor_ref.clone(),
        docs_node_ref: docs_node.docs_node_id.clone(),
        source_class: docs_node.source_class,
        source_pack_ref: docs_node.source_pack_ref.clone(),
        source_pack_revision_ref: docs_node.source_pack_revision_ref.clone(),
        target_ref: citation
            .doc_ref
            .clone()
            .unwrap_or_else(|| citation.subject_ref.clone()),
        exact_anchor_ref: availability.is_exact().then(|| anchor_ref.clone()),
        locale: docs_node.effective_locale.clone(),
        version_match_state: docs_node.version_match_state,
        freshness_class: docs_node.freshness_class,
        locality_class: docs_node.locality_class,
        citation_availability: availability,
        inference_marker: inference_marker_from_evidence(citation),
        confidence_class: confidence_from_token(&citation.confidence),
        hidden_or_omitted_note: docs_node.hidden_or_omitted_note.clone(),
    });
    Some(CitationDrawerEvidenceView::from_node_and_anchors(
        format!("citation-drawer:{packet_id}:{}", citation.citation_id),
        docs_node,
        [anchor],
        SourcePrecedenceClass::NotApplicable,
        format!("{packet_id}:non_canvas_citations"),
    ))
}

fn first_source_anchor_ref(node: &GraphNode) -> Option<String> {
    node.source_anchors
        .iter()
        .find(|anchor| {
            matches!(
                anchor.anchor_kind,
                AnchorKind::DocsPackEntry
                    | AnchorKind::SymbolDefinitionSite
                    | AnchorKind::FilesystemIdentity
                    | AnchorKind::AnnotationNote
            ) && !anchor.anchor_ref.trim().is_empty()
        })
        .map(|anchor| anchor.anchor_ref.clone())
}

fn docs_node_kind_from_graph_doc_kind(doc_kind: &str) -> DocsNodeKind {
    let normalized = doc_kind.to_ascii_lowercase();
    if normalized.contains("glossary") {
        DocsNodeKind::GlossaryItem
    } else if normalized.contains("onboarding") {
        DocsNodeKind::OnboardingCard
    } else if normalized.contains("runbook") {
        DocsNodeKind::SupportRunbook
    } else if normalized.contains("explain") {
        DocsNodeKind::DerivedExplainer
    } else {
        DocsNodeKind::ReferencePage
    }
}

fn citation_source_class_from_graph(source_class: SourceClass) -> CitationSourceClass {
    match source_class {
        SourceClass::WorkspaceFilesystem | SourceClass::ManualAnnotation => {
            CitationSourceClass::ProjectDocs
        }
        SourceClass::DocsPack | SourceClass::ImportedBundle => {
            CitationSourceClass::MirroredOfficialDocs
        }
        SourceClass::CodegenTool | SourceClass::BuildToolchain => {
            CitationSourceClass::GeneratedReference
        }
        SourceClass::ConnectedProvider | SourceClass::RemoteAgent => {
            CitationSourceClass::VendorProviderDocs
        }
        SourceClass::AiInference => CitationSourceClass::DerivedExplanation,
        _ => CitationSourceClass::ProjectDocs,
    }
}

fn freshness_from_graph(freshness: Freshness) -> DocsFreshnessClass {
    match freshness {
        Freshness::Authoritative => DocsFreshnessClass::AuthoritativeLive,
        Freshness::Warming | Freshness::Cached => DocsFreshnessClass::WarmCached,
        Freshness::Stale => DocsFreshnessClass::Stale,
        Freshness::Replayed | Freshness::Imported => DocsFreshnessClass::DegradedCached,
    }
}

fn version_match_from_graph_freshness(freshness: Freshness) -> VersionMatchState {
    match freshness {
        Freshness::Authoritative => VersionMatchState::ExactBuildMatch,
        Freshness::Cached | Freshness::Warming => VersionMatchState::CompatibleMinorDrift,
        Freshness::Stale | Freshness::Imported | Freshness::Replayed => {
            VersionMatchState::UnknownTargetBuild
        }
    }
}

fn locality_from_graph_source(source_class: SourceClass) -> CitationLocalityClass {
    match source_class {
        SourceClass::WorkspaceFilesystem | SourceClass::ManualAnnotation => {
            CitationLocalityClass::LocalProjectPack
        }
        SourceClass::DocsPack | SourceClass::ImportedBundle => {
            CitationLocalityClass::MirroredOffline
        }
        SourceClass::CodegenTool | SourceClass::BuildToolchain => {
            CitationLocalityClass::GeneratedLocal
        }
        SourceClass::ConnectedProvider | SourceClass::RemoteAgent => {
            CitationLocalityClass::VendorLive
        }
        _ => CitationLocalityClass::CachedLocal,
    }
}

fn inference_marker_from_evidence(citation: &EvidenceCitation) -> CitationInferenceMarker {
    if citation.source_kind == ExplainerSourceKind::Generated {
        CitationInferenceMarker::GeneratedSummary
    } else if matches!(citation.confidence.as_str(), "low" | "unknown") {
        CitationInferenceMarker::Heuristic
    } else {
        CitationInferenceMarker::RawSource
    }
}

fn confidence_from_token(confidence: &str) -> CitationConfidenceClass {
    match confidence {
        "high" => CitationConfidenceClass::EvidenceBacked,
        "medium" => CitationConfidenceClass::Inferred,
        "low" => CitationConfidenceClass::LowConfidence,
        _ => CitationConfidenceClass::UnknownUnverified,
    }
}

fn trim_workspace_prefix(path: &str) -> String {
    path.strip_prefix("/workspace/aureline/")
        .or_else(|| path.strip_prefix("/workspace/"))
        .unwrap_or(path)
        .to_owned()
}
